### ISSUE TITLE
[Feature request] theme customization 

### ISSUE THREAD

**Issue by jrfVP42bLiUWAYOShp5r** [laurent22/joplin#396] opened 2018-04-09 14:14 UTC
### Operating system

- Android

### Application

- Mobile

It would be very nice if there were some more options to customize the appearance of the app. like:
true black themen (AMOLED)
switch for turning off the animations.

thanks!

**Comment by Kachilero** [comment] 2018-04-14 02:52
I would like this as well. As someone with "night blindness" the white background is a real strain on my eyes and a dark theme is much easier to read.

**Comment by laurent22** [comment] 2018-04-16 14:18
Duplicate of #93

**Closed by laurent22** 2018-04-16 14:18 UTC
