### ISSUE TITLE
Text blurred, Some Entries in the Overview on the left side are affected

### ISSUE THREAD

**Issue by Tommy-01** [laurent22/joplin#7516] opened 2022-12-22 10:07 UTC
## Environment

Joplin version: 2.9.17
Platform: Linux Mint 21.1 Cinnamon

## Steps to reproduce

1. Open Joplin for Desktop 

## Describe what you expected to happen

Some of the entries in the Overview on the left side are blurred.
If i hover over this entries, they turn to look normal. But if i continue with the mouse, the text look blurred again.

See the Screenshot for an example.

What have i tried to fix:
To fix this, I did change the resolution from 3000x2000 (3:2) with screen scaling 200% to 1400x900 (3:2) with screen scaling 100%. 
But this had no effect.

![screenshot](https://user-images.githubusercontent.com/34900296/209110597-dbfa0645-329d-4e9b-bbf1-ae16d8b6fadb.png)

**Comment by laurent22** [comment] 2022-12-22 11:16
Duplicate of #7506

**Closed as completed by laurent22** 2022-12-22 11:16 UTC
Labels: bug
