### ISSUE TITLE
Markdown search no longer scrolls to result

### ISSUE THREAD

**Issue by lehitoskin** [laurent22/joplin#5872] opened 2021-12-17 16:47 UTC
Joplin no longer scrolls to Markdown search results. Clicking on the up and down arrows to go to the next search result also does not scroll to the result. The results are still highlighted, like normal.

## Environment

Joplin version: 2.6.9
Platform: macOS (Intel)
OS specifics: Monterey 12.1

## Steps to reproduce

1. Open Joplin
2. Select Markdown
3. Search for text

## Describe what you expected to happen
The window should scroll to the search results

## Logfile
I wasn't sure what to include with the logs, so I just included the warnings from the Console tab.
[debug.log](https://github.com/laurent22/joplin/files/7736565/debug.log)

**Comment by laurent22** [comment] 2021-12-17 18:02
@ken1kob, looks like it's indeed broken in 2.6 probably due to the recent scroll changes, any idea what might be the issue? Maybe whatever function is used to programmatically scroll got lost in a refactoring? No error in the console though, so I'm not sure where the problem might be.

**Comment by ken1kob** [comment] 2021-12-18 05:18
Some programmatic scrolling caused by CodeMirror is incorrectly negated. 
For example, in addition to scrolling in local search, page up/down are often negated.
The severity is high.

They are fixed in PR #5876.

**Comment by markbacker** [comment] 2021-12-18 11:22
Also jumping to the end or beginning of a (long) note doesn't always work (using ctrl-home or ctrl-end).
- works in viewer
- works in split view after clicking on rendered view, but doesn't work with the cursor in the editor
- doesn't work in editor

Perhaps another issue, but it could be related.
- the outline plugin stopped working correct in editor and split view mode. But it does work in viewer mode.

**Comment by ken1kob** [comment] 2021-12-18 11:57
@markbacker, thanks for another report.
ctrl-home and ctrl-end are also fixed by #5876.

But in my environment (Win10), the Outline plugin works correctly. What's your env?

The jump functionality of note anchors and Outline's indexes are not relevant to the cause of this bug. 
So, if there is some malfunction in Outline's index jump, it may be another issue.

**Closed** 2021-12-18 15:14 UTC
Labels: bug, desktop, high

**Comment by markbacker** [comment] 2021-12-18 16:09
@ken1kob my environment is also Win10. I will have to look further for my outline issue. 
Thanks for the quick fix and the magic in syncing the editor and viewer !

**Comment by shbach** [comment] 2021-12-21 06:17
@markbacker I'm also having the issue with the outline plugin but I'm on Linux.
