### ISSUE TITLE
Android: Sharing file to Joplin doesn't work

### ISSUE THREAD

**Issue by wh201906** [laurent22/joplin#7691] opened 2023-01-30 05:24 UTC
## Environment

Joplin version: 2.10.4, 2.10.5
Platform: Android

## Steps to reproduce

1. Open Joplin
2. Switch to a file browser
3. Select a image, share it to Joplin
4. Joplin doesn't show the shared image

## Describe what you expected to happen

A new note will be created with the shared image in it

## Logfile

I didn't find any useful lines for file sharing in Joplin log, but the Logcat shows the error.

<details>
<summary>Logcat</summary>

```
13:08:13.884 unknown:ReactContext     W  initializeMessageQueueThreads() is called.
13:08:13.884 BufferQueueDebug         E  [net.cozic.joplin/net.cozic.joplin.share.ShareActivity#0](this:0xb400006feed8d8e0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'net.cozic.joplin/net.cozic.joplin.share.ShareActivity#0'
...
13:08:13.910 ReactNativeJS            E  TypeError: Cannot read property 'supportedSensors' of null
                                         
                                         This error is located at:
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in JoplinSafeAreaView
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in MenuProvider
                                             in DeprecatedComponent
                                             in RCTView
                                             in Unknown
                                             in AnimatedComponent
                                             in AnimatedComponentWrapper
                                             in RCTView
                                             in Unknown
                                             in SideMenuComponent
                                             in Connect(SideMenuComponent)
                                             in RCTView
                                             in Unknown
                                             in ThemeProvider
                                             in RCTView
                                             in Unknown
                                             in Portal.Host
                                             in RNCSafeAreaProvider
                                             in SafeAreaProvider
                                             in SafeAreaProviderCompat
                                             in Provider
                                             in AppComponent
                                             in Connect(AppComponent)
                                             in Provider
                                             in Root
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in AppContainer, js engine: hermes
13:08:13.910 ReactNativeJS            E  TypeError: Cannot read property 'supportedSensors' of null
                                         
                                         This error is located at:
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in JoplinSafeAreaView
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in MenuProvider
                                             in DeprecatedComponent
                                             in RCTView
                                             in Unknown
                                             in AnimatedComponent
                                             in AnimatedComponentWrapper
                                             in RCTView
                                             in Unknown
                                             in SideMenuComponent
                                             in Connect(SideMenuComponent)
                                             in RCTView
                                             in Unknown
                                             in ThemeProvider
                                             in RCTView
                                             in Unknown
                                             in Portal.Host
                                             in RNCSafeAreaProvider
                                             in SafeAreaProvider
                                             in SafeAreaProviderCompat
                                             in Provider
                                             in AppComponent
                                             in Connect(AppComponent)
                                             in Provider
                                             in Root
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in AppContainer, js engine: hermes
13:08:13.912 unknown:ReactNative      E  TypeError: Cannot read property 'supportedSensors' of null
                                         
                                         This error is located at:
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in JoplinSafeAreaView
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in MenuProvider
                                             in DeprecatedComponent
                                             in RCTView
                                             in Unknown
                                             in AnimatedComponent
                                             in AnimatedComponentWrapper
                                             in RCTView
                                             in Unknown
                                             in SideMenuComponent
                                             in Connect(SideMenuComponent)
                                             in RCTView
                                             in Unknown
                                             in ThemeProvider
                                             in RCTView
                                             in Unknown
                                             in Portal.Host
                                             in RNCSafeAreaProvider
                                             in SafeAreaProvider
                                             in SafeAreaProviderCompat
                                             in Provider
                                             in AppComponent
                                             in Connect(AppComponent)
                                             in Provider
                                             in Root
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in AppContainer, js engine: hermes, stack:
                                         anonymous@1:4282697
                                         renderWithHooks@1:138649
                                         beginWork$1@1:180405
                                         performUnitOfWork@1:166905
                                         workLoopSync@1:166763
                                         renderRootSync@1:166647
                                         performSyncWorkOnRoot@1:164072
                                         flushSyncCallbacks@1:128601
                                         scheduleUpdateOnFiber@1:160982
                                         updateContainer@1:172150
                                         anonymous@1:181440
                                         renderApplication@1:570953
                                         run@1:567833
                                         runApplication@1:568338
                                         __callFunction@1:103920
                                         anonymous@1:102329
                                         __guard@1:103279
                                         callFunctionReturnFlushedQueue@1:102287
13:08:13.914 AndroidRuntime           E  FATAL EXCEPTION: mqt_native_modules
                                         Process: net.cozic.joplin, PID: 25567
                                         com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'supportedSensors' of null
                                         
                                         This error is located at:
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in JoplinSafeAreaView
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in MenuProvider
                                             in DeprecatedComponent
                                             in RCTView
                                             in Unknown
                                             in AnimatedComponent
                                             in AnimatedComponentWrapper
                                             in RCTView
                                             in Unknown
                                             in SideMenuComponent
                                             in Connect(SideMenuComponent)
                                             in RCTView
                                             in Unknown
                                             in ThemeProvider
                                             in RCTView
                                             in Unknown
                                             in Portal.Host
                                             in RNCSafeAreaProvider
                                             in SafeAreaProvider
                                             in SafeAreaProviderCompat
                                             in Provider
                                             in AppComponent
                                             in Connect(AppComponent)
                                             in Provider
                                             in Root
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in AppContainer, js engine: hermes, stack:
                                         anonymous@1:4282697
                                         renderWithHooks@1:138649
                                         beginWork$1@1:180405
                                         performUnitOfWork@1:166905
                                         workLoopSync@1:166763
                                         renderRootSync@1:166647
                                         performSyncWorkOnRoot@1:164072
                                         flushSyncCallbacks@1:128601
                                         scheduleUpdateOnFiber@1:160982
                                         updateContainer@1:172150
                                         anonymous@1:181440
                                         renderApplication@1:570953
                                         run@1:567833
                                         runApplication@1:568338
                                         __callFunction@1:103920
                                         anonymous@1:102329
                                         __guard@1:103279
                                         callFunctionReturnFlushedQueue@1:102287
                                         
                                         	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                         	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                         	at com.facebook.jni.NativeRunnable.run(Native Method)
                                         	at android.os.Handler.handleCallback(Handler.java:938)
                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                         	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                         	at android.os.Looper.loopOnce(Looper.java:210)
                                         	at android.os.Looper.loop(Looper.java:299)
                                         	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                         	at java.lang.Thread.run(Thread.java:920)
13:08:13.915 OOMEventManager          E  oom event not support this pkg, dismiss this!
13:08:13.916 MQSEventManager          W  jeoccur
13:08:13.918 ActivityTaskManager      W    Force finishing activity net.cozic.joplin/.share.ShareActivity
...
```

</details>

**Comment by roman-r-m** [comment] 2023-01-30 17:45
That property `supportedSensors` is only mentioned in the code in the context of biometrics lock. Probably a bug is around there somewhere.

**Comment by wh201906** [comment] 2023-01-30 23:40
OK. FYI I don't use the biometrics lock in Joplin.

**Comment by wh201906** [comment] 2023-02-01 02:34
According to the code, the `supportedSensors` is a member of `SensorInfo`, so I guess sometimes `props.sensorInfo` might be null?

**Comment by roman-r-m** [comment] 2023-02-01 09:49
Seems so.

I'm not even sure what is the correct behaviour for sharing when the biometric lock is enabled. Either the user needs to unlock the app to receive shared data, or, if the lock is not enabled for sharing, then anyone (with physical access to the phone) can see the list of notebooks (and even potentially view notes) without unlocking.

One for @laurent22

**Comment by wh201906** [comment] 2023-02-11 01:10
@laurent22 Hi. The sharing doesn't work on 2.10.6.
***
If I close Joplin, then share a file to it, it pops up a message box shows:
```
Couldn't read row 0, col 4 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
```
The log of Joplin shows it does receive the shared file
<details>
<summary>Log</summary>

```
02-11T08:46:56,20,"""Could not attach file:", "Error: Couldn't read row 0, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
Code: EUNSPECIFIED
Error: Couldn't read row 0, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at promiseMethodWrapper (address at index.android.bundle:1:111187)
    at copyFile (address at index.android.bundle:1:2939183)
    at ?anon_0_ (address at index.android.bundle:1:2936520)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2932494)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/164673tg/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/164673tg/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:213202)
    at _callTimer (address at index.android.bundle:1:212151)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:212315)
    at callReactNativeMicrotasks (address at index.android.bundle:1:214290)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:114674)
    at anonymous (address at index.android.bundle:1:113767)
    at __guard (address at index.android.bundle:1:114515)
    at flushedQueue (address at index.android.bundle:1:113678)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:113621)""
02-11T08:46:56,30,"""Original dimensions ", "{"width":1000,"height":1000}""
02-11T08:46:56,30,"""about to attach resource {"name":"IMG_202210.jpg","mimeType":"image/jpeg","uri":"content://me.zhanghai.android.files.file_provider/file%253A%252F%252F%252Fstorage%252Femulated%252F0%252FDCIM%252FScreenshots%252FIMG_202210.jpg"}""
02-11T08:46:56,30,"""Got file: content://me.zhanghai.android.files.file_provider/file%253A%252F%252F%252Fstorage%252Femulated%252F0%252FDCIM%252FScreenshots%252FIMG_202210.jpg""
02-11T08:46:56,30,"""Got type: image/jpeg""
02-11T08:46:56,30,"""Received shared data""
```

</details>

I think this bug is similar to the one you mentioned there.
https://github.com/laurent22/joplin/issues/6942#issuecomment-1426061350
***
If I keep the Joplin in the background, then share a file to it, it just shows the notebook I opened. It behaves like I just switch back to Joplin rather than sharing a file to it.
However, the Logcat shows the `ShareActivity.onResumed()` is called, but the `ShareActivity` doesn't appear, and the log of Joplin doesn't show lines like `Received shared data` and `about to attach resource`. Seems like `ShareActivity` is activated first, then it just exits without doing anything.

**Comment by laurent22** [comment] 2023-02-11 12:23
Yes, my approach was to delay the sharing handler until biometrics are done, but that didn't help much it seems. It works better in emulator, but it still has random errors especially on device.

**Comment by laurent22** [comment] 2023-02-20 12:24
Duplicate of #7791

**Closed as completed by laurent22** 2023-02-20 12:24 UTC
Labels: bug, mobile, high
