### ISSUE TITLE
LastError: TypeError: Cannot read property 'size' of null

### ISSUE THREAD

**Issue by victor03303** [laurent22/joplin#9123] opened 2023-10-23 20:23 UTC
# Joplin stopped synchronizing
![image](https://github.com/laurent22/joplin/assets/55033363/a190a8b6-309b-458f-a9bc-322ef086e4f1)

The notes available on the tablet are out-of-date compared to my iPhone and the ones on my desktop and laptop. It's just the tablet that's having issues.

# Environment
Joplin version: 12.12.3
Platform: iOS
OS specifics: 15.3

# Steps to reproduce
Let it sync 

# What I expected
To synchronize an encrypted copy to Onedrive.

# Logfile
https://pastebin.com/vgQyNiiT

![image](https://github.com/laurent22/joplin/assets/55033363/97020b6e-8a0e-4312-a142-46b54eb11067)

**Comment by personalizedrefrigerator** [comment] 2023-10-24 00:15
From the stack trace, it looks like the error is either coming from

https://github.com/laurent22/joplin/blob/773e02bcd01a2c1e86decb6fda4c3d87bb55a283/packages/lib/onedrive-api.ts#L154

or

https://github.com/laurent22/joplin/blob/773e02bcd01a2c1e86decb6fda4c3d87bb55a283/packages/lib/services/e2ee/EncryptionService.ts#L511

though most likely the first of the two.

**Comment by victor03303** [comment] 2023-10-24 19:24
> From the stack trace, it looks like the error is either coming from
> 
> https://github.com/laurent22/joplin/blob/773e02bcd01a2c1e86decb6fda4c3d87bb55a283/packages/lib/onedrive-api.ts#L154
> 
> or
> 
> https://github.com/laurent22/joplin/blob/773e02bcd01a2c1e86decb6fda4c3d87bb55a283/packages/lib/services/e2ee/EncryptionService.ts#L511
> 
> though most likely the first of the two.

Thank you for your feedback!
What does the first error message mean?

**Comment by personalizedrefrigerator** [comment] 2023-10-24 21:04
This is coming from the `uploadBigFile` OneDrive sync target function.

It should also add a line to the log that looks like this
```
Uploading File Fragment {{some number}} - {{some number}} from {{some number}} Mbit ...
```
just before the error. If you show all messages, is there a line similar to this just below/above the error? If so, what does it say?

**Comment by victor03303** [comment] 2023-10-26 21:35
I don't know where to begin. All text is very small on the tablet, all text is packed together, there's no way to export the logs or to even select it, copy and paste it somewhere else.

This is really frustrating how little thought of the log function is. Users are expected to share the logs in case of errors but you can't export them ...

No I don't think something similar is there

**Comment by personalizedrefrigerator** [comment] 2023-10-26 22:49
Thank you for checking! In that case, I think that one ~~fix~~ workaround could be handling `readFileChunk` failures better (e.g. the item should be skipped and sync should continue).

> This is really frustrating how little thought of the log function is. Users are expected to share the logs in case of errors but you can't export them ...

Definitely! A share button will be in the next release ([commit](https://github.com/laurent22/joplin/commit/53c82434be69a68b5edf397d2dcdbc6769660f4b)).

**Comment by victor03303** [comment] 2023-10-31 23:01
> Thank you for checking! In that case, I think that one ~~fix~~ workaround could be handling `readFileChunk` failures better (e.g. the item should be skipped and sync should continue).
> 
> 
> 
> > This is really frustrating how little thought of the log function is. Users are expected to share the logs in case of errors but you can't export them ...
> 
> 
> 
> Definitely! A share button will be in the next release ([commit](https://github.com/laurent22/joplin/commit/53c82434be69a68b5edf397d2dcdbc6769660f4b)).

I'm glad that the log function will become easier to use.

What must I do to fix my problem? What can I do?

**Comment by maiux** [comment] 2023-11-01 19:21
I have the same problem but in a more complex scenario. I used to sync with OneDrive. Now I'm moving to Nextcloud. I configured my iPhone (iOS 16.7.8) with both sync providers and now I can select one a time of them in settings. If I sync with OneDrive, I have no problems. Nextcloud is giving me this error message after completing the first whole sync.
If you think it's useful, how can I provide further information?

**Comment by personalizedrefrigerator** [comment] 2023-11-02 01:59
> I have the same problem but in a more complex scenario. I used to sync with OneDrive. Now I'm moving to Nextcloud. I configured my iPhone (iOS 16.7.8) with both sync providers and now I can select one a time of them in settings. If I sync with OneDrive, I have no problems. Nextcloud is giving me this error message after completing the first whole sync.
If you think it's useful, how can I provide further information?

I think that more information would be useful here &mdash; It's interesting that it happens with both OneDrive and Nextcloud.

Soon after experiencing this error, to "Configuration" then scroll down to "Log", click on "Errors only", then (if you can find it) take a screenshot of the Nextcloud sync error.

If you're using the [TestFlight version](https://discourse.joplinapp.org/t/a-new-ios-beta-version-is-available/32361), there should be a "Share" option that can be used to export the log.

**Comment by maiux** [comment] 2023-11-02 04:12
After first try I understood log records order is by most recent first 🤦🏻‍♂️🤣

These are the logs:
![image](https://github.com/laurent22/joplin/assets/278691/4e79a2ea-d933-4b7e-9c29-3b16726fee4b)![image](https://github.com/laurent22/joplin/assets/278691/f51b5313-32a8-4c3e-b4b7-048b6c4a0a17)![image](https://github.com/laurent22/joplin/assets/278691/20018d90-88f7-453d-92e5-e6ffa3adf2c7)

**Comment by maiux** [comment] 2023-11-02 06:26
> From the stack trace, it looks like the error is either coming from
> 
> https://github.com/laurent22/joplin/blob/773e02bcd01a2c1e86decb6fda4c3d87bb55a283/packages/lib/onedrive-api.ts#L154
> 
> or
> 
> https://github.com/laurent22/joplin/blob/773e02bcd01a2c1e86decb6fda4c3d87bb55a283/packages/lib/services/e2ee/EncryptionService.ts#L511
> 
> though most likely the first of the two.

Can you teach me how can you refer the source to the stack trace? I tried to search for function names in the github repository but I had no luck. Certainly I'm missing something :)

**Comment by personalizedrefrigerator** [comment] 2023-11-03 00:21
>  I tried to search for function names in the github repository but I had no luck. 

That's what I did, too.

The important function names seem to be `read` and `readFileChunk`:
![screenshot: read and readFileChunk highlighted in stack trace](https://github.com/laurent22/joplin/assets/46334387/86fb07ea-5511-48d1-9e77-f63291849a22)

Notice that both are listed as being part of the `main.jsbundle`, while other functions are listed as being part of `InternalByteCode.js` or are marked as `(native)` (or have unhelpful names like `anonymous`).

Fro a [code search for readFileChunk](https://github.com/search?q=repo%3Alaurent22%2Fjoplin%20readFileChunk&type=code), I see that there is one instance of `readFileChunk` directly within a `read` function, in `EncryptionService`:

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/services/e2ee/EncryptionService.ts#L511

As this occurs in both Nextcloud and OneDrive sync, I suspect that it **isn't** the OneDrive search result.

Thank you for the logs! This suggests an encryption issue instead of a sync issue.

**Comment by personalizedrefrigerator** [comment] 2023-11-03 00:58
It looks like `fileReader_` is used to create a file reader object for both encryption and decryption (so in both `encryptFile` and `decryptFile`).

# If decryption related

If the issue is `decryptFile`, because this is sync related, the most likely place it is being used is in `Resource.ts`,

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/models/Resource.ts#L186

This method is then used here (searching for the regular expression `.decrypt(` and ignoring calls that definitely aren't on a `Resource`):

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/services/DecryptionWorker.ts#L207

However, that's wrapped in a `try { ... } catch { ... }` that should log if decryption fails:

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/services/DecryptionWorker.ts#L260

Assuming that the error messages window doesn't include an error message that starts with `DecryptionWorker: `, this suggests that the error is *probably* not related to decryption.

# If related to encryption (more likely)

In this case, the following is a likely stack trace (constructed with code search, similar to the decryption version).

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/services/e2ee/EncryptionService.ts#L511

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/services/e2ee/EncryptionService.ts#L544

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/models/Resource.ts#L223

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/models/Resource.ts#L228

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/Synchronizer.ts#L695

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/Synchronizer.ts#L722

https://github.com/laurent22/joplin/blob/9723ab0ba6d17ffe1447866a070daee8cf229d3d/packages/lib/Synchronizer.ts#L1067

**Comment by ricog** [comment] 2023-11-06 14:19
I'm getting the same error on Android with Joplin Cloud. I am migrating to Joplin Cloud from Dropbox and am about 2/3 through the initial re-sync on this device. I first synced a desktop instance, and then followed up with syncing this Android instance. Both copies were in sync before switching the sync target to Joplin Cloud.

Joplin 2.12.3
Database v43
Android 14

[Debug Log Export](https://gist.github.com/ricog/ac2cf80f99307545c8b9156d307a2fd1)

![image](https://github.com/laurent22/joplin/assets/66134/0c598ab9-f644-4c98-b93e-5123887e6883)

**Comment by laurent22** [comment] 2023-11-06 16:22
@ricog, do you use encryption?

**Comment by ricog** [comment] 2023-11-06 16:52
> @ricog, do you use encryption?

Yes

**Comment by personalizedrefrigerator** [comment] 2023-11-06 19:02
I've found a way to reproduce this on an Android 12 emulator.

Reproduction steps:
1. Apply this diff:
```diff
diff --git a/packages/app-mobile/components/screens/ConfigScreen/ConfigScreen.tsx b/packages/app-mobile/components/screens/ConfigScreen/ConfigScreen.tsx
index 63e1e7f61..c24a77806 100644
--- a/packages/app-mobile/components/screens/ConfigScreen/ConfigScreen.tsx
+++ b/packages/app-mobile/components/screens/ConfigScreen/ConfigScreen.tsx
@@ -28,6 +28,9 @@ import configScreenStyles from './configScreenStyles';
 import NoteExportButton from './NoteExportSection/NoteExportButton';
 import ConfigScreenButton from './ConfigScreenButton';
 import Clipboard from '@react-native-community/clipboard';
+import Resource from '@joplin/lib/models/Resource';
+import { ResourceEntity } from '@joplin/lib/services/database/types';
+import uuid from '@joplin/lib/uuid';
 
 class ConfigScreenComponent extends BaseScreenComponent {
 	public static navigationOptions(): any {
@@ -667,6 +670,31 @@ class ConfigScreenComponent extends BaseScreenComponent {
 			</View>,
 		);
 
+		console.log('nocommit');
+		settingComps.push(
+			<View key="test-button-add-resource-without-file" style={this.styles().settingContainer}>
+				<TouchableOpacity
+					onPress={async () => {
+						let resource: ResourceEntity = Resource.new();
+						resource.id = uuid.create();
+						resource.mime = 'text/plain';
+						resource.title = 'TEST';
+						resource.file_extension = 'txt';
+
+						const targetPath = Resource.fullPath(resource);
+						await shim.fsDriver().remove(targetPath);
+
+						resource = await Resource.save(resource, { isNew: true });
+					}}
+				>
+					<Text key="label" style={this.styles().linkText}>
+						{'TEST: Add resource without file'}
+					</Text>
+				</TouchableOpacity>
+			</View>,
+		);
+		console.log('end nocommit');
+
 		settingComps.push(
 			<View key="version_info_app" style={this.styles().settingContainer}>
 				<Text style={this.styles().settingText}>{`Joplin ${VersionInfo.appVersion}`}</Text>

```
2. Enable encryption and set up a sync target
3. Click the `TEST: Add resource without file` button in settings
4. Sync

The issue seems to be related to syncing a resource that is missing a file.

**Closed as completed** 2023-11-10 14:22 UTC
Labels: bug

**Comment by laurent22** [comment] 2023-11-10 14:24
@personalizedrefrigerator improves this by providing a better error message, but the underlying issue is still present. The problem is that users may switch the sync target when they do not have all the data on their device. This is especially true on mobile where the resources might only be partially downloaded per the `resourceDownloadMode` option.

We should probably improve this as part of another issue.

**Comment by laurent22** [comment] 2023-11-10 14:28
New issue is there: https://github.com/laurent22/joplin/issues/9263
