### ISSUE TITLE
Image.md files are not synced

### ISSUE THREAD

**Issue by seeseekey** [laurent22/joplin#152] opened 2018-01-09 19:42 UTC
### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

Hi,

i had import some ENEX file to Joplin and sync them to the file system. There was images in the ENEX file. Later i remove all notes from Joplin and wait if the sync is complete. If i look in the filesystem i see many <hash>.md files with these content:

```
id: b515b3be110c2c994016b2f97bc91102
mime: image/png
filename: 
created_time: 2018-01-01T15:56:48.132Z
updated_time: 2018-01-01T15:56:48.132Z
user_created_time: 2018-01-01T15:56:48.132Z
user_updated_time: 2018-01-01T15:56:48.132Z
file_extension: 
type_: 4
```

It is possible that the meta data files for attachments not removed if the attachment is removed?

**Comment by laurent22** [comment] 2018-01-09 19:54
Yes this is a current limitation of the application - unused resources are not automatically deleted. It's on my to-do list though so it will be implemented at some point.

**Comment by laurent22** [comment] 2018-01-10 08:27
Duplicate of #154

**Closed** 2018-01-10 08:28 UTC
