### ISSUE TITLE
Bug with cursors in the editor mode when typing in Cyrillic

### ISSUE THREAD

**Issue by vendornet** [laurent22/joplin#3130] opened 2020-04-26 06:41 UTC
When editing a note with **Cyrillic** text, the **cursor is not showing in the right place and is offset**. I've changed the Keyboard Mode to Emacs just to make it more visible in the screenshot. The bug is present in all Keyboard Modes. The bug is not present on the iOS app. I've been using the app from January 2020 and the bug is present in all versions I've used so far. Screenshot 3 is showing the correct position of the cursor in the English text. The issue is only present when editing Cyrillic text. It makes it very hard to type and edit Cyrillic text as you cannot see where you are typing or editing.

## Environment
Joplin 1.0.201 (prod, darwin)

Client ID: c7bdb05d25ae406ead29a22aed8af698
Sync Version: 1
Profile Version: 28

Revision: e65af8c (master)

MacOS 10.15.4

## Steps to reproduce

1. Open Joplin app on Mac
2. Create a new note
3. Start typing in Cyrillic a little bit longer text like "абвгдежзийклмнопрст" and you will see how the cursor in the editor starts to offset and not showing the real position of the letter you are typing or editing.

## Describe what you expected to happen

Expected result is for the cursor to show the right position of the letter you are typing or editing.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/4534733/log.txt)
[console_log.txt](https://github.com/laurent22/joplin/files/4534734/console_log.txt)

## Screenshot

<img width="1721" alt="Screenshot 1 with the incorrect cursors position in the Cyrillic text" src="https://user-images.githubusercontent.com/10926427/80299885-a0c4f180-87a0-11ea-9844-e3beb3193095.png">

<img width="1721" alt="Screenshot 2 with the incorrect cursors position in the Cyrillic text" src="https://user-images.githubusercontent.com/10926427/80299956-5728d680-87a1-11ea-9498-8ee5e54d41f6.png">

<img width="1721" alt="Screenshot 3 with correct cursor position in the English text" src="https://user-images.githubusercontent.com/10926427/80299967-6019a800-87a1-11ea-82b2-b685dcab202f.png">

**Comment by roman-r-m** [comment] 2020-04-26 08:26
Duplicate of https://github.com/laurent22/joplin/issues/3125

**Comment by vendornet** [comment] 2020-04-26 09:02
For some reason I did not found the previous reported issue. It's a good idea to improve the font selection window from the settings menu. Before posting this bug, I've tried to change the fonts several times. It did not work as the fonts weren't monospace. I've tried with "Courier New" and the issue was resolved. A better font suggestion for MacOS can be implemented.

**Closed** 2020-04-27 23:37 UTC
