### ISSUE TITLE
Copy code block function includes the code block markdown code

### ISSUE THREAD

**Issue by gemorgan** [laurent22/joplin#5508] opened 2021-09-27 17:57 UTC
When I select "copy" from the code block secondary menu in the Rich Text editor, it copies the code to clipboard but also the  markdown code ( ``` )

## Environment

Joplin version:  2.3.5
Platform: Linux
OS specifics: Ubuntu 21.04

## Steps to reproduce

1. Create a code block with leading ``` or use rich text editor to create a code block
2. Switch to rich text only editor
3. Rt click code block and select copy
4. Paste clipboard anywhere else and the markdown code is included. This always needs to be deleted (except if pasting into another note.

## Describe what you expected to happen
Pasting the code into a terminal etc should not have markdown code included.

## Logfile
n/a

**Comment by tessus** [comment] 2021-09-30 10:33
Duplicate of #2383

**Closed by tessus** 2021-09-30 10:33 UTC
