### ISSUE TITLE
[feature request] enable cloning a note (mainly for lists)

### ISSUE THREAD

**Issue by leolivier** [laurent22/joplin#749] opened 2018-09-01 06:54 UTC
Hi, 
I love Joplin and I think one useful and simple feature would be to add a menu item for cloning a note. This could be used mainly for reminder todo lists. E.g. you have a list of things you need to to take with you each time you travel, you create a list with tick boxes for that [ ] and at each travel, you clone it and use the clone for ticking the things you gathered... When it's done, you can delete the clone.

**Comment by tessus** [comment] 2018-09-01 20:11
You can duplicate a note in the desktop apps (`right click the note -> select Duplicate`). Not sure, if there's a menu item for that in the mobile apps.

**Comment by foxmask** [comment] 2018-09-01 20:27
@tessus no there is no choice in any menu on mobile for that

**Comment by tessus** [comment] 2018-09-02 07:05
Imo, it shouldn't be too hard to make this available on mobile as well.

I'm sure @laurent22 can comment on this as well.

 

On September 2, 2018 2:20:45 AM EDT, leolivier <notifications@github.com> wrote:
>@tessus, sorry, I forgot to say I wanted this on mobile. I'm using the
>mobile app 90% of the time. Not sure if it's the same for everyone but
>it's clearly for me one of the strength of Joplin
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/laurent22/joplin/issues/749#issuecomment-417908088

-- 
regards Helmut K. C. Tessarek

(sent from a mobile device)

**Comment by foxmask** [comment] 2018-10-15 11:53
duplicate of #545

**Closed by foxmask** 2018-10-15 11:53 UTC
Labels: Hacktoberfest :jack_o_lantern:, enhancement, essential, mobile

**Comment by sgostelow** [comment] 2019-07-08 07:10
It seems both this and #545 were closed without the enhancement being made to the mobile apps.

**Comment by foxmask** [comment] 2019-07-08 09:17
The issue 545 is not closed, isn't it?

**Comment by sgostelow** [comment] 2019-07-11 14:50
Sorry foxmask, my bad!  I wrote that comment late at night and obviously wasn't fully awake.  I've added a comment to #545.  Thanks for being patient! :)
