### ISSUE TITLE
Desktop: Beta Editor: Toggle checkbox using Markdown Viewer does not check box in Markdown Editor

### ISSUE THREAD

**Issue by bsavant** [laurent22/joplin#10416] opened 2024-05-09 03:27 UTC
### Operating system

Linux

### Joplin version

3.0.6

### Desktop version info

Joplin 3.0.6 (prod, linux)

Client ID: b2bc7fbd98864f42af824c2361a1a1bb
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 18b9f5c

Backup: 1.4.1

### Current behaviour

1. Set Layout Button Sequence to Editor/Viewer
2. Create a note with a list of todo/checkboxes
3. Switch to the Markdown Viewer
4. Check off one of the checkboxes
5. Toggle back to the Markdown Editor and notice the checkbox is not checked.

This does still work correctly if using the Editor/Viewer/Split View sequence

### Expected behaviour

Changes to the html should render the new markdown.

https://github.com/laurent22/joplin/assets/209364/0b7eaba5-fb72-4d40-b8dd-3a066a9e5079

**Comment by personalizedrefrigerator** [comment] 2024-05-09 03:40
This seems to be a regression — I can't reproduce this in v2.14.20, but can in v3.0.6.

**Comment by TARishabh** [comment] 2024-05-09 11:48
Hey @personalizedrefrigerator ! Could you please assign this issue to me?

**Comment by personalizedrefrigerator** [comment] 2024-05-09 20:15
@TARishabh feel free to work on this without being assigned.

**Closed as completed** 2024-06-04 08:52 UTC
Labels: bug, desktop, high
