### ISSUE TITLE
Clicking checkbox anywhere in list causes screen to scroll to top of page

### ISSUE THREAD

**Issue by ikwyl6** [laurent22/joplin#4062] opened 2020-11-08 16:45 UTC
If an existing checkbox list is created and checking or unchecking any box in this list scrolls the screen to the top of the screen. See atatched video grab. This did not happen in the past. I see that 10.3.1 was updated about two weeks ago..

## Environment
Joplin version: 10.3.1 iPhone iOS App
Platform: iOS
OS specifics: Database v34, FTS enabled: 1
Synchronization using https webDAV using username and password to sync.

## Steps to reproduce
1. Open Joplin iOS app using a previously created list 
2. check or uncheck an item in your list
3. The screen scrolls to the very top of the list.

## Describe what you expected to happen
The screen not to scroll anywhere.

## Logfile
Log file from my webdav/lighttpd host:
[joplin_screen_scrollingup.txt](https://github.com/laurent22/joplin/files/5506684/joplin_screen_scrollingup.txt)
Screengrab of what is going on:
https://imgur.com/gallery/9LZyDqo

**Comment by laurent22** [comment] 2020-11-14 00:43
Duplicate of #4014

**Closed by laurent22** 2020-11-14 00:43 UTC
Labels: bug, high
