### ISSUE TITLE
Feature Request: Spell check

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#275] opened 2018-03-07 09:07 UTC
Since Joplin is note taking app having some option to check the text for spelling errors could be a nice feature.

### Operating system

- [X] Windows
- [X] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by nhoening** [comment] 2018-03-20 17:58
+1

**Comment by diogogomes** [comment] 2018-07-26 15:49
Consider to add multiple language checker. Thanks

**Comment by xelcho** [comment] 2018-09-18 17:33
+1

**Comment by alexdevero** [comment] 2018-09-19 07:30
The [electron-spell-check](https://www.npmjs.com/package/electron-spell-check-provider) package might be useful.

**Comment by noamgu** [comment] 2018-09-29 16:15
+1

**Comment by kelseyurgo** [comment] 2018-11-27 15:00
+1

**Comment by marc0der** [comment] 2018-12-21 13:52
+1

**Comment by diogogomes** [comment] 2018-12-21 15:31
Please, use the :+1: icon instead of write +1 to not overflow the mail subscribers of this issue.

Thank you

**Comment by laurent22** [comment] 2018-12-21 15:34
Another thing is that +1s are ignored during the development process. There could be a thousand of them and still the issue would be ignored. However thumbs up are used to determine what issues are the most popular so that's what you need to do to push the issue forward.

**Comment by marc0der** [comment] 2019-02-02 11:33
@diogogomes @laurent22 Totally agree and point taken. The issue does remain that you have 27 thumbs up for this issue at this point with no action taken or feedback given since the 7th March 2018 (almost a year ago).

I'm sure many folks (including myself) would love to help get this feature built but we would probably need some guidance regarding how to do this.

**Comment by blueorignal** [comment] 2019-02-15 10:05
@laurent22, following on from @marc0der, would it be helpful if the community provided you with dictionaries for different languages? Otherwise, I too would like to assist implement the spell check functionality, but would require inputs as to what you need to help make this happen. Irrespective about your decision re: spell checking, I wanted to say a **big thank you** for your work on Joplin. Joplin has become one of my most critical programs and substantially improved my general workflow.

**Comment by laurent22** [comment] 2019-02-15 18:56
If we were to implement this we would use the built-in system dictionaries, if at all possible.

**Comment by blueorignal** [comment] 2019-02-18 23:20
> If we were to implement this we would use the built-in system dictionaries, if at all possible.

Thank you. That makes perfect sense.

**Comment by laurent22** [comment] 2019-03-03 22:38
Blocked by https://github.com/laurent22/joplin/issues/1128 because Ace Editor doesn't support spell checking.

**Comment by blueorignal** [comment] 2019-03-04 02:46
Thank you for investigating. Much appreciated.

**Comment by CollinChaffin** [comment] 2019-03-09 17:39
As much as I've been ranting about how great Joplin is and quickly has become my go-to note app overtaking onenote & evernote, it's funny that spell-check is like air you just assume it's there and sometimes you forget about it as much as I need spell-check it wasn't until I hit a really tough doc and knew I needed that magic "right-click to fix" that we've all becomed so accustomed to, and found unlike any other recent app - it was not there! :(

I chucked as I typed this comment and sure enough needed to right-click-to-fix twice.  Point is this is a pretty basic feature nowadays and it looks like there is even a pre-built electron spellcheck library that could be used, so can I as as someone who is not an electron app dev but does other dev work as to what the major hurdles are on getting this implemented?  Reading above I don't see many specifics on why is CANNOT be done and hasn't been in a year, so is it just a matter of resources or ?

**Comment by laurent22** [comment] 2019-03-10 18:18
The editor we use doesn't support the built in Electron spell checking so something custom would need to be built.

**Comment by dddjjjbbb** [comment] 2019-04-02 23:04
Just a note, in case it's of any interest to any of you in the thread. Given the Electron package doesn't seem to be a viable option and this feature isn't part of the current road map, you can open any note in question in an external editor via the button to the left of the tag icon (in my case, CotEditor) and run a spell check there. It's the best solution I found for the time being. Hope that helps.

**Comment by blueorignal** [comment] 2019-04-03 00:17
@dddjjjbbb thank you. That's a simple, workable solution.

**Comment by flemay** [comment] 2019-04-04 06:13
@CollinChaffin I, too, thought spellcheck would come by default and having the workflow: write your document in Joplin -> copy into another app to fix the mistakes -> copy back to Joplin is not ideal. 

@dddjjjbbb's suggestion works although I am not sure if the file stays on disk indefinitely (i.e: `~/.config/joplin-desktop/tmp/eb94e8d92e23f72fa8fe153b9fa1f72c.md`)

**Comment by kign** [comment] 2019-07-29 15:45
Indeed, like many others pointed out, spell check is a must-have. There are multiple other problems I encountered in a few days I was trying to use it, but spellcheck is a deal breaker for me.

**Comment by deljones** [comment] 2019-08-06 12:22
I love Joplin, use it for everything and yes the absence of a spell checker is a shame so what I do , as a Windows user, is to use NotePad++ and then in Joplin point to an external. I have installed the spell check plugin for NotePad++ and asked the plug in to use Windows Native spell checking. It works perfectly for me. My spelling is atrocious at best. Click save in NotePad++ and Joplin picks it up. Nice, not ideal but as a work around I find it useful.

Just my thoughts

**Comment by vb0** [comment] 2019-08-16 10:22
Funny thing is that with Joplin I've been trying to move away from NotePad++ after I've got tired from having my sessions saved FINE every day for weeks until BANG at some point it'll forget everything (usually after an update or possibly after a hasty shutdown with "this program is preventing windows from shutting down would you like to close it"). And then I had to hunt for a bunch of files opened from I don't even remember where and some drafts I've never saved. But who knows, maybe as just a spell-checking editor npp would work well after all.

**Comment by kylepwarren** [comment] 2019-09-29 14:44
+1

**Comment by askpatrickw** [comment] 2019-12-04 20:33
> Blocked by #1128 because Ace Editor doesn't support spell checking.

That issues was closed due to inactivity.

**Comment by laurent22** [comment] 2019-12-04 22:28
No, spell checking is important and I'd like to support it, but there's no easy way to add it. Indeed the entire editor needs to be changed, which I hope will be done some day. I'm hoping that Code Mirror 6, if it's ever released, would be a good replacement as it could also be used on mobile.

**Comment by i-need-to-tell-you-something** [comment] 2020-01-05 16:13
I see that the previously mentioned [electron-spell-check-provider](https://www.npmjs.com/package/electron-spell-check-provider#usage) only support en-US (for now). 

I wanted to throw another idea in the air while not knowing much about the topic. [Enchant](https://en.wikipedia.org/wiki/Enchant_%28software%29) looks like something potentially usable. The things that caught my eye were user customization and support for OS-native spell-checkers.

**Comment by dissolved** [comment] 2020-01-15 18:14
> No, spell checking is important and I'd like to support it, but there's no easy way to add it. Indeed the entire editor needs to be changed, which I hope will be done some day. I'm hoping that Code Mirror 6, if it's ever released, would be a good replacement as it could also be used on mobile.

Thank you @laurent22 for validating the need, and explaining why it isn't there yet.

**Comment by shahin-bayat** [comment] 2020-03-25 15:13
👍

**Comment by EricB10** [comment] 2020-04-05 15:33
Anyone know of an easy work-around or 3rd party app on Mac/Linux that could be used to spellcheck in real time?

**Comment by dissolved** [comment] 2020-04-05 15:36
@EricB10 I think using an external editor ([more here)](https://joplinapp.org/#external-text-editor) seems to be the best work around until proper spell checking is added 🙏

**Comment by AngelCrawford** [comment] 2020-04-05 15:36
> Anyone know of an easy work-around or 3rd party app on Mac/Linux that could be used to spellcheck in real time?

Typora, open the Note with the "Edit in external Editor". Typora has a great Spellcheck, but you can use every other Markdown Editor.

**Comment by zrml** [comment] 2020-04-07 09:48
FWIW it'd be great to have the spellchecker implemented as a plugin option so people can use whatever they prefer or different languages, etc. Unfortunately, I have no idea how this would work or if there even is a standard for it. However, I wanted to share that I use Grammarly and as of late I see they now support Confluence (Atlassian) which they did not use to, so I think maybe they could support Joplin if the right API is there... (incidentally, Grammarly just corrected a couple of misspelling here on Chrome at Github) :) - a must as many already said. THANK YOU.

**Comment by severus-tux** [comment] 2020-04-20 11:02
Any news on this?

**Comment by robsonpeixoto** [comment] 2020-05-04 10:15
Maybe could use this: https://www.npmjs.com/package/electron-spellchecker
From description:

electron-spellchecker:
- Spell checks in all of the languages that Google Chrome supports by reusing its dictionaries.
- Automatically detects the language the user is typing in and silently switches on the fly.
- Handles locale correctly and automatically (i.e. users who are from Australia should not be corrected for 'colour', but US English speakers should)
- Automatically downloads and manages dictionaries in the background.
- Checks very quickly, doesn't introduce input lag which is extremely noticable
- Only loads one Dictionary at a time which saves a significant amount of memory

**Comment by Tiger862000** [comment] 2020-06-17 14:54
If you want a speel and grammar checker with wide support for many languages and already a broad ecosystem, then have a look at “LanguageTool”. It has besides fool-proof spell check also an inbuilt grammar checks, all for free and open source. Code can be found here: https://github.com/languagetool-org/

**Comment by ashiquelal** [comment] 2020-06-28 18:23
> > Anyone know of an easy work-around or 3rd party app on Mac/Linux that could be used to spellcheck in real time?
> 
> Typora, open the Note with the "Edit in external Editor". Typora has a great Spellcheck, but you can use every other Markdown Editor, @EricB10

@laurent22 Would it be possible for you to combine one of the open source markdown editor so that it provides the spell checking too? Something like Mark Text which is semi-WYGIWYS ?

**Comment by ashiquelal** [comment] 2020-06-28 18:25
> > Anyone know of an easy work-around or 3rd party app on Mac/Linux that could be used to spellcheck in real time?
> 
> Typora, open the Note with the "Edit in external Editor". Typora has a great Spellcheck, but you can use every other Markdown Editor, @EricB10

@laurent22 Would it be possible for you to combine one of the open source markdown editor so that it provides the spell checking too? Something like Mark Text which is semi-WYGIWYS ?

**Comment by jmacmichael** [comment] 2020-06-29 04:14
> Anyone know of an easy work-around or 3rd party app on Mac/Linux that could be used to spellcheck in real time?

On Linux, I'm using terminal + the aspell utility as the external editor. This makes Ctrl-E go to a terminal-based spell check window, not an editor per se. But as I don't use an external editor for anything else, this works well for me. The configuration is (update for your terminal prog):

Text editor command path: `/usr/bin/gnome-terminal`
Text editor command args: `-- /usr/bin/aspell -c`

This opens gnome-terminal with the params (see gnome-terminal help) to open an aspell session to check the file that Joplin gives it. Then I fix any spelling mistakes inside aspell and it saves the file. Et voila.

**Comment by NukeManDan** [comment] 2020-07-02 01:30
+1 :pray:

**Comment by Abhi18022** [comment] 2020-07-29 09:21
+1

**Comment by karma12gaming** [comment] 2020-08-15 13:44
I have terrible spelling. Even a basic spell check would be greatly appreciated as I primarily use Joplin for academic notation.

**Comment by hypergig** [comment] 2020-08-19 13:55
I have never seen a github issue with so many thumbs up before... this is a must have.

Throw a feature bounty on this, I would easily donate $100 bucks to the cause and I only discovered joplin 12 hours ago.

![Screenshot from 2020-08-19 09-52-47](https://user-images.githubusercontent.com/8643560/90643623-c79cad00-e201-11ea-8457-fe08bef32590.png)

**Comment by itpropaul** [comment] 2020-08-28 12:10
+1

**Comment by laszukdawid** [comment] 2020-08-29 20:03
Hey @laurent22 ,
At least for me it still isn't clear whether you/anyone is working on this. You mentioned that the issue lays on Joplin's dependency and a proper way would be to rewrite the editor. That's been a year ago. The original issue post has some ticks but I'm not sure when were those done.

Just checked that Monaco-editor has open spell checking feature request (https://github.com/microsoft/monaco-editor/issues/1977) but there's little activity on it.

Given the interest in the issue, could I ask to be more explicit with the progress/state? There are many devs using Jopling so maybe someone could contribute. I'd be happy to know if this is something I could help with :)

**Comment by hypergig** [comment] 2020-09-11 13:52
I notice that you can open the devtools in Joplin, is there a javascript hack that we can use to support spellcheck? Like copy / paste ye giant block of js into the console sorta scrapy fix I am looking for here...

**Comment by hypergig** [comment] 2020-09-12 22:59
:shield: I pledge $100 bucks to this feature

**Comment by tinchi** [comment] 2020-10-13 02:43
👍

**Comment by zrml** [comment] 2020-10-13 07:30
This is important IMO and deserves attention for long-term product consideration by prospect & survivability.
Thanks

**Comment by laurent22** [comment] 2020-10-13 20:58
Just an update - thanks to the effort of @CalebJohn to replace the old editor with a new one, it's now technically possible to add spell checking. It doesn't mean it's going to be done right away but at least we got closer to eventually have spell checking.

**Comment by hychrisli** [comment] 2020-10-14 15:13
+1

**Comment by ChronoTriggered** [comment] 2020-11-09 02:28
So yeah I started using this a few months ago, and spell checking is the main thing I miss rn

**Comment by laurent22** [comment] 2020-11-26 11:48
After nearly 3 years and 340 votes, this feature is finally implemented! Please have a look at the announcement post, in particular for information on how to enable it in the Markdown Editor: https://www.patreon.com/posts/44328867

**Closed by laurent22** 2020-11-26 11:48 UTC
Labels: backlog, desktop, enhancement

**Comment by kylepwarren** [comment] 2020-12-14 22:35
Not doing this for so long was kind of like hiding the last puzzle piece so you can be the one who finishes the puzzle. This is a good app.

**Comment by alex-rusakevich** [comment] 2023-10-15 19:29
> If you want a spell and grammar checker with wide support for many languages and already a broad ecosystem, then have a look at “LanguageTool”. It has besides fool-proof spell check also an inbuilt grammar checks, all for free and open source. Code can be found here: https://github.com/languagetool-org/

+1 for LanguageTool. Chrome default spell checker doesn't have Belarusian language support, but LT has. Besides that, LT is far more advanced than the default Chrome spell checker, as stated above.

I like Joplin, and I'd like to write everything using it, but absence of LT makes me use Google Docs or Zettlr to write something serious like books, poems and news articles.

**Comment by ttrakker** [comment] 2023-10-17 14:59
Will this be implemented? Thinking this is a deal breaker for me and joplin now.
