### ISSUE TITLE
No Preview, when using file:// (Only tested PDF)

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#4332] opened 2021-01-10 18:48 UTC
## Environment

Joplin version: 1.5.14 (from AUR) and Pre-Release 1.6.6 (AppImage)
Platform: GNU/Linux (Desktop)
OS specifics: Archlinux

## Steps to reproduce

1. Attach a PDF-File to a note
2. Change the path from e.g. ``[test.pdf](:/631eaa8ceaf8449185096acf93ba9efd)`` to ``[test.pdf](file:///home/mika/test.pdf)``
3. See that the Link (opening it) is still working, but the preview disappeared

## Describe what you expected to happen
I expected to also see the preview, when I provide a full absolute path.

## Logfile
I found nothing interresting there (Only default output)
```
2021-01-10 19:17:32: "Loaded note:", "{"id":"28b7b9854548483397faa9fa6c0c5731","parent_id":"86d4a9426ed040f9acaced269c7aa868","title":"","body":"","created_time":1610302652342,"updated_time":1610302652342,"is_conflict":0,"latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplin-desktop","source_application":"net.cozic.joplin-desktop","application_data":"","order":0,"user_created_time":1610302652342,"user_updated_time":1610302652342,"encryption_cipher_text":"","encryption_applied":0,"markup_language":1,"is_shared":0,"type_":1}"
2021-01-10 19:17:32: "CodeMirror: execCommand", "{"name":"editor.focus"}"
2021-01-10 19:17:34: "SearchEngine: Updating FTS table..."
2021-01-10 19:17:34: "Saving settings..."
2021-01-10 19:17:34: "Settings have been saved."
2021-01-10 19:17:34: "SearchEngine: Updated FTS table in 67ms. Inserted: 6. Deleted: 0"
2021-01-10 19:17:37: "CommandService::execute:", "attachFile", "[]"
2021-01-10 19:17:37: "CodeMirror: execCommand", "{"name":"attachFile"}"
2021-01-10 19:17:41: "Attaching /home/mika/test.pdf"
2021-01-10 19:17:41: "CommandService::execute:", "editor.focus", "[]"
2021-01-10 19:17:41: "CodeMirror: execCommand", "{"name":"editor.focus"}"
2021-01-10 19:17:41: "File was attached."
2021-01-10 19:17:42: "Saving note...", "{"id":"28b7b9854548483397faa9fa6c0c5731","parent_id":"86d4a9426ed040f9acaced269c7aa868","title":"test.pdf","body":"[test.pdf](:/631eaa8ceaf8449185096acf93ba9efd)"}"
2021-01-10 19:17:42: "Scheduling sync operation...", "30000"
2021-01-10 19:17:52: "SearchEngine: Updating FTS table..."
2021-01-10 19:17:52: "Saving settings..."
2021-01-10 19:17:52: "CommandService::execute:", "textCopy", "[]"
2021-01-10 19:17:52: "CodeMirror: execCommand", "{"name":"textCopy"}"
2021-01-10 19:17:52: "Settings have been saved."
2021-01-10 19:17:52: "SearchEngine: Updated FTS table in 71ms. Inserted: 1. Deleted: 0"
2021-01-10 19:17:54: "ResourceService::indexNoteResources: Start"
2021-01-10 19:17:54: "Saving settings..."
2021-01-10 19:17:54: "Settings have been saved."
2021-01-10 19:17:54: "ResourceService::indexNoteResources: Completed"
2021-01-10 19:17:54: "ResourceService::deleteOrphanResources:", "[]"
2021-01-10 19:17:56: "CommandService::execute:", "textCopy", "[]"
2021-01-10 19:17:56: "CodeMirror: execCommand", "{"name":"textCopy"}"
2021-01-10 19:18:04: "CommandService::execute:", "textCopy", "[]"
2021-01-10 19:18:04: "CodeMirror: execCommand", "{"name":"textCopy"}"
2021-01-10 19:18:11: "CommandService::execute:", "textCopy", "[]"
2021-01-10 19:18:11: "CodeMirror: execCommand", "{"name":"textCopy"}"
2021-01-10 19:18:12: "Preparing scheduled sync"
2021-01-10 19:18:12: "Synchroniser is missing credentials - manual sync required to authenticate."
2021-01-10 19:18:19: "CommandService::execute:", "textPaste", "[]"
2021-01-10 19:18:19: "CodeMirror: execCommand", "{"name":"textPaste"}"
2021-01-10 19:18:19: "Saving note...", "{"id":"28b7b9854548483397faa9fa6c0c5731","parent_id":"86d4a9426ed040f9acaced269c7aa868","title":"test.pdf","body":"[test.pdf](file:///home/mika/test.pdf)"}"
2021-01-10 19:18:19: "Scheduling sync operation...", "30000"
2021-01-10 19:18:21: "CommandService::execute:", "textCopy", "[]"
2021-01-10 19:18:21: "CodeMirror: execCommand", "{"name":"textCopy"}"
2021-01-10 19:18:29: "SearchEngine: Updating FTS table..."
2021-01-10 19:18:29: "Saving settings..."
2021-01-10 19:18:29: "Settings have been saved."
2021-01-10 19:18:29: "SearchEngine: Updated FTS table in 41ms. Inserted: 1. Deleted: 0"
2021-01-10 19:18:49: "Preparing scheduled sync"
2021-01-10 19:18:49: "Synchroniser is missing credentials - manual sync required to authenticate."
```

## Other
I also tried release 1.6.2, because it stated ``Fixed: file:// URLs would not be rendered correctly``, but it didn't work

**Comment by ron-debajyoti** [comment] 2021-03-18 15:15
I tested this on release 1.8.0 in Ubuntu 18.04 and the issue still exists. I would like to take this up as a beginner if that's fine @laurent22

**Comment by ron-debajyoti** [comment] 2021-03-23 12:58
Hi ! Sorry for the delay in finding out the problem.

The issue is seen while attaching pdf, audio, and video files in a note, and its caused due to this [line](https://github.com/laurent22/joplin/blob/656673ed57bd0d3a010a4d28f6852c01a0e64730/packages/renderer/urlUtils.js#L3) which is used by all the `urlUtils` functions, which are used in rules like this [here](https://github.com/laurent22/joplin/blob/656673ed57bd0d3a010a4d28f6852c01a0e64730/packages/renderer/MdToHtml/rules/link_open.ts#L11)

A possible solution is to update the regex mentioned to accept resource files starting with `file:///home` but we also need to change the `parseResourceUrl` function [(here)](https://github.com/laurent22/joplin/blob/656673ed57bd0d3a010a4d28f6852c01a0e64730/packages/renderer/urlUtils.js#L13) in `urlUtils.js` accordingly. 

Would appreciate your views regarding this @laurent22

**Comment by laurent22** [comment] 2021-03-23 14:09
Hmm, perhaps we aren't going to support this then. Support for `file://` is not really official and the changes you suggest would mean blurring the line between what's an embedded resource and what's an external file, which would affect many parts of the code. In general people should use the built-in resource mechanism if they want all features to be working.

**Comment by ron-debajyoti** [comment] 2021-03-23 15:13
Yeah I understand that `ResourceUrl` is definitely based on the regex used in `urlUtils`. 

But I couldn't help but try it with image files and it worked without showing the bug! I noticed that the regex for image files is set [here](https://github.com/laurent22/joplin/blob/656673ed57bd0d3a010a4d28f6852c01a0e64730/packages/renderer/MdToHtml/rules/html_image.ts#L27). Is there any specific reason why we aren't strictly considering embedded resource for image files? Is it maybe due to them being of lesser size?

**Comment by ron-debajyoti** [comment] 2021-03-25 20:00
Update: @laurent22 Since we are not going to support this, maybe we should close this issue.

**Comment by laurent22** [comment] 2021-06-23 11:20
This is tricky to solve and we only partially support file:// protocol so closing this for now.

**Closed by laurent22** 2021-06-23 11:20 UTC
Labels: bug, desktop, medium
