### ISSUE TITLE
Pressing Shortcut keys is adding Letters to the Editor

### ISSUE THREAD

**Issue by vijayveluri03** [laurent22/joplin#4814] opened 2021-04-06 03:29 UTC
![Annotation 2021-04-06 085209](https://user-images.githubusercontent.com/2283037/113654482-8a642d00-96b5-11eb-8f92-a09f03781033.png)

When i use a shortcut to open Tags (Ctl + Alt + T ) ,It opens tag overlay but also added a Letter "T" in the editor. Refer to the screen shot above. 

I have found this issue in Windows application. Havent checked in Mac. 

## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: Windows 10 pro

## Steps to reproduce

1. Create a new note. 
2.  Have your cursor on Title or the Description (notes)
3. Press "Ctrl + Alt + T" (on windows)

## Describe what you expected to happen

It is expected to do the action associated with the shortcut, but not to have those keys modify my notes.

**Comment by tessus** [comment] 2021-04-06 08:15
I was not able to reproduce it on macOS Joplin 1.8.1 dev 29a8e815d.

Neither in CodeMirror nor in the WYSIWYG editor.

**Comment by Pavan-Bellam** [comment] 2021-04-07 05:47
even I was not able to reproduce it on windows 10

**Comment by vijayveluri03** [comment] 2021-04-07 06:04
Thanks for Responding. 

https://user-images.githubusercontent.com/2283037/113818279-2fa20280-9795-11eb-8c43-90fe360944c3.mp4

Please find the Repro video.

**Comment by JackGruber** [comment] 2021-04-08 05:35
I can't replicate the issue with `CRT+ALT+T` on Windows 10 and Joplin 1.8.1

**Comment by darkcheftar** [comment] 2021-04-09 09:52
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>t</kbd> On any typing Environment is Producing latin alphabet. [ṭ](https://en.wikipedia.org/wiki/%E1%B9%AC#:~:text=%E1%B9%AC%20(minuscule%3A%20%E1%B9%AD)%20is,as%20it%20sounds%20in%20English.)

**Comment by tessus** [comment] 2021-04-10 11:31
@darkcheftar this makes no sense. What do you mean by "on any"? Certainly not on macOS and as you can see others can't even reproduce it on Windows.

**Comment by darkcheftar** [comment] 2021-04-10 12:00
I don't know about Mac Os
Sorry for being ambiguous.
On Windows when I tried to use the shortcut <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>t</kbd>.
-  notepad 
- Joplin's Note's Title 
- chrome search bar
- Typora
I got the same result.
May be that is because of some default behaviour of the shortcut which may not have been prevented by the implementation in the app.
![image](https://user-images.githubusercontent.com/54063851/114268870-0f867380-9a21-11eb-9a4d-f8d8d5f6f2bd.png)
![image](https://user-images.githubusercontent.com/54063851/114268903-42306c00-9a21-11eb-8e98-dac2f48ff882.png)
![image](https://user-images.githubusercontent.com/54063851/114268912-60966780-9a21-11eb-84e4-b4abfdb0cb69.png)
![image](https://user-images.githubusercontent.com/54063851/114268977-c682ef00-9a21-11eb-849f-cb7fc124f39c.png)

**Comment by JackGruber** [comment] 2021-04-10 13:39
Sorry, but this is no Jublin Bug, 
This is a setting on your system, when this happens in every program!

**Comment by darkcheftar** [comment] 2021-04-10 13:50
> * Maybe that is because of some default behaviour of the shortcut in windows
That is what I'm emphasising @JackGruber 😃

**Comment by vijayveluri03** [comment] 2021-04-11 02:07
It appears, this issue occurs only when Language setting is set to "English (India)". Tested with "English(US)", seems to be fine. 
Like @darkcheftar @JackGruber have pointed it out, perhaps its some default behavior for those languages.

**Comment by darkcheftar** [comment] 2021-06-02 18:22
so, @vijayveluri03 Does this issue needed to be taken further or shall it be closed?

**Comment by vijayveluri03** [comment] 2021-07-10 11:34
It appears this is the way Windows OS handles that shortcut for certain language settings. So this ccan be be closed. Thank you @darkcheftar

**Comment by darkcheftar** [comment] 2021-07-19 08:33
closing the issue is only possible for contributors or issue creator or by the owner of the repo so @vijayveluri03. It's in your hands to close the issue.

**Closed** 2021-07-19 09:08 UTC
Labels: bug, desktop, editor
