### ISSUE TITLE
Abort during sync (Android)

### ISSUE THREAD

**Issue by HelmutL** [laurent22/joplin#453] opened 2018-04-24 06:15 UTC
### Operating system
- Windows
- Android

### Application
- Desktop
- Mobile

I have installed Joplin on Windows 10 desktop and Android. I created several books and notes (from desktop) and sync'ed them to the Android without problems, using encryption and WEBDAV. Also creating notes on Android and sync to desktop was ok.

Then, I imported a lot of notes originating from Evernote using the desktop application. 
The synchronization on Android counts up to 74/219 objects, then Joplin terminates inadvertently. This can be repeated and happens every time. I attach the syncReport.

Note:
the synchronisation to another PC is ok, so the data in the cloud must be correct.

[syncReport.zip](https://github.com/laurent22/joplin/files/1941091/syncReport.zip)

**Comment by laurent22** [comment] 2018-04-24 07:10
It seems the log doesn't have the crash info. Is there any chance you could create a bug report from developer mode ?

To do so first enable developer mode - https://developer.android.com/studio/debug/dev-options.html

Then replicate the crash in Joplin

Finally go to the developer menu and press Create bug report. If you could send this report to me that would be great.

**Comment by HelmutL** [comment] 2018-04-24 07:31
Logs attached
[newSyncReport.txt](https://github.com/laurent22/joplin/files/1941378/newSyncReport.txt)
![bugreport-2018-04-24-09-22-37](https://user-images.githubusercontent.com/17042607/39172494-395f708c-47a2-11e8-8922-06cbfd621e8c.png)
[newSyncReport.zip](https://github.com/laurent22/joplin/files/1941379/newSyncReport.zip)

**Comment by HelmutL** [comment] 2018-04-24 07:34
Sorry,, forgot this in previous comment.

[bugreport-2018-04-24-09-22-37.zip](https://github.com/laurent22/joplin/files/1941386/bugreport-2018-04-24-09-22-37.zip)

**Comment by HelmutL** [comment] 2018-04-24 09:59
Requested info attached to bugreport.


Am 24.04.2018 um 09:10 schrieb Laurent Cozic:

**Comment by HelmutL** [comment] 2018-05-03 09:58
Hi,

the largest file in .resource is about 41 MB.

BTW:
I do not understand why Joplin (Java) wants to allocate additional 110 MB.
I do not understand why the total size of .resource is around 70 MB.

The size of a local export of whole Joplin data on the desktop is around 14 MB. In my personal opinion if Joplin needs so much space on disk (i.e. cloud) and memory there is something wrong, either in the programming or in the design.

Regards

**Comment by laurent22** [comment] 2018-05-03 10:06
Duplicate of #371

**Closed by laurent22** 2018-05-03 10:06 UTC
Labels: bug
