### ISSUE TITLE
The Mac app doesn't sync with webdav because of an expired certificate...which is not expired on my Synology nas.

### ISSUE THREAD

**Issue by romu70** [laurent22/joplin#5611] opened 2021-10-21 18:41 UTC
The Mac app doesn't sync with webdav because of an expired certificate...which is not expired on my Synology nas.

## Environment

Joplin version: 2.4.12
Platform: macOS BigSur
OS specifics: 

## Steps to reproduce

1. Open the app, the sync occurs at launch

And then you see in the sidebar:

```
Completed: 21/10/2021 20:04 (22s)
Last error: FetchError: request to https://webdav.xxxxxxx/notes/info.json failed, reason: certificate has expired
```

Another way to reproduce is to go to Joplin settings and "Check synchronisation configuration", and...same result.

I guess this happens since the update to 2.4.12 I did some days ago. No problem before that. I tried to downgrade to 2.4.9, no luck, the problem persists.

## Describe what you expected to happen

A sync without error. The certificate attached to my webdav API expires on December 27. The problem does not happen with the iOS app.

**Comment by Daeraxa** [comment] 2021-10-21 20:07
Pinned issue https://github.com/laurent22/joplin/issues/5513
Turn on ignore TLS errors or upgrade to the pre-release

**Comment by tessus** [comment] 2021-10-21 21:13
duplicate of #5513

**Closed by tessus** 2021-10-21 21:13 UTC
