### ISSUE TITLE
Backticks in command crash the editor 

### ISSUE THREAD

**Issue by Koroeskohr** [laurent22/joplin#12] opened 2017-11-30 13:18 UTC
To replicate : 
```
:config editor "vim`
```
then press Enter.

(Edit : MacOS Sierra, terminal app with iTerm2, installed through npm if ever needed)

Associated stacktrace : 
```
unhandled promise rejection Promise {
  <rejected> Error: Unclosed quote in command line: config editor "vim`
    at splitCommandString (/Users/victor/.nvm/versions/node/v8.5.0/lib/node_modules/joplin/lib/string-utils.js:180:9)
    at AppGui.processCommand (/Users/victor/.nvm/versions/node/v8.5.0/lib/node_modules/joplin/app-gui.js:524:14)
    at Object.action (/Users/victor/.nvm/versions/node/v8.5.0/lib/node_modules/joplin/app-gui.js:286:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } reason: Error: Unclosed quote in command line: config editor "vim`
    at splitCommandString (/Users/victor/.nvm/versions/node/v8.5.0/lib/node_modules/joplin/lib/string-utils.js:180:9)
    at AppGui.processCommand (/Users/victor/.nvm/versions/node/v8.5.0/lib/node_modules/joplin/app-gui.js:524:14)
    at Object.action (/Users/victor/.nvm/versions/node/v8.5.0/lib/node_modules/joplin/app-gui.js:286:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by yafp** [comment] 2017-12-01 14:09
I can't reproduce that on Linux 0.10.28

* Created a new note
* pasted your example string to the note content field
* confirmed line by pressing enter

Joplin is still working without issues.

**Comment by Koroeskohr** [comment] 2017-12-01 14:46
It's not about note content, it's a command in the terminal app on OSX
```
$ joplin
> :config editor "vim`
```
then it crashes

**Comment by laurent22** [comment] 2017-12-01 14:51
Yes I see what's the issue is. Normally it should display the error "Unclosed quote in command line" but not crash.

**Comment by laurent22** [comment] 2017-12-01 18:13
Hi, that should be fixed in the latest version.

**Closed by laurent22** 2017-12-01 18:13 UTC
Labels: bug
