### ISSUE TITLE
Deleting notebooks/reorganizing notes system crash.

### ISSUE THREAD

**Issue by Viscometer** [laurent22/joplin#3463] opened 2020-07-06 18:54 UTC
Deleting notebooks/reorganizing notes.
System Crashed.
I am running Latest Release.
-->

## Environment

Joplin version: 1.0.226  Rev 9c057071(master) 
Platform: Windows 10
OS specifics: 64 bit

## Steps to reproduce

1. Added notebook moved or deleted notebook not sure what last action exactly was.

## Describe what you expected to happen
I expected the ntoebook to be added/deleted or moved. 

## Logfile
`
Error from joplin:
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Cannot read property 'id' of null

Stack trace
TypeError: Cannot read property 'id' of null
    at NoteToolbar (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteToolbar\NoteToolbar.js:51:43)
    at renderWithHooks (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:15108:18)
    at mountIndeterminateComponent (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17342:13)
    at beginWork$1 (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18486:16)
    at HTMLUnknownElement.callCallback (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397:16)
    at invokeGuardedCallback (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454:31)
    at beginWork$$1 (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23217:7)
    at performUnitOfWork (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22208:12)
    at workLoopSync (C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22185:22)
Component stack

    in NoteToolbar (created by Connect(NoteToolbar))
    in Connect(NoteToolbar) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

Err
`

**Comment by laurent22** [comment] 2020-07-06 23:43
Duplicate of the bug report just below yours: https://github.com/laurent22/joplin/issues/3461

**Closed by laurent22** 2020-07-06 23:43 UTC
Labels: bug
