### ISSUE TITLE
[Feature request] Support widgets for todo lists

### ISSUE THREAD

**Issue by FleischKarussel** [laurent22/joplin#909] opened 2018-10-23 08:08 UTC
### Operating system

- Android

### Application

- Mobile

### Description
I'm used to Wunderlist and their implementation of a widget for the todo list and missing this for Joplin.
https://6wunderkinder.desk.com/customer/de/portal/articles/1641035-android-widget-zur-listen%C3%BCbersicht
![grafik](https://user-images.githubusercontent.com/1714374/47345070-2f3b4d00-d6aa-11e8-95c9-864658f4b7a8.png)

As far as I can tell there is not a single widget currently implemented.
#875 goes into that direction but is another aspect.
So it seems it needs to be started from scratch to get this sorted out.
I do not have any programming skills nor development experience (with android apps) yet.

Probably I should start here?
Any hints or links how to get started?

thanks and best regards
FleischKarussel

**Comment by foxmask** [comment] 2018-10-23 09:28
can be duplicate of #19

**Comment by FleischKarussel** [comment] 2018-10-23 09:41
damn it, I searched the open issues list twice.
anyway, we then should upvote this one. :)

https://react-native.canny.io/feature-requests/p/android-home-screen-widget

**Comment by foxmask** [comment] 2018-10-23 09:58
3years old :(

**Closed** 2018-10-23 09:58 UTC
