### ISSUE TITLE
Search Functionality Issue in v2.10.2

### ISSUE THREAD

**Issue by godylockz** [laurent22/joplin#7486] opened 2022-12-19 06:15 UTC
## BUG
In v2.10.2, when using the keyboard shortcut CTRL+F, it opens the search bar (below note window). However when typing afterwards, the typing focus is still inside the note not in the search bar (below note window).

## Solution
Change the focus back to the search bar for typing after CTRL+F is pressed to type directly after when searching within the note.

**Comment by laurent22** [comment] 2022-12-19 20:29
OS?

**Comment by godylockz** [comment] 2022-12-19 23:01
> OS?

Windows 11 sorry about that!

**Comment by sanskarfc** [comment] 2022-12-20 09:09
reproduced in macOS too. 

Seems to be weird. I would like to work on this bug for some time 👍

**Comment by sanskarfc** [comment] 2022-12-21 17:46
Is this code snippet relevant to this issue?

https://github.com/laurent22/joplin/blob/115cf116a2a9ab5024fd8fb2e531d6bf97d81d5c/packages/app-desktop/gui/MainScreen/commands/search.ts#L3-L18

**Comment by laurent22** [comment] 2022-12-22 14:01
Duplicate of #7520

**Closed as completed by laurent22** 2022-12-22 14:01 UTC
Labels: bug, desktop, high
