### ISSUE TITLE
[question] Why is there no web app for joplin?

### ISSUE THREAD

**Issue by ecthiender** [laurent22/joplin#852] opened 2018-10-05 03:48 UTC
It seems a little strange that there exists mobile and desktop app but no web app for joplin.

Especially, as the dekstop app is in Electron?

Any plans for having a web app? What are the reasons for not having a web app?

I'm not too keen on running a desktop Electron app, I'd much prefer running a web app.

PS: This is just a question to understand the standpoint.

**Comment by laurent22** [comment] 2018-10-05 08:53
Duplicate of #228

**Closed by laurent22** 2018-10-05 08:53 UTC

**Comment by ecthiender** [comment] 2018-10-06 09:28
@laurent22 how is this a duplicate of #228 ? It talks about Nextcloud integration. Please correct me and point me to the right comment where it gets discussed about (not supporting) a standalone web client (and its reasons). From the comments all I can see is talks about supporting markdown and Nextcloud integration.

**Comment by laurent22** [comment] 2018-10-06 10:37
The linked issue is about accessing the notes on the internet in general, whether by editing the files on Nextcloud, or via a web client, none of these possibilities exist at the moment.

It's not a question about supporting such solution or not - before supporting it, someone has to spend a few months developing it.

**Comment by ecthiender** [comment] 2018-10-16 06:12
> ... none of these possibilities exist at the moment.

Hmm. That's a little weird. You have a desktop Electron app (written in Javascript) which fetches notes from the server (over internet) and displays them. Is this understanding wrong from my part?

If the above is the case, then why would having the same functionality (using Javascript) be different on the browser fundamentally? I'm sorry if I'm missing something obvious, but I cannot understand why they would be different. 

In fact, the whole point of Electron is so that you can have a desktop and a web app with the same code base. Agreed it wouldn't be that 100% of code from the desktop app will work on the web, there would be some modifications required, but I can't fathom why would be "few months" of development time.

Sorry if I'm spamming you, but this sounds very strange, hence the brain-dump. Sorry again.

**Comment by laurent22** [comment] 2018-10-16 07:48
The app uses an SQLite database for storage and browsers don't have SQLite databases for example, so there would be a lot of work to convert this. It also caches the resource files to the file system and browser would have to load them from a server, so lots of changes there as well, etc.

**Comment by immartian** [comment] 2019-03-11 01:02
it's pretty much useful for Joplin web as a roaming solution to Chromebook users, especially in this period when Linux is quite much not mature on Chromebook, with no support to AppImage. Millions of users could be affected.

**Comment by MFAshby** [comment] 2019-04-03 08:32
There's an in-browser sqlite database: https://github.com/kripken/sql.js/
and an in-browser filesystem implementation: https://github.com/jvilk/BrowserFS
so it's not insurmountable, but I don't expect it's trivial either.
