### ISSUE TITLE
Mermaid erDiagram not working in Joplin 1.1.1

### ISSUE THREAD

**Issue by MHoeller** [laurent22/joplin#3740] opened 2020-09-12 19:56 UTC
A mermaid  erDiagram is not rendered in Joplin 1.1.1

## Environment
Joplin version: 1.1.1
Platform:  AppImage
OS specifics:  Ubuntu 20.04  LTS

## Steps to reproduce
Add mermaid code to a notebook: 
```mermaid
erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER }|..|{ DELIVERY-ADDRESS : uses
```

This code is not rendered. The rendering in general seems to work since this code IS renderd:
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

The mermaid syntax should be ok, the example is take from the mermaid page

**Comment by CalebJohn** [comment] 2020-09-13 06:32
It looks like erDiagrams were [added in mermaid 8.5.0](https://github.com/mermaid-js/mermaid/releases/tag/untagged-31c93788afe260d914bb). And Joplin uses mermaid 8.4.6, so these diagrams are not supported in Joplin currently.

@laurent22 would you accept a pull bumping the mermaid version? It seems like the last few release have (8.8.0 and 8.7.0) have primarily been focused on bug fixing.

**Comment by laurent22** [comment] 2020-09-13 10:27
Yes sure, feel free to go ahead and update, provided there's no breaking changes. Also make sure you run `npm run buildAssets` from the joplin-renderer folder to make sure all assets are installed properly.

**Comment by tessus** [comment] 2020-09-16 22:50
Duplicate of #3108

**Closed** 2020-09-16 22:51 UTC
