### ISSUE TITLE
Joplin not Synchronizing with OneDrive on Ubuntu 22.04 - IPv6 Unreachable Error

### ISSUE THREAD

**Issue by joseroane** [laurent22/joplin#9438] opened 2023-12-04 00:06 UTC
### Operating system

Linux

### Joplin version

2.12.19

### Desktop version info

Joplin 2.12.19 (prod, linux)

Client ID: c063ad0339de451984232b92a592cf55
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: 7081046

Metis: 0.1.5

### Current behaviour

Joplin stopped syncing with Onedrive on the Ubuntu app. This happened in the previous version, showing the same log as it shows right now. 
Upgrading to the most recent version fixed it the first time but it shows again now.
Syncing on Windows and iPad is working fine. 

### Logs

This is the error showed while trying to sync:

request to https://login.microsoftonline.com/common/oauth2/v2.0/token failed, reason: connect EHOSTUNREACH 2603:1036:3000:e8::2:443

Authentication was not completed (did not receive an authentication token).

**Comment by personalizedrefrigerator** [comment] 2023-12-04 03:22
Possible duplicate of https://github.com/laurent22/joplin/issues/8788 (which should be fixed in the latest pre-release).

**Closed as completed** 2023-12-07 00:59 UTC
Labels: bug
