### ISSUE TITLE
Fatal error when deleting notebook

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#3461] opened 2020-07-06 09:30 UTC
When trying to delete a notebook, I wasn't clear if it had worked or not (there is no progress bar etc.) and I clicked around the UI a little. It then was clear that the note counter was decreasing. But I then received an  error:

```
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Cannot read property 'id' of null

Stack trace
TypeError: Cannot read property 'id' of null
    at NoteToolbar (/tmp/.mount_JoplinsIOzUC/resources/app.asar/gui/NoteToolbar/NoteToolbar.js:51:43)
    at renderWithHooks (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15108:18)
    at mountIndeterminateComponent (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17342:13)
    at beginWork$1 (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18486:16)
    at HTMLUnknownElement.callCallback (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at beginWork$$1 (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
    at performUnitOfWork (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22208:12)
    at workLoopSync (/tmp/.mount_JoplinsIOzUC/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22185:22)
Component stack

    in NoteToolbar (created by Connect(NoteToolbar))
    in Connect(NoteToolbar) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider
```

I now get this on starting Joplin.

## Environment

Joplin version: v1.0.226
Platform: linux
OS specifics: ubuntu 18.04

**Comment by msbentley** [comment] 2020-07-06 09:31
OK, Joplin did not quit cleanly and so I had to hunt down and kill it - after this, Joplin started nominally again. Feel free to close this issue if that is appropriate!

**Comment by Viscometer** [comment] 2020-07-06 19:27
Just saw this earlier bug report.

Looks like a duplicate of mine:
https://github.com/laurent22/joplin/issues/3463

**Comment by msbentley** [comment] 2020-07-07 09:13
Just to add to this, the bug is triggered by deleting _any_ notebook - I guess at the end of the deletion, since I didn't see this immediately yesterday, but when deleting a very small notebook today I saw this instantly.

**Closed** 2020-07-07 18:17 UTC
Labels: bug, desktop, high
