### ISSUE TITLE
[Feature Request] Asciidoc support

### ISSUE THREAD

**Issue by sarlej** [laurent22/joplin#66] opened 2017-12-04 16:08 UTC
Hello,
it will be really nice to have asciidoc support (http://asciidoc.org/). It is simple as markdown but have lot more formating possibilities. And it is one standardized markup language, instead of lot markdown variations.
Do you have any plans to support another text renderer?

**Comment by laurent22** [comment] 2017-12-04 18:17
Duplicate of https://github.com/laurent22/joplin/issues/60

**Closed by laurent22** 2017-12-04 18:17 UTC
