### ISSUE TITLE
Editor font not changing even if changed under Joplin > Preferences > Appearance > Editor Font Size - Mac OS Catalina

### ISSUE THREAD

**Issue by ipentest** [laurent22/joplin#3825] opened 2020-09-24 16:47 UTC
## Environment

Joplin version: 1.2.2 Darwin prod
Platform: Mac OS Catalina 
OS specifics: 10.15.6

Thanks and keep up the wonderful work

**Comment by CalebJohn** [comment] 2020-09-24 19:26
Hi @ipentest 

This is a duplicate of #3816 , this has been fixed already and will be available in the next release.

**Closed by CalebJohn** 2020-09-24 19:26 UTC
Labels: bug

**Comment by ipentest** [comment] 2020-09-26 11:35
Awesome! Thanks a lot for the speedy response. Much appreciated.
