### ISSUE TITLE
White Flash When Switching from Notes in One Notebook to Another in Dark Mode

### ISSUE THREAD

**Issue by monkeylove** [laurent22/joplin#4929] opened 2021-05-07 10:49 UTC
Hello. Is there a way to remove the white flash when one clicks on notebooks while in dark mode?

## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: Windows 10 Home SL x64

## Steps to reproduce

1. Use dark mode (like solarized dark).
2. Using the mouse, click on one notebook and then another. (There's no white flash when switching from note to note in the same notebook.)
3. Watch the white flash prior to the selected note appearing.

## Describe what you expected to happen

I hope white flash doesn't show up.

**Comment by coderrsid** [comment] 2021-05-07 22:16
Couldn't confirm this issue on my machine (macOS 11.2.1) on latest build. Can you please provide a GIF of issue occurring or a video link? 
Thanks.

**Comment by roman-r-m** [comment] 2021-05-07 22:37
It only happens if you have WYSIWYG editor.

**Comment by roman-r-m** [comment] 2021-05-07 22:37
Actually, this is a duplicate of https://github.com/laurent22/joplin/issues/4879

**Closed by roman-r-m** 2021-05-07 22:37 UTC
Labels: bug

**Comment by monkeylove** [comment] 2021-05-09 00:58
Thanks! The GIF in the other thread is what I see, but in Windows OS. I think it's similar to the white flash problem issue in Firefox:

https://www.reddit.com/r/firefox/comments/ahfhaq/white_flash_between_webpages/
