### ISSUE TITLE
Global search focuses text in notes so that edits overwrite highlighted text

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#6035] opened 2022-01-18 16:08 UTC
I have noticed recently that when doing a global search, and choosing a note from the note list, the found text is highlighted in the note. So far so good. But when I click into the note (e.g. at the end to append something) the cursor jumps _after the first character_ to the highlight and Joplin starts to over-write this text.

I've attached a short video to explain more clearly!

https://user-images.githubusercontent.com/1671065/149974279-7f5c02fd-0ed5-4ba4-87cc-c970c3d35d9a.mp4

## Environment

Joplin version: 2.7.7 (although I think this happened on at least the few recent releases of the 2.7 series)
Platform: linux
OS specifics: ubuntu 20.04

## Steps to reproduce

1. Create a note with given text
2. Search for this text in the global search
3. Select the created note from the list
4. Click at the end of the note to position the cursor to append some text
5. Start tying
6. Note that the _first_ character is correctly placed, but that subsequent characters overwrite the "found" text in the note

(note that I have tested this in safe mode - as in the video - to make sure it was not due to a plugin)

## Describe what you expected to happen
Regardless of the search highlighting, edits should occur where the cursor is positioned.

**Comment by laurent22** [comment] 2022-01-18 18:30
Is it really a new issue? I think it would have happened in previous versions too, because it's just the highlighted text being overwritten.

**Comment by msbentley** [comment] 2022-01-18 19:06
Hmm, good question @laurent22 - I've only noticed in the last week or so, but perhaps I changed my workflow? I just can't imagine that I wouldn't have hit this earlier if it had always been there. Either way, I guess it's not expected behaviour?

**Comment by tessus** [comment] 2022-01-18 19:07
This does not happpen in CodeMirror, so I suspect this is a WYSIWYG editor related issue. We should change the issue template to include the editor info when opening an editor bug.

**Comment by msbentley** [comment] 2022-01-18 19:12
Just FWIW @tessus I'm not using the WYSIWYG editor (see video above)

**Comment by tessus** [comment] 2022-01-18 19:20
Sorry, I was in the wrong branch. 2.6.9 does not have the issue. But I can reproduce it on 2.7.x (fdba6c076).

**Comment by laurent22** [comment] 2022-01-18 19:21
I guess it might be a new issue then, as it's true no-one ever mentioned this problem before and it probably would have come up. I don't know what could have caused this though.

**Comment by tessus** [comment] 2022-01-18 19:23
We had a few editor related commits. I think 3 with sync scroll and 2 with search highlighting or something other related to search. I can't recall off the top of my head.

**Comment by splerman** [comment] 2022-01-18 21:13
I upgraded to 2.7.6 yesterday and 2.7.7 today (Windows...and not using the WYSWIG editor either) and can confirm the same behavior started for me on 2.7.6. Didn't report it because I hadn't had a chance to disable all plugins to see if it was a plugin causing the issue. Happy to provide any additional info/troubleshooting that might be useful.

**Comment by laurent22** [comment] 2022-01-18 21:22
Right, that's probably this commit:

https://github.com/laurent22/joplin/pull/5919/files

Before we didn't set the selection at all, and now we do. @ken1kob, do you think this issue can be fixed, or should we rollback for now? Perhaps if the goal is to focus the editor we could just call focus() on one of the html elements? We did that for something else and it worked well.

**Comment by godylockz** [comment] 2022-01-18 23:55
@laurent22 I suggest rolling this back, I think i've deleted countless things by just clicking the enter key after searching .... its preety bad. I reverted to 2.6.10
Unless your implementing a find/replace with the search functionality, it shouldn't be selecting for editing. Just for finding notes.

**Comment by laurent22** [comment] 2022-01-19 09:04
The feature has been reverted in c668bb03706bbf86c57c7152160c2a5ff59022e7 for now to give us time to consider how it should be fixed.

**Comment by CalebJohn** [comment] 2022-01-19 09:13
Looks like the issue is a combination of #5919 and #5894. The bug itself is from #5894, which causes the selection to be remade every time the document is edited. 

I'm going to follow up with a PR in a couple minutes.

**Comment by ken1kob** [comment] 2022-01-19 10:31
> @ken1kob, do you think this issue can be fixed, or should we rollback for now?

@laurent22, first, we have to clarify the spec of local/global search. For example:

Local search: (recently discussed in #5850)
- The first search item is selected (with cursor move) for uninterrupted keyboard operations. It conforms with other applications.

Global search: (**to be clarified here**)
- The first search item is scrolled to, but without any selection or cursor move

If this spec is OK, PR #6038 will fix this problem. (#6038 needs #5919.)

**Comment by ken1kob** [comment] 2022-01-19 10:59
It would be better both #6037 and #6038 are applied.

**Comment by msbentley** [comment] 2022-01-19 22:02
Just a heads-up - the behaviour is different, but not resolved in 2.7.8. Now the cursor position is not constantly reset, but the page seems to scroll either to the top (or first search match?). So no data loss is involved, but after each keystroke the page scrolls away from the cursor position:

https://user-images.githubusercontent.com/1671065/150221226-87ce8841-a11b-4b75-b130-dd69601d3c26.mp4

**Closed** 2022-01-20 11:52 UTC
Labels: bug, desktop, high
