### ISSUE TITLE
OneDrive full sync issue did not fix

### ISSUE THREAD

**Issue by daviding924** [laurent22/joplin#4351] opened 2021-01-12 22:56 UTC
## Environment

Joplin version: 1.6.6
Platform: Windows10
OS specifics: 

## Steps to reproduce

1. backup to JEX file
2. delete JoplinProfile in local
3. delete Joplin data in OneDrive
4. restore form JEX file
5. setup OneDrive and upload all of items
6. first full sync is fine
7. normal work and no full sync issue
8. full sync issue happened after half day

Here is my guess, maybe help.
OneDrive like ClearCase, which use VIEW and VOB. VIEW save info, such as file name and change history. VOB save real objects, such as file history version. They link 2 layer VOB object and VIEW name together and show to us. OneDrive cloud storage like that, you may find file history and restore it.

I know that because I rename Apps folder name from "应用" to appdata, no change from Joplin side. Joplin sync worked smoothly with the old data, even folder name changed. Because Joplin use OneDrive API which point Apps to object layer, it is not folder name layer.
/应用/Joplin -> /appdata/Joplin

The key issue happened, I stop Joplin sync and rename appdata to Apps and start sync in short time, Joplin still use old path /appdata/Joplin, then create 5 folders and info.json file. The sync is normal form new path Apps/Joplin. And then I rename old appdata to anyone, no same issue happened. That means Joplin use new path /Apps/Joplin after sync.
/appdata/Joplin -> /Apps/Joplin

From my test and experience, I guess that OneDrive use cache or buffer for object and name link, which mode has asynchronous issue. When Joplin use OneDrive API ask OneDrive data info, OneDrive's response is outdated data info, Joplin confused and try to full sync fix asynchronous issue.

**Comment by DawMatt** [comment] 2021-01-12 23:22
Is this a duplicate of #4305 ? You've added additional steps (backup/restore via JEX and deleting data in OneDrive) but it doesn't look like that is material to the issue.

**Comment by laurent22** [comment] 2021-01-13 00:11
Closed as duplicate of #4305

**Closed by laurent22** 2021-01-13 00:11 UTC
Labels: bug
