### ISSUE TITLE
External editor bug: Joplin stops watching file

### ISSUE THREAD

**Issue by matthewmoppett** [laurent22/joplin#710] opened 2018-08-07 12:32 UTC
### Operating system

- Linux

### Application

- Desktop

After clicking on the "Edit in external editor" icon, the feature works as you'd expect. I have a file to edit, and Joplin updates the note whenever I save the file from the external editor (in my case, Neovim-gnome-terminal-wrapper, although GVim has the same problem). However, Joplin sporadically stops watching the edited file, especially if the file is saved several times in rapid succession. In that case, I have to copy my most recent work, close the file, reopen it, and paste my work back in.

I'm attaching a copy of log.txt copied after a note-taking session when the bug occurred quite frequently,  just in case that has any useful information: 
[joplin.log.txt](https://github.com/laurent22/joplin/files/2266365/joplin.log.txt)

Watching the console in debug mode did not yield any messages when the bug was triggered.

**Comment by laurent22** [comment] 2018-09-05 20:44
Could it be the same bug as this one? https://github.com/laurent22/joplin/issues/766

**Comment by matthewmoppett** [comment] 2018-09-05 22:56
I don't think so. That bug seemed to be describing something that happens every time the file is saved. But in my case, the bug occurs fairly regularly, but not every time I save the file (maybe one time in ten).

**Comment by laurent22** [comment] 2018-09-09 19:53
@matthewmoppett, I cannot replicate on Windows so maybe it's something specific to Linux. Please could you add all the debug flags to flags.txt as described there? https://joplin.cozic.net/debugging/ And then if you could post the log right after the bug happens it might help figuring out what's happening.

**Comment by matthewmoppett** [comment] 2018-09-10 11:07
/tmp/.mount_Joplin1VQ1FT/app/resources/app/node_modules/brace/index.js:1392 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
/tmp/.mount_Joplin1VQ1FT/app/resources/app/gui/Root.min.js:29 [Violation] 'setTimeout' handler took 67ms
/tmp/.mount_Joplin1VQ1FT/app/resources/app/gui/Root.min.js:29 [Violation] 'setTimeout' handler took 87ms
/tmp/.mount_Joplin1VQ1FT/app/resources/app/gui/Root.min.js:29 [Violation] 'setTimeout' handler took 71ms
/tmp/.mount_Joplin1VQ1FT/app/resources/app/gui/Root.min.js:29 [Violation] 'setTimeout' handler took 56ms
/tmp/.mount_Joplin1VQ1FT/app/resources/app/gui/Root.min.js:29 [Violation] 'setTimeout' handler took 70ms

**Comment by matthewmoppett** [comment] 2018-09-13 12:58
The strange thing is that after turning on debug mode mode using flags.txt, the bug seems to happen much less often than normal (which is fine by me, but hardly a permanent solution!).

Anyway, eventually the bug came up again. This is a record of the console log for my current session:
[console.log](https://github.com/laurent22/joplin/files/2379361/console.log)

And this is the last five minutes or so of activity from log.txt before the bug occurred:
[logtail.txt](https://github.com/laurent22/joplin/files/2379384/logtail.txt)

**Comment by laurent22** [comment] 2018-09-13 18:32
I think the issue is that the file is unwatched when it is temporarily moved by emacs. I've removed the code that was causing this and it seems to work now. I don't think any new issue would popup by removing this code but let's see. It will be in the next release.

**Closed** 2018-09-13 18:31 UTC
Labels: bug, essential

**Comment by matthewmoppett** [comment] 2018-10-02 04:52
The latest version of Joplin (I've just updated to 1.0.111) does seem to have fixed the issue for me. Thanks.

**Comment by matthewmoppett** [comment] 2019-03-17 04:21
Actually it seems that the issue is still there, but I've found a fix for Vim/ Neovim users: the problem goes away if you do :set backupcopy=yes. This command can of course be put in your .vimrc/init.vim or in .../ftplugin/markdown.vim so that it executes every time you edit a markdown file.
