### ISSUE TITLE
Version 2.9.2 appimage not running on Arch Linux

### ISSUE THREAD

**Issue by thomascrisan** [laurent22/joplin#6752] opened 2022-08-14 22:47 UTC
Joplin version:  2.9.2
Platform:  Arch Linux 
OS specifics:  version 5.19.1-arch2-1

Currently running Joplin-2.9.1.AppImage with no problems.

Attempting to run Joplin-2.9.2.AppImage results with the AppImage starting but no window ever opens up.  I have to manually kill the processes.

I will provide more information if  instructions are provided.

**Comment by ncatanchin** [comment] 2022-08-15 01:53
Same on Ubuntu

Got this from the developer tools console:

![image](https://user-images.githubusercontent.com/2169122/184564782-2a2e8f31-48f2-4306-9fb2-70c377291020.png)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'concat')
    at Object.<anonymous> (app.ts:57:36)
    at Object.<anonymous> (app.ts:607:20)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(anonymous) @ app.ts:57
(anonymous) @ app.ts:607
Module._compile @ node:internal/modules/cjs/loader:1116
Module._extensions..js @ node:internal/modules/cjs/loader:1169
Module.load @ node:internal/modules/cjs/loader:988
Module._load @ node:internal/modules/cjs/loader:829
c._load @ node:electron/js2c/asar_bundle:5
i._load @ node:electron/js2c/renderer_init:33
Module.require @ node:internal/modules/cjs/loader:1012
require @ node:internal/modules/cjs/helpers:102
(anonymous) @ main-html.js:13
```

**Comment by Daeraxa** [comment] 2022-08-15 09:26
I think this is the same as reported in the beta testing thread for 2.9
https://discourse.joplinapp.org/t/pre-release-v2-9-is-now-available-updated-12-august/26416/3
and 
https://discourse.joplinapp.org/t/i-am-dealing-with-a-problem-to-open-app-in-new-joplin-instalation/26890/

**Comment by thomascrisan** [comment] 2022-08-16 11:51
As the update, I was able to build 2.9.2 on an Arch system using the source code and while I have not done extensive testing, it runs and appears to function normally.  I would conclude that the problem is likely in the AppImage packaging for Linux, not the code.

**Comment by laurent22** [comment] 2022-08-18 13:11
Duplicate of #6756

**Closed as completed by laurent22** 2022-08-18 13:11 UTC
Labels: bug
