### ISSUE TITLE
[Feature Request] Add support for equations in LaTex or other similar symbolic engine

### ISSUE THREAD

**Issue by rgalbo** [laurent22/joplin#146] opened 2018-01-08 18:41 UTC
### Operating system

- [ ] Windows
- [ ] macOS
- [X ] Linux
- [ ] Android
- [X ] iOS

### Application

- [X ] Desktop
- [ ] Mobile
- [X ] Terminal

---

I use Joplin to take notes on data science and statistical methods along side my project notes and it would be awesome to be able to include in-line equations that render when the note is being viewed in markdown mode. I understand that there github and other markdown flavors don't support these, so I assume that there might be an issue with that but I hope there is a workaround

**Comment by laurent22** [comment] 2018-01-08 19:36
Duplicate of #11

**Closed by laurent22** 2018-01-08 19:36 UTC
