### ISSUE TITLE
Can't edit stylesheet

### ISSUE THREAD

**Issue by 38569459** [laurent22/joplin#3083] opened 2020-04-18 09:10 UTC
I can't edit stylesheet to change UI text size.

## Environment

Joplin version: 1.0.201
Platform: Linux
OS specifics: i3wm

## Steps to reproduce

1. Ctrl+Comma
2. Click Appearance tab
3. Click Show Advanced Settings
4. Click Edit

## Describe what you expected to happen

Can edit stylesheet

**Comment by coderrsid** [comment] 2020-04-18 11:18
Where does it open the `userstyle.css` file after clicking `Edit`? In a browser?  Because in my case (macOS), it opens the file in Safari web-browser.

**Comment by tessus** [comment] 2020-04-18 20:32
It will open the css file in the app that is associated with css files in the OS.

**Comment by coderrsid** [comment] 2020-04-18 20:35
As tessus said, @38569459 you can change the default application set to open stylesheets in your OS to a text-editor and it will work perfectly fine.

**Comment by tessus** [comment] 2020-04-18 20:39
This works as designed. Closing. For discussions, please use the forum.

**Closed by tessus** 2020-04-18 20:39 UTC
