### ISSUE TITLE
Can't scroll to bottom list of to-do

### ISSUE THREAD

**Issue by kaifaty** [laurent22/joplin#3964] opened 2020-10-21 07:29 UTC
![изображение](https://user-images.githubusercontent.com/11953142/96686494-08e34180-1398-11eb-81de-c18c4536f42f.png)
Mouse scrolldown can't move list of todos to bottom. Only way is keydown, but it generate some artefacts(img).

Windows 10.
v.1.2.6
Rev. f5f117cb

**Comment by laurent22** [comment] 2020-10-21 09:27
Could you explain step by step how to replicate this bug? As for me it's not doing it.

**Comment by laurent22** [comment] 2020-10-21 09:27
Probably a duplicate of #3891

**Comment by kaifaty** [comment] 2020-10-21 09:43
[https://youtu.be/0coBUJSoi8s](Video)
1. Create new notebook
2. Append 33 todo items. 
3. Trying to scroll them.

**Comment by laurent22** [comment] 2020-10-21 14:38
This video makes it look like you found a [hidden world in Mario](https://www.youtube.com/watch?v=HG-MYCopLTk&feature=youtu.be&t=41) :) But I don't understand how you append the additional items? Is it by duplicating them?

**Comment by kaifaty** [comment] 2020-10-21 14:58
Hmmm.. may be..  I used portable version and now I have install normal way. Bug was disapered.

**Comment by laurent22** [comment] 2020-10-29 23:06
Closing in favour of #4001 3891

**Closed by laurent22** 2020-10-29 23:06 UTC
Labels: bug, desktop, high
