### ISSUE TITLE
Android version attachment file open camera application error exit

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#7675] opened 2023-01-27 14:21 UTC
Android version attachment file open camera application error exit.

https://user-images.githubusercontent.com/112467275/215106592-fda86bdd-000b-47b1-b082-5aeae839a048.mp4

## Environment

Joplin version: 2.10.5(64)
Platform: android
OS specifics: android 10

## Steps to reproduce

1. attachment file
2.  open camera

## Logfile

![Screenshot_2023_0127_221950](https://user-images.githubusercontent.com/112467275/215108902-8cd76e81-fa76-415a-b9ee-8c280f598643.jpg)

**Comment by wh201906** [comment] 2023-01-28 05:59
This bug also exists on Android 2.10.4

<details>
<summary>Crash log from Logcat</summary>

```
13:52:18.892 ReactNativeJS            E  Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
13:52:18.899 ReactNativeJS            E  TypeError: Cannot read property 'RNCamera' of undefined
                                         
                                         This error is located at:
                                             in CameraView
                                             in Connect(CameraView)
                                             in NoteScreenComponent
                                             in Connect(NoteScreenComponent)
                                             in RCTView
                                             in Unknown
                                             in KeyboardAvoidingView
                                             in AppNavComponent
                                             in Connect(AppNavComponent)
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in JoplinSafeAreaView
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in MenuProvider
                                             in DeprecatedComponent
                                             in RCTView
                                             in Unknown
                                             in AnimatedComponent
                                             in AnimatedComponentWrapper
                                             in RCTView
                                             in Unknown
                                             in SideMenuComponent
                                             in Connect(SideMenuComponent)
                                             in RCTView
                                             in Unknown
                                             in ThemeProvider
                                             in RCTView
                                             in Unknown
                                             in Portal.Host
                                             in RNCSafeAreaProvider
                                             in SafeAreaProvider
                                             in SafeAreaProviderCompat
                                             in Provider
                                             in AppComponent
                                             in Connect(AppComponent)
                                             in Provider
                                             in Root
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in AppContainer, js engine: hermes
13:52:18.902 ReactNativeJS            E  TypeError: undefined is not a function
                                         
                                         This error is located at:
                                             in AppComponent
                                             in Connect(AppComponent)
                                             in Provider
                                             in Root
                                             in RCTView
                                             in Unknown
                                             in RCTView
                                             in Unknown
                                             in AppContainer, js engine: hermes
13:52:18.931 AndroidRuntime           E  FATAL EXCEPTION: mqt_native_modules
                                         Process: net.cozic.joplin, PID: 24975
                                         com.facebook.react.common.JavascriptException: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes, stack:
                                         invariant@1:98856
                                         get ViewPropTypes@1:92981
                                         anonymous@1:4123123
                                         loadModuleImplementation@1:80435
                                         guardedLoadModule@1:79984
                                         metroRequire@1:79612
                                         anonymous@1:4121270
                                         loadModuleImplementation@1:80435
                                         guardedLoadModule@1:79941
                                         metroRequire@1:79612
                                         render@1:4120331
                                         finishClassComponent@1:146737
                                         updateClassComponent@1:146598
                                         beginWork$1@1:180008
                                         performUnitOfWork@1:166905
                                         workLoopSync@1:166763
                                         renderRootSync@1:166647
                                         performSyncWorkOnRoot@1:164072
                                         flushSyncCallbacks@1:128601
                                         scheduleUpdateOnFiber@1:160982
                                         enqueueSetState@1:176503
                                         anonymous@1:255854
                                         takePhoto_onPress@1:4090858
                                         ?anon_0_@1:4092874
                                         fulfilled@1:4078878
                                         tryCallOne@53:15
                                         anonymous@139:26
                                         anonymous@1:202108
                                         _callTimer@1:201057
                                         _callReactNativeMicrotasksPass@1:201221
                                         callReactNativeMicrotasks@1:203185
                                         __callReactNativeMicrotasks@1:103438
                                         anonymous@1:102531
                                         __guard@1:103279
                                         flushedQueue@1:102442
                                         callFunctionReturnFlushedQueue@1:102298
                                         
                                         	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                         	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                         	at com.facebook.jni.NativeRunnable.run(Native Method)
                                         	at android.os.Handler.handleCallback(Handler.java:938)
                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                         	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                         	at android.os.Looper.loopOnce(Looper.java:210)
                                         	at android.os.Looper.loop(Looper.java:299)
                                         	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                         	at java.lang.Thread.run(Thread.java:920)
13:52:18.938 OOMEventManager          E  oom event not support this pkg, dismiss this!
13:52:18.942 MQSEventManager          W  jeoccur
13:52:18.954 ActivityTaskManager      W    Force finishing activity net.cozic.joplin/.MainActivity
```

</details>

**Comment by wh201906** [comment] 2023-01-28 06:08
I guess it is caused by the deprecated library [`react-native-camera`](https://github.com/react-native-camera/react-native-camera), which might not support the newer version of React Native.
The suggested alternative is [`react-native-vision-camera`](https://github.com/mrousavy/react-native-vision-camera).

**Comment by ghost** [comment] 2023-01-28 12:45
Yes, maybe it's time to update the camera.Looking forward to it.
I found some expectant voices in the community. I will test positively if there are results.
https://discourse.joplinapp.org/t/mobile-camera-photography-supports-zooming-add-scanning-capabilities/27490

**Comment by Aditya-150** [comment] 2023-01-29 02:21
I want to work on this. Can you assign this to me.

**Comment by roman-r-m** [comment] 2023-01-29 07:53
> I want to work on this. Can you assign this to me.

We do not assign issues

**Comment by Aditya-150** [comment] 2023-01-29 08:18
> > I want to work on this. Can you assign this to me.
> 
> We do not assign issues

So we have to find a bug or propose a feature update through an issue.
In order to contribute to the repository.

If there's any way I can contribute to the repo please let me know.

**Comment by wh201906** [comment] 2023-01-29 08:22
IMO you should replace the `react-native-camera` in Joplin with `react-native-vision-camera`. You need to check the differences between these two packages and make migration.
(Please correct me if I'm wrong.)
By the way, if you are here for GSoC or Hacktoberfest, I guess you need to read them first.
https://github.com/laurent22/joplin/issues/6937
https://github.com/laurent22/joplin/issues/7548

**Comment by roman-r-m** [comment] 2023-01-29 09:18
> > > I want to work on this. Can you assign this to me.
> > 
> > We do not assign issues
> 
> So we have to find a bug or propose a feature update through an issue.
> In order to contribute to the repository.
> 
> If there's any way I can contribute to the repo please let me know.

You can still work on it, it's just that we don't formally assign issues

**Comment by Aditya-150** [comment] 2023-01-29 09:36
> > > > I want to work on this. Can you assign this to me.
> > > 
> > > We do not assign issues
> > 
> > So we have to find a bug or propose a feature update through an issue.
> > In order to contribute to the repository.
> > 
> > If there's any way I can contribute to the repo please let me know.
> 
> You can still work on it, it's just that we don't formally assign issues

Got it. Thanks for informing.

**Comment by ghost** [comment] 2023-02-01 07:54
Is this related to the problem of f-droid?
https://github.com/laurent22/joplin/issues/15
https://gitlab.com/fdroid/rfp/-/issues/434#note_441861147

**Comment by wh201906** [comment] 2023-02-01 08:07
If I remember it correctly, the non-free dependencies are only introduced by `react-native-camera`, so replacing it with `react-native-vision-camera` might make it suitable for F-Droid repo.

**Comment by muelli** [comment] 2023-02-01 08:14
yes, indeed. It would be great if anybody could replace the current camera thingy.

**Comment by laurent22** [comment] 2023-02-13 17:05
As a first step, I'd prefer if we just get the current react-native-camera to work (since I'm sure the new lib will also have plenty of bugs)

According to this issue https://github.com/react-native-camera/react-native-camera/issues/3458, we can simply patch one of the file to import ViewPropTypes

**Comment by vikneshwar** [comment] 2023-02-15 07:26
@laurent22 and @muelli created a pr #7775 to fix the `react-native-camera` and also parallely working on integrating `react-native-vision-camera`

**Closed as completed** 2023-02-19 13:09 UTC
Labels: bug, android, high
