### ISSUE TITLE
Goto Anything [Ctrl] + [P] fails to switch notes on first trie

### ISSUE THREAD

**Issue by rubbsdecvik** [laurent22/joplin#5392] opened 2021-08-27 18:39 UTC
I've noticed that my desktop environment will not switch notes using the `Goto Anything` function on the first try. It will however do so on subsequent tries. However, the behavior repeats as soon as there is a new note loaded. Steps to repeat are below.

## Environment

Joplin version: 
    Joplin 2.3.5 (prod, linux)
      
    Client ID: c61a67d917b94579a4c6581bba582dbe
    Sync Version: 3
    Profile Version: 39
    Keychain Supported: No

Platform: Linux

OS specifics: 
`Linux 5.13.10-100.fc33.x86_64 #1 SMP Thu Aug 12 21:15:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
Fedora 33

## Steps to reproduce

1. Start in any note and hit `Ctrl` + `P`
2. Search for a different note and hit `Enter`
3. Note view will stay on original note
4. Repeat Steps 1 and 2
5. Note view will now switch.

## Describe what you expected to happen
I would expect that the note view switches to the desired note the first time you hit `Enter`.

## Logfile
Log file is large, so I put it in a separate gist: https://gist.github.com/rubbsdecvik/ca61edbc90f1394eeb3457f283170bde 

The only changed information in the log file above is the name of a note which appeared. I replaced it with the string `Name Redacted`.

**Comment by Daeraxa** [comment] 2021-08-28 00:46
I believe this was the thing fixed in 2.4.1 pre-release:
https://github.com/laurent22/joplin/releases/tag/v2.4.1
https://github.com/laurent22/joplin/issues/5184
https://github.com/laurent22/joplin/commit/4f5ad86028de9123c2cfd4f7507356dbbb0b3c67

**Comment by tessus** [comment] 2021-08-28 11:25
duplicate of #5361
duplicate of #5355

**Closed by tessus** 2021-08-28 11:25 UTC
Labels: bug
