### ISSUE TITLE
[Feature Request] Integration into Thunderbird and nextcloud tasks

### ISSUE THREAD

**Issue by jrfVP42bLiUWAYOShp5r** [laurent22/joplin#394] opened 2018-04-09 13:48 UTC
### Operating system

- Windows
- macOS
- Linux

### Application

- Addon

I guess it would be killer if it was possible to use Joplin out of Thunderbird and integrate to the caldav stuff on nextcloud. any ideas how to achieve this?

**Comment by laurent22** [comment] 2018-04-16 14:17
Duplicate of #228

**Closed by laurent22** 2018-04-16 14:17 UTC
