### ISSUE TITLE
URL syntax highlighting is incorrect on certain URLs

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9193] opened 2023-11-02 13:27 UTC
In the beta editor, create a link with subdomain, such as `https://en.m.wikipedia.org/wiki/Duck`

`https://en.m.wikipedia` will be highlighted in blue, while the rest of the link will be in black. In practice, the whole link should be blue.

<img width="273" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/33ee15b8-fd0a-4f26-af5f-c18e4b4aeac0">

This applies to both mobile and desktop

**Comment by personalizedrefrigerator** [comment] 2023-11-02 13:50
I think we're using CodeMirror's syntax tree to detect URLs:

https://github.com/laurent22/joplin/blob/2b9d519f4badee5716eaf1fa16fdc097eeb1d7a7/packages/editor/CodeMirror/markdown/decoratorExtension.ts#L139-L141

I plan to create a minimal reproducible example and report the bug upstream.

**Comment by personalizedrefrigerator** [comment] 2023-11-02 18:10
It looks like it's already been fixed upstream: https://github.com/lezer-parser/markdown/issues/29

There doesn't seem to be a new version yet, however.

**Comment by personalizedrefrigerator** [comment] 2023-11-20 21:50
A new version with the fix has been released! https://github.com/lezer-parser/markdown/commit/6230859dccc0c157dff1e5df6d08d3860334b8e7

**Comment by personalizedrefrigerator** [comment] 2024-01-27 22:26
I think this is fixed in the latest version of Joplin (tested in Joplin 12.14.2 on iOS).

**Closed as completed by personalizedrefrigerator** 2024-01-27 22:26 UTC
Labels: bug, desktop, upstream, editor
