### ISSUE TITLE
Defaulted Simple Backup build has race condition that breaks builds

### ISSUE THREAD

**Issue by JGCarroll** [laurent22/joplin#10074] opened 2024-03-06 19:15 UTC
### Operating system

Linux

### Joplin version

2.14.17

### Desktop version info

Tested on Ubuntu 22.04 (Snap build environment, but that's just LXD with automation and approximates a traditional environment).

When trying to build 2.14.17 as a snap, everything worked fine locally. When then ferrying off to Github, the following errors occur in the CI environment:
https://github.com/MrCarroll/joplin-desktop-snap/actions/runs/8124527302/job/22206113265

> ➤ YN0009: │ root@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-33bd7822/build.log)

Looking into this, this happens as a result `npm install` call during the Simple Backup installation.

Similarly, the Flatpak appears to be hitting the exact same situation, using their own CI (I don't think Flathub uses Actions directly), in the end, going for this solution (Which looks like it simply avoids building the plugin at all):
https://github.com/flathub/net.cozic.joplin_desktop/pull/186/commits/3a9d303aa5cefeae6a7418c8cd6889be8292bb90

### Expected behaviour

Joplin should successfully build in the same execution environments regardless of speeds

### Logs

I'm cheating here as the Flatpak builds actually have better logging defaults and I'm still frantically experimenting on my end:
https://buildbot.flathub.org/#/builders/7/builds/12853

Ultimately, the `npm install` for the Simple Backup plugin seems to die with error code 243 (EACCESS) but every investigation into permissions issues so far doesn't suggest that it actually is one.

**Comment by JGCarroll** [comment] 2024-03-06 19:22
I've just looked at the Flathub logs and seen they don't show the same `npm install` error I do. I've got a cheeky build running at the moment where to upset the race condition I've put a sleep function for 10 minutes prior to the `npm install` for simple backup, in an hour-ish I'll provide the Snap equivilent version of the logs which error on `npm install` and not the `git clone`.

**Comment by personalizedrefrigerator** [comment] 2024-03-06 19:50
I previously experienced an issue with `npm install` failing while trying to build the `@joplin/lib` version `~2.9` dependency. @MrCarroll Does the following patch help?
`````diff
diff --git a/packages/default-plugins/plugin-patches/io.github.jackgruber.backup.diff b/packages/default-plugins/plugin-patches/io.github.jackgruber.backup.diff
index 79d976624..871ed06d2 100644
--- a/packages/default-plugins/plugin-patches/io.github.jackgruber.backup.diff
+++ b/packages/default-plugins/plugin-patches/io.github.jackgruber.backup.diff
@@ -1,3 +1,17 @@
+diff --git a/package.json b/package.json
+index 7c29698..241ba9e 100644
+--- a/package.json
++++ b/package.json
+@@ -39,8 +39,7 @@
+     "typescript": "^4.8.2",
+     "webpack": "^5.74.0",
+     "webpack-cli": "^4.10.0",
+-    "yargs": "^16.2.0",
+-    "@joplin/lib": "~2.9"
++    "yargs": "^16.2.0"
+   },
+   "browser": {
+     "fs": false,
 diff --git a/src/sevenZip.ts b/src/sevenZip.ts
 index ef2a527..d98c777 100644
 --- a/src/sevenZip.ts
@@ -38,10 +52,29 @@ index ef2a527..d98c777 100644
    export async function setExecutionFlag() {
      if (process.platform !== "win32") {
 diff --git a/webpack.config.js b/webpack.config.js
-index 34a1797..7b2a480 100644
+index b32f37f..a42f68a 100644
 --- a/webpack.config.js
 +++ b/webpack.config.js
-@@ -200,15 +200,9 @@ const pluginConfig = { ...baseConfig, entry: './src/index.ts',
+@@ -16,7 +16,6 @@ const CopyPlugin = require('copy-webpack-plugin');
+ const tar = require('tar');
+ const glob = require('glob');
+ const execSync = require('child_process').execSync;
+-const allPossibleCategories = require('@joplin/lib/pluginCategories.json');
+ 
+ const rootDir = path.resolve(__dirname);
+ const userConfigFilename = './plugin.config.json';
+@@ -85,10 +84,6 @@ function currentGitInfo() {
+ function validateCategories(categories) {
+ 	if (!categories) return null;
+ 	if ((categories.length !== new Set(categories).size)) throw new Error('Repeated categories are not allowed');
+-	// eslint-disable-next-line github/array-foreach -- Old code before rule was applied
+-	categories.forEach(category => {
+-		if (!allPossibleCategories.map(category => { return category.name; }).includes(category)) throw new Error(`${category} is not a valid category. Please make sure that the category name is lowercase. Valid categories are: \n${allPossibleCategories.map(category => { return category.name; })}\n`);
+-	});
+ }
+ 
+ function validateScreenshots(screenshots) {
+@@ -205,15 +200,9 @@ const pluginConfig = { ...baseConfig, entry: './src/index.ts',
  		path: distDir,
  	},
  	plugins: [
`````

This change adjusts the patch file for the Simple Backup build to remove the dependency on `@joplin/lib` version `~2.9`. Note that it doesn't adjust the `package-lock.json` file within Simple Backup.

**Comment by JGCarroll** [comment] 2024-03-06 20:39
Thanks Henry, I'll give it a go ASAP and let you know. Main challenge is finding the best way to fit that patchinto the `Snapcraft` system, doubled down by... it's a remote system rather than a local one, meaning all the usual things like being able to just access the shell don't exist :). I'll think something up though.


[joplin-desktop_amd64.txt](https://github.com/laurent22/joplin/files/14515307/joplin-desktop_amd64.txt)
I've attached the Launchpad logs here. Primarily we're looking at everything between ` ~~Forcing dump of raw logs in /tmp ~~` and `~~Ending dump of raw logs in /tmp~~`, specifically the bit that stands out to me:

```
:: ➤ YN0000: [@joplin/app-desktop]: [96m Applying patch. [0m
:: ➤ YN0000: [@joplin/app-desktop]: > git apply /build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/default-plugins/plugin-patches/io.github.jackgruber.backup.diff
:: ➤ YN0000: [@joplin/app-desktop]: [96m Installing dependencies. [0m
:: ➤ YN0000: [@joplin/app-desktop]: > npm install
:: ➤ YN0000: [@joplin/app-mobile]: Compiling with Babel: /build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/editor/node_modules/@replit/codemirror-vim/dist/index.cjs
:: ➤ YN0000: [@joplin/app-mobile]: Compiling with Babel: /build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/editor/node_modules/@replit/codemirror-vim/dist/index.cjs
:: ➤ YN0000: [@joplin/app-mobile]: Compiling with Babel: /build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/lib/string-utils-common.js
:: ➤ YN0000: [@joplin/app-mobile]: Compiling with Babel: /build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/lib/string-utils-common.js
:: ➤ YN0000: [@joplin/app-desktop]: Error: Command failed with exit code 243: npm install
:: ➤ YN0000: [@joplin/app-desktop]:     at makeError (/build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/utils/node_modules/execa/lib/error.js:60:11)
:: ➤ YN0000: [@joplin/app-desktop]:     at handlePromise (/build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/utils/node_modules/execa/index.js:118:26)
:: ➤ YN0000: [@joplin/app-desktop]:     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
:: ➤ YN0000: [@joplin/app-desktop]:   shortMessage: 'Command failed with exit code 243: npm install',
:: ➤ YN0000: [@joplin/app-desktop]:   command: 'npm install',
:: ➤ YN0000: [@joplin/app-desktop]:   escapedCommand: 'npm install',
:: ➤ YN0000: [@joplin/app-desktop]:   exitCode: 243,
:: ➤ YN0000: [@joplin/app-desktop]:   signal: undefined,
:: ➤ YN0000: [@joplin/app-desktop]:   signalDescription: undefined,
:: ➤ YN0000: [@joplin/app-desktop]:   stdout: '',
:: ➤ YN0000: [@joplin/app-desktop]:   stderr: '',
:: ➤ YN0000: [@joplin/app-desktop]:   failed: true,
:: ➤ YN0000: [@joplin/app-desktop]:   timedOut: false,
:: ➤ YN0000: [@joplin/app-desktop]:   isCanceled: false,
:: ➤ YN0000: [@joplin/app-desktop]:   killed: false
:: ➤ YN0000: [@joplin/app-desktop]: }
:: ➤ YN0000: [@joplin/app-desktop]: Build directory /tmp/default-plugin-build1kOPvK
:: ➤ YN0000: [@joplin/app-desktop]: Input is not from a TTY -- not waiting for input.
:: ➤ YN0000: [@joplin/app-desktop]: [96m Removed build directory [0m
:: ➤ YN0000: [@joplin/app-desktop]: [20:28:33] 'buildDefaultPlugins' errored after 22 s
:: ➤ YN0000: [@joplin/app-desktop]: [20:28:33] Error: Command failed with exit code 243: npm install
:: ➤ YN0000: [@joplin/app-desktop]:     at makeError (/build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/utils/node_modules/execa/lib/error.js:60:11)
:: ➤ YN0000: [@joplin/app-desktop]:     at handlePromise (/build/snapcraft-joplin-desktop-22e866c2a0f06321b07b8f77d0692141/parts/joplin/build/packages/utils/node_modules/execa/index.js:118:26)
:: ➤ YN0000: [@joplin/app-desktop]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
:: ➤ YN0000: [@joplin/app-desktop]: [20:28:33] 'build' errored after 23 s
:: ➤ YN0000: [@joplin/app-desktop]: Process exited (exit code 1), completed in 27s 548ms
```

I've also tried the same on Github but, safe to say it didn't like it:
https://github.com/MrCarroll/joplin-desktop-snap/actions/runs/8178204288
Is there an easy way to toggle the logs to go to STDOUT by default (It seems Flathub can!) ? I've tried looking but the availability of documentation around Electron/NPM hasn't been kind to me as someone outside the NJS ecosystem, things as simple as `--verbose` existing or not just make every little bit of this difficult to work with :(.

**Comment by JGCarroll** [comment] 2024-03-06 21:35
Hi Henry,

I've made a second temporarily test repo where I merge the Snap scripts with the actual Joplin source, meaning the files can be just directly edited in Github web/locally and submitted straight to Github without having to install the dev tools directly.

I've tried applying your patch but I think Github has messed with the formatting slightly. I'd managed to get it to be accepted and hopefully https://github.com/MrCarroll/Joplin-Snap-Test/actions/runs/8179065896/job/22364328872 1) correctly has the patch and 2) works :)

**Comment by personalizedrefrigerator** [comment] 2024-03-06 21:54
Thank you for checking!

Unfortunately, it looks like that didn't work. Searching for `npm exits with code 243`, these StackOverflow posts ([post 1](https://stackoverflow.com/questions/72104367/npm-error-code-eacces-243-what-is-causing-some-directories-in-the-npm-cache-to) and [post 2](https://stackoverflow.com/a/71892226)) suggest that it could be related to the current NodeJS version or user account permissions.

I'm currently checking whether we can increase the output verbosity of `npm install`. For reference, the build script runs `npm install` here:
https://github.com/laurent22/joplin/blob/31777296635d44c111fc00b7fe7b3f1dc9356f25/packages/default-plugins/buildDefaultPlugins.ts#L89

**Comment by personalizedrefrigerator** [comment] 2024-03-06 22:07
I can reproduce this locally on an Ubuntu 23.10 virtual machine.

Interestingly, this only happens with the `npm` installed alongside the `nodejs` snap. In this case, `which npm` results in `/snap/bin/npm`.

If I run `npm install -g npm`, it then builds successfully (note that my [NPM install prefix is `~/.npm-global`](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)). In this case, `which npm` results in `/home/user/.npm-global/bin/npm`.

Both copies of `npm` are version 10.2.4.

**Edit**: On the VM, however, the patch linked above (or a very similar one that also modifies `package-lock.json`) seems to fix the issue.

**Comment by JGCarroll** [comment] 2024-03-06 22:12
My main thought reading those comments were that it was possible `/tmp` itself was weird and perhaps had e.g `noexec` set. One of the changes I've tried already was to override the build folder to be a normal folder, but it had no effect.

For both `/tmp` and the user permissions itself though, my general thought would be that this is running in LXD, may be less popular than Docker sure, but it's actually designed for VM-like containers rather than microservices. All 3 environments (Launchpad, Github, Local) are effectively pure Ubuntu 22.04 setup nearly exactly identical and there shouldn't be much difference between them. Ultimately this is why it's driving me mad, it's a classic "It works on my machine" and the irony isn't lost on me.

Regarding the Node as a Snap vs Node (elsewhere), I'd be happy to look into whether there might be some issues with potential conflicts, but I'd be curious to know whether that local build actually breaks inside `snapcraft` itself (I.E inside LXD, in our clean environment :)).

If you need a quick rundown (preferably in a different VM incase you have e.g Docker locally that can also interfere), that's:

```
sudo snap install snapcraft --classic
sudo snap install lxd
sudo lxd init --auto
sudo addgroup $USER lxd
sudo systemctl reboot

git clone https://github.com/MrCarroll/joplin-desktop-snap
cd joplin-desktop-snap
snapcraft --verbose --debug
```


I've also set a run running with `npm install --verbose` specifically on the line causing it just to see what might come out.

https://github.com/MrCarroll/Joplin-Snap-Test/actions/runs/8179429814/job/22365480284

**Comment by JGCarroll** [comment] 2024-03-07 00:39
Hi again,

We've some success! It looks like in this instance it is more about the Node installation method than the build environment itself, using a .DEB for NodeJS gives working results with no other changes:

https://github.com/MrCarroll/Joplin-Snap-Test/actions/runs/8179931440/job/22366970050

I'd say I'm happy to have this issue officially closed since it seems like I don't need to encourage devs to not use snaps (although for the most part the --classic devtools ones do work very well). But there seems to be something exceptional in this instance and your comment earlier about the snap working fine when you install npm inside npm makes me think there might be some assumptions on paths/variables that aren't necessarily true.

I'll pick up with this for tomorrow but hopefully this means I can release an ARM64 snap tomorrow and then look back on what the root cause properly is now we have a solid lead.

Thanks for the help :)

**Comment by personalizedrefrigerator** [comment] 2024-03-07 00:43
> If you need a quick rundown (preferably in a different VM incase you have e.g Docker locally that can also interfere), that's:

I'm able to reproduce this in LXD on my virtual machine (same error message). If I pause the build and remove the dependency on `@joplin/lib` from the `simple-backup` build directory, it builds successfully.

I've created a [pull request](https://github.com/laurent22/joplin/pull/10075) that should apply this change, however, it will require Simple Backup to update its Joplin build script and `package.json`.

**Closed as completed** 2024-03-11 10:11 UTC
Labels: bug, high
