### ISSUE TITLE
[Feature request] Option to disable auto-save

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#280] opened 2018-03-09 12:52 UTC
At this moment, app automatically saves any edits after a short delay. It could be useful to have an option to disable this auto-saving.

### Operating system

- [X] Windows
- [X] macOS
- [X] Linux
- [X] Android
- [X] iOS

### Application

- [X] Desktop
- [X] Mobile
- [ ] Terminal

**Comment by laurent22** [comment] 2018-03-26 16:25
Duplicate of #310

**Closed by laurent22** 2018-03-26 16:25 UTC
