### ISSUE TITLE
Linux install script fails due to change in the AppImage name

### ISSUE THREAD

**Issue by rkraken** [laurent22/joplin#2336] opened 2020-01-22 00:46 UTC
The Linux install script Joplin_install_and_update.sh fails on the latest version due to change in the AppImage name.  The x86_64 suffix is no longer part of the name.

**Comment by CalebJohn** [comment] 2020-01-22 08:42
duplicate of #2319

**Comment by laurent22** [comment] 2020-01-22 15:43
Fixed

**Closed by laurent22** 2020-01-22 15:43 UTC

**Comment by Peppeo** [comment] 2020-01-22 16:02
![Screenshot from 2020-01-22 22-59-35](https://user-images.githubusercontent.com/53419266/72910473-7b9f8d80-3d30-11ea-9129-f1beee1758e5.png)

Mmmm, this doesn't seem completely fixed yet?

**Comment by Peppeo** [comment] 2020-01-22 23:28
Works, thanks!
