### ISSUE TITLE
Note does not get synced from Android to Windows

### ISSUE THREAD

**Issue by okoetter** [laurent22/joplin#79] opened 2017-12-07 09:09 UTC
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
I have a note that I created on the Android app that does not get synced (via OneDrive) to my Windows app. All other notes in the same workbook seem to sync just fine.
Are there any logs on the Android or Windows side that I can provide?

**Comment by laurent22** [comment] 2017-12-07 10:08
You can enable the logs by doing this:
- Click on Configuration
- Enable "Advanced options"
- Start a synchronisation
- Once it's complete, click on "Log" in the top right menu
If you see any error in there, please send me a screenshot.

By the way, on OneDrive, the maximum file size is 4MB so synchronisation might be stuck there if you have a large file attach to a note. This will be addressed in the next version by disabling sync for these items, so that they don't block synchronisation of the other items.

**Comment by okoetter** [comment] 2017-12-07 10:31
This is a very small text only note.
The last syncs have no error but I saw that the log has older entries as well, there were some errors.

[Log file](https://pastebin.com/TebvdZ0M)

**Comment by laurent22** [comment] 2017-12-07 10:40
I'm not seeing anything obviously wrong in the log. There are some connection errors but this is normal, it's something that would get solved on the next sync. 

Could you display the metadata on this note and send a screenshot? When advanced options are enabled, you'd just need to open the note and click "Show metadata"

**Comment by okoetter** [comment] 2017-12-07 10:54
![screenshot_20171207-114900](https://user-images.githubusercontent.com/4048240/33711766-680d0328-db45-11e7-9c1d-9404d3cc0632.png)

**Comment by laurent22** [comment] 2017-12-07 18:14
Hmm, it seems to have been synced so the issue is on the Windows client, which somehow is not downloading it.

Could you also check the logs of the Windows app? It should be in `C:\Users\YOUR_USERNAME\.config\joplin-desktop\` and the file is called "log.txt".

Please let me know if there's any error in there. By the way, likewise if there's a file bigger than 4MB on the desktop app it would also be blocking the synchronisation process.

**Comment by laurent22** [comment] 2017-12-07 20:02
The last Windows version has some improvements regarding sync:

https://github.com/laurent22/joplin/releases

Could you give it a try and see if the note shows up after sync? Also I've added a Synchronisation Status page under the Options menu. Could you check if the info in there matches the info in the Android app (the same page is available by enabling Advanced Options and selecting the menu Status).

**Comment by okoetter** [comment] 2017-12-08 07:21
I just synced with the old version and found this in the Windows log:

`2017-12-08 08:18:46: "Error: Maximum request length exceeded.
Code: BadRequest
Header: {"_headers":{"cache-control":["private"],"transfer-encoding":["chunked"],"content-type":["application/json; charset=utf-8"],"request-id":["3e5a37d9-2f73-483e-ba31-a7189ea2d46b"],"client-request-id":["3e5a37d9-2f73-483e-ba31-a7189ea2d46b"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"SouthEast Asia\",\"Slice\":\"SliceA\",\"Ring\":\"3\",\"ScaleUnit\":\"002\",\"Host\":\"AGSFE_IN_1\",\"ADSiteName\":\"SIN\"}}"],"duration":["25261.5664"],"date":["Fri, 08 Dec 2017 07:18:44 GMT"],"connection":["close"]}}
Request: PUT https://graph.microsoft.com/v1.0/drive/root:/Anwendungen/Joplin/.resource/2ba7cddb62d0d9b654c3b9a4feeb684e:/content null {"type":"Buffer","data":[137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,7,90,0,0,4,110,8,2,0,0,0,245,85,162,126,0,0,0,3,115,66,73,84,5,6,5,51,11,141,128,0,33,14,245,73,68,65,84,120,156,188,189,79,168,102,73,118,39,246,171,91,241,189,138,43,189,103,125,159,233,28,85,106,212,166,115,144,102,148,237,153,30,149,208,200,106,89,238,65,13,51,48,2,141,65,94,12,238,109,227,133,105,188,106,188,16,137,64,52,133,22,162,152,69,147,244,162,120,170,69,153,87,134,130,87,139,50,153,134,18,153,2,23,206,26,176,169,18,180,232,106,84,131,94,219,93,56,211,211,101,189,207,234,103,221,80,190,240,109,47,226,252,249,157,184,247,203,238,197,148,63,146,91,81,113,207,141,63,39,34,206,57,113,206,47,226,225,71,159,206,239,253,247,30,180,127,143,222,189,247,254,123,15,222,95,60,67,254,123,247,140,94,115,244,219,119,239,201,243,225,189,71,15,239,61,184,127,254,224,254,249,163,135,146,243,254,187,141,38,150,47,255,25
Error: Maximum request length exceeded.
    at OneDriveApi.oneDriveErrorResponseToError (C:\Users\ko110063\AppData\Local\Programs\Joplin\resources\app.asar\lib\onedrive-api.js:124:17)
    at OneDriveApi.exec (C:\Users\ko110063\AppData\Local\Programs\Joplin\resources\app.asar\lib\onedrive-api.js:194:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)" `

I guess you are right and there is a file bigger than 4MB?
Will try again with the new version.

**Comment by okoetter** [comment] 2017-12-08 07:49
The new version shows the `Some items cannot be synchronised. View them now` message at the top:
![grafik](https://user-images.githubusercontent.com/4048240/33755876-267ac8c4-dbf3-11e7-9d14-133f5ffdcbf3.png)

1. Where do I find these images? This `ENIMAGE1357567010574.jpg` is neither on my Windows machine nor on my OneDrive. Is it on my Android machine? I did not find it there but maybe I looked at the wrong places.

2. Did you maybe changed the order of the numbers? Shouldn't it read `Note 173/176` instead of `Note 176/173`? Also for the other lines.

3. The new note from Android did still not show up on Windows. Log shows a JSON-Error: [Log](https://pastebin.com/AjFVcMe7)

**Comment by laurent22** [comment] 2017-12-08 16:50
> Where do I find these images? This ENIMAGE1357567010574.jpg is neither on my Windows machine nor on my OneDrive. Is it on my Android machine? I did not find it there but maybe I looked at the wrong places.

It's probably a file that was attached to one of the note. The feature to handle unsyncable items is not complete yet - the first step was to put these resources aside so that the rest can sync. The next step will be to link to this resources so that they can be inspected, and an option to delete them too.

OneDrive is a bit annoying with this as 4MB is quite low. Nextcloud is around 500MB max and Dropbox is about 200MB I think.

> Did you maybe changed the order of the numbers? Shouldn't it read Note 173/176 instead of Note 176/173? Also for the other lines.

It's most likely items that have been synced and have been deleted since them. The stats aren't very accurate because of this, I'll see if it can be improved.

> The new note from Android did still not show up on Windows. Log shows a JSON-Error: Log

OneDrive doesn't work properly today and I'm getting these errors too. This is not an issue as sync is designed to resume from the last errors so eventually, once OneDrive starts working again, it should work. Please try again a bit later and let me know.

**Comment by laurent22** [comment] 2018-01-15 15:32
I assume this bug is now fixed so closing the issue for now. Feel free to re-open with more information, if it's still happening.

**Closed by laurent22** 2018-01-15 15:32 UTC
Labels: bug
