### ISSUE TITLE
Joplin Cloud down

### ISSUE THREAD

**Issue by akamiya** [laurent22/joplin#5719] opened 2021-11-14 04:38 UTC
Syncing with Joplin Cloud results in:

502 Bad Gateway

Using:

Joplin 2.5.12 (prod, win32)

Client ID: ebfd62331a3346ce8006382d54211124
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: 884b86f

On Windows 10:

Edition		Windows 10 Home
Version		21H1
Installed on	‎2020/‎05/‎28
OS Build		19043.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by laurent22** [comment] 2021-11-14 16:34
Yes sorry about this. This is fixed now and the cause of this crash is being worked on: https://discourse.joplinapp.org/t/is-joplin-cloud-down/21725/3

**Closed by laurent22** 2021-11-14 16:34 UTC
Labels: bug
