### ISSUE TITLE
Android 1.1.2 preferences lost: sync settings, date/time formats, theme, ...

### ISSUE THREAD

**Issue by deftdawg** [laurent22/joplin#3807] opened 2020-09-23 01:07 UTC
Upon opening Joplin tonight on my Android phone it immediately crashed, reopening it all of my preferences appear to be gone.   Maybe related to #3804 

## Environment

Joplin version: 1.1.2
Platform:  Android
OS specifics:  Android 10

## Steps to reproduce

1.  Update to 1.1.2 (play store will do this for you)
2. Open the app
3. Done

## Describe what you expected to happen

Expected settings to be retained

**Comment by laurent22** [comment] 2020-09-23 08:19
Duplicate of #3804

**Closed by laurent22** 2020-09-23 08:19 UTC
Labels: bug

**Comment by laurent22** [comment] 2020-09-23 08:20
Indeed a duplicate of that issue. I'd like to get to the bottom of it so any feedback or details you can provide to replicate this issue would be welcome. 

In particular for one user it seems to happen due to the share feature. Do you often share data (image or text) with Joplin from other apps?

**Comment by deftdawg** [comment] 2020-09-23 13:17
I never send anything to Joplin via the Android "share" feature. 

My app + settings have so far been stable following reapplying my preferences and completing a sync that pulled down 1900 items. (At least some of those were still present at time of crash and after; though one was an outdated version and I didn't check if there were missing ones)

I'll move over #3804

**Comment by dspacejs** [comment] 2020-10-14 06:04
I have the same problem
