### ISSUE TITLE
Allow the Android app to open attached files using Android "open with" application picker

### ISSUE THREAD

**Issue by valmar** [laurent22/joplin#519] opened 2018-05-13 12:50 UTC
### Operating system

- Android

### Application

- Mobile

Currently, if a note has an attached file, when I tap on it trying to open it with another app, I get this message: "The Joplin mobile app does not currently support this type of link: resource"

Instead I would expect to see the "Open the file using..." context menu from Android. 

Please let me know if more information is needed on the issue!

Valerio

PS: This is the last thing preventing me from using Joplin on a day to day basis! I am extremely pleased with how it is developing...

**Comment by laurent22** [comment] 2018-05-14 09:08
Duplicate of #350

**Closed by laurent22** 2018-05-14 09:08 UTC
