### ISSUE TITLE
error in joplin server v2.10.3. (docker)

### ISSUE THREAD

**Issue by wyl-i** [laurent22/joplin#7479] opened 2022-12-18 14:52 UTC
## Environment

Joplin serverversion update from v2.9.7 to v2.10.3
Platform: synology docker
OS specifics: 

## Steps to reproduce

1. update from v2.9.7 to v2.10.3
2. 
3. 

## Describe what you expected to happen
Looked at this "bug". I don't know what to do. Please give advice.

## Logfile

```
  message: 'Missing required property: type_: ',

  stack: 'Error: Missing required property: type_: \n' +

    '    at Function.<anonymous> (/home/joplin/packages/lib/models/BaseItem.ts:504:28)\n' +

2022-12-17 18:37:06: App: PUT /api/items/root:/6c3ee7288b6a4eab93b05f1fc935dd3d.md:/content (500) (12ms)

    '    at Generator.next (<anonymous>)\n' +

    '    at /home/joplin/packages/lib/models/BaseItem.js:8:71\n' +

    '    at new Promise (<anonymous>)\n' +

    '    at __awaiter (/home/joplin/packages/lib/models/BaseItem.js:4:12)\n' +

    '    at Function.unserialize (/home/joplin/packages/lib/models/BaseItem.js:438:16)\n' +

    '    at /home/joplin/packages/server/src/utils/joplinUtils.ts:97:18\n' +

    '    at Generator.next (<anonymous>)\n' +

    '    at /home/joplin/packages/server/dist/utils/joplinUtils.js:8:71\n' +

    '    at new Promise (<anonymous>)'
```

**Comment by laurent22** [comment] 2022-12-18 15:28
Do you have any way to inspect the traffic leaving the app, using Charles, Wireshark or similar? You would want to see what exactly is being uploaded at `/api/items/root:/6c3ee7288b6a4eab93b05f1fc935dd3d.md:/content`

Also please provide more information from the log before and after the other.

**Comment by laurent22** [comment] 2022-12-18 15:33
Duplicate of #7479

**Closed as completed by laurent22** 2022-12-18 15:33 UTC
Labels: bug, high, server

**Comment by wyl-i** [comment] 2022-12-19 08:40
Hi, thank you for your answer. I have never worked with whireshark or similar apps. So I am afraid executing your question is too difficult for me. And I can imaging that explaining this step by step to me is too much time consuming for you. I am a relatively beginner in this matter.
Sorry for the inconvenience.
Wyl

**Comment by wyl-i** [comment] 2022-12-20 16:34
Hi Laurent, today I was astonished: when i started my PC i saw that my joplin server was working again. No errors anymore!. I do not know is you have changed something but all of the sudden everything is working normal again. I am very grateful. Thank you very very much.
Wyl

**Comment by laurent22** [comment] 2022-12-20 16:47
If you had your server setup to automatically it probably picked up the latest version, which includes a fix for the issue you had.
