### ISSUE TITLE
Desktop: Show installed plugins in Help - About Joplin

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#6143] opened 2022-02-12 14:02 UTC
- The list of plugin should appear within the About box.
- When clicking on "Copy", that list should be included too.
- If there are more than 20 plugins, just add "..." in the About box, but still make sure that all the plugins are copied when pressing "Copy". Also please check that the dialog is not broken when there are 20 plugins.
  
![image](https://user-images.githubusercontent.com/1285584/155844375-5fc0ef89-67b2-4595-aa84-ea84525d9c2b.png)

**Comment by roman-r-m** [comment] 2022-02-12 14:12
go for it

**Comment by Aman-Mandal** [comment] 2022-02-12 14:15
Actually am very new in this.. can you tell me what exactly I need to do ? I would be glad if you can help
Thankyouuuu

**Comment by roman-r-m** [comment] 2022-02-12 14:18
On high level:

* Check out the code
* Make sure you can build the app
* Start it, find the dialog
* Find in the code where it's created; see how it's populated
* Find the class that keeps track of installed plugins
* Access this class from the place where the dialog is populated, get the list of plugins, and display them

**Comment by tessus** [comment] 2022-02-12 20:45
Was this discussed on the forum? Some people use many plugins (20+). I think it would mess up the About dialog. But maybe not.

I'd rather go for something similar to `Synchronisation Status`.

**Comment by roman-r-m** [comment] 2022-02-12 20:52
I sent a message to Laurent and we was fine with it.

But I see your point - I assumed this dialog is just like every other view and the list could be made scrollable. But now having looked at how it's done I am no longer sure.

The idea was that often when someone reports an issue the 1st question is "what plugins do you have" and if we could add this info to the version it should save some time.

**Comment by tessus** [comment] 2022-02-12 20:57
I totally understand the reasoning behind it. I think it makes sense to put it in the About dialog or at least add the installed plugins, when you click the `Copy` button. I am just afraid it messes up the About dialog when a lot of plugins are used.

We can always add a `Copy` button to a window like `Synchronisation Status`. So, in case it messes up the About dialog, craeting a separate menu item `Inatlled plugins` with a Copy button would do the trick.

**Comment by roman-r-m** [comment] 2022-02-12 21:04
> add the installed plugins, when you click the `Copy` button

This is what Android Studio does. I agree this makes more sense.

I suggest when someone implements this we have a look and if it does indeed messes up the dialog we can ask to implement  only the copy - the difference between the 2 approaches looks to be trivial.

**Comment by Daeraxa** [comment] 2022-02-12 21:29
Could the list of plugins just be within a scrollable frame within the main about dialogue box? (I'm sure there is a technical term for what I mean). This actually is how software I use at work displays installed drivers which can easily exceed 100 on some systems.

**Comment by roman-r-m** [comment] 2022-02-12 22:24
From a quick look I think that dialog only supports plain text

**Comment by ahsenkamal** [comment] 2022-02-13 15:42
> If you read the comments above, you'll see that Aman-Mandal was going to work on it.

I'm new to all this, does it mean that I can not do anything related to this issue now?

**Comment by roman-r-m** [comment] 2022-02-13 21:19
> I'm new to all this, does it mean that I can not do anything related to this issue now?

Well you can, it just may not be the most useful thing as someone else has already starting working on this and may be first to submit a PR.

**Comment by ahsenkamal** [comment] 2022-02-14 12:01
> Well you can, it just may not be the most useful thing as someone else has already starting working on this and may be first to submit a PR.

Okay thanks

**Comment by Aman-Mandal** [comment] 2022-02-19 14:36
> > If you read the comments above, you'll see that Aman-Mandal was going to work on it.
> 
> I'm new to all this, does it mean that I can not do anything related to this issue now?

Hey you can go ahead.. am sorry , am unable to solve this issue

**Comment by Daeraxa** [comment] 2022-03-10 17:23
Have you read the closed PR that is linked just above your comment? There are comments in there and things you need to be aware of.
Otherwise yes, the issue/enhancement is still active as it has not been closed.

**Comment by rookieCoder9** [comment] 2022-03-10 17:41
Yeah, I have already read that and the problems with that commit. I always comment after reading the above discussion! But it is always good to first ask the moderator before working on the issue. Let me go through it.
But still, the expected outcome isn't clear ? Will there be a scrollable area to display all plugins?

**Comment by Daeraxa** [comment] 2022-03-10 17:55
The goal is in the issue text:

> If there are more than 20 plugins, just add "..." in the About box, but still make sure that all the plugins are copied when pressing "Copy". Also please check that the dialog is not broken when there are 20 plugins.

There are other comments pointing out that the popup being used doesn't support anything beyond plain text so I don't think scrolling is even an option.

**Comment by rookieCoder9** [comment] 2022-03-12 11:00
Hey, I have fixed my issue locally but don't know how to write unit tests. Can someone help me how to write unit tests?

Below I am attaching ss.
The first two are with around 17 plugins installed. The next ones are with 34 plugins installed. Please give feedback.

![Screenshot from 2022-03-12 16-24-49](https://user-images.githubusercontent.com/78199565/158015302-04f681ce-c09b-47ad-861a-5e1b9bcb3c3b.png)
![Screenshot from 2022-03-12 16-26-33](https://user-images.githubusercontent.com/78199565/158015303-e7a57ed5-1e83-40c9-a3b8-f33aae4c4875.png)
![Screenshot from 2022-03-12 16-28-21](https://user-images.githubusercontent.com/78199565/158015346-52793cbe-135d-4a77-90c1-02126d75b06e.png)
![Screenshot from 2022-03-12 16-28-33](https://user-images.githubusercontent.com/78199565/158015347-c38ea455-96ec-4722-9022-2ddf4c50e399.png)

**Comment by Daeraxa** [comment] 2022-03-12 11:10
There is newly (as in the last few days) updated documentation on test units so make sure you read that: https://github.com/laurent22/joplin/blob/dev/CONTRIBUTING.md#automated-tests

**Comment by rookieCoder9** [comment] 2022-03-12 11:17
Thanks, I will go through it and will soon raise PR  :)

**Comment by rookieCoder9** [comment] 2022-03-14 15:40
Hey, I am still not getting how to add tests for this bug fix . Please help! 

I have read the documentation of Jest but couldn't find a suitable test for this bug fix.

**Comment by Daeraxa** [comment] 2022-03-14 15:55
To start with this is an enhancement, not a bug fix so therefore tests are even more critical that they are included.

If you want to ask specific questions about how to do something like that then I would advise asking in the forum development category but you won't get anywhere just asking "how to I do it" because that is a vital part of the challenge of adding a feature or creating a fix that you need to overcome. You at the very least need to demonstrate specifically what you are stuck on and what you have already done.

Otherwise you should look at other merged PRs and see how they have implemented tests so you can understand what you need to do.

**Comment by rookieCoder9** [comment] 2022-03-14 16:18
Ok, thanks I will ask my doubts in the forum. Further, I will look at the previous merged PRs tests.

**Comment by mirchandani-mohnish** [comment] 2022-03-21 11:13
@rookieCoder9 , are you done with the tests or are nearing the end given that you have not made a pull request. Can I help in any way?

**Comment by rajdama** [comment] 2022-03-28 07:01
![Screenshot 2022-03-28 122915](https://user-images.githubusercontent.com/75741866/160343353-aac0bd5a-8ca2-45ad-9015-3621a904477c.png)

I am not able to see the installed plugins in the dialog box.

**Comment by Daeraxa** [comment] 2022-03-28 09:04
> I am not able to see the installed plugins in the dialog box.

There is no merged PR for this and you are running prod so this is entirely expected.

**Comment by rajdama** [comment] 2022-03-28 11:12
> > I am not able to see the installed plugins in the dialog box.
> 
> There is no merged PR for this and you are running prod so this is entirely expected.



> > I am not able to see the installed plugins in the dialog box.
> 
> There is no merged PR for this and you are running prod so this is entirely expected.

What you mean by prod I didn't understood

**Comment by Daeraxa** [comment] 2022-03-28 11:59
Literally in your screenshot `(prod, win32)` i.e. a "full" release version of Joplin.
You aren't running a dev version with somebody else's commit to add the plugins it and it obviously wouldn't contain your own code to fix it so I'm not sure what you are expecting to see. This entire issue exists to add the plugins list to the box.

**Comment by rajdama** [comment] 2022-03-28 12:03
> Literally in your screenshot `(prod, win32)` i.e. a "full" release version of Joplin. You aren't running a dev version with somebody else's commit to add the plugins it and it obviously wouldn't contain your own code to fix it so I'm not sure what you are expecting to see. This entire issue exists to add the plugins list to the box.

Ok I got it

**Closed** 2023-02-08 14:16 UTC
Labels: enhancement, desktop
