### ISSUE TITLE
Allow change of notes sort order

### ISSUE THREAD

**Issue by cicithesquirrel** [laurent22/joplin#13] opened 2017-11-30 13:18 UTC
It would be nice to be able to change the notes sort order.

I guess this order is currently alphabetical. There could be an option to have a "last update descending" sort order (so that the last modified note is on top of the list).

**Comment by dariosalviwork** [comment] 2017-12-11 13:36
+1 !
also, it would help to be able to change the date of each note manually.

For example, I am taking a diary of some things or events, if I later change one note (eg I want to correct a mistake) I would like to date not to be updated, or I would like to set it manually to its original date.

Another example: I am copying my diary from another application, one by one, and I would like to set the actual dates to the notes.

**Comment by alexdevero** [comment] 2018-01-14 08:23
+1
Agree with @dariosalviwork. I encountered this "issue" when I was working with some old notes in my diary. I use dates to name these notes (01.01.2018, 02.01.2018, etc.) to keep the order. However, when I find a typo or edit some older note, say from 05.01.2018, it will immediately "jump" on the top of the list, before 06.01.2018, 07.01.2018 and so on.

Ability to sort notes according to the "created" date instead of "last edit" or by "name" would solve this.

**Comment by ronaldgit** [comment] 2018-01-23 08:55
+1
Reordering manually and / or alphabetically would be very nice. Now the latest note is always on top, which is not always logical.

**Comment by natuk** [comment] 2018-01-29 13:00
+1
I would suggest the same sorting functionality for notebooks as well, not only notes.

**Comment by laurent22** [comment] 2018-02-11 20:41
Duplicate of #51

**Closed** 2018-02-11 20:42 UTC
Labels: enhancement

**Comment by istodorionut** [comment] 2018-08-06 04:07
Hello guys,

They're is a problem with sorting notes by number 1 - 100.
Take a look at the picture.

![image](https://user-images.githubusercontent.com/42129745/43696557-2ade8fec-9947-11e8-91c3-d9c9906e04a4.png)

Thanks,
