### ISSUE TITLE
Feature Request: Implement a Trash Bin in Joplin

### ISSUE THREAD

**Issue by devtool15424** [laurent22/joplin#9625] opened 2023-12-29 13:12 UTC
### Operating system

Android

### Joplin version

all

### Current behaviour

Hello,

As a new user of Joplin, I've noticed a critical feature missing: a trash bin for recovering deleted notes. Currently, if a note is deleted, especially if it's new or seldom modified, there's no way to recover it.

I suggest adding a trash bin where deleted notes can be temporarily stored before permanent deletion. This would significantly improve data management and align Joplin with other note-taking apps.

Thank you for considering this enhancement to improve user experience.

**Comment by laurent22** [comment] 2024-01-04 16:27
Duplicate of #483

**Closed as completed by laurent22** 2024-01-04 16:27 UTC
Labels: bug
