### ISSUE TITLE
Display note tags in the note edit/view pane

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#916] opened 2018-10-25 02:48 UTC
Currently, the only way to know the tags of a note is to click on the tag icon, which is inconvenient. Why not showing all the tags (above or below the note title)?

### Application
- Desktop

**Comment by CastedConst** [comment] 2019-03-27 15:24
Duplicate of #469 .
I suggest to close this one as the other one is more up to date

**Closed** 2019-03-27 15:42 UTC
