### ISSUE TITLE
Glitches in notebook view – Text partly unreadable

### ISSUE THREAD

**Issue by codiflow** [laurent22/joplin#8057] opened 2023-04-17 12:23 UTC
I'm using Joplin for a very long time now and after some update (I think about a year ago?) glitches started to happen inside the notebook area. It seems like text from upper elements is being put upon lower elements – but not everywhere.

I thought maybe this is a bug which gets fixed but as it is persistent for such a long time now and I couldn't find anything related in the issues I opened a new issue now.

I already tried to
- disable all plugins (no effect)
- cleared Joplin cache using developer tools (no effect)
- removed `tmp` and `cache` folders in profile folder (no effect)
- start in safe mode (no effect)

## Screenshots / Screencast
![glitches_joplin](https://user-images.githubusercontent.com/43847817/232477859-7afd98cc-4018-4222-bc9b-5f6f66329c48.png)

---

![glitches_joplin_3](https://user-images.githubusercontent.com/43847817/232477999-05bac8a1-32fd-4c40-93af-dd64c203d433.png)

I know we should not post code as screenshot – this was  just inserted to show that the elements are not overlapping (with same classes or ids):
![glitches_joplin_3_code](https://user-images.githubusercontent.com/43847817/232478003-a03a314b-06e9-47c8-ba57-c60f44ce3484.png)

---

Also the "Last update" date is affected sometimes:
![glitches_joplin_4](https://user-images.githubusercontent.com/43847817/232478011-71886615-5609-40c3-88a1-372cb16331d4.png)

## Environment

Joplin version: `Desktop 2.9.17 (prod, linux) Revision: a84a8e7`
Platform: `Linux x64`
OS specifics: `Manjaro Linux, XFCE`
Installed package: `aur/joplin-appimage 2.9.17-1` (https://aur.archlinux.org/packages/joplin-appimage)

```
This is xfwm4 version 4.18.0 (revision 7e7473c5b) for Xfce 4.18
Released under the terms of the GNU General Public License.
Compiled against GTK+-3.24.35, using GTK+-3.24.37.

Build configuration and supported features:
- Startup notification support:                 Yes
- XSync support:                                Yes
- Render support:                               Yes
- Xrandr support:                               Yes
- Xpresent support:                             Yes
- X Input 2 support:                            No
- Embedded compositor:                          Yes
- Epoxy support:                                Yes
```

Command lines while running Joplin (`ps -aef | grep joplin`):
`/tmp/.mount_joplinOYZ2hA/@joplinapp-desktop --no-sandbox --enable-crashpad`
`/usr/bin/joplin-desktop --no-sandbox`
`/tmp/.mount_joplinOYZ2hA/@joplinapp-desktop --type=zygote --no-zygote-sandbox --no-sandbox --enable-crashpad --enable-crashpad`
`/tmp/.mount_joplinOYZ2hA/@joplinapp-desktop --type=zygote --no-sandbox --enable-crashpad --enable-crashpad`
`/tmp/.mount_joplinOYZ2hA/@joplinapp-desktop --type=gpu-process --no-sandbox --enable-crashpad --enable-crash-reporter=87149631-1eec-46a9-a611-20061bc21c0c,no_channel --user-data-dir=/home/USER/.config/Joplin --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,5977730271428655015,4216591786243426591,131072 --disable-features=SpareRendererForSitePerProcess`
`/tmp/.mount_joplinOYZ2hA/@joplinapp-desktop --type=utility --utility-sub-type=network.mojom.NetworkService --lang=de --service-sandbox-type=none --no-sandbox --enable-crashpad --enable-crash-reporter=87149631-1eec-46a9-a611-20061bc21c0c,no_channel --user-data-dir=/home/USER/.config/Joplin --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,5977730271428655015,4216591786243426591,131072 --disable-features=SpareRendererForSitePerProcess --enable-crashpad`
`/tmp/.mount_joplinOYZ2hA/@joplinapp-desktop --type=renderer --enable-crashpad --enable-crash-reporter=87149631-1eec-46a9-a611-20061bc21c0c,no_channel --user-data-dir=/home/USER/.config/Joplin --app-path=/tmp/.mount_joplinOYZ2hA/resources/app.asar --no-sandbox --no-zygote --no-sandbox --lang=de --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --launch-time-ticks=235082276559 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,5977730271428655015,4216591786243426591,131072 --disable-features=SpareRendererForSitePerProcess --enable-crashpad`

## Steps to reproduce

1. Open Joplin
2. Notice the glitches on the left hand side
3. Hover the glitches with your mouse – they disappear and reappear depending on the mouse position. They also remain in place if I scroll down or resize the window.

## Describe what you expected to happen
No glitches happen at all.

## Logfile
log.txt
```
2023-04-17 14:13:55: App: "Profile directory: /home/USER/.config/joplin-desktop"
2023-04-17 14:13:55: App: "Root profile directory: /home/USER/.config/joplin-desktop"
2023-04-17 14:13:55: "Database was open successfully"
2023-04-17 14:13:55: "Checking for database schema update..."
2023-04-17 14:13:55: "Current database version", "{"version":41,"table_fields_version":41}"
2023-04-17 14:13:55: "Upgrading database from version 41"
2023-04-17 14:13:55: "New version: 41. Previously recorded version: 41"
2023-04-17 14:13:55: "KeychainService: checking if keychain supported"
2023-04-17 14:13:55: "KeychainService: check was already done - skipping. Supported:", "0"
2023-04-17 14:13:55: e2ee/utils: "Master password is not set - trying to get it from the active master key..."
2023-04-17 14:13:55: handleSyncStartupOperation: "Processing operation:", "0"
2023-04-17 14:13:55: App: "Client ID: XXX"
2023-04-17 14:13:55: models/Setting: "Applying default migrations..."
2023-04-17 14:13:55: e2ee/utils: "Trying to load 0 master keys..."
2023-04-17 14:13:55: e2ee/utils: "Loaded master keys: 0"
2023-04-17 14:13:55: "ResourceFetcher: Auto-add resources: Mode: always"
2023-04-17 14:13:55: "ResourceFetcher: Auto-added resources: 0"
2023-04-17 14:13:55: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-04-17 14:13:55: e2ee/utils: "Trying to load 0 master keys..."
2023-04-17 14:13:55: e2ee/utils: "Loaded master keys: 0"
2023-04-17 14:13:55: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-04-17 14:13:55: e2ee/utils: "Trying to load 0 master keys..."
2023-04-17 14:13:55: e2ee/utils: "Loaded master keys: 0"
2023-04-17 14:13:55: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-04-17 14:13:55: e2ee/utils: "Trying to load 0 master keys..."
2023-04-17 14:13:55: e2ee/utils: "Loaded master keys: 0"
2023-04-17 14:13:55: "app.start: doing regular boot"
2023-04-17 14:13:55: "KeymapService: Loading keymap from file: /home/USER/.config/joplin-desktop/keymap-desktop.json"
2023-04-17 14:13:55: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-04-17 14:13:55: e2ee/utils: "Trying to load 0 master keys..."
2023-04-17 14:13:55: e2ee/utils: "Loaded master keys: 0"
2023-04-17 14:13:55: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-04-17 14:13:55: e2ee/utils: "Trying to load 0 master keys..."
2023-04-17 14:13:55: e2ee/utils: "Loaded master keys: 0"
2023-04-17 14:13:55: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-04-17 14:13:55: e2ee/utils: "Trying to load 0 master keys..."
2023-04-17 14:13:55: e2ee/utils: "Loaded master keys: 0"
2023-04-17 14:13:56: RevisionService: "runInBackground: Starting background service with revision collection interval 600000"
2023-04-17 14:13:56: defaultPluginsUtils: "Could not find default plugins' directory: /tmp/.mount_joplinzOz1Fv/resources/build/defaultPlugins - skipping installation."
2023-04-17 14:13:56: PluginService: "Loading plugin from /home/USER/.config/joplin-desktop/cache/com.hieuthi.joplin.slash-commands"
2023-04-17 14:13:56: PluginService: "Not running disabled plugin: "com.hieuthi.joplin.slash-commands""
2023-04-17 14:13:56: PluginService: "Loading plugin from /home/USER/.config/joplin-desktop/cache/joplin.plugin.templates"
2023-04-17 14:13:56: PluginService: "Not running disabled plugin: "joplin.plugin.templates""
2023-04-17 14:13:56: PluginService: "Loading plugin from /home/USER/.config/joplin-desktop/cache/net.rmusin.joplin-table-formatter"
2023-04-17 14:13:56: PluginService: "Not running disabled plugin: "net.rmusin.joplin-table-formatter""
2023-04-17 14:13:56: PluginService: "Loading plugin from /home/USER/.config/joplin-desktop/cache/outline"
2023-04-17 14:13:56: PluginService: "Not running disabled plugin: "outline""
2023-04-17 14:13:56: SpellCheckerServiceDriverNative: "Set effective languages to "de""
2023-04-17 14:13:58: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-04-17 14:13:58: "Preparing scheduled sync"
2023-04-17 14:13:58: "Starting scheduled sync"
2023-04-17 14:13:58: Synchronizer: "Sync: starting: Starting synchronisation to target 5... supportsAccurateTimestamp = false; supportsMultiPut = false [1681733638049]"
2023-04-17 14:13:58: Synchronizer: "Indexing resources..."
2023-04-17 14:13:58: "ResourceService::indexNoteResources: Start"
2023-04-17 14:13:58: "ResourceService::indexNoteResources: Completed"
2023-04-17 14:13:59: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2023-04-17 14:13:59: Synchronizer: "Sync target is already setup - checking it..."
2023-04-17 14:13:59: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2023-04-17 14:14:00: RevisionService: "maintenance: Starting..."
2023-04-17 14:14:00: RevisionService: "maintenance: Service is enabled"
2023-04-17 14:14:00: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-04-17 14:14:00: RevisionService: "maintenance: Done in 105ms"
2023-04-17 14:14:04: Synchronizer: "BasicDelta: Report: {"timestamp":1681685479000,"older":5478,"newer":0,"equal":1}"
2023-04-17 14:14:04: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2023-04-17 14:14:04: Synchronizer: "Sync: finished: Synchronisation finished [1681733638049]"
2023-04-17 14:14:04: Synchronizer: "Operations completed: "
2023-04-17 14:14:04: Synchronizer: "fetchingTotal: -"
2023-04-17 14:14:04: Synchronizer: "Total folders: 245"
2023-04-17 14:14:04: Synchronizer: "Total notes: 888"
2023-04-17 14:14:04: Synchronizer: "Total resources: 648"
2023-04-17 14:14:04: "Updating all notifications..."
2023-04-17 14:14:04: "Garbage collecting alarms..."
2023-04-17 14:14:04: "Sync has finished and note has never been changed - reloading it"
2023-04-17 14:14:05: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-04-17 14:14:05: "SearchEngine: Updating FTS table..."
2023-04-17 14:14:05: "SearchEngine: Updated FTS table in 1ms. Inserted: 0. Deleted: 0"
2023-04-17 14:14:26: "ResourceService::indexNoteResources: Start"
2023-04-17 14:14:26: "ResourceService::indexNoteResources: Completed"
2023-04-17 14:14:26: "ResourceService::deleteOrphanResources:", "[]"
2023-04-17 14:19:04: "Running background sync on timer..."
2023-04-17 14:19:04: "Preparing scheduled sync"
2023-04-17 14:19:04: "Starting scheduled sync"
2023-04-17 14:19:04: Synchronizer: "Sync: starting: Starting synchronisation to target 5... supportsAccurateTimestamp = false; supportsMultiPut = false [1681733944776]"
2023-04-17 14:19:04: Synchronizer: "Indexing resources..."
2023-04-17 14:19:04: "ResourceService::indexNoteResources: Start"
2023-04-17 14:19:05: "ResourceService::indexNoteResources: Completed"
2023-04-17 14:19:05: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2023-04-17 14:19:05: Synchronizer: "Sync target is already setup - checking it..."
2023-04-17 14:19:05: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2023-04-17 14:19:06: Synchronizer: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2023-04-17 14:19:06: Synchronizer: "TaskQueue.stop: syncDownload: Done, waited for 0"
2023-04-17 14:19:10: Synchronizer: "BasicDelta: Report: {"timestamp":1681685479000,"older":5478,"newer":0,"equal":1}"
2023-04-17 14:19:10: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2023-04-17 14:19:10: Synchronizer: "Sync: finished: Synchronisation finished [1681733944776]"
2023-04-17 14:19:10: Synchronizer: "Operations completed: "
2023-04-17 14:19:10: Synchronizer: "fetchingTotal: -"
2023-04-17 14:19:10: Synchronizer: "Total folders: 245"
2023-04-17 14:19:10: Synchronizer: "Total notes: 888"
2023-04-17 14:19:10: Synchronizer: "Total resources: 648"
2023-04-17 14:19:10: "Sync has finished and note has never been changed - reloading it"
2023-04-17 14:19:11: "DecryptionWorker: cannot start because no master key is currently loaded."
```

**Comment by Daeraxa** [comment] 2023-04-17 13:49
Duplicate of https://github.com/laurent22/joplin/issues/7506 and closed in https://github.com/laurent22/joplin/pull/7897. Changes available in 2.10.9 pre-releases and later.

**Closed as completed by Daeraxa** 2023-04-17 13:49 UTC
Labels: bug
