### ISSUE TITLE
Tab doesn't indent when in non-empty list items

### ISSUE THREAD

**Issue by masonproffitt** [laurent22/joplin#4470] opened 2021-02-04 13:40 UTC
Pressing tab while the cursor is within a non-empty list item places a literal tab character at the cursor as opposed to indenting the list item.

## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: Windows 10 Home 20H2

## Steps to reproduce

1. Open any note in the CodeMirror editor
2. Create a list item containing any non-whitespace text
3. Place the cursor anywhere after the list token on that line
3. Press tab

Example:

![test1](https://user-images.githubusercontent.com/32773304/106900142-73757e80-66f6-11eb-931e-f68a0b453d29.png)

After hitting tab:

![test2](https://user-images.githubusercontent.com/32773304/106900185-825c3100-66f6-11eb-9400-283ff5304dbd.png)

## Describe what you expected to happen

The whole line should get indented, and there should not be a tab in the middle of the list item text.

**Comment by tessus** [comment] 2021-02-04 17:08
I think that was on purpose. Some people might want to use a `tab` in a list item.

`- Text<TAB>some other text`

You can always use the indent/unindent shortcuts `Cmd+[` and `Cmd+]`.

**Comment by masonproffitt** [comment] 2021-02-04 17:34
I'm pretty sure this was an unintended consequence of #3581. If the intended design is to only use `Ctrl-[` and `Ctrl-]` for indentation, why does tab in an empty list item indent?

Example:

![test3](https://user-images.githubusercontent.com/32773304/106931741-31a90000-6717-11eb-9eaf-67a1cf444d7b.png)

After pressing tab:

![test4](https://user-images.githubusercontent.com/32773304/106931759-379ee100-6717-11eb-8fe2-17f6ad0ac120.png)

By your argument, there should be a tab inserted at the cursor position rather than an indent before the list token. Either way, the current state is inconsistent.

**Comment by masonproffitt** [comment] 2021-02-04 18:01
Incidentally, `Ctrl-[` doesn't work in the vim keyboard mode. Of course then you have `<<` and `>>`, but those don't work in insert mode.

**Comment by tessus** [comment] 2021-02-04 18:48
> By your argument, there should be a tab inserted at the cursor position rather than an indent before the list token.

No, my statement was referring to "when in non-empty list item".

The reason for only allowing TAB in an empty list/checkbox was to allow quick and easy indentation when **creating** a list.
For me the current behavior makes perfect sense.
When I hit RETURN to create a new item, it will be on the same level. Then I can quickly use TAB / Shift+TAB to change the indentation. Using TAB is a lot quicker than `Cmd+[`. However, when text requires me to use a TAB I can do that.
With your approach, it won't be possible to use TABs in (checkbox) lists.

> Incidentally, Ctrl-[ doesn't work in the vim keyboard mode.

It was cleary stated (when adding those modes and also in the documentation) that
- some shortcuts might not work in non-default keyboard modes
- non-default keyboard modes are not supported

**Comment by CalebJohn** [comment] 2021-02-04 19:06
@tessus is correct, this is working as intended. Allowing tab to indent a new list is a special case to make new lists easier, but I wouldn't want it everywhere. This is, of course, a personal preference, but one I believe is shared across much of our userbase.

We appreciate the effort you put into tracking down this issue and submitting a PR with the patch. You went further than most people that submit bugs and it's appreciated.

While I don't think the default behaviour of Joplin will be changed, it is still possible for you to make the change without affecting the core Joplin behaviour. The Joplin [plugin system](https://joplinapp.org/api/references/plugin_api/classes/joplincontentscripts.html) is powerful enough that it will allow you to overwrite the `smartListIndent` and `smartListUnindent` with the behaviour that you're looking for! Additionally, you can use the same plugin system to add any commands you want to the vim mode (as Tessus said, vim mode isn't really supported beyond wait CodeMirror provides, so having someone that actually uses vim mode help out would be a real asset for the project). If you take a look at the [plugin resources](https://github.com/laurent22/joplin/blob/dev/readme/api/get_started/plugins.md) you'll see that it's really easy to get write plugins (especially for something simple like redefining a CodeMirror command). 

If you do want to turn this into a plugin and get stuck, please let me know and I can give you some guidance!

**Comment by masonproffitt** [comment] 2021-02-04 19:13
Interesting. The behavior seems unintuitive to me, but my expectations are perhaps biased towards how Boost Note handles this, since I have more experience with it. I had already started working on a plugin to control other aspects of indentation, so I can indeed try to move this there.

**Comment by CalebJohn** [comment] 2021-02-05 15:42
Thanks, I'm going to close this now. But please let me know when you finish the plugin. A forum announcement is best, but if you don't want to use the forum, let me know and I can post it for you.

**Closed by CalebJohn** 2021-02-05 15:42 UTC

**Comment by hongwen000** [comment] 2022-04-29 16:32
Any news here?
