### ISSUE TITLE
Feature Request: Reminders - list all of them + display the due date

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#322] opened 2018-03-22 06:58 UTC
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

On the welcome page, may be it could be useful to list the reminders to come and those ones that are already passed but still not checked
And in that list sorted by due date from the nearer  ; next the event title, the due date of that event.

**Comment by laurent22** [comment] 2018-03-26 16:33
Duplicate of #322

**Closed by laurent22** 2018-03-26 16:33 UTC
