### ISSUE TITLE
iOS Synch issue

### ISSUE THREAD

**Issue by WhyMe4** [laurent22/joplin#3980] opened 2020-10-24 20:06 UTC
I've just installed Joplin desktop 1.2.6 and imported some notebooks from EverNote. Everything is working well on the desktop version (though synch with DropBox is slow).
However, on Joplin mobile for iOS 10.2.1, I keep getting synch issues
error invalid parameters in updateSyncTimeQueires
Sometimes I can fix this by removing extended ASCII characters (like 171 for ½)
but sometimes I cannot figure out why it's bombing.
## Environment

Joplin version: desktop 1.2.6 and iOS 10.2.1
Platform: iOS
OS specifics: iOS 14

## Steps to reproduce

1. Import notes from EverNote which have extended ASCII characters into Windows client of Joplin 
2. Synch to DropBox
3. Synch from iOS Joplin - Fail

## Describe what you expected to happen
Successful synch

## Logfile

![SyncIssue](https://user-images.githubusercontent.com/73404897/97092547-70a0c300-160a-11eb-8b6f-1fb8e155f624.png)

**Comment by laurent22** [comment] 2020-10-25 21:57
Would you mind sharing an ENEX file with a note that's causing this bug?

**Comment by WhyMe4** [comment] 2020-10-26 13:18
I've created a 2 note sample of the problem notes (duplicated the notes in Evernote to a new notebook, exported). They are giving an error, though not the same one. 
The actual notebook is a bit bigger.
[JoplinTest.zip](https://github.com/laurent22/joplin/files/5438966/JoplinTest.zip)

**Comment by WhyMe4** [comment] 2020-10-26 16:47
I've started with fresh installs of the Windows and iOS client. Got they synch with the test data, and all was good. Imported the JoplinTest into the Windows client. Synched, then tried to synch on iOS. iOS failed.

**Comment by tessus** [comment] 2020-11-02 01:07
Laurent asked for an Enex file to reproduce the issue. So unless you can provide some more info why this is happening, how hall we figure out that the problem is?

**Comment by WhyMe4** [comment] 2020-11-02 02:16
Thank you for the information. I'm not sure the if the problem is with the the import (it does import and work in the Windows client) or with the sync to iOS client. During the sync to iOS is where the problem is happening.

**Comment by laurent22** [comment] 2020-11-02 09:53
Fixed in https://github.com/laurent22/joplin/issues/3955

**Closed by laurent22** 2020-11-02 09:53 UTC
Labels: bug
