### ISSUE TITLE
funny paste behaviour in tools>general options>Text editor command

### ISSUE THREAD

**Issue by kr4z33** [laurent22/joplin#1428] opened 2019-04-17 19:05 UTC
### Operating system

- Windows (7)

### Application

- Desktop

Only Tested in Windows 7, Joplin version 1.0.142 (prod, win32)

Steps to replicate:

`ctrl`+`comma` (getting to general settings)
In Text editor command, Path field, paste in the following: `"C:`
observe a slash `\` in the Path field 
and a colon followed by a quote `:"` in the Arguments field

Expected behavior would show exactly what is pasted in the Path field

**Comment by laurent22** [comment] 2019-04-17 19:38
It's not clear what the issue is. What exactly did you paste, and what result did you get?

**Comment by kr4z33** [comment] 2019-04-18 01:30
Pasted the following line into Text editor command Path: input box in Joplin's general settings
`"C:`
Result is that the Text editor command Path: input box contains what is on the following line
`\`
while the Arguments: input box contains what is on the following line
`:"`

The context is pasting in a windows style path with spaces, the path is within quotes. Workaround for this funny paste behavior is to omit the quotes around the path before putting it into the Text editor command Path: text box in joplin's settings - the spaces in my particular path seem to be handled fine without encasing it in double quotes.

**Comment by laurent22** [comment] 2019-04-20 18:02
When pasting a path, the quotes indeed should not be included. There's not really a fix for this unfortunately.

**Closed by laurent22** 2019-04-20 18:02 UTC
Labels: bug, essential
