### ISSUE TITLE
Joplin 2.12.10 stopped creating log.txt file ?

### ISSUE THREAD

**Issue by MR-Joplin** [laurent22/joplin#8592] opened 2023-07-31 21:51 UTC
Joplin 2.12.10

does not create log.txt file!

**Comment by laurent22** [comment] 2023-07-31 23:40
There's log rotation now, but it should create a current log.txt.

There's nothing at all for you?

**Comment by MR-Joplin** [comment] 2023-08-01 09:53
> There's log rotation now, but it should create a current log.txt.
> 
> There's nothing at all for you?

Laurent22, thanks for your time.
So far I haven’t...
It is not a problem for the functioning of the application.
It’s just my curiosity and on the other hand it’s good not to have to delete the log.txt file from time to time.

**Comment by MR-Joplin** [comment] 2023-08-01 10:53
Laurent22
Not wanting to bother and thanking in advance, just one more small question: 
Is it definite that the editor (toggle editors) stops removing blank lines ?

**Comment by laurent22** [comment] 2023-08-01 13:25
Yes it should do that now

**Comment by laurent22** [comment] 2023-08-01 17:13
Duplicate of #8598

**Closed as completed by laurent22** 2023-08-01 17:13 UTC
Labels: bug

**Comment by MR-Joplin** [comment] 2023-08-01 17:43
> Yes it should do that now

Thank you, Laurent22
