### ISSUE TITLE
use export 'markdown + front matter', part of attachment loses extension

### ISSUE THREAD

**Issue by lin0kin** [laurent22/joplin#5679] opened 2021-11-05 16:46 UTC
## Environment

Joplin version: Joplin 2.5.10 (prod, win32)
Platform: win10 , amd 5900hx
OS specifics: 

## Steps to reproduce

1. click file to export 
2. exoprt
3. markdown + front matter

## Describe what you expected to happen

using 'markdown + front matter' to export md to share, but lot of md file is losing their extension, like :

11.gif ->  11.g or 11.gi
22.png -> 22.p or 22.pn
...
some file dont have one ,it's id on joplin, like ce7ea5e6d064796921360f3d8cb8f29 -> when exported, it;'s name like 
 watermark_type_ZmFuZ3poZW5naGVpd_3380d30ba4c94dc6a

plz fix it !

**Comment by laurent22** [comment] 2021-11-05 18:10
Probably a duplicate of https://github.com/laurent22/joplin/issues/5653

**Comment by lin0kin** [comment] 2021-11-06 02:17
> 
> 
> Probably a duplicate of #5653

looks very similar. This is the filename of a file exported from joplin:

15777556-982bd5a0f9382128_d7a3ac2fbd7340a09492d8b5

Exactly 50 characters. how to fix it?

**Closed** 2021-12-23 03:46 UTC
Labels: bug
