### ISSUE TITLE
[Renderer] Alt-text of a local image is not rendered

### ISSUE THREAD

**Issue by ylc395** [laurent22/joplin#5803] opened 2021-11-29 04:06 UTC
```markdown
![this is alt text](:/06f049df282b4780bbfbdc306383bab5)
```
Its renderring result won't contain alt text. Is it a bug or intended feature? In fact, I''m a plugin developer and want to store some information as images' alt text. It would be better if alt text won't be ignored.

**Comment by CalebJohn** [comment] 2021-11-29 05:41
@ylc395 alt text only displays when an image can't be rendered, hence the name alt (from "alternative"). This is a standard part of html/markdown.

I think maybe what you want is to set the hover text? This is called a title and it is available in markdown as follows:

```markdown
![this is alt text](:/06f049df282b4780bbfbdc306383bab5 "I'm a title")
```

**Comment by ylc395** [comment] 2021-11-29 06:14
Yes, alt text is only displayed when image can not be loaded. But what I said is rendered-HTML doesn't cantain alt attribute.

**Comment by CalebJohn** [comment] 2021-11-29 19:43
Thanks for the clarification @ylc395 

Looks like the alt text is preserved when the image is not available, so it performs in the way it should for that case. But indeed it's odd that the alt text isn't transferred to the html and leave the rendering to the actual HTML display.

The best next step would be to post about this on the forum, that will put the issue in front of the community and perhaps someone that knows more about the MD to HTML system will be able to chime in if this is beneficial or not.

**Comment by CalebJohn** [comment] 2022-01-09 01:16
Not stale.

**Comment by mak2002** [comment] 2022-01-11 05:22
Hey there @CalebJohn , Can I want to work on this issue ?

**Comment by CalebJohn** [comment] 2022-01-11 05:31
Go for it @mak2002, good luck!

**Comment by mak2002** [comment] 2022-01-13 13:46
hey @CalebJohn I was following [this markdown-it issue](https://github.com/markdown-it/markdown-it/issues/107) about alt text and modified a [JSFiddle](https://jsfiddle.net/makb/bqydc9v6/10/) provided there. Can you suggest how we can use this code to fix this issue?

**Comment by roman-r-m** [comment] 2022-01-13 14:24
I'm pretty sure Joplin overrides the default rule for images (somewhere here https://github.com/laurent22/joplin/tree/dev/packages/renderer/MdToHtml/rules) and this is where you should be looking.

**Comment by mak2002** [comment] 2022-01-14 16:33
Hey @roman-r-m I was thinking maybe this issue is caused by putting this `(:/06f049df282b4780bbfbdc306383bab5)` into the editor because when I tried by putting actual address like this:  `![alt-text](/path/to/file/image.png)` and it works this way. So maybe we can put the actual address of file in editor instead of `(:/06f049df282b4780bbfbdc306383bab5)` while importing.

**Comment by roman-r-m** [comment] 2022-01-14 17:03
> Hey @roman-r-m I was thinking maybe this issue is caused by putting this `(:/06f049df282b4780bbfbdc306383bab5)` into the editor because when I tried by putting actual address like this: `![alt-text](/path/to/file/image.png)` it works this way. So maybe we can put the actual address of file in editor instead of `(:/06f049df282b4780bbfbdc306383bab5)` while importing the image.

We can not put the actual path - there's a reason Joplin uses resource IDs there.

Namely - if you sync such note to another OS, the path will most likely be incorrect, e.g. on Linux it's `~/.config/joplin-desktop` and on Windows - `%USERPROFILE%\.config\joplin-desktop`

**Comment by mak2002** [comment] 2022-01-14 17:44
ohhk got it. Thanks for clarification @roman-r-m

**Comment by mak2002** [comment] 2022-01-15 15:19
hey @roman-r-m I think I have fixed this issue by getting alt text like: `const alt = token.content;` and inserting it in img html: `return <img data-from-md ${htmlUtils.attributesHtml(Object.assign({}, r, { title: title, alt: alt}))}${js}/>`;. So should I open a pull request or you want to suggest something?

**Comment by roman-r-m** [comment] 2022-01-15 16:07
Did you test it?

**Comment by mak2002** [comment] 2022-01-15 16:30
Yes @roman-r-m I tested.

**Comment by roman-r-m** [comment] 2022-01-15 16:52
Well it'd be good to see some results.

You'll need to include them in the PR anyway (I assume you have read the contributor's guide)

**Comment by mak2002** [comment] 2022-01-15 17:00
Yes I have read contributor's guide and soon will make a PR including the results.

**Closed** 2022-01-18 11:11 UTC
Labels: bug
