### ISSUE TITLE
[iOS] App must be restarted after each note edit

### ISSUE THREAD

**Issue by jwinebarger** [laurent22/joplin#6682] opened 2022-07-21 06:26 UTC
## Environment

Joplin version: 12.8.1
Platform: iOS, iPhone 11 Pro
OS specifics: Version 15.5

## Steps to reproduce

1. Close and reopen Joplin
2. Open a note 
3. Tap on the pen and paper button in the lower right-hand corner to start editing the note
4. Make any edit, however trivial
5. Tap on the “back” arrow at the upper leftmost edge of the screen to exit the editing of the note

## Describe what you expected to happen
Expectation is: 
- to return to the list of notes
- to be able to access the menu on the left hand side of the screen (the button composed of three horizontal strips)

## Description of the actual result (contrary to expectations):
- all control interfaces are squeezed to a thin line at the top of the screen
- no scrolling through the list of notes is possible
- there is no menu button on the left side of the screen (or anywhere on the screen)
- some buttons such as the button to add a new note may be visible. If that button is tapped on, the buttons that rise up from it go up off the screen, one of them being placed underneath the icon for Wi-Fi and battery
- App usability is re-established only after closing and re-opening the app

## Problem-solving steps tried:
- deleting and reinstalling the app
- deleting all notes and app data and reinstalling the app
- repeating the process with the accessibility option “reduced motion” both on and off

Images below show the state of the app after the bug has occurred:
![494F3F4F-54A1-45C1-BD25-59FB643694E4](https://user-images.githubusercontent.com/28265892/180144051-336fb54c-4660-435c-a0b7-15c14666bd67.jpeg)
![AC3006E5-1ECC-400C-AB84-2692757CC9CB](https://user-images.githubusercontent.com/28265892/180144059-0a5605c6-4c26-4dbc-93bc-a6a1d65f56f5.jpeg)

## Logfile

I cannot attach a debug log because:
1.1 debug logs are (apparently) wiped after each app restart
1.2 after the bug happens, I cannot access the menu on the left hand side of the screen, and therefore cannot enter the app configuration, and therefore cannot access the bug report
2. a search for the Joplin app in iOS Settings > Privacy > Analytics & Improvements > Analytics yields no results

**Comment by personalizedrefrigerator** [comment] 2022-07-24 08:48
It's working for me (iOS 15.6, iPhone SE). What happens if you enable the beta editor? Does uninstalling/reinstalling fix the issue?

Recording of me trying to reproduce the issue:

https://user-images.githubusercontent.com/46334387/180639821-3f60da5a-020e-495a-a751-245947fb20f0.mov

**Comment by jwinebarger** [comment] 2022-07-24 11:05
I've previously uninstalled and reinstalled twice. It does not fix the issue.
I just opted in to the beta editor. Nothing changed.

**Comment by RedBearAK** [comment] 2022-07-28 09:00
I saw something similar with Joplin on an iPad Pro running iOS 14. Totally screwed up UI. Had to reinstall the app to get it back to normal. This happened while I was just initially testing the app, and I haven't really used it since then. 

I can reproduce by just making a new note and then trying to go "back" out of the note. No apparent way to get back to the note list or the menu without at least quitting and restarting the app.

**Comment by personalizedrefrigerator** [comment] 2022-07-28 12:56
I tested this on the iOS 15.5 simulator (iPhone 11 Pro) and still can't reproduce the issue. As such, the issue doesn't seem to be device-specific. It might be related to a device setting, though...

Are you using a bluetooth keyboard or a custom keyboard (e.g. [GBoard](https://apps.apple.com/us/app/gboard-the-google-keyboard/id1091700242))? If you hide the keyboard before clicking "back" does this still happen?

**Comment by RedBearAK** [comment] 2022-07-29 00:21
@personalizedrefrigerator 

Normal keyboard. No hiding. Just made a new note, entered a word and hit the back arrow. On iPad Pro (2017, 12.9).

**Comment by pascalsiemsen** [comment] 2022-08-05 19:13
Same problem here.

iPhone 13 Mini
iOS 15.6

**Comment by pascalsiemsen** [comment] 2022-08-05 21:17
Fixed it. 

As found  [here](https://github.com/laurent22/joplin/issues/4980) I had to deselect „prefer cross-fade transitions“ (which is the default).

**Comment by RedBearAK** [comment] 2022-08-06 00:06
> Fixed it.
> 
> As found [here](https://github.com/laurent22/joplin/issues/4980) I had to deselect „prefer cross-fade transitions“ (which is the default).

@pascalsiemsen @laurent22 

This had no effect for me. As related by multiple users in that thread, this worked for some people but not for others. 

Some people in that thread mentioned the floating keyboard. I can confirm that I have two devices (iPhone and iPad Pro) where "Prefer Cross-Fade Transitions" was disabled (even though I've never heard of that setting before). On the iPad that has the UI issue, it seems to only occur when using the **_floating keyboard_** and the UI resets itself (without restarting the app!) if you un-pinch on the floating keyboard to expand the it back to the docked/large state. The issue also doesn't seem to immediately come back if you re-float the keyboard with a pinch. But it will if you make a new note, edit the title and then hit the back arrow. 

The process of hitting the "Back" arrow to leave a new note seems to be different depending on whether you're using the floating keyboard or the docked keyboard. With the floating keyboard, if you hit the arrow it immediately leaves the note (or tries to leave the note) and triggers the UI issue. With the docked large keyboard mode, if you hit the arrow it first just hides the keyboard, but leaves the note displayed, and **DOES NOT** trigger the UI issue. Then you have to hit the arrow again in order to actually leave the note. 

So I am one of the users whose Accessibility settings does not seem to have any effect on the UI issue. Maybe it's different between iOS devices (phones) and iPadOS devices (tablets) at this point. But it definitely has something to do with using the floating keyboard mode, for me. 

I would look into maybe just hiding the floating keyboard when you hit the back arrow, as happens with the docked keyboard. I'm not an iOS developer, so I don't know if this is an option with whatever framework the Joplin app is based on (React?) or things just work this way automatically in iOS in general.

**Comment by personalizedrefrigerator** [comment] 2022-08-06 01:45
> As found [here](https://github.com/laurent22/joplin/issues/4980) I had to deselect „prefer cross-fade transitions“ (which is the default).

Link to upstream bug: https://github.com/facebook/react-native/issues/29974
I'm not sure whether the floating keyboard issue has the same cause...

[Comment](https://github.com/facebook/react-native/issues/29974#issuecomment-925444658) in the upstream issue suggests patching React Native until the issue is fixed upstream...

**Comment by personalizedrefrigerator** [comment] 2022-09-03 11:51
A fix for https://github.com/facebook/react-native/issues/29974 seems to have been merged! See https://github.com/facebook/react-native/commit/4b9382c250261aab89b271618f8b68083ba01785 . It was just merged 3 days ago, so we may have to wait a month for it to make it into `react-native`.

**Comment by personalizedrefrigerator** [comment] 2022-10-03 18:18
Still an issue — may be fixed by upgrading to `react-native 0.70.1`.

**Comment by personalizedrefrigerator** [comment] 2022-11-13 18:24
We might be able to fix this by patching react native. See https://github.com/facebook/react-native/issues/29974#issuecomment-925444658

**Comment by J-Maertens** [comment] 2022-12-18 11:57
I have the same problem. 
iPhone 12 mini
iOS 16.1.1

**Closed as completed** 2023-01-11 17:17 UTC
Labels: bug, iOS, medium
