### ISSUE TITLE
macos cmd+m shortcut doesn't work in desktop app

### ISSUE THREAD

**Issue by arekm** [laurent22/joplin#9488] opened 2023-12-10 22:44 UTC
### Operating system

macOS

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, darwin)

Client ID: 2d7ab95cbeb4489db005cb8d545a7077

### Current behaviour

1. Open joplin on macos
2. Press cmd+m

### Expected behaviour

Joplin should minimise to macos dock. That's standard macos shortcut and described here: https://support.apple.com/en-us/HT201236 ).

**Comment by dimitristsilis** [comment] 2023-12-11 16:03
Is this really a bug or just a not implemented feature? I see that there is no "Minimize Window" shortcut available in the "Keyboard shortcuts" preferences window, although there is one for "Hide Joplin" and "Close Window". If this is the case, a simple line of code can fix this by adding the shortcut in the list.

**Comment by arekm** [comment] 2023-12-11 16:22
It's operating system / macos shortcut, so I assume Joplin is disabling / overriding all system shortcuts and insisting on its internal shortcuts *only* ?

btw. That hiding behaves differently than other macos apps on opt+m (opt+m causes window "shrinking and moving to dock" animation while "hide joplin" just hides window immediately) but for me any version is fine. Changed locally "hide joplin" to activate on opt+m as a workaround.

**Comment by dimitristsilis** [comment] 2023-12-11 17:51
That's why I think it should be a feature request.

**Comment by dimitristsilis** [comment] 2023-12-11 17:58
> It's operating system / macos shortcut, so I assume Joplin is disabling / overriding all system shortcuts and insisting on its internal shortcuts _only_ ?

That's why I think it should be a feature request. If you read the file [KeymapService.ts](https://github.com/laurent22/joplin/blob/de67ec46846b608584ce2402da9c4307e60dfdda/packages/lib/services/KeymapService.ts#L4), you'll see that "CloseWindow", "hideApp" and "quit" are defined commands with accelerators. I assume that indeed Joplin ignores local shortcuts by design.

**Comment by arekm** [comment] 2023-12-11 18:03
I consider disabling global shortcuts to be a buggy behaviour since it causes one app to behave differently on OS causing bad user experience but I won't insist (since there could be reasons for it that I'm not aware).

**Comment by tessus** [comment] 2023-12-14 11:46
I remember that there was a reason why we didn't use the `Cmd+M` key binding.

I believe it was because `Cmd+H` and `Cmd+W` were already working and minimizing the app or hiding/closing the app is the same on macOS, except the former puts the app in the right side of the Dock.
However, one can click the menu item or on the icon in the Dock (if Joplin was added to the Dock permanently) to un-hide it again.

Joplin has a lot of functionality and plugins. Thus using `Cmd+M` for something else or leaving it available makes IMO more sense.

**Comment by pedr** [comment] 2024-01-29 21:16
@laurent22 I don't have access to MacOs, maybe would be better to assign this issue to another person?

**Closed as completed** 2024-02-06 16:19 UTC
Labels: bug, desktop, macOS, high
