### ISSUE TITLE
Automatically switch theme to match system theme setting doesn't work on Linux

### ISSUE THREAD

**Issue by MarkWieczorek** [laurent22/joplin#9152] opened 2023-10-27 21:12 UTC
"Automatically switch theme to match system theme" setting doesn't work on Linux (flatpak version).  Changing the system theme does change the color of the menu bar, but that is it, the remainder of the window remains in the "light" mode. I note that the dark theme does indeed work if you manually choose it.

## Environment

Joplin version: 2.12.19
Platform: Linux (fedora)
OS specifics: flatpak version

## Steps to reproduce

1. enable "Automatically switch theme to match system theme"
2. change system theme

# Note
This has been reported previously, but the issue was marked as stale and was closed.
* https://github.com/laurent22/joplin/issues/6921
* https://github.com/laurent22/joplin/issues/3788

**Comment by personalizedrefrigerator** [comment] 2023-10-28 00:17
It works for me in Ubuntu 23.10 (GNOME desktop with Ubuntu modifications). I've tested with
- the (unofficial) snap distribution (2.12.19)
- the official AppImage distribution (2.12.19 and 2.13.3)

It may be be it doesn't work in a specific desktop, or that it's an issue with the Flatpak distribution.

Note that bugs specific to the Flatpak distribution can be [reported to its GitHub repository](https://github.com/flathub/net.cozic.joplin_desktop/issues).

**Comment by danilown** [comment] 2023-11-03 23:59
You mentioned the issue that you tested the Appimage and the Snap versions on Ubuntu and it worked. Have you tested the flatpak version on Ubuntu as well? If not, could you test it and inform us of the results?

I think the problem is that changing to Dark Style in GNOME only changes the Adwaita theme. You probably need to install [adw-gtk3](https://github.com/lassekongo83/adw-gtk3). At least the flatpak themes.

After installing, try to change to Dark Style. It should work.

If it does not work, try running this command:

```
gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
```

**Comment by personalizedrefrigerator** [comment] 2023-11-07 22:41
I'm closing this because https://github.com/flathub/net.cozic.joplin_desktop/issues/144 has been closed.

If this is still an issue, please let me know and I can re-open it.

**Closed as completed by personalizedrefrigerator** 2023-11-07 22:41 UTC
Labels: bug
