### ISSUE TITLE
Mac App Renders formula source code

### ISSUE THREAD

**Issue by mikea** [laurent22/joplin#2811] opened 2020-03-19 19:54 UTC
Joplin app renders a portion of formula source code before the correct rendering:

<img width="1174" alt="Screen Shot 2020-03-19 at 12 53 18 PM" src="https://user-images.githubusercontent.com/3236/77109136-a4ff3180-69e0-11ea-956e-3903f467d1e2.png">

## Environment

Joplin version: Joplin 1.0.194 (prod, darwin)
Platform: Mac OS 10.15.3 (19D76)

**Comment by tessus** [comment] 2020-03-20 07:47
I can confirm this. It only happens for inline Katex:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/223439/77144921-7ffcd400-6a5d-11ea-82a8-5ad1580d4b85.png">

**Comment by anjulalk** [comment] 2020-03-22 03:51
On file `ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js` Line 246:
```
return `<span class="joplin-editable"><pre class="joplin-source" data-joplin-source-open="$" data-joplin-source-close="$">${latex}</pre>${renderToStringWithCache(latex, options)}</span>`;
```

`<pre class="joplin-source" data-joplin-source-open="$" data-joplin-source-close="$">${latex}</pre>` renders the source and then `${renderToStringWithCache(latex, options)}` renders the formula. Almost looks like it was intentional. Removing the first part fixes the issue. Any idea why it was there?

**Comment by tessus** [comment] 2020-03-22 03:55
Maybe it was debugging code that was not removed. Or maybe it has something to do with the new WYSIWYG editor. Laurent would know for sure.

**Comment by sealch** [comment] 2020-03-22 12:50
> On file `ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js` Line 246:
> 
> ```
> return `<span class="joplin-editable"><pre class="joplin-source" data-joplin-source-open="$" data-joplin-source-close="$">${latex}</pre>${renderToStringWithCache(latex, options)}</span>`;
> ```
> 
> `<pre class="joplin-source" data-joplin-source-open="$" data-joplin-source-close="$">${latex}</pre>` renders the source and then `${renderToStringWithCache(latex, options)}` renders the formula. Almost looks like it was intentional. Removing the first part fixes the issue. Any idea why it was there?

I can confirm this on Electron client as well.

**Comment by cow8** [comment] 2020-03-23 16:23
Confirm this.
Joplin 1.0.195 (prod, darwin)

**Comment by laurent22** [comment] 2020-03-24 09:39
That should be fixed on master.

**Comment by mikea** [comment] 2020-03-25 14:54
@laurent22 can confirm fixed on master. Any chance to get another release cut with this? The bug made it to my iPhone :(

**Comment by roachsinai** [comment] 2020-03-28 01:51
Same issue, thanks for fix and waiting for the next release!

**Comment by laurent22** [comment] 2020-04-08 00:27
Should be fixed from next version

**Closed by laurent22** 2020-04-08 00:27 UTC
Labels: bug, desktop, high, renderer
