### ISSUE TITLE
Syntax Code Block Highlight has stopped working

### ISSUE THREAD

**Issue by symisz** [laurent22/joplin#5365] opened 2021-08-21 18:48 UTC
PowerShell syntax code highlighting stopped working in the markdown pane, since the recent update.

![image](https://user-images.githubusercontent.com/32195791/130332006-82ff4a07-1b70-4007-b620-46c1882ec29e.png)

>Joplin 2.3.5 (prod, win32)
>
>Client ID: dae2dbe2e4bf47c09ce30e01887dd788
>Sync Version: 3
>Profile Version: 39
>Keychain Supported: Yes
>
>Revision: 819af3c

**Comment by laurent22** [comment] 2021-08-21 19:51
We've upgraded highlight.js so maybe they've renamed it to something else? Have you tried with "powershell"?

**Comment by symisz** [comment] 2021-08-21 20:16
I've tried that as well. Previously it worked with both with "powershell" or "ps".

**Comment by roman-r-m** [comment] 2021-08-21 21:31
Does CodeMirror also use hightlight.js? Because if I understand the issue correctly, the problem is with the editor and not the renderer.

**Comment by symisz** [comment] 2021-08-21 21:47
> Does CodeMirror also use hightlight.js? Because if I understand the issue correctly, the problem is with the editor and not the renderer.
> 
> EDIT
> Isn't it just a consequence of the editor style change? It's not like it's only Powershell that isn't highlighted. E.g. for me this isn't highlighted
> 
> ```
> ```javascript
> console.log("Hello world")
> ```
> ```

Strange, both "javascript" and "js" works for me just fine in both panes.

**Comment by roman-r-m** [comment] 2021-08-21 21:49
I may have had a dev build running when I checked.

**Comment by laurent22** [comment] 2021-08-21 22:22
It works for me on 2.4. I think Caleb fixed the issue in his recent code block update.

**Comment by CalebJohn** [comment] 2021-08-22 21:55
Powershell was never highlighted in the markdown pane. Joplin only supports a handful of markdown syntax highlighters in order to prevent loading times from getting bogged down. 
You can see the supported list [here](https://github.com/laurent22/joplin/blob/dev/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx#L38). Powershell has never been on this list. 

It's possible to create a plugin that enables powershell, maybe you had a custom plugin installed?

**Comment by symisz** [comment] 2021-08-23 09:26
PowerShell is highlighted in the readers pane however without plugins, by writing backticks with ps or powershell.  But the highlighting has some inconsistency here and there, probably caused by using a substitute language to highlight. But I take that over, no highlighting at all.

How can I contribute to create such a plugin? I've currently no knowledge creating plugins, but I'll check out the guide.

**Comment by laurent22** [comment] 2021-08-23 10:46
Closing for now, as this is not a bug.

**Closed by laurent22** 2021-08-23 10:46 UTC
Labels: bug, desktop, high

**Comment by CalebJohn** [comment] 2021-08-23 15:36
@symisz you'll need to create a CodeMirror content script. Inside the content script you will have to add the PowerShell mode into the CodeMirror resources option.
Basically, in the content script you'll have the line.
`codeMirrorResources: ['mode/powershell/powershell']`

You can find a demo plugin in the documentation.
