### ISSUE TITLE
Application layout resets unexpectedly every time Joplin is restarted.

### ISSUE THREAD

**Issue by Sinacs** [laurent22/joplin#8282] opened 2023-06-06 12:56 UTC
## Environment

Joplin version: v2.11.8
Platform: Win11 pro
OS specifics: 22621.1778

## Steps to reproduce

1. I've installed 2 plugins `Note Tab` and `Favorites`
2. Use `View` > `Change application layout` to set both positions. (see picture)

![Screenshot 2023-06-06 204006](https://github.com/laurent22/joplin/assets/110529913/68012d9a-9805-49e3-a2a5-eccb54392159)

3. Quit & restart Joplin.
4. And then the positions were reset. (see picture)

![Screenshot 2023-06-06 203927](https://github.com/laurent22/joplin/assets/110529913/b58473cb-077a-4a0b-9079-d72e7af8b78f)

## Describe what you expected to happen

The application layout should not be reset when restart Joplin.

**Comment by stevemagruder** [comment] 2023-06-06 13:47
I experienced the same problem last night and had to roll back to 2.11.6 because of it. I also noticed extraneous panels in the "Change application layout", one that said "Loading...".

**Comment by Sinacs** [comment] 2023-06-06 17:20
This issue seems to be fixed in the v2.11.9 released but without mention.

**Comment by stevemagruder** [comment] 2023-06-06 17:48
Thanks Sinacs. I can confirm v2.11.9 has fixed this issue on the two installations I have.

**Comment by laurent22** [comment] 2023-06-08 15:24
Yes it was indeed fixed in 2.11.9, thanks for confirming

**Closed as completed by laurent22** 2023-06-08 15:24 UTC
Labels: bug, desktop, high
