### ISSUE TITLE
website has outdated version listed

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#1808] opened 2019-08-15 23:15 UTC
Currently (as of now), the website https://joplinapp.org lists outdated application versions:

https://joplinapp.org/#desktop-applications

![joplin website outdated version bug](https://user-images.githubusercontent.com/802786/63132952-d827a100-bf77-11e9-86c1-dbac82bfdcd3.png)

maybe there is a way to use the github api to get the latest release so it doesn't have to be manually updated with every release?

**Comment by tessus** [comment] 2019-08-17 00:01
> Currently (as of now), the website https://joplinapp.org lists outdated application versions

fixed it.

> maybe there is a way to use the github api to get the latest release so it doesn't have to be manually updated with every release?

Yes there is. But I'm not sure, if @laurent22 wants to change his current workflow. The web site is created from the README.md, so first a script updates the README.md and then another script changes the html.
The problem is that we can't use the github api for the README.md.

I could change the html so that the github api is used to display the latest release, but the README.md still has to be updated with a script. Therefore I'm not sure, if that makes any sense.

**Comment by tessus** [comment] 2019-09-28 01:12
It doesn't seem that Laurent wants to change the workflow. I'm closing this for now.

**Closed by tessus** 2019-09-28 01:12 UTC
Labels: documentation

**Comment by laurent22** [comment] 2019-09-28 08:37
I would prefer if it was all automated of course, but it's not easy to do as far as I remember.
