### ISSUE TITLE
Dark mode/oled mode issue

### ISSUE THREAD

**Issue by jacobgonzales20** [laurent22/joplin#3353] opened 2020-06-10 07:30 UTC
On the iOS app of Joplin the dark mode and oled mode have issues and show a black/white background on the top of the bar 
![3C8E6A1F-91B6-4EB2-99FD-D43CCA22B1AC](https://user-images.githubusercontent.com/63844598/84239455-5d54e700-aab1-11ea-87f1-114cace57d5c.jpeg)

When you select a note the colors shift 
![5FDC47F1-E01D-446A-9679-1FDB397B5982](https://user-images.githubusercontent.com/63844598/84239492-6c3b9980-aab1-11ea-8d9a-9b3cda74d723.jpeg)

Version: 10.0.47
iOS: 13.4.1

**Comment by CalebJohn** [comment] 2020-06-12 05:45
For reference, this was also reported on the forums.
https://discourse.joplinapp.org/t/light-stripe-in-oled-dark-mode-on-ios/7813
https://discourse.joplinapp.org/t/10-0-46-bug-dark-themes-on-iphone-xs-13-4/7653

**Comment by amandamcg** [comment] 2020-06-12 21:34
Looks like this was fixed here: https://github.com/laurent22/joplin/pull/3055 I also still see it, but I can't tell if it's a regression or if that version of the app hasn't been released.

**Comment by CalebJohn** [comment] 2020-06-12 21:40
> Looks like this was fixed here: #3055 I also still see it, but I can't tell if it's a regression or if that version of the app hasn't been released.
Looks like the latest ios release (10.0.47) was 4 days before the fix was merged in. This should be fixed in the next release.

**Closed** 2020-06-13 16:18 UTC
Labels: bug, high, mobile
