### ISSUE TITLE
Notebooks titles glitching

### ISSUE THREAD

**Issue by semdner** [laurent22/joplin#7614] opened 2023-01-12 11:40 UTC
The text of some notebooks seems to be rendered twice with an offset. This causes the text to appear corrupted in some way. When you move the cursor over the notebook, the duplicate title appears and disappears randomly. When you select the notebook, the duplicate title disappears, and when you deselect it, the bug occurs again. If you move a sub-notebook to another notebook, the bug disappears.

[Screencast from 2023-01-12 12-08-44.webm](https://user-images.githubusercontent.com/56640416/212054846-8db2fe58-5a10-4c75-aa99-16d4b64a481d.webm)

## Environment

Joplin version: 2.9.17
Platform: Linux
OS specifics: Fedora 37 (GNOME using Wayland)

## Steps to reproduce

No relation to any steps taken found.

## Describe what you expected to happen

The title should only appear once.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/10401192/log.txt)

**Comment by laurent22** [comment] 2023-01-12 12:49
Duplicate of #7506

**Closed as completed by laurent22** 2023-01-12 12:49 UTC
Labels: bug
