### ISSUE TITLE
Desktop: Command toolbar should be disabled when the editor is not focused

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#4807] opened 2021-04-03 12:52 UTC
* Click into the note header or even the search bar
* Click one of the buttons on the toolbar like bold or checkbox, etc; or press Ctrl-Shift-P and select equivalent action from there
* The formatting applied to the editor even though it not focused

**Comment by coderrsid** [comment] 2021-04-05 10:51
This is for TinyMCE right?

**Comment by roman-r-m** [comment] 2021-04-05 11:02
Nope. TinyMCE is fine actually. The commands aren't disabled but at least they don't do anything.

CodeMirror on the other hand...
![ezgif com-gif-maker(5)](https://user-images.githubusercontent.com/995612/113567521-ae1c6a00-9606-11eb-9aaf-e09fa25a5852.gif)

**Comment by axtyax** [comment] 2021-04-06 15:37
Is the expected behavior that simply nothing happens? Or that the formatting is applied at the cursor's position as soon as the editor is refocused?

**Comment by roman-r-m** [comment] 2021-04-06 20:33
I'd expect these menu items to not be available at all when the focus is not in the editor.

**Comment by coderrsid** [comment] 2021-04-07 07:31
So how should it be solved? 
1. Disabling command toolbar and Ctrl+Shift+P action, if the focus is not there.
2. Let the user use the action but not applying it in editor and showing alert that focus is not on editor and put the focus on editor as soon as alert is solved.

**Comment by roman-r-m** [comment] 2021-04-07 11:24
#1 is preferable in my view
@laurent22 what do you think?

**Comment by laurent22** [comment] 2021-04-07 17:52
I don't think we should disable the command palette if the editor is not in focus, because the palette contains all kind of commands, some of which are not related to the editor.

**Comment by laurent22** [comment] 2021-04-07 17:57
Also I'm not sure if it's an issue that the buttons work when the editor is not focused? If there's a selection and I click to "Bold", I want it to work even if the focus is not on the editor. Or is this behaviour causing a particular issue?

**Comment by roman-r-m** [comment] 2021-04-07 19:36
> I want it to work even if the focus is not on the editor. Or is this behaviour causing a particular issue?

No issues, I just found it nonintuitive that I have a cursor in a text field but the formatting is inserted in a completely different field.
If you feel this isn't a problem -- feel free to close, I'm not going to insists it's a bug.

**Comment by ksaiprajwal** [comment] 2021-04-08 07:20
Is the issue still open to work on ?

Because the commands do not work in TinyMCE when the editor is not focused, but the commands work in CodeMirror.

**Comment by laurent22** [comment] 2021-04-08 08:28
Ok let's close the issue then, because the alternative would be to have the toolbar being enabled/disabled whenever the editor focus changes and I think that would be distracting and not that useful.

**Closed by laurent22** 2021-04-08 08:28 UTC
Labels: bug, desktop
