### ISSUE TITLE
Inputting single, isolated diacritics cause de cursor to move to the start of the current note

### ISSUE THREAD

**Issue by fabiorzfreitas** [laurent22/joplin#6460] opened 2022-04-26 17:53 UTC
When inputting diacritics (symbols that can be used in conjunction with other letters, as in `à`, `õ` and `é`) separated from any letter (e. g. inputting ``` ` ```, `~` or `´`) the cursor will return to the start of the current notex unless it's inputted using `space`.

This is how the issue is reproducible:

In a new document,

`~[space]` > the symbol is inputted correctly and the cursor stays in place
`~[any other key]` > the symbol is inputted and the cursor moves to the start of the current note

## Environment

Joplin version: 2.7.15
Platform: Windows 10 21H2

## Logfile

Nothing on the log file, only save and sync messages

**Comment by Daeraxa** [comment] 2022-04-26 20:03
Is this a duplicate of https://github.com/laurent22/joplin/issues/6256?

**Comment by fabiorzfreitas** [comment] 2022-04-26 21:30
Yes, it's the same, except I'm experience it with other diacritics as well. I'm using a QWERTY keyboard configured to Portuguese ABNT2.

**Comment by Daeraxa** [comment] 2022-04-26 21:35
In which case could you just add those details to the issue linked above and I'll close this as a duplicate. Thanks.

**Closed as completed by Daeraxa** 2022-04-26 21:35 UTC
Labels: bug
