### ISSUE TITLE
[Feature Request] Go back to previous note, history, next note

### ISSUE THREAD

**Issue by Dasymi** [laurent22/joplin#1451] opened 2019-04-24 18:08 UTC
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

A menu option, ideally with a keyboard shortcut, to go back to the previous note would be really useful. Evernote has this with arrow icons for forward and back you can put on the toolbar, and holding one of them down displays note history so you can click on one to go to the required note.

**Comment by laurent22** [comment] 2019-04-29 13:03
That could be done with a plugin I guess.

**Comment by laurent22** [comment] 2019-09-04 12:00
Duplicate of #716

**Closed by laurent22** 2019-09-04 12:00 UTC
Labels: enhancement
