### ISSUE TITLE
Can't set editor to windows program when using the WSL

### ISSUE THREAD

**Issue by Nyhilo** [laurent22/joplin#2039] opened 2019-10-29 01:03 UTC
This is likely two separate errors. The first is Joplin encountering an error with file paths that have spaces in them. Consider the following:

```shell
:config editor "/mnt/c/Program Files/Sublime Text 3/subl.exe"
:config editor "/mnt/c/Program\ Files/Sublime\ Text\ 3/subl.exe"
:config editor "/mnt/c/Program\\ Files/Sublime\\ Text\\ 3/subl.exe"
:config editor "\"/mnt/c/Program Files/Sublime Text 3/subl.exe\""
:config editor "'/mnt/c/Program Files/Sublime Text 3/subl.exe'"
:config editor '"/mnt/c/Program Files/Sublime Text 3/subl.exe"'
```

All of these produce an error along the lines of 

```
edit: Error opening note in editor: spawnSync /mnt/c/Program\ ENOENT
```

I also tried adding the .exe to my PATH (potentially a different bug)

```shell
export PATH=$PATH:/mnt/c/Program\ Files/Sublime\ Text\ 3/
```

which allows `subl.exe` to be called from the cli, but still produces the following error for Joplin:

```shell
:config editor "subl.exe"
```

```
edit: Error opening note in editor: spawnSync subl.exe ENOENT
```

## Environment

Joplin version: 1.0.149 (CLI)
Platform: Windows 10 1903
OS specifcs: WSL Ubuntu 18.04

## Steps To Reproduce

1. Install Sublime Text 3 on Windows
2. Install the Ubuntu flavor of WSL
3. Install Joplin CLI in the WSL
4. Try to configure subl.exe as Joplin's note editor

**Comment by tessus** [comment] 2019-10-29 01:14
Can you please try with Joplin version 1.0.170

**Comment by Nyhilo** [comment] 2019-10-29 20:57
> Can you please try with Joplin version 1.0.170

Through node it looks like the most recent version is the 1.0.149 that I have

```shell
> npm install -g joplin@1.0.170
> NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin@1.0.170
```

both return 

```shell
npm ERR! code ETARGET
npm ERR! notarget No matching version found for joplin@1.0.170.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by tessus** [comment] 2019-10-29 22:45
Ah, ok. You did not mention that you installed the cli version of Joplin. It looked like as if you installed the Linux desktop version.

Unfortunately I can't reproduce any of this (because I don't have Windlows), so we'll have to wait for Laurent's input. Maybe there's some info about it on the forum. It could be that somebody else ran into a similar issue.

**Comment by Nyhilo** [comment] 2019-10-31 22:12
I created a support post [over on the forum](https://discourse.joplinapp.org/t/cant-set-editor-to-windows-program-when-using-the-wsl/4135) for this as well. If you guys feel that it is more of a normal support question than a bug report, feel free to close this issue.

Thanks for working on this! This app is essentially exactly the kind of thing I was looking for.

**Comment by tessus** [comment] 2019-10-31 23:24
We should leave it open for now. Laurent assigned it to himself, so I guess he will have a look at it. ;-)

Using the forum was just a suggestion, because more people are reading the forum than the github tracker. So I thought that somebody might have a similar setup like you and maybe even a solution. But since Laurent assigned it to himself, I think this might be a real bug after all.

**Comment by laurent22** [comment] 2019-11-01 22:44
It will be fixed in the next release and the correct syntax will be:

    :config editor '"/mnt/c/Program Files/Sublime Text 3/subl.exe"'

This is because the "editor" property is actually the executable path followed by optional arguments, so to make the difference between path and arguments, the path needs to be quoted.

Note that the editor will need to understand WSL paths, which Sublime does not, so you'll need some kind of wrapper to translate the paths.

**Closed** 2019-11-01 22:45 UTC
Labels: bug

**Comment by Nyhilo** [comment] 2019-11-04 17:18
Thanks Laurent,

Out of curiosity, I saw on the forums that you were a heavy WSL user. What is your go-to for development/text editing?

**Comment by laurent22** [comment] 2019-11-04 23:10
I'm using vscode now. I've got a simple wrapper that takes the wsl path and convert it to Windows style, to finally pass it to vscode. I use this utility to convert the path: https://github.com/laurent22/wslpath

**Comment by Nyhilo** [comment] 2019-11-07 19:14
You're a saint. Thank you!
