### ISSUE TITLE
I can’t copy/paste note ID

### ISSUE THREAD

**Issue by eromawyn** [laurent22/joplin#4658] opened 2021-03-11 18:56 UTC
I would like to be able to copy the ID, to copy it in my API scripts and help debugging, I don’t understand why it seems to disabled in properties window.

## Environment

Joplin version: Joplin 1.7.11
Platform: Windows
OS specifics: Installed via Chocolatey

## Steps to reproduce

1. Click on any note on the properties icon on top right to get this popup : 
![image](https://user-images.githubusercontent.com/17792937/110839531-519a8900-82ac-11eb-94b0-89d965036136.png)

2. Select the note ID
3. Right clic to copy the ID.... Paste is greyed. Ctrl-C does not work

## Describe what you expected to happen

I would like the note ID to be copied in the clipboard.

**Comment by CalebJohn** [comment] 2021-03-11 19:12
I just tested on my computer v1.7.11 Ubuntu 20.04 and indeed the context menu did not work. But copying with Ctrl-C works fine.

Odd that it doesn't work on windows.

**Comment by laurent22** [comment] 2021-03-11 19:28
Works in macOS too.

**Comment by eromawyn** [comment] 2021-03-12 09:25
I tried again this morning : ctrl-C is working, but the copy option on the right clic menu is still desactivated (grayed). I disabled the Note Tabs plug-in also, since it adds also adds an entry to this menu.

This menu also features a « paste » option. Really ? So I tried to clic on paste.... It pasted my clipboard content on the note. 

So, it’s the « paste » option which should not appear / be desactivated on right clic, but not the « copy » option. 

Also there is a « cut » option in the same menu (grayed). As you can’t edit this field, it should not appear too.

**Comment by Petemir** [comment] 2021-03-12 13:31
The problem appears to be that the right-click opens the context menu for the note panel, and not for the popup. If you select some text previous to opening the "Properties" you won't have "copy" greyed out.

**Comment by ron-debajyoti** [comment] 2021-03-26 15:23
This issue is still seen in joplin (dev) v1.8.0 in my Ubuntu 18.04 environment. I would like to work on the issue and try and find out the cause of this bug.

**Comment by HOLLYwyh** [comment] 2021-03-26 16:50
@eromawyn  
Hello, in my Joplin 1.7.11, windows10,when I select the ID ,I can use ctrl+C to copy and  paste the ID correctly. However I find that  after selecting the ID and right click,I can paste but I can't copy .When I choose paste , the ID I copied appears in my notes. I think that  the bug is: although we click the icon , a new windows appears and we try to copy the ID ,actually we are operating notes!!!!(We may not convert to the new window)So we can just choose paste and we paste the ID into the note.     

Additionally,I'm sorry that I haven't read the source code about this part yet. But I would like to work the issue , try  to find out the reason and solve the problem.

**Comment by ron-debajyoti** [comment] 2021-03-26 17:06
Hi @HOLLYwyh I am currently working on this issue. Please wait until I mention that I can't solve this issue or perhaps you could take a look at other open issues to solve.

**Comment by HOLLYwyh** [comment] 2021-03-26 17:17
@ron-debajyoti ok. please solve it first

**Comment by ron-debajyoti** [comment] 2021-03-26 21:33
Alright, I think I got the origin of the bug. 
I checked that the right-click function only works only in the `NoteEditor` region of the application( from `app-desktop/gui/MainScreen.tsx`) while the Properties dialog box is live. Since, the `NoteEditor` can be changed to any of the 3 modes, the context menu changes accordingly. For the `CodeMirror` mode, I traced the execution to [this](https://github.com/laurent22/joplin/blob/3fa13828cdd59c56aaacb15b4ef6bda442ac524a/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx#L648). Similarly, `TinyMCE` has it's own context menu and in its case we only see the **Paste** option.

I think we need to have a separate context menu for the Properties dialog box, i.e in `app-desktop/gui/NotePropertiesDialog.jsx` and ensure a way to allow the menu to work only in the region of the dialog box.

@CalebJohn @laurent22 would appreciate your inputs regarding this issue and maybe I can start working on a PR asap.

**Comment by lkiThakur** [comment] 2021-03-28 07:22
> ctrl-C is working, but the copy option on the right clic menu is still desactivated (grayed)

Actually joplin was showing you cut copy paste menu to perform the respective actions in the editor not on the properties popup that was opened.
It's a bug since joplin shows this menu based on coordinates of right click action. **the position where you right clicked was in front of the note editor while nothing was selected in the editor  that's why there was option to paste to editor but not copy or cut**
***
in this screenshot properties popup is not in front of editor so no such context menu is shown on right click !
![image](https://user-images.githubusercontent.com/63918341/112745226-5ce7f700-8fc4-11eb-9dc7-edc27838035a.png)

**Comment by xUser5000** [comment] 2021-03-28 10:57
I'm currently working on this issue and have submitted an initial pull request #4749

**Comment by ron-debajyoti** [comment] 2021-03-28 11:08
@xUser5000 I already mentioned above in the comments and added a post in the forum that I was working on this issue and was waiting for feedback after finding out the bug causing the issue. You could have at least waited a day or commented in the post iand then you could asked me if i was working or not. I was about to send PR. Can we follow FOSS best practices?

**Comment by xUser5000** [comment] 2021-03-28 11:33
@ron-debajyoti
I'm so so sorry for the inconvenience. This is the first time I noticed your comment. Please excuse me for my foolishness.
Can I at least have your permission to help solving the issue ? I would be very grateful.

**Comment by xUser5000** [comment] 2021-03-28 11:34
@ron-debajyoti 
Also can you please post a link to the discussion post in the forum ?

**Comment by ron-debajyoti** [comment] 2021-03-28 11:39
> Can I at least have your permission to help solving the issue ? I would be very grateful.

Hey @xUser5000 I noticed that your quick implementation is going to be different than mine. So, I don't know maybe one of the moderators can answer your question. @roman-r-m @CalebJohn @laurent22?

> Also can you please post a link to the discussion post in the forum?

Most of the discussion has been here. I made a [post](https://discourse.joplinapp.org/t/adding-context-menu-for-noteproperties-4658/16201) to initiate a discussion regarding this issue.

**Comment by xUser5000** [comment] 2021-03-28 11:44
@ron-debajyoti 
Thank you so much.
Again, I'm so sorry

**Comment by ron-debajyoti** [comment] 2021-03-28 12:27
> Again, I'm so sorry
No worries @xUser5000, I shall ask you to solve the issue in case I'm unable to. Please keep your PR live for other moderators to review.

**Comment by akshith271** [comment] 2021-03-29 16:17
@ron-debajyoti your analysis is correct, but adding a new context menu to NoteProperties only fixes the issue for that dialog. This issue is reproducible for other dialogs as well. Considering this I have created an initial PR for the issue #4763, which is different from @xUser5000's solution.

**Comment by ron-debajyoti** [comment] 2021-03-29 18:16
@akshith271 I understand, but I believe that the context menu functionality should be specific to its dialog. It's best to maintain the functionality of `CodeMirror.tsx` strictly related to CodeMirror and Editor.

**Comment by laurent22** [comment] 2021-03-29 20:26
Fixed in https://github.com/laurent22/joplin/pull/4768

**Closed by laurent22** 2021-03-29 20:26 UTC
Labels: bug, desktop, medium

**Comment by ron-debajyoti** [comment] 2021-03-29 20:45
@laurent22 I was working separately to add the functionalities of Cut, Copy and Paste ( and not just the copy functionality) exclusively for the `NoteProperties` depending on the field value, and also trying to add an overlay to prevent focus on the editor. Is it recommended to add the related PR?

**Comment by CalebJohn** [comment] 2021-03-29 23:02
@ron-debajyoti

If you can prevent the context menu from coming up on dialogs, that would be a good pull request. Copy for the other fields would also be useful.

**Comment by akshith271** [comment] 2021-04-01 17:01
> @ron-debajyoti
> 
> If you can prevent the context menu from coming up on dialogs, that would be a good pull request. Copy for the other fields would also be useful.

@CalebJohn I did the exact same thing in my PR #4768 , but was closed..😞

**Comment by CalebJohn** [comment] 2021-04-01 20:13
Hi @akshith271,

Your PR was closed based on [Rules 3, 5, and 6](https://joplinapp.org/gsoc2021/pull_request_guidelines/)
Rule 3: Your PR did as I stated, but the way it was implemented was not correct (as per Laurent's comment).
Rule 5: You didn't include test units
Rule 6: All PR's must be final quality and according to your comment, you felt that this was more of a draft.
