### ISSUE TITLE
Fatal Error on Launch After Fresh Install on Windows 11

### ISSUE THREAD

**Issue by tof0074** [laurent22/joplin#8819] opened 2023-09-10 20:25 UTC
After fresh install I get:
Fatal error:
Not enough memory resources are available to process this command

Uninstalled program and deleted config files in user profile. Restarted computer and redownloaded latest windows install file. Did this a few times over the last week or so and always the same result.

## Environment

Joplin version: Joplin-Setup-2.12.15.exe
Platform: Windows
OS specifics: Windows 11 Home
10.0.22621 Build 22621

## Steps to reproduce

1. Run EXE
2. Appears to install correctly
3. Run Joplin, then immediately get error. Application never shows
4. Uninstall, delete config files, restart computer
5. Try again, run EXE and same result as above

Cannot turn on debugging because app never launches. Attached is the log file.

[log.txt](https://github.com/laurent22/joplin/files/12570522/log.txt)

**Comment by laurent22** [comment] 2023-09-10 21:11
Could you provide a screenshot of the error?

**Comment by tof0074** [comment] 2023-09-10 21:25
![image](https://github.com/laurent22/joplin/assets/119343131/651c2212-34e2-4d33-b296-eb52c2ee71f0)

**Comment by personalizedrefrigerator** [comment] 2023-09-10 22:01
I think someone posted something similar in Discord: https://discord.com/channels/610762468960239627/610762468960239629/1131644883019518003

The user's [Windows Credential Manager was full and the solution was to delete entries](https://discord.com/channels/610762468960239627/610762468960239629/1132456460534677505).

**Comment by tof0074** [comment] 2023-09-10 22:16
@personalizedrefrigerator - Thanks for bringing this up. I do have a lot of Adobe and other programs listed in windows credentials, but it is not "full" I believe. I am constantly installing and testing or using programs and am only having problems with Joplin right now. I would also prefer not to mess with the credentials. I use Adobe cloud products and other products and don't want to mess anything up there. Any other ideas on how to fix?

**Comment by personalizedrefrigerator** [comment] 2023-09-10 22:28
[It looks like there's a similar issue when saving credentials with GitHub desktop](https://github.com/desktop/desktop/issues/15217) it's possible that some of the comments on that issue could be helpful here. From the comments, it looks like there should be a way to back up credentials before making any changes.

**Edit 1**: The last message in the log posted above is
```
2023-09-10 14:19:37: "KeychainService: checking if keychain supported"
```
so I think that these issues are the same.

**Edit 2**: Another option (assuming Joplin-related passwords are saved somewhere else!) could be to check whether the credential manager has Joplin-related passwords already stored and to remove only those. [Windows seems to have a limit of 20 credentials per app](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/troubleshoot/credential-limit) and it could be that Joplin has exceeded this. (If this is the case, please let us know!)

**Comment by tof0074** [comment] 2023-09-10 22:47
I removed one entry in credentials. That was not enough and had the same issue. I went ahead and removed 4 more "XblGrts" entries because I no longer have a xbox live subscription. However, I do use some purchased games. Hopefully this will not cause an issue. Joplin now opens up just fine.

**Comment by laurent22** [comment] 2023-09-11 08:43
@personalizedrefrigerator, do you think it's possible to catch this error and add additional information?

Also we should try to find an alternative to keytar if possible. I've created an issue about it here: https://github.com/laurent22/joplin/issues/8829

**Comment by laurent22** [comment] 2023-09-25 12:49
Duplicate of https://github.com/laurent22/joplin/issues/8829

**Closed as completed by laurent22** 2023-09-25 12:49 UTC
Labels: bug, desktop, windows, high
