### ISSUE TITLE
Feature request: inline preview

### ISSUE THREAD

**Issue by jeanm** [laurent22/joplin#80] opened 2017-12-07 15:56 UTC
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

---

An inline preview would be a really neat addition to Joplin, and would make the separate preview pane redundant. Here is a great example of how to implement this: https://github.com/brrd/Abricotine

**Comment by infinity85** [comment] 2017-12-17 12:12
Wow, this Abricotine is an awesome editor!

I really love joplin as an Evernote alternative, though I miss features like 

- html export
- interpretation of html code (to write e.g. coloured text). 
- Also the renderer doesn't show grey background for quotations and especially code paragraphs

So a hybrid of joplin with this Abricotine would fulfil kind of all wishes :D

These features are kind of part of every markdown editor out there. But I understand that joplin is very young and I really enjoy that it exists :-)


Please keep up this awesome work!!!

**Comment by laurent22** [comment] 2018-02-16 18:17
Duplicate of #176

**Closed by laurent22** 2018-02-16 18:17 UTC
Labels: enhancement
