### ISSUE TITLE
Feature request: Search within page

### ISSUE THREAD

**Issue by robert-franz** [laurent22/joplin#1016] opened 2018-11-27 12:54 UTC
There should be a way to search within a page.

Currently it's only possible to use the global search. But it should be possible to search within the current note/todo only.

### Operating system
- Windows
- macOS
- Linux
- Android
- iOS
### Application
- Desktop
- Mobile
- Terminal

**Comment by tessus** [comment] 2018-11-28 02:38
Duplicate of #382

It's one of the most requested features so far...

**Closed by tessus** 2018-11-28 02:38 UTC
