### ISSUE TITLE
Feature Request : Resources Manager

### ISSUE THREAD

**Issue by dbozec** [laurent22/joplin#1512] opened 2019-05-11 12:53 UTC
### Operating system

all

### Application

all

### Feature

When a resource is not used anymore by any note, there is no way to delete it. Adding a resources manager should help removing old resources that are not used and reduce disk usage.

**Comment by laurent22** [comment] 2019-05-11 12:55
Duplicate of #592

**Comment by laurent22** [comment] 2019-05-11 12:56
Note that unused resources are auto-deleted after a while, but currently there's indeed no way to view them all and manually delete them.

**Closed by laurent22** 2019-05-11 12:55 UTC

**Comment by dbozec** [comment] 2019-05-11 13:03
ok, I wasn't aware of the auto-deletion process
