### ISSUE TITLE
table of contents

### ISSUE THREAD

**Issue by peng19832** [laurent22/joplin#1340] opened 2019-03-14 10:41 UTC
Hi，how to automatically generate a table of contents？
I tried using [toc], but it didn't work.

### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

**Comment by subi54** [comment] 2019-03-14 12:59
Because it is not yet supported. markdown-it plugins can be integrated now. Perhaps make a toc plugin case for that, till then good old html ahref id manual toc creation.

**Comment by tessus** [comment] 2019-03-14 19:01
Duplicate of #478

**Closed by tessus** 2019-03-14 19:01 UTC
