### ISSUE TITLE
Import Markdown file including local images  failed!

### ISSUE THREAD

**Issue by Micalson** [laurent22/joplin#4040] opened 2020-11-04 02:02 UTC
Hello, thank you for the nice app. I find a bug while importing a md file whose insterted images are local, and the images cannot display after importing it. Maybe Joplin takes all images from md files as  web images, but most md files use local images. Thank you for the reply.

Regards,

**Comment by laurent22** [comment] 2020-11-06 22:04
Could you upload an example of MD file + image (in a ZIP file for example) so that we can try to replicate the issue?

**Comment by Micalson** [comment] 2020-11-07 13:30
Sorry, the problem had been solved after I update the Joplin. But another problem is that the image inserted by a third-party md  editor cannot be displayed. Maybe the image name dosen't meet the image naming rules in Joplin. The third-party editor I used is [Typora](https://typora.io/).

**Comment by autolyric** [comment] 2020-11-16 05:33
I meet the same problem when I inserted picture by a third-party md editor(Typora). And I know that Joplin rename the image name when inserted picture in the default editor even when drag the same picture another time.  For the reason of the Joplin's this behavior. Does it mean that It's not supported for inserting imagine in external editor?

**Comment by Micalson** [comment] 2020-11-16 05:55
According to my experience, the reason is that Joplin is not compatible with the name of the image inserted by the third party editor. So, the solution to this bug should be to rename the image name inserted by the third party editor.

**Comment by JackGruber** [comment] 2020-11-16 07:51
This has nothing to do with the name. 
All this examples will work. 
```
![image.png](:/978f01002bfa408fb70911c4eb02aba5)
![6562ba2b9c44800ca41a8a9bf23aa5f9.png](:/978f01002bfa408fb70911c4eb02aba5)
![](:/978f01002bfa408fb70911c4eb02aba5)
![fancy text](:/978f01002bfa408fb70911c4eb02aba5)
```
The problem in the external editors is that the the image is stored at the original storage location or in a folder of the external editor and not attached as resource to Joplin. Therefore the images cannot be synchronized and displayed on another device.

**Comment by autolyric** [comment] 2020-11-16 12:06
When I say the name, I mean the resouce file name. Not the display name in joplin. I have check the resouces file of joplin. All the resouces(original file) need name with the 32 ascii charater format. And I test by rename it by just change the last charactor. And the image can't be loaded. So I can confirm that the 32 ascii charater need fullfilled some rules(checksum or other check rule). All the examples your listed the display name just a string in joplin. The real source file is in resources of joplin.

I also config the external editor(Typora). Make the external editor copy the imagine to the joplin's resouces path after inserting the imagine. But because the joplin can't recognize the file with any other format name. So the picture can't display in the joplin's default editor.

**Comment by JackGruber** [comment] 2020-11-16 12:22
The files in the resource folder are not automatically synchronized if I am correct. Because the database entry for this is missing. 
Only storing a file in the resource folder is a file that joplin does not know about for sync/handling. 
You can add resources with the API.

**Comment by autolyric** [comment] 2020-11-16 12:28
![图片](https://user-images.githubusercontent.com/34681013/99251989-37462680-2849-11eb-93a4-80ce8166863d.png)
![图片](https://user-images.githubusercontent.com/34681013/99252334-c05d5d80-2849-11eb-896d-a6cd9f446735.png)

**Comment by autolyric** [comment] 2020-11-16 12:40
I don't know whether the rename picture mechanism related with the synchronous behavior. But every time I inserted a picture the renaming process worked. And the external editor can't act like joplin does. So I just wirte charactor note when I using joplin now. It's a pity for me

**Comment by Micalson** [comment] 2020-11-16 13:37
> When I say the name, I mean the resouce file name. Not the display name in joplin. I have check the resouces file of joplin. All the resouces(original file) need name with the 32 ascii charater format. And I test by rename it by just change the last charactor. And the image can't be loaded. So I can confirm that the 32 ascii charater need fullfilled some rules(checksum or other check rule). All the examples your listed the display name just a string in joplin. The real source file is in resources of joplin.
> 
> I also config the external editor(Typora). Make the external editor copy the imagine to the joplin's resouces path after inserting the imagine. But because the joplin can't recognize the file with any other format name. So the picture can't display in the joplin's default editor.
>   

I agree with u.

**Comment by Micalson** [comment] 2020-11-16 13:40
> ![图片](https://user-images.githubusercontent.com/34681013/99251989-37462680-2849-11eb-93a4-80ce8166863d.png)
> ![图片](https://user-images.githubusercontent.com/34681013/99252334-c05d5d80-2849-11eb-896d-a6cd9f446735.png)
> 

I had tried this way, and it could not work.

**Comment by autolyric** [comment] 2020-11-16 14:25
> I had tried this way, and it could not work.

Try to set the Typora to copy the imagine in the joplin's resources path can't solve the problem. Because the Typora don't know how to rename files like joplin's way. If typora can rename the imagine file name just following the joplin's rule/format. I think then joplin can display the picture normally. So Micalson can you propose this problem to  laurent22.

**Comment by JackGruber** [comment] 2020-11-16 16:57
Putting the file in the resourcefolder does not solve the problem, because this is not a resource for Joplin, because the database entry for this new resource with all meta information is missing! 

Therefore Joplin does not manage this resource and the following problems will occur: 
- Conflicted possible
- No Sync of the file
- No Export of the files possible from the Joplin menu
- ...

So I would say putting / editing files in the resource folder by hand and not with the API or Joplin is a bad idea!

**Comment by Micalson** [comment] 2020-11-16 23:20
> > I had tried this way, and it could not work.
> 
> Try to set the Typora to copy the imagine in the joplin's resources path can't solve the problem. Because the Typora don't know how to rename files like joplin's way. If typora can rename the imagine file name just following the joplin's rule/format. I think then joplin can display the picture normally. So Micalson can you propose this problem to laurent22.

@laurent22

**Comment by autolyric** [comment] 2020-11-17 01:03
@laurent22 
I can understand why joplin need rename the imagine file by it's own way. Make the imagine named by a unified format will be very  helpfull for manage/store/sync. 
But it actually made it impossible for inserted imagine in external editor which will limited the external editor's usage. After all make notes with picture is necessary for most people.

So, I suggest. maybe This problem  can be solved by adding  a step when convert from external editor to internal editor. 
 Just make a copy and rename it by joplin's way. 

And this copy and rename step exists already.  When I drag a picture which already named by joplin's format(32 characters) in resouces path. Joplin just made a copy and rename it with another name.  But this behavior is not what I want. although no matter with display result. But I think it made my note size bigger.

**Comment by Micalson** [comment] 2020-12-17 04:27
The problem has not been solved, and I think it should be taken seriously.

**Comment by laurent22** [comment] 2020-12-17 12:05
Closing as the bug description is insufficient to fix the bug, and whatever it was OP said it has been solved. For other issues, please open a separate bug.

**Closed by laurent22** 2020-12-17 12:05 UTC

**Comment by nxy1999** [comment] 2023-12-25 12:04
I have the same peoblem, how to solve it?
