### ISSUE TITLE
Some expression can't be distinguish

### ISSUE THREAD

**Issue by username0occupied** [laurent22/joplin#3520] opened 2020-07-18 01:28 UTC
Some expression can be shown correctly in typora,but can't shown in joplin.

![image](https://user-images.githubusercontent.com/36435293/87841506-5901c200-c8d8-11ea-80fa-28dab21436d6.png)
in this picture,you can see the expression 1 and 2 can be shown in typora,but can't show in joplin.And the 3th expression is shown both correctly.

version information:
Joplin 1.0.227 (prod, win32)

客户端 ID：af99bed220054991a0a631b38b12ea36
同步版本：1
最新版本：30
Keychain Supported: 是

调整： 4913fdb8 (master)
windows7 typora 0.9.92

**Comment by CalebJohn** [comment] 2020-07-18 05:29
Can you copy the contents of the note into your report? It will make reproducing the error much easier

**Comment by username0occupied** [comment] 2020-07-18 07:03
Such as：
sometimes the line feed is one of the reason.
$\left\{ {\begin{array}{*{20}{c}}
{z = f(x,y)}\\
{y = {y_0}}
\end{array}} \right.$
​
	$$\frac{\partial }{{\partial y}}\left( {\frac{{\partial z}}{{\partial x}}} \right) = \frac{{{\partial ^2}z}}{{\partial x\partial y}} = {f_{xy}}(x,y)$$

 	$$ \frac{\partial }{{\partial x}}\left( {\frac{{\partial z}}{{\partial y}}} \right) = \frac{{{\partial ^2}z}}{{\partial y\partial x}} = {f_{yx}}(x,y)$$

I thank you for considering my advertise,and sorry for i'm not thoughtful.

**Comment by username0occupied** [comment] 2020-07-18 07:06
Such as：
sometimes the line feed is one of the reason.

  ​	$$\frac{\partial }{{\partial y}}\left( {\frac{{\partial z}}{{\partial x}}} \right) = \frac{{{\partial ^2}z}}{{\partial x\partial y}} = {f_{xy}}(x,y)$$

 	$$ \frac{\partial }{{\partial x}}\left( {\frac{{\partial z}}{{\partial y}}} \right) = \frac{{{\partial ^2}z}}{{\partial y\partial x}} = {f_{yx}}(x,y)$$

$\left\{ {\begin{array}{*{20}{c}}
{z = f(x,y)}\\
{y = {y_0}}
\end{array}} \right.$

I thank you for considering my advise,and sorry for i'm not thoughtful.

**Comment by username0occupied** [comment] 2020-07-18 12:27
> 您可以将注释的内容复制到报告中吗？这将使重现错误变得更加容易

look the new remark

**Comment by CalebJohn** [comment] 2020-07-18 20:46
Looking closer at your screenshot it seems that you have made a mistake using the math formatting. If you want to use multiple lines you must use $$. Using a single $ is only for inline math. In the screenshot you also have a space before the $, which is not recognized as a math block, once this is removed the math should work.

I didn't get a chance to test on the computer yet, but the math you pasted (thank you) works on mobile.

**Comment by username0occupied** [comment] 2020-07-19 03:15
thanks

**Comment by username0occupied** [comment] 2020-07-19 03:24
If it is convenient to you,you can try this new expression.
$$J=\frac{{\partial(F,G)}}{{\partial(u,v)}}=\left|{\begin{array}{{20}{c}}{{F_u}}&{{F_v}}\\{{G_u}}&{{G_v}}\end{array}}\right|$$

**Comment by username0occupied** [comment] 2020-07-19 03:27
If it is convenient to you,you can try this new expression.
`$$J=\frac{{\partial(F,G)}}{{\partial(u,v)}}=\left|{\begin{array}{{20}{c}}{{F_u}}&{{F_v}}\\{{G_u}}&{{G_v}}\end{array}}\right|$$`

**Comment by CalebJohn** [comment] 2020-07-19 05:33
I've re-written you equations from above to use correct syntax (and be easier to read), Joplin uses [Katex](https://katex.org/docs/supported.html) for math rendering, typora uses MathJax, these aren't 100% compatible so please refer to [Katex](https://katex.org/docs/supported.html) for all your equations in the future. I'm going to close this issue since it's not actually a bug in Joplin.
```
$$
\left(
	\begin{array}{c}
		z = f(x,y) \\
		y = y_0
	\end{array}
\right)
$$

$$
J=\frac{{\partial(F,G)}}{{\partial(u,v)}}
=\left|
	\begin{array}{c}
		F_u & F_v \\
		G_u & G_v
	\end{array}
\right|
$$

```

**Closed by CalebJohn** 2020-07-19 05:33 UTC
