### ISSUE TITLE
Not showing Korean Language in Joplin

### ISSUE THREAD

**Issue by readingsnail** [laurent22/joplin#2229] opened 2019-12-27 13:40 UTC
So I finished korean language, something is not seen Joplin.

<img width="351" alt="스크린샷 2019-12-27 오후 10 31 39" src="https://user-images.githubusercontent.com/1904967/71518987-ccba8e00-28f8-11ea-8188-193746a77fa1.png">

<img width="225" alt="스크린샷 2019-12-27 오후 10 33 21 1" src="https://user-images.githubusercontent.com/1904967/71519015-ec51b680-28f8-11ea-933a-2f9e192c411c.png">
New Sub-notebook is not contain ko.pot file.

and config, it's some weird. Path: and Arguement is not contain ko.pot and it's weird line. and Also '한국말' is not... '한국어' is right thing. it's not contain ko.pot, and keyboard mode is not contained. '키보드 모드' is right

<img width="1140" alt="스크린샷 2019-12-27 오후 10 36 13" src="https://user-images.githubusercontent.com/1904967/71519131-6f730c80-28f9-11ea-8391-02cfe06f76f7.png">

## Environment

Joplin version: 1.0.175 (prod, darwin)
Platform: macOS
OS specifcs: 10.15.2

**Comment by tessus** [comment] 2019-12-29 07:53
duplicate of #2140

**Closed by tessus** 2019-12-29 07:53 UTC
Labels: bug
