### ISSUE TITLE
Please enable the Joplin Android app on Chromebooks

### ISSUE THREAD

**Issue by Keeblo** [laurent22/joplin#324] opened 2018-03-23 01:13 UTC
Please enable the Joplin Android app on Chromebooks. Does Chromebook compatibility require anything different than regular Android compatibility?

I have included two screenshots. One screenshot is from the Play Store on my Samsung Chromebook Plus, and the other is from the Play Store accessed through a browser.

![screenshot from the play store online](https://user-images.githubusercontent.com/7781968/37806287-32a2d3b4-2e0d-11e8-86bf-fe94f50e9f58.png)

![screenshot of joplin app from chromebook](https://user-images.githubusercontent.com/7781968/37806345-70269aa4-2e0d-11e8-8925-792900ef355e.png)

Thank you all for this amazing app!

**Comment by laurent22** [comment] 2018-03-23 20:35
Duplicate of #37

**Comment by laurent22** [comment] 2018-03-23 20:36
If you have any idea on how to get it working with a chromebook though please let me know

**Closed by laurent22** 2018-03-23 20:35 UTC

**Comment by nicxz** [comment] 2018-08-16 07:56
I would like to see Joplin working on my Chromebook as well. Let me know if I can help in any way.  

My initial guess would be that the permissions declared in the app manifest file (read_phone_state, camera) are not always available on chromebooks. See https://developer.android.com/topic/arc/manifest for more information. Ofcourse that would be the first step, I assume these permissions are expected in the application. So it will probably not be as simple as changing the app manifest file :)
