### ISSUE TITLE
Android 11 Fails to Access Filesystem: Operation not Permitted

### ISSUE THREAD

**Issue by Riolku** [laurent22/joplin#5810] opened 2021-12-01 04:46 UTC
Android 11 seems to have a similar issue to #4122, wherein the file permissions requested are for media type only. I cannot confirm that this issue was _caused_ by the upgrade to android 11, but I have observed it since the upgrade.

## Environment

Joplin version: 2.6.3
Platform: Android
OS specifics: 11

## Steps to reproduce

1. Install Joplin on Android 11
2. Attempt to sync with filesystem
3. Allow access to the filesystem as per the prompt.

## Describe what you expected to happen

Well, ideally it would sync with the filesystem. However, the log instead throws an error, presumably because JSON files are not multimedia files.

## Logfile
![tempFileForShare_20211130-233846](https://user-images.githubusercontent.com/41458184/144173206-bc339a07-33a2-4c9b-98b4-9187b084f094.jpg)
![tempFileForShare_20211130-234038](https://user-images.githubusercontent.com/41458184/144173209-0b346031-5209-43f7-9938-24d97772b2ce.jpg)
![tempFileForShare_20211130-234147](https://user-images.githubusercontent.com/41458184/144173215-c107e4a4-6409-4c32-b5fc-7f90e4a45642.jpg)
![tempFileForShare_20211130-234352](https://user-images.githubusercontent.com/41458184/144173376-bb209d51-10d6-4e21-9525-9fefebca9006.jpg)

This says:
"Authorization for Storage" "Access for this application: storage" "Authorize the app to access multimedia items only" "Refuse" "Show all applications who have this permission"

## Extra

I created a custom folder for the express purpose of testing this, and re-installed the app.

**Comment by Riolku** [comment] 2021-12-01 04:49
Per [the storage documentation](https://developer.android.com/about/versions/11/privacy/storage):

> Apps that run on Android 11 but target Android 10 (API level 29) can still request the requestLegacyExternalStorage attribute. This flag allows apps to temporarily opt out of the changes associated with scoped storage, such as granting access to different directories and different types of media files. **After you update your app to target Android 11, the system ignores the `requestLegacyExternalStorage` flag.**

Looks like some further reading is required to figure out how to fix this. Looks like the storage model has changed non-trivially.

**Comment by Riolku** [comment] 2021-12-01 04:54
[This link](https://developer.android.com/training/data-storage/manage-all-files) about managing all files is likely to be helpful. However, it may be the case that we should be using the newer APIs. The former is likely to be faster, but we should note that Google Play has policies in place for apps that request this global permission.

**Comment by Riolku** [comment] 2021-12-01 04:58
> **Use scoped storage unless your app needs access to a file that's stored outside of an app-specific directory and outside of a directory that the MediaStore APIs can access.** If you store app-specific files on external storage, you can make it easier to adopt scoped storage by placing these files in an app-specific directory on external storage. That way, your app maintains access to these files when scoped storage is enabled.

I think this will be my last comment for now. I am not well-equipped to investigate further, as I have no experience with Android development. However, unless the external storage they speak of can be accessed easily by multiple apps, I would not recommend it. I, as well as many others (from what I've heard), use SyncThing to backup my notes and sync them across devices. If this functionality was removed in some way, it would likely be a deal-breaker for many people

**Comment by laurent22** [comment] 2021-12-01 10:37
I think that's a duplicate of https://github.com/laurent22/joplin/issues/5779

**Closed by laurent22** 2021-12-01 10:37 UTC
Labels: bug

**Comment by SuperFes** [comment] 2022-01-20 19:43
Just FYI, I built my own debug APK with the additional permission MANAGE_EXTERNAL_STORAGE and I can now sync with the file-system in Android 11.
