### ISSUE TITLE
sync interval is ignored - syncs after every character

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#391] opened 2018-04-08 21:13 UTC
### Operating system

- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

### Problem

I'm using the latest clients across the board, e.g. Joplin 1.0.83 for macOS.

As soon as one single character is added to a note, the entire note is synced, even though the sync interval is set to 5 minutes. Disabling the sync interval does not fix this either.

I'm also using the nextcloud sync client and when I'm editing a note in Joplin, I have a lot of syncs within a minute.

**Comment by foxmask** [comment] 2018-04-09 06:15
This is how evernote works too, or at least, as soon as the network is available.

**Comment by foxmask** [comment] 2018-04-09 06:55
Evernote on desktop does not sync until you ask to, on the web page, it syncs each time you do nothing after ~5s on a note you modified, and on the mobile, each time you save a note, that pushes the local modification to the server but does not grab the notes from the server until the sync period or a sync user request.
Joplin syncs also when you saved on the mobile. I didnt notice any extra sync activity on the desktop version (linux), I am going to make a try.

**Comment by laurent22** [comment] 2018-04-09 08:08
Duplicate of #310

**Closed by laurent22** 2018-04-09 08:08 UTC

**Comment by tessus** [comment] 2018-04-09 20:53
@laurent22 I'm sorry, I've been enthusiastically opening tickets and missed to check for a similar issue beforehand.
However, #310 is marked as a question, but the fact that the interval is ignored and I have at least 10 syncs per minute when I edit a note, this is rather a bug. Wouldn't you agree?
