### ISSUE TITLE
Conflicts notebok does not show count

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#3997] opened 2020-10-29 12:12 UTC
I do not know if this is intentional or not, but when the "Conflicts" notebook is created, there are no counts, which makes it hard to easily see the situation and its evolution (e.g. if the count of conflicting notes is increasing during a sync), e.g.

![image](https://user-images.githubusercontent.com/1671065/97572071-525f0c80-19e8-11eb-8d8b-2fe16da56387.png)

It would be really useful to have the number of conflicting notes shown via a count of notes in this notebook, as others.

## Environment

Joplin version: 1.3.9
Platform: linux
OS specifics: ubuntu 20.04

**Comment by vaibhav135** [comment] 2020-11-04 14:09
Hiii @msbentley ,
 I think that the following has been already resolved in version 1.3.10 
![cannot_create_file_name_conflict](https://user-images.githubusercontent.com/39329182/98121472-55b93300-1ed5-11eb-8845-1031bc4a3eb8.png)

**Comment by msbentley** [comment] 2020-11-04 15:05
Thanks @vaibhav135 - but the issue was on whether or not the special "Conflicts" notebook shows the note counts, so that one can see how many conflicting notes there are...

I checked on 1.3.10 and the behaviour is still as reported in this ticket.

**Comment by vaibhav135** [comment] 2020-11-04 16:40
@msbentley what I am saying is that maybe you have created the notebook named conflict in previous versions. And in previous versions maybe they didn't restricted user from creating a notebook with the reserved keyword. Since that keyword is itself reserved hence resulting in not showing the count. In the above comment what I was saying was that you cannot create a notebook named conflict anymore (or so not atleast in the version 1.3.10 onwards). Since I am new here I don't know why the keyword is itself is reseved ..... but it is

**Comment by vaibhav135** [comment] 2020-11-04 16:46
@laurent22 how can I know which keywords are reserved

**Comment by msbentley** [comment] 2020-11-04 17:04
When you have a synchronisation conflict, a "special" notebook is created to hold the local notes which are conflicted, this is why it is reserved.

**Comment by vaibhav135** [comment] 2020-11-04 17:59
oh ok now I understand thanks. Sorry for barging in like that.

**Comment by vaibhav135** [comment] 2020-11-05 07:12
hiii, @msbentley how can I produce a sync conflict. I looked in the forums but could'nt reproduce those.

**Comment by msbentley** [comment] 2020-11-05 08:23
Hi @vaibhav135 did you read [this](https://joplinapp.org/conflict/)? To test yesterday I just modified one note on two machines between sync cycles.

**Comment by vaibhav135** [comment] 2020-11-05 16:20
Hii 
@msbentley I was successfully able to reproduce the Conflict but only in the prod version (app installed in linux pc and phone). Because in the dev version the synchronisation is resulting in creating a different folder named joplindev. Can you tell me how I can solve the issue
Thank you

**Comment by msbentley** [comment] 2020-11-05 16:46
Sorry, no idea - I'm using webdav for sync and have no experience of anything else, and am using two instances of the desktop app.

**Closed** 2020-11-14 13:15 UTC
Labels: bug, high
