### ISSUE TITLE
Broken link and underscore sign

### ISSUE THREAD

**Issue by cppcode1** [laurent22/joplin#9037] opened 2023-10-09 10:45 UTC
Hi, the app breaks the web site link adding backslash before '_' underscore sign in the visual mode editor.

scenario:
- just copy any link (must contain '_' sign) to the visual note editor from a web browser firefox
- press enter & reopen the note to make the link active
- open the link (ctrl +left mouse button)

example
![image](https://github.com/laurent22/joplin/assets/52190011/c252e1f6-2f3e-4d49-8507-0cfb1ecc4392)

Joplin 2.12.18 (prod, win32)
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes
Revision: a0a4a81

**Comment by laurent22** [comment] 2023-10-09 11:06
I think this is fixed in 2.13? Or if not there's an issue still open about this, and this is a duplicate

**Comment by cppcode1** [comment] 2023-10-09 12:15
good, I will update the app and let you know if it is fixed.

**Comment by cppcode1** [comment] 2023-11-02 13:02
hi, it is still not working. I wait for the new release to test it again.
![image](https://github.com/laurent22/joplin/assets/52190011/e973c42f-3f15-4eec-9b71-47d24de5652a)

**Joplin 2.12.19 (prod, win32)**
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes
Revision: 7081046

**Comment by laurent22** [comment] 2023-11-02 14:00
Duplicate of #9122

**Closed as completed by laurent22** 2023-11-02 14:00 UTC
Labels: bug
