### ISSUE TITLE
Numbered list in markdown editor is not working as expected

### ISSUE THREAD

**Issue by aashimawadhwa** [laurent22/joplin#4972] opened 2021-05-15 18:37 UTC
## Environment

Joplin version: 1.8.5
Platform: Linux
OS specifics: Ubuntu 21.04

## Steps to reproduce

1. write a few lines on the markdown editor.
2. select all the text , click on numbered list.
3. after multiple clicks the bug can be seen.

![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/73706697/118374549-58aa8400-b5da-11eb-9aac-c253e08f9b1c.gif)

## Describe what you expected to happen
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/73706697/118374383-6dd2e300-b5d9-11eb-962e-0dfb894a75ee.gif)

the numbered list should be enabled at first click and should be disabled at second click

**Comment by roman-r-m** [comment] 2021-05-15 20:10
Looks like a duplicate of https://github.com/laurent22/joplin/issues/4877

**Comment by aashimawadhwa** [comment] 2021-05-15 20:23
okay I will see to it

**Comment by laurent22** [comment] 2021-05-15 20:30
I think this PR should fix this: https://github.com/laurent22/joplin/pull/4914

**Comment by aashimawadhwa** [comment] 2021-05-15 20:56
still i am having this bug , it is not fixed?

**Comment by roman-r-m** [comment] 2021-05-15 21:19
The PR is still open, so no, it's not.

**Comment by aashimawadhwa** [comment] 2021-05-15 21:33
Ok got it.

**Comment by tessus** [comment] 2021-05-16 18:20
Duplicate of #4877

**Closed by tessus** 2021-05-16 18:20 UTC
Labels: bug
