### ISSUE TITLE
Desktop: Note list does not scale properly with window. 

### ISSUE THREAD

**Issue by decryptedchaos** [laurent22/joplin#10037] opened 2024-03-02 15:20 UTC
### Operating system

Windows

### Joplin version

2.14.17

### Desktop version info

Joplin 2.14.17 (prod, win32)

Client ID: 0a80033d17974af2a611ab52d4b3fc8e
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 094175c

ABC Sheet Music Plugin: 1.0.3
Autolinker: 1.0.4
Backup: 1.4.0
Enhancement: 1.2.1
Plugin Bundle: 0.5.5

### Current behaviour

Ok so the note list doesn't scale properly with the window and its quite annoying to have to manually size it every time I change the size of the window the best way I can show the behavior is a video 

https://github.com/laurent22/joplin/assets/1302391/7272ad16-7540-4ea5-848c-41295941b81b

### Expected behaviour

It should scale proportionally to its relative size.

**Comment by decryptedchaos** [comment] 2024-03-07 01:42
Please advise if this hasn't explained this issue enough.   

This hasn't received a label yet and i'm not sure if its just low priority or not understood.

**Comment by laurent22** [comment] 2024-03-08 00:26
Dev note: The fix would be to always make the editor the element with a dynamic width.

**Comment by G0maa** [comment] 2024-03-29 09:12
Is this issue different from [this one](https://github.com/laurent22/joplin/issues/10151)?

**Comment by G0maa** [comment] 2024-03-29 09:25
Isn't this issue same as [this one](https://github.com/laurent22/joplin/issues/10151)?

**Comment by laurent22** [comment] 2024-03-29 12:04
Duplicate of #10151

**Comment by laurent22** [comment] 2024-03-29 12:04
> Isn't this issue same as [this one](https://github.com/laurent22/joplin/issues/10151)?

Indeed it is, thanks for spotting this!

**Closed as completed by laurent22** 2024-03-29 12:04 UTC
Labels: bug, desktop, medium
