### ISSUE TITLE
orphaned resources don’t get deleted

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#932] opened 2018-10-30 07:01 UTC
### Operating system

- macOS
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

For some reason orphaned resources are not deleted. I'm currently using the latest versions on Android and iOS. On macOS I'm using 1.0.111, although I also tried 1.0.114 (until I saw that internal anchors don't work anymore - I'll open anothe issue for that one).

Here's an export of the `note_resources` table. As you can see quite a few of them don't have an associated page, yet they still exist in my `.resources` directory.

[note_resources.csv.txt](https://github.com/laurent22/joplin/files/2528370/note_resources.csv.txt)

Please let me know, if you need anything else.  (There's nothing suspicious in the debug.log)

**Comment by microcreators** [comment] 2018-11-11 11:34
I can confirm same behaviour on macOS. The sync report shows me same number of resources stored vs. 2 weeks ago, although related notes are long-time gone. Thanks for having a second look at it.

**Comment by tessus** [comment] 2018-11-15 22:39
any update on this?

**Comment by tessus** [comment] 2018-11-20 04:40
@laurent22 can you confirm that this is a bug?

**Comment by laurent22** [comment] 2018-11-20 09:04
Don't known yet, I flagged it so that I remember to check.

**Comment by laurent22** [comment] 2018-11-20 22:41
The last_seen_time = 0 indicates that they've never been associated with a resource (or perhaps were only shortly associated with one). If you can look them up in the resources folder, do you remember if there's something special about these resources?

**Comment by tessus** [comment] 2018-11-20 23:15
Nope, nothing special. Some of them were downloaded by the web clipper service, like avatars for comments. But when I deleted the comments, so were the references to those avatar images.
Some others are test files, but were apparently never deleted after 24h.

**Comment by tessus** [comment] 2019-03-16 20:53
Wouldn't it be easy to delete all not associated resources on start of the app? Or use this algorithm as an additional step should the cleanup task be run in a timed loop.

**Comment by tessus** [comment] 2019-05-26 05:24
@laurent22 I know how to delete the data from the database and also from the local `resources` directory. I can also remove the orphaned files (metadata + actual resources) on the sync target.
This process is manual and rather tedious. (I can send the SQL as well.)
Is there a way to mark these files to be deleted (in the code), so that they are removed from the sync target and locally (database and folder)?

**Comment by laurent22** [comment] 2019-05-26 15:52
If you add the ID to deleted_items it should remove them from the sync target too.

**Comment by tessus** [comment] 2019-05-26 18:45
Thanks for the info, but what are the correct steps then?

Only copy the ids to the `deleted_items` table, or do I have to delete them from the tables `resources` and `note_resources` manually as well? What about the files in the `resources` folder? What is the order of the steps?

```
cd ~/.config/joplin-desktop
for i in `sqlite3 database.sqlite "select resource_id from note_resources where is_associated = 0"`
do 
    rm resources/$i*
done
sqlite3 database.sqlite "delete from resources where id in (select resource_id from note_resources where is_associated = 0)"
sqlite3 database.sqlite "delete from note_resources where is_associated = 0"
```

**Comment by laurent22** [comment] 2019-05-26 18:58
I don't really know off the top of my head, and I don't really want to support such method. Editing the db directly could cause all kind of unexpected problems. Maybe for you it's fine, but other users might see this, try to do the same, make a mistake and a week later realise some data is missing, etc. and wonder why. So if it's not supported by the app, the solution is to fix the app rather than editing the db.

**Comment by tessus** [comment] 2019-05-26 19:00
No, I think you misunderstood. As soon as I know the steps I add that process to Joplin so that orphaned resources get deleted properly.

**Comment by laurent22** [comment] 2019-05-26 19:21
Ah I see, but there's already a process to delete orphaned resources so I guess it just need to be fixed. Simply deleting resources that are not associated with any note doesn't work because those resources might have come via sync, and their associated note has not been downloaded yet. There's a mechanism to handle all this, and I guess it needs to be fixed once we understand the cause for your bug.

**Comment by tessus** [comment] 2019-05-26 19:33
Unfortunately it does not happen for me alone. I'd be ok with doing it manually, but it has come up several times on gh and the forum. So there are quite a few others who experienced the same problem.

**Comment by tessus** [comment] 2019-06-27 02:57
I wrote a script that retrieves a list of orphaned resources from the db, but uses the API to delete the resources, so the db is not changed directly.

> it needs to be fixed once we understand the cause for your bug.

I'm not the only one who's experiencing this bug. It's quite easy to reproduce:
1. clip a page that includes one or 2 images
2. wait 1-5 minutes
3. delete the note

After 24 hours you will see that the 2 images are still in your resource folder and that they have `is_associated = 0` in the database.

**Comment by tessus** [comment] 2019-06-27 06:10
I've just noticed that the API command to delete resources does not delete the resources from the sync target. Only the meta data files are deleted from the sync target.

e.g.: `ecfef68586324b6a88149f651af58068.md` is removed from the sync target, but `.resources/ecfef68586324b6a88149f651af58068` still remains.

**Comment by tessus** [comment] 2019-06-27 17:53
@laurent22 did you see this comment https://github.com/laurent22/joplin/issues/932#issuecomment-506136563

**Comment by laurent22** [comment] 2019-06-27 18:05
Yes I did, I'm planning to try to replicate this.

**Comment by tessus** [comment] 2019-06-27 18:32
If there's anything I can do to help, please let me know.

**Comment by laurent22** [comment] 2019-10-11 18:46
I've checked and see why it happens, but there's no easy fix for it as of now. The fact that a resource can be used by more than one note make things complicated, yet it's a feature that's probably almost never used. So I'm thinking eventually to enforce a one-to-one relation between notes and resources, which will make resource management a lot easier. When that's done, this issue will be resolved.

**Comment by tessus** [comment] 2019-10-11 22:12
What does this mean? So if I tried to inline an image (local attached resource), I could only do it from one note?
Btw, how's the web clipper handling resources right now. e.g. you clip 2 articles from the same web site. Some resources are the same, e.g. like logo, background image, ... Are these common elements always re-downloaded with a different hash?

> The fact that a resource can be used by more than one note make things complicated

I'm not sure why that is, because `is_associated` is only set to 0, when no notes are using the resource.
I always thought that the problem lies with the cleanup process that actually removes the resources which have `is_associated = 0`.

When I was changing my script, this is the SQL that makes it aware of the history and thus safe to use - given that no decrypion/encryption/sync process is unfinished:

```
KEEP=`sqlite3 $DB "select value from settings where key = 'revisionService.ttlDays'"`

select resource_id from note_resources 
where is_associated = 0 and 
  resource_id not in (select resource_id from note_resources where is_associated = 1) 
group by resource_id 
having max(last_seen_time) < strftime('%s','now','-${KEEP} days')*1000
```

**Comment by tessus** [comment] 2020-01-16 23:44
I think this is still relevant. Not sure why the `essential-reviewed` was removed.

**Comment by ssvaluev** [comment] 2020-02-02 10:52
Of course this is still relevant. I tried Joplin for the first time yesterday and today I faced this problem.
And also probably you could find out how it work in my previous PIM - [MyTerta](https://webhamster.ru/site/page/index/articles/projectcode/138) ([GitHub](https://github.com/xintrea/mytetra_dev)). It is open-source, but written on C++. Sorry, I am only learn how to code and can't help with it yet.

**Comment by 0815horsti** [comment] 2020-03-05 08:26
Plus 1 on that and easy very to reproduce.

I started one week ago, added some notes, played with markdown and everything is fine.
Then I deleted the "Welcome"-notebook on windows and the three images remain in the ressouce folder (plus a fourth one which was added by me).

**Comment by laurent22** [comment] 2020-03-05 09:14
I just had this idea that the client should keep in cache a list of resources it has created and it has synced. Then if a resource is not associated with any note, and it is in this list, and has never been synced, we know it can be deleted. That would take care of this specific edge case, at least for newly created resources.

**Comment by 0815horsti** [comment] 2020-03-05 09:38
I had the same idea/concept in mind: Some kind of "clean-up" menu entry which lists all unused ressources and the user can manually decide wether to delete or to keep the files. The sync would then clean up the directory in the cloud.

**Comment by virtadpt** [comment] 2020-03-05 18:04
What do you have Note History (Preferences -> Note History) set to?

**Comment by 0815horsti** [comment] 2020-03-06 09:49
@virtadpt: It is set to 7 days ...

**Comment by naviji** [comment] 2020-03-11 15:49
I just imported my Evernote notes into Joplin on Windows. There was a lot of useless notes, so I deleted most of them. I made sure the sync was complete.

Then when I synced from the Joplin client in my ubuntu installation, it was extremely slow. When I checked the resources folder, I saw that all the images from the deleted notes were also getting downloaded.

**Comment by roachsinai** [comment] 2020-04-09 08:09
> This was one of the first things I checked after downloading the application. Remove the demo notes. Notes history turned off. Then the resources stay on the sync target.
> 
> Disappointed, that after 1.5 year this issue was not solved. This is a showstopper.

I encounter same issue! But I think the show will resume well again, lol. And looking forward to watching!

**Comment by SKILLSHOT-b** [comment] 2020-06-15 00:08
Hi Laurent & Team,

We appreciate the time and effort you all place into Joplin.

Just touching base regarding this issue - hopefully we see a fix soon!

Can confirm this still is present in Joplin for Desktop v1.0.218 

Few recent confirmations via:
https://discourse.joplinapp.org/t/notes-containing-attachments-notes-are-deleted-how-to-delete-all-attachments-cached-images-of-deleted-notes-easily/9380/2
https://discourse.joplinapp.org/t/best-way-to-delete-orphaned-resources/9374/3



Thanks!!

**Comment by littleperks** [comment] 2020-09-04 13:47
This is also a very big frustration for me as I have lots of resources in my notes.  I really like the idea of a manual clean unused resources option.  

Can confirm this still is present in Joplin for Desktop v1.0.233

**Comment by danielb2** [comment] 2020-09-04 16:29
@littleperks 

You can use my ruby script to delete for now:

```
gem install joplin # may require sudo
joplin clean -n # -n is dry run so remove if you want to actually delete
```

**Comment by roachsinai** [comment] 2020-09-04 16:56
> @littleperks
> 
> You can use my ruby script to delete for now:
> 
> ```
> gem install joplin # may require sudo
> joplin clean -n # -n is dry run so remove if you want to actually delete
> ```
> 
> You need to have the webclipper API turned on and run it on the machine running joplin. And if it can't find your joplin db you'll need to pass the `--token` option

That for your tool for Joplin! Would it rebuild `database.sqlite`?

**Comment by danielb2** [comment] 2020-09-04 17:43
> That for your tool for Joplin! Would it update database.sqlite?

The API is the external interface so I use that only.  Touching the DB directly is fragile and not good practice IMO.

**Comment by alexanderadam** [comment] 2020-09-07 12:15
> Simply deleting resources that are not associated with any note doesn't work because those resources might have come via sync, and their associated note has not been downloaded yet.

Is it possible to get the info whether a full sync happened?
If so: wouldn't it be possible to run a cleaning task after it was ensured that a full sync happened?

**Comment by laurent22** [comment] 2020-09-07 16:47
> Is it possible to get the info whether a full sync happened?
> If so: wouldn't it be possible to run a cleaning task _after_ it was ensured that a full sync happened?

No, because in a distributed setup you never know if you have the same data as all the other clients. In this particular case, even if your current client has made a full sync, there could still be another client which hasn't synced yet and which is using the resources. People sometimes leave Joplin clients on some forgotten laptop and sync six months later - in that case we shouldn't delete all their data.

**Comment by roachsinai** [comment] 2020-09-08 00:39
> > Is it possible to get the info whether a full sync happened?
> > If so: wouldn't it be possible to run a cleaning task _after_ it was ensured that a full sync happened?
> 
> No, because in a distributed setup you never know if you have the same data as all the other clients. In this particular case, even if your current client has made a full sync, there could still be another client which hasn't synced yet and which is using the resources. People sometimes leave Joplin clients on some forgotten laptop and sync six months later - in that case we shouldn't delete all their data.

Or add a entry `Delete Orphaned Resources` or other zone? If user press the button means user agree delete those orphaned resources in all devices! So the delete user orphaned resources task never autorun.

**Comment by alexanderadam** [comment] 2020-09-08 07:08
So moving to a 1:1 relationship would solve everything, right?

Since having m:n relations between resources and notes is obviously
> a feature that's probably almost never used

anyway.

Also it's causing issues like this one. And a feature that nobody uses which is causing bugs, is probably not a very good feature. :wink:

**Comment by faydin** [comment] 2020-10-06 08:09
> > Is it possible to get the info whether a full sync happened?
> > If so: wouldn't it be possible to run a cleaning task _after_ it was ensured that a full sync happened?
> 
> No, because in a distributed setup you never know if you have the same data as all the other clients. In this particular case, even if your current client has made a full sync, there could still be another client which hasn't synced yet and which is using the resources. People sometimes leave Joplin clients on some forgotten laptop and sync six months later - in that case we shouldn't delete all their data.

I don't know if this mentioned before but my solution:

A new column can be added in the 'Note attachment' tool to show how many notes have that resource, in that device. Let's call the column **Occurrence** or **Used ... Times**.
And when the user choose to order according to that property (like in 'Size'), the result will be the resources with '0' values at the beginning of the list which also means orphaned resources. It's up to the user the view and delete those orphaned resources.

**Comment by alexanderadam** [comment] 2020-10-09 10:02
Since my use case for having resources is usually that I copied some things from a website.
The extension I'm using ([Copy Selection as Markdown](https://addons.mozilla.org/en-US/firefox/addon/copy-selection-as-markdown/)), just added support for [embedding images as base64 at the bottom of the note](https://github.com/0x6b/copy-selection-as-markdown#advanced).

Thus no new resource is added and when I delete the note, the images are deleted automatically as well.

Maybe this helps someone else as well.

**PS:** isn't this a duplicate [of issue 154](https://github.com/laurent22/joplin/issues/154)?

**Comment by ioogithub** [comment] 2020-11-03 17:35
What is the best way to deal with this issue? How can the orphaned resources be removed without messing up the sync? Is there a guide or best practice somewhere?

**Comment by ssvaluev** [comment] 2020-11-04 15:41
> What is the best way to deal with this issue? How can the orphaned resources be removed without messing up the sync? Is there a guide or best practice somewhere?
I find some solution. Orphaned resources will be removed while "Export all" process.
I do so. After that I remove all notes from Joplin and clear "C:\Users\%UserName%\.config\joplin-desktop\resources" folder. Also remove all attachments in Tools - Note attachments... Unfortunately there is no button "Delete all attachments" (I use LMB+Enter for everyone).
All that's left for me to do is import previously exported notes already without orphaned resources.
It's a long way. But it's working and rarely required. And I hope we will see more convenient way to do this in future. As well as native collapsible text. :)

**Comment by ioogithub** [comment] 2020-11-07 18:54
Yes you are describing a similar process as what myself and others have described. Basically deleting all your data and importing everything again from scratch every time you need to delete a resource. From the test I have done, this is the only way I have verified that works for me as well. I have spent many days exporting all my data, deleting the database, importing it again and uploading all data and syncing all clients again.

Is this a viable solution for a note taking app with synchronizing capabilities?

**Comment by laurent22** [comment] 2020-11-14 11:03
@tessus, I'm wondering whether we could add something like a "Vaccum" button in Joplin that would clear out resources according to certain rules, probably rules similar to what you have in your script, but we should document caveats. Do you know what are the current limitation of your scripts? At least I assume it requires that everything has been synced before running it?

**Comment by tessus** [comment] 2020-11-14 20:24
Yes, I think that was one of the things you mentioned. That all data has to be synced, but I don't check for that in my script. I'm not even sure, if there's a way to get that info from the db or API.
What about enryption? What happens, if some items are not decrypted yet?

I took care of the note history in my script, so it should be fairly safe. But I also put a big fat warning and told people to make backups.
e.g. I'm not 100% about the `Attachment download behavior` setting.

Such a vacuum button would have to take care of a few things (and if not possible, people would have to check those manually):

- sync status
- encryption status
- Attachment download behavior
- note history

Maybe we can use the current `Note attachments` page as a preview of what would be deleted. One thing I highly miss in that screen though is a search field. I would love to be able to search for attachment name or id.

**Comment by mzguy** [comment] 2020-11-18 23:08
> No, because in a distributed setup you never know if you have the same data as all the other clients. In this particular case, even if your current client has made a full sync, there could still be another client which hasn't synced yet and which is using the resources. People sometimes leave Joplin clients on some forgotten laptop and sync six months later - in that case we shouldn't delete all their data.

Why not store in the resource database, with each attachment, the note ID(s) of each note the resource is used by, **_per syncing device_**? Then, if a client deletes a note, and finds that is the last note the resource is used by, delete the resource as well.

Of course, we need each client to have a good copy of the resource database. I don't know how sync works, but we need to ensure the resource database is always synced before resources are downloaded.

**Comment by KolyaKorruptis** [comment] 2021-04-02 16:38
This is important to me, considering all these useless resources get synced. And there is no easy consistent way to remove them.
I barely dare to use the webclipper anymore because chances are my sync storage gets pumped with junk.

**Comment by alexanderadam** [comment] 2021-04-02 17:11
> I barely dare to use the webclipper anymore because chances are my sync storage gets pumped with junk.

You could still use ([Copy Selection as Markdown](https://addons.mozilla.org/en-US/firefox/addon/copy-selection-as-markdown/)) and activate the option for [embedding images as base64 at the bottom of the note](https://github.com/0x6b/copy-selection-as-markdown#advanced).
This way you won't have any separate assets and thus no junk. Deleting a note will delete everything.

**Comment by KolyaKorruptis** [comment] 2021-04-02 17:53
That's a viable workaround, although images in base64 require a lot of storage space in the database. 
I can also remove attachments from Tools=>Note Attachments, if I happen know they are not being used anymore.

What baffles me is that exporting all data filters out unused resources efficiently. It's just a maintenance nightmare to clean up multiple synced devices (including mobile) this way. 

Why can't we just have a button that applies the same filtering (like export) to the current resources and then let's me sync that cleaned up data? Slap a warning on it about all devices having to be in sync, if necessary.
Reading through this thread I get the feeling that a few rare edge cases prevent you from fixing it for the majority of users.

**Comment by thammawat-s** [comment] 2021-05-22 08:28
I'd like to add when encryption is active, it creates *.crypted files.   When I delete resources via Tools/Note attachments, it will delete only regular files, not these *.crypted files.  (tested on Windows)

**Comment by KolyaKorruptis** [comment] 2021-05-22 10:10
If I'm not mistaken work has been done to solve this for most use cases. In a6caa357c8df77a77ceedfa74904dd18c0d95e96 @laurent22 introduced a new function (and a new button in advanced sync settings) to **Re-upload local data to sync target**. 

In combination with a data export (that filters out unused data) this should hopefully make it much easier to force-update all other devices. Maybe @laurent22 can confirm that.

**Comment by danielb2** [comment] 2021-05-31 03:41
> If I'm not mistaken work has been done to solve this for most use cases. In [a6caa35](https://github.com/laurent22/joplin/commit/a6caa357c8df77a77ceedfa74904dd18c0d95e96) @laurent22 introduced a new function (and a new button in advanced sync settings) to **Re-upload local data to sync target**.
> [...]

Maybe this is a foolish question, but how does re-uploading data enable orphaned resources to be deleted?

@laurent22? Does this in-fact accomplish this?

**Comment by KolyaKorruptis** [comment] 2021-05-31 07:32
@danielb2 Orphaned resources get deleted during a data export. You can then import that exported data and have clean data on the local device. The hardest problem was syncing this clean data to other devices afterwards. My hope is that **Re-upload local data to sync target.** will help with this.

**Comment by jerrylususu** [comment] 2021-07-21 11:03
I wrote a tool to remove orphaned resources using the export-reimport idea. It takes a JEX file as input, reads the files under `resources`, and compares it to the full resources list fetched from Joplin Data API, finally removes the items orphaned (in the full list but not in JEX). It prevents directly editing the DB, and the object removal can be safely synced. Hope this helps!

https://github.com/jerrylususu/joplin-vacuum

**Comment by harcel** [comment] 2021-09-15 07:56
Would it be very difficult to get that count of the resources that use the media in a column in that table you get with Tools - Note Attachments... ? Now I can sort them by size, open the huge ones and decide whether I want to delete them or not, but it would be great to automatically find the unused ones here (with the above caveats...).

**Comment by laurent22** [comment] 2021-10-04 18:19
Since a few versions, the resources are being indexed just before sync, which should partially solve the problem.

The last needed fix is this:

When indexing the resources, if an orphan is found, and that resource has never been synced, it means it can be safely deleted. This is because it's only ever been present on the current device.

I think this is an easy fix, which solves the issue for good. Although of course existing orphan resources will unfortunately have to stay, or be purged using tessus's script.

I'm locking the issue for now because I want this comment to be the last one so that it's easy to find back.

**Closed** 2021-10-05 16:49 UTC
Labels: bug, high
