### ISSUE TITLE
ctrl+F toggles layout to split view

### ISSUE THREAD

**Issue by v-marinkov** [laurent22/joplin#2488] opened 2020-02-10 18:27 UTC
`ctrl+F` for in-note search toggles the layout to split view. 

I would like it to stay at whatever layout I have right now. I see it doesn't do any highlighting in the edit mode so at least if I am at the rendered layout, don't switch me to the split one - there are notes which I use are reference and would like to see only the rendered text.

## Environment
Joplin version: 1.0.175
Platform: Ubuntu 19.10

**Comment by tessus** [comment] 2020-02-10 22:02
I remember @laurent22 mentioned that this is working as designed.

**Comment by mic704b** [comment] 2020-02-11 10:00
https://github.com/laurent22/joplin/issues/2308

**Comment by tessus** [comment] 2020-02-11 10:13
duplicate of #2308 

thx, @mic704b

**Closed by tessus** 2020-02-11 10:13 UTC
Labels: bug
