### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by Gankaku** [laurent22/joplin#1618] opened 2019-06-03 22:07 UTC
Hello!

I'm new here and hoping I'm submitting this properly. I have recently installed Joplin (both PC and mobile) and am considering migrating Evernote files to it. I have eye issues and need to be able to get the largest, most readable font that I can.

On the PC, I try everything I can to change the font. I have put in only the font name. The font name with Regular attached. The font name as it is in the file folder (with and without the ttf). Nothing I have tried changes the font on my PC. I've also looked up the information (I believe here in the forums) and that was what I tried first (just inserting the font name). Nothing changes. I've tried Fira Mono, IBMPlexMono, Roboto Mono (all Regular fonts). Could someone please confirm the format that is supposed to be in the field? Also perhaps the format could be listed under the field so it would be clearer.

Also, on the Android side, will there be the capability to enlarge the font more than what it is already? Thank you for your assistance.

EDIT: It finally worked. I rebooted today and the fonts look correct now. But I did try shutting down Joplin and reopening each time yesterday when I made a change, to no avail. Must I reboot to have the change take effect? A little frustrating.  

Operating system
Windows

Application
Desktop

**Comment by CalebJohn** [comment] 2019-06-04 03:22
Do you have joplin set to minimize to the tray? You likely were not actually closing the joplin application. Just minimizing it.

**Comment by tessus** [comment] 2019-06-04 03:53
Time for another FAQ entry... How do I close Joplin properly?

Windows users in particular seem to have major issues there. I believe it has to do with the fact that on Windows an app is usually quit when closing the main window. But I am not a Windows user, so I'm not sure. This has came up many, many times. On the other hand I don't know, if people even read the documentation/FAQ, before opening an issue or posting in the forum.

**Comment by laurent22** [comment] 2019-06-05 11:48
> Windows users in particular seem to have major issues there. I believe it has to do with the fact that on Windows an app is usually quit when closing the main window. But I am not a Windows user, so I'm not sure. This has came up many, many times. On the other hand I don't know, if people even read the documentation/FAQ, before opening an issue or posting in the forum.

I believe the issue is that Windows, by default, **hide the tray icon** for new apps, which is quite dumb actually. You have to follow [complicated steps](https://usbtip.com/show-hide-system-tray-icon-windows-10/) to unhide even one tray icon. So, understandably, users don't even know there's a tray icon and that Joplin is still running.

Perhaps a solution would be to display an alert when the user click on the "Close" button saying something like "Joplin has been minimised to the tray, and is still running. To prevent this behaviour, go to the configuration screen.".

**Comment by ParkerD13** [comment] 2019-06-05 12:50
It does not work for me either with certain fonts. @tessus Where is it documented how to change the font correctly on Windows, btw.? I cannot find anything. Am I blind? 

After trying allot I think **the problem is with font families containing font variants**. When I use a font family from c:\windows\fonts\ that is displayed like a single sheet (= contains only one font), it works. When I select one that looks like a stack of sheets (a font that contains e.g. "font-name bold", "font-name italic"...) then it does not work. So font families composed of different fonts do not work on my Windows 7 machine with Joplin 1.0.158.

I checked that briefly on Ubuntu 18.04 and I cannot get most fonts to work. Again font variants are a problem. As long a font has variants (e.g. "Courier 10 Pitch", "Courier 10 Pitch, bold"...) I cannot get any of these to work in Joplin 1.0.158. 

Maybe it is because the "register" under the same name and have to be "addressed" differently? (I am out of my depth here)

**Comment by tessus** [comment] 2019-06-05 19:55
@ParkerD13 Unfortunately I do not know. I use macOS and I cannot reproduce your issues. I know that the font has to be a monospace font.

e.g.: I have installed the following font with the following variants:

<img width="150" alt="image" src="https://user-images.githubusercontent.com/223439/58985190-c7ed8b80-87a8-11e9-8802-d7ff5b60cb05.png">

I only set the font name to `IBM Plex Mono` and click `Apply`. I don't even have to restart Joplin.

I believe I have read in either a gh issue or a forum post that on Windows you have to use double quotes: `"IBM Plex Mono"`

**Comment by Gankaku** [comment] 2019-06-08 20:51
> 
> 
> It does not work for me either with certain fonts. @tessus Where is it documented how to change the font correctly on Windows, btw.? I cannot find anything. Am I blind?
> 
> After trying allot I think **the problem is with font families containing font variants**. When I use a font family from c:\windows\fonts\ that is displayed like a single sheet (= contains only one font), it works. When I select one that looks like a stack of sheets (a font that contains e.g. "font-name bold", "font-name italic"...) then it does not work. So font families composed of different fonts do not work on my Windows 7 machine with Joplin 1.0.158.
> 
> I checked that briefly on Ubuntu 18.04 and I cannot get most fonts to work. Again font variants are a problem. As long a font has variants (e.g. "Courier 10 Pitch", "Courier 10 Pitch, bold"...) I cannot get any of these to work in Joplin 1.0.158.
> 
> Maybe it is because the "register" under the same name and have to be "addressed" differently? (I am out of my depth here)

Thank you to everyone. I think the app was minimizing and once I rebooted my system and came back the next day, the font was recognized.

Only Monospace fonts are supposed to work. I put in the font name, minus the regular, and it works. Like, Roboto. Or IBM Plex Mono. 

I love the Martel font (easiest to read for me on all platforms.) I'm not sure, it doesn't appear to be a monospace font, but that one works for me in Joplin. So that's what I'm using for now. I have Martel in the Editor Font Family filed under Appearance on the Tools/General dropdown.

Thanks to everyone for your comments and help.

**Comment by tessus** [comment] 2019-06-09 06:22
I'm glad that everything works now. I think this issue is resolved thus I'll close it. Otherwise, please let me know and I'll re-open it.

**Closed by tessus** 2019-06-09 06:22 UTC
