### ISSUE TITLE
Synchronize button seems do not work.

### ISSUE THREAD

**Issue by TencentSZ** [laurent22/joplin#5925] opened 2021-12-28 12:55 UTC
## Environment

Joplin version:  2.6.10
Platform:  Joplin for deskop
OS specifics:  Windows 10 21H1

## Steps to reproduce

Click on Synchronize button on the left bottom of the window.

## Describe what you expected to happen
It supposed to show progress on synchronization but nothing is shown here.
![joplin-bug-01](https://user-images.githubusercontent.com/52615214/147568112-73273be0-c247-4983-8d1b-eb1189b74247.png)

## Logfile
[sync-debug.log](https://github.com/laurent22/joplin/files/7784724/sync-debug.log)

**Comment by roman-r-m** [comment] 2021-12-28 13:01
Seems like a duplicate of https://github.com/laurent22/joplin/issues/5287 or https://github.com/laurent22/joplin/issues/5875

**Closed** 2021-12-28 13:08 UTC
Labels: bug
