### ISSUE TITLE
Broken editor children widths after disabling noteTabs plugin

### ISSUE THREAD

**Issue by banan314** [laurent22/joplin#4864] opened 2021-04-20 07:58 UTC
After disabling Note Tabs plugin, the application layout is broken. In `settings.json`, a child is not removed:

```json
{
	"$schema": "https://joplinapp.org/schema/settings.json",
	"locale": "en_GB",
	"markdown.plugin.softbreaks": false,
	"markdown.plugin.typographer": true,
	"noteVisiblePanes": [
		"editor",
		"viewer"
	],
	"revisionService.ttlDays": 50,
	"newNoteFocus": "title",
	"markdown.plugin.deflist": true,
	"markdown.plugin.abbr": true,
	"markdown.plugin.multitable": true,
	"style.editor.fontSize": 13,
	"sync.interval": 3600,
	"sync.target": 7,
	"clipperServer.autoStart": true,
	"windowContentZoomFactor": 90,
	"autoUpdateEnabled": false,
	"notes.sortOrder.field": "order",
	"editor.codeView": true,
	"notes.sortOrder.reverse": false,
	"spellChecker.language": "pl",
	"ui.layout": {
		"key": "root",
		"children": [
			{
				"key": "sideBar",
				"width": 246,
				"visible": true
			},
			{
				"key": "noteList",
				"width": 169,
				"visible": true
			},
			{
				"key": "editor",
				"visible": true,
				"width": 1987
			},
			{
				"key": "plugin-view-joplin.plugin.note.tabs-note.tabs.panel",
				"context": {
					"pluginId": "joplin.plugin.note.tabs"
				},
				"visible": false
			}
		],
		"visible": true
	},
}
```

which results in the following broken layout:
![image](https://user-images.githubusercontent.com/17968722/115359240-c8397900-a1be-11eb-8170-e33f55f3303f.png)

The viewer is wider than the editor. 

Also, there is not button for WYSIWYG.
![image](https://user-images.githubusercontent.com/17968722/115359400-eef7af80-a1be-11eb-8627-67fb3c491a7e.png)

## Environment

Joplin version: 1.8.1, prod, sync 2, profile 34
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Install Note Tabs plugin and enable it
2. use it, tweak its options
3. disable Note Tabs plugin

## Describe what you expected to happen

Everything should go back to normal. The viewer should be as wide as the editor.

**Comment by roman-r-m** [comment] 2021-05-02 19:16
I suspect it might be fixed by https://github.com/laurent22/joplin/pull/4865

**Comment by banan314** [comment] 2021-05-18 15:51
@roman-r-m 
It's still broken in 1.8.5, Linux Mint this time

**Comment by roman-r-m** [comment] 2021-05-18 15:56
Ok, thanks for checking. Looks like a separate issue then.

**Comment by banan314** [comment] 2021-05-18 16:07
Wide:
![image](https://user-images.githubusercontent.com/17968722/118685705-963e2580-b803-11eb-8a73-1c7812905df1.png)
Narrow:
![image](https://user-images.githubusercontent.com/17968722/118685779-a950f580-b803-11eb-981e-b93d585be1d6.png)
From left to right: notebooks, notes, editor, viewer (only part on the narrow monitor), noteTabs (not visible on the narrow monitor).
I cannot upload a video because there is too much private data.

**Comment by banan314** [comment] 2021-05-18 16:10
But this time I haven't disabled noteTabs, maybe this issue should be closed and a new one opened?

**Comment by mablin7** [comment] 2021-05-18 18:09
After disabling note tabs everything worked fine for me, I'm pretty sure my PR fixed the original issue.

> When I move the Joplin window from a wide monitor (2560x1440) to a narrower one (1920x1080), the side panel of noteTabs hides.

I think that's a different unrelated issue of Joplin not updating the width of panes when the window size suddenly changes after moving between screens. Do you see this problem if you resize the Joplin window on the same screen? For me that way there was no issue. It also seems to be unrelated to the plugin, part of the note editor can overflow the edge of the window too.

Did you move the window with a keyboard shortcut? Just asking because I'm using a tiled window manager and I can only move windows between screens with keyboard shortcuts and I'm thinking maybe the way that the wm quickly changes the window size has something to do with this issue.

As a side note, is this how the note tabs plugin is supposed to look? I've never used it. Just wondering if there's a separate issue with that as well.
![image](https://user-images.githubusercontent.com/7415668/118701771-651a2100-b814-11eb-92de-d0499278825f.png)

**Comment by banan314** [comment] 2021-05-19 17:35
@mablin7 
> Do you see this problem if you resize the Joplin window on the same screen?

Yes.

> Did you move the window with a keyboard shortcut?

Doesn't matter now, but initially I probably did. I'm using Cinnamon DM, but I also have a shortcut for moving a window from one monitor to another
![image](https://user-images.githubusercontent.com/17968722/118858281-45006580-b8d9-11eb-8495-dd24327994d3.png)

> is this how the note tabs plugin is supposed to look?

Yes.

It's my settings for note tabs:
![image](https://user-images.githubusercontent.com/17968722/118857676-9a884280-b8d8-11eb-9a91-0ec4e8ca56fe.png)
![image](https://user-images.githubusercontent.com/17968722/118857750-ae33a900-b8d8-11eb-8c1a-07797aa79b21.png)

**Comment by mablin7** [comment] 2021-05-19 17:59
Hey thanks for the answers! I've been looking into this today, and it turns out the problem is not what I initially thought it to be, since it's not just related to window resizing.

It seems to me that Joplin doesn't have a set maximum size for the panes, so if the sum of their widths is greater than the window, they'll just overflow. I've been working on a solution, though there are still a few kinks to iron out. I'll make a PR as soon as it's ready.

**Closed** 2021-05-22 17:30 UTC
Labels: bug, desktop

**Comment by banan314** [comment] 2021-06-02 13:46
fixed
