### ISSUE TITLE
Search field focus is steal on layout change

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#6514] opened 2022-05-14 07:58 UTC
The search field loses focus if a plugin or command change the editor (markdown or rich text) or the layout (splitview, preview) with `toggleVisiblePanes` and `toggleEditors`.

For the plugins, the problem has become worse since the performance optimization of Joplin, because the list is updated quickly and therefore a note is displayed more quickly, which then triggers the command. This happens all the time when you only pause for a moment when entering text in the search box.

## Environment

Joplin 2.8.6 (prod, win32)

Client ID: 6c4a316296944e2eb07a539f4d50eeb1
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 2486c78

## Steps to reproduce

Manually: 
1. Set Layout to preview
2. Start searching
3. Use shortcut to switch the Layout `Ctr+L`
4. Now the editor window has the focus

Plugin:
1. Install [Persist Editor Layout Plugin](https://discourse.joplinapp.org/t/persist-editor-layout-plugin/14411)
2. Add the tag `layout:viewer` for the `4. Tips` note in the `Welcome! (Desktop)` 
3. Configure in the Persist Editor Layout Plugin settings the `Default editor layout` to `Split View`
4. Search for `tips` and wait a second 
5. Search list is updated and the focus of the search field is steal through the plugin API commandos `toggleVisiblePanes` / `toggleEditors`.

## Describe what you expected to happen

The focus should remain in the search field

## Additional information

https://github.com/benji300/joplin-persistent-layout/issues/12
https://discourse.joplinapp.org/t/persist-editor-layout-plugin/14411/47
https://discourse.joplinapp.org/t/i-have-found-some-problems-using-joplin-search-feature/25561

## Plugins that cause the problem
- [Auto show active note in sidebar ](https://github.com/laurent22/joplin/issues/6514#)v1.0.1
- [Persistent Editor Layout ](https://github.com/laurent22/joplin/issues/6514#)v2.2.0

**Comment by mzguy** [comment] 2022-12-13 19:30
Joplin 2.9.4 - there's still a bug here.

I'm still losing focus from the search box while typing a search. It seems to happen consistently when I do the reverse of the steps for reproducing above: switching from preview to editor view steals the focus from the search box.

**Comment by mzguy** [comment] 2022-12-30 16:11
Can anyone confirm?

**Comment by mzguy** [comment] 2022-12-30 16:12
@JackGruber Can you confirm this is still occurring?

**Comment by JackGruber** [comment] 2022-12-30 17:13
No the error for stealing the focus of the search field in combination with plugins and the `toggleVisiblePanes` / `toggleEditors` command was fixed.

**Comment by mzguy** [comment] 2022-12-30 17:16
> No the error for stealing the focus of the search field in combination with plugins and the `toggleVisiblePanes` / `toggleEditors` command was fixed.

I'm on 2.9.4, and I'm still having focus stealing during search as described above.

**Comment by JackGruber** [comment] 2023-01-04 15:47
@laurent22 Could you reopen the Issue or should I create a new one.

It seems that the problem now occurs again when switching from viewer to editor during the search (With the persistent layout plugin) or if you scroll up and down in the note list with the arrow keys and the layout is switched through the plugin persistent layout.

This also happens when the layout is changed with `Ctrl+L`

I tested this with Joplin `2.9.17` and `2.10.13`

**Comment by laurent22** [comment] 2023-01-04 16:45
Is that he exact same problem with the same steps to reproduce?

**Comment by JackGruber** [comment] 2023-01-06 07:53
Yes, the problem can be reproduced with the plugin and manual steps from the Issue.

**Comment by JackGruber** [comment] 2023-01-06 08:02
The error occurs again in version `2.9.12` and higher

**Comment by mzguy** [comment] 2023-03-27 18:28
Any update on this one? I see release notes stating that search focus issues were fixed in pre-release versions over the past month, but this issue seems to still be occurring.

**Comment by JackGruber** [comment] 2023-05-13 15:37
Error is still there on `2.11.2`

**Comment by mzguy** [comment] 2023-06-09 16:50
@laurent22 @JackGruber 

Is this a fix for this issue?

https://github.com/laurent22/joplin/commit/489d6778dbd3df5372d198a23af1b36416b0f5c0

Or is there something else that causes loss of focus as described here?

**Comment by JackGruber** [comment] 2023-06-10 09:58
The problem still exist in `2.11.9`

**Comment by mzguy** [comment] 2023-06-30 22:07
It's still there in 2.11.11.

Is this not getting fixed because of the Plugin label? It's triggered by a plugin, but the cause isn't a plugin.

**Closed as completed** 2023-09-24 13:42 UTC
Labels: bug, desktop, high, plugins

**Comment by corwin42** [comment] 2023-10-30 14:54
This problem still occurs, if the "outline" plugin has the "auto hide" option switched on.

**Comment by kennethmgreen17** [comment] 2025-05-31 21:30
> This problem still occurs, if the "outline" plugin has the "auto hide" option switched on.

I just now confirmed that this issue is still occurring 3.3.12 on Windows with Outline plugin set to Auto-hide. The reason I was only seeing it sporadically is because it requires two conditions: 1. Outline plugin set to Auto-hide and 2. the first note of results has no headings so Outline hides it. A lot of my notes have headings, so I only saw this issue occasionally. I went searching and landed here - very glad you mentioned the Outline plugin, because I don't use any of the other listed culprits. 

For now, I have disabled the auto-hide feature. And since I have a shortcut assigned to toggling Outline, this isn't a problem for me. But the issue does still exist, and there are lots of comments and posts and closed GitHub issues claiming this issue is fixed.

**Comment by mahibi** [comment] 2025-10-24 09:38
This bug appears for me with "Auto show active note in sidebar: 1.0.1"

```
Joplin 3.3.12 (prod, linux)

Auto show active note in sidebar: 1.0.1
Backup: 1.4.2
Emoji: 1.0.4
Favorites: 1.3.2
Freehand Drawing: 2.14.0
Outline: 1.5.14
```

Disabling "Auto show active note in sidebar: 1.0.1" seems to solve it.
