### ISSUE TITLE
Web Clipper does not capture PDFs

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6156] opened 2022-02-14 02:42 UTC
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Try to clip "http://waltercosand.com/CosandScores/Composers%20E-K/Joplin,%20Scott/Collected_Piano_Music.pdf"
2. No PDF is clipped

## Describe what you expected to happen

PDF is clipped and saved into note with the link to pdf included in header

**Comment by CalebJohn** [comment] 2022-02-14 08:43
Isn't this a duplicate of #6098 ?

**Closed** 2022-02-14 13:44 UTC
Labels: bug
