### ISSUE TITLE
`**name:**dantezhu` render unexpeced

### ISSUE THREAD

**Issue by dantezhu** [laurent22/joplin#5022] opened 2021-05-28 14:34 UTC
## Environment

Joplin version: 1.8.5
Platform: Windows and macOS
OS specifics: Windows10 and macOS10

## Steps to reproduce

1. type `**name:**dantezhu`

## Describe what you expected to happen
render like this:
![image](https://user-images.githubusercontent.com/1105212/120000874-db353980-c005-11eb-846f-7ca9aee490a2.png)

but the right render should be like this:
![image](https://user-images.githubusercontent.com/1105212/120001344-4717a200-c006-11eb-8f0e-8661dd0ab90c.png)

but github markdown render unexpected too:
**name:**dantezhu

so I don't know if this is a bug.

**Comment by roman-r-m** [comment] 2021-05-28 15:12
Does not seem to be a bug - both commonmark & markdownId render the same as Joplin:

https://spec.commonmark.org/dingus/?text=**name%3A**dantezhu
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%2A%2Aname%3A%2A%2Adantezhu%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by CalebJohn** [comment] 2021-05-28 17:55
This is not a bug, but it's certainly new to me! Joplin (mostly) follows the commonmark spec, you can find the [relevant section here](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis). I will copy the relevant paragraph below. This paragraph gives rules about the closing `**` (called a right-flanking delimiter run).

> A **right-flanking delimiter run** is a delimiter run that is (1) not preceded by Unicode whitespace, and either **(2a) not preceded by a punctuation character**, or (2b) preceded by a punctuation character and followed by Unicode whitespace or a punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.

I've bolded item (2a) because it is the relevant rule.

**Closed by CalebJohn** 2021-05-28 17:55 UTC

**Comment by dantezhu** [comment] 2021-05-29 23:19
thanks you very much
