### ISSUE TITLE
Solarized Dark theme's preview pane does not follow the theme

### ISSUE THREAD

**Issue by GreatestFool** [laurent22/joplin#3887] opened 2020-10-09 20:16 UTC
## Environment

Joplin version: 1.2.6
Platform: Windows
OS specifics: 1809 17763.1397

## Steps to reproduce

Switch to Solarized Dark theme.

![Capture12_1](https://user-images.githubusercontent.com/3003484/95627600-bee78b00-0a7c-11eb-9e49-451f9dc50949.PNG)

See #2626 for an example of how it normally looks when using the Solarized Dark theme.

**Comment by laurent22** [comment] 2020-10-09 20:55
Theming in Joplin has been refactored and although I've tried to make sure all the themes had good defaults, it's possible some colours here and there aren't right. Pull requests to improve this are welcome.

**Comment by GreatestFool** [comment] 2020-10-16 07:29
So, while I couldn't find the source file for the solarized dark theme, I did edit it manually through advanced, if that helps. The Options menu is still not fitting the theme, but one of them are missing the class and I don't have enough time beyond this, at least at this moment.

```css
/* Note sidebar */
div.sc-AxirZ {
	background-color: rgb(0, 43, 54);
}

/* Note sidebar hover */
div.sc-AxjAm > *:hover {
	background-color: #073642;
}

/* Note sidebar search */
div.biSLgK {
	background-color: rgb(0, 43, 54);
}

/* Note editing text configuration bar */
div.editor-toolbar {
	background-color: rgb(0, 43, 54) !important;
}
```

**Comment by GreatestFool** [comment] 2020-11-16 16:28
It has not been fixed.

**Comment by HermasciousLevander** [comment] 2020-12-14 09:27
This styling works for version 1.4.19:

```
/* For styling the entire Joplin app (except the rendered Markdown, which is defined in `userstyle.css`) */

/* Note sidebar */
div.iOpiTN {
	background-color: rgb(0, 43, 54);
}

/* Note sidebar hover */
div.sc-fzoKki > *:hover {
	background-color: #073642;
}

/* Note sidebar search */
div.gFVnAG {
	background-color: rgb(0, 43, 54);
}

/* Note editing text configuration bar */
div.editor-toolbar {
	background-color: rgb(0, 43, 54) !important;
}
```

**Comment by HermasciousLevander** [comment] 2021-01-14 07:52
Still a thing my dude.

**Comment by jurf** [comment] 2021-01-23 09:43
I’ve been looking into fixing this – is there a way to edit the colours live?

**Comment by jurf** [comment] 2021-02-23 06:50
Still a thing.

**Comment by coderrsid** [comment] 2021-03-20 07:40
i am not able to reproduce this..

**Comment by Priyaraj17** [comment] 2021-03-20 08:44
Is this issue open? May I work on it?

**Comment by roman-r-m** [comment] 2021-03-20 12:35
> Is this issue open? May I work on it?

Are you able to reproduce it? @coderrsid just wrote that he couldn't

Since this has been raised a while ago it could've been fixed by now

**Comment by jurf** [comment] 2021-03-20 14:38
Joplin 1.7.11

Solarized Light:
![image](https://user-images.githubusercontent.com/7472425/111873736-2c83d580-8992-11eb-969c-caf3ce508395.png)

Solarized Dark:
![image](https://user-images.githubusercontent.com/7472425/111873750-3c9bb500-8992-11eb-9eb0-93a9f589d651.png)

As you can see, there are still considerable inconsistencies.

**Comment by Priyaraj17** [comment] 2021-03-20 14:57
> > Is this issue open? May I work on it?
> 
> Are you able to reproduce it? @coderrsid just wrote that he couldn't
> 
> Since this has been raised a while ago it could've been fixed by now

It's working fine on my PC.

**Comment by GreatestFool** [comment] 2021-03-21 09:01
Can you provide screenshots and log please? Every machine I've installed this on since this issue was raised has had the same problem, if for some reason it works on a freshly installed system but not on systems where it has been previously installed, then it is a rather large issue since it must not be removing itself properly for that to happen.

**Comment by jurf** [comment] 2021-03-21 17:47
@Priyaraj17 what Joplin version are you on?

**Comment by richtwin567** [comment] 2021-03-25 02:13
> Joplin 1.7.11
> 
> Solarized Light:
> ![image](https://user-images.githubusercontent.com/7472425/111873736-2c83d580-8992-11eb-969c-caf3ce508395.png)
> 
> Solarized Dark:
> ![image](https://user-images.githubusercontent.com/7472425/111873750-3c9bb500-8992-11eb-9eb0-93a9f589d651.png)
> 
> As you can see, there are still considerable inconsistencies.

It looks like this for me on Linux, (Kubuntu 20.04) with Joplin 1.7.11. I am going to try it on Windows and with the dev branch's version as well.

**Comment by richtwin567** [comment] 2021-03-25 02:30
![image](https://user-images.githubusercontent.com/14096959/112409291-3e91ab00-8ce7-11eb-882a-0352d1be7da0.png)
The dark notebook list background in the Solarized light theme is intentional or a part of this bug?

**Comment by richtwin567** [comment] 2021-03-25 04:23
It happens for me on Windows as well and it seems it hasn't been fixed in the dev branch yet either. May I work on this bug?

**Comment by richtwin567** [comment] 2021-03-26 13:26
@roman-r-m or anyone, would it be possible to provide an image of the correctly themed options screen? I would like to check if the modifications I have made align with the expected result.

**Comment by roman-r-m** [comment] 2021-03-26 13:30
See the 1st comment:

> See #2626 for an example of how it normally looks when using the Solarized Dark theme.

**Comment by richtwin567** [comment] 2021-03-26 13:36
> See the 1st comment:
> 
> > See #2626 for an example of how it normally looks when using the Solarized Dark theme.

I did look at this but they only show images where I see the notebook and notes. Can I assume that once I get the background colour in that view correct, it would follow that the background colour in options is also correct?

**Comment by roman-r-m** [comment] 2021-03-26 13:52
Not sure, either try or check the code/css

**Comment by richtwin567** [comment] 2021-03-26 13:58
okay, thanks.

**Comment by Priyaraj17** [comment] 2021-03-27 08:09
> @Priyaraj17 what Joplin version are you on?

sorry, didn't see your message. It was 1.8.0. 
OS: linux

**Comment by jurf** [comment] 2021-03-27 09:58
@richtwin567 I would probably follow the semantics on https://ethanschoonover.com/solarized/

**Comment by richtwin567** [comment] 2021-03-27 20:56
> @richtwin567 I would probably follow the semantics on https://ethanschoonover.com/solarized/, i.e. the colourful buttons don’t really fit the paradigm.

![image](https://user-images.githubusercontent.com/14096959/112734608-d7593e00-8f14-11eb-91ad-94259dca9288.png)
![image](https://user-images.githubusercontent.com/14096959/112734630-f48e0c80-8f14-11eb-8454-6f70b32717ba.png)

**Closed** 2021-03-29 08:46 UTC
Labels: bug, medium
