### ISSUE TITLE
Broken link "Server Sharing" in main README

### ISSUE THREAD

**Issue by johnsaigle** [laurent22/joplin#4775] opened 2021-03-30 13:10 UTC
The link goes to the URL `https://github.com/laurent22/joplin/blob/dev/readme/spec/server_sharing.md` which results in a 404.

**Comment by roman-r-m** [comment] 2021-03-30 13:25
Duplicate of https://github.com/laurent22/joplin/issues/4485

**Closed by roman-r-m** 2021-03-30 13:25 UTC
Labels: bug
