### ISSUE TITLE
Desktop: Code markdown syntax component's inappropriate behaviour

### ISSUE THREAD

**Issue by coderrsid** [laurent22/joplin#3007] opened 2020-04-08 11:16 UTC
The code in markdown syntax is showing color syntax on both side of layout. 

![image](https://user-images.githubusercontent.com/35633575/78777645-8d034800-79b7-11ea-8685-1d1036ebc4ad.png)

It should behave something like this 👍: 
![image](https://user-images.githubusercontent.com/35633575/78777735-b7550580-79b7-11ea-86cd-043d25313111.png)
![image](https://user-images.githubusercontent.com/35633575/78778002-2df20300-79b8-11ea-8169-5a45733877c9.png)

Platform : Desktop (macOS)

**Comment by laurent22** [comment] 2020-04-08 12:24
I don't understand anything, can you clarify?

**Comment by coderrsid** [comment] 2020-04-08 12:35
I am saying.. that it's showing color fir code syntax in editor too .. which it shouldn't i guess.

**Comment by laurent22** [comment] 2020-04-08 12:37
> it's showing color fir code syntax in editor too .. which it shouldn't i guess.

I'd say it's a good thing that syntax highlighting works in the editor too, why should we disable this?

**Comment by coderrsid** [comment] 2020-04-08 12:55
> I'd say it's a good thing that syntax highlighting works in the editor too, why should we disable this?

It's because it's an editor as you can try here in github in editor it is plain text and not highlighted markdown which is rather in Preview section.

**Comment by tessus** [comment] 2020-04-08 21:18
I'm a bit confused about this. There's no syntax highlighting in the editor, except for the language `javascript` - and only, iff the language is specifically indicated (not auto-detected).

Also, once again: it is great that you post a screenshot of text, which makes it really easy to copy and paste it for testing. I'm sorry, to be harsh but after a few times asking you no to do this: do you have a learning problem or are you just ignorant?

**Comment by tessus** [comment] 2020-04-08 21:22
I understand that you want to show the highlighting, but pasting the text helps people to replicate the problem.

**Comment by coderrsid** [comment] 2020-04-08 21:33
Sorry @tessus, as it was just a matter of line. I didn't think i need to paste the syntax, but i guess you need that so : 

```javascript
var a = "abcd" 
print(a)
```

**Comment by coderrsid** [comment] 2020-04-08 21:35
and as for the problem. I guess you didn't see that `var` highlighted in somewhat blue color in the editor and after rendering in view layout too.

**Comment by laurent22** [comment] 2020-04-08 21:35
Sorry I'm just going to close this. It's unclear what the issue is, and if it's so hard to clarify then probably it's not that important.

**Closed by laurent22** 2020-04-08 21:35 UTC
Labels: bug

**Comment by tessus** [comment] 2020-04-08 21:36
No, I actally meant everything in the screenshot. But never mind, I wrote my own js code for the test and used some others I had. But since it's closed, it's not important anymore.

**Comment by coderrsid** [comment] 2020-04-08 21:47
Sorry guys.. i didn't mean to be harsh to anyone and it's not that this issue is not important.

**Comment by coderrsid** [comment] 2020-04-09 09:27
Although what i was trying to say was, as you see in the below screenshot
![image](https://user-images.githubusercontent.com/35633575/78879924-39096980-7a72-11ea-84e4-ab4c96322fe6.png)

It's coloring the javascript syntax `var` in editor and viewer both which it shouldn't and just wanted to know whether this is an issue or not @laurent22 . If it's not, it's perfectly fine. But if it is, i'd like to work on it.

**Comment by Rishgod** [comment] 2020-04-09 13:45
this I believe is a feature that was added and I believe its a good thing if the text is distinguished by different colouring, for example, if you bold a text the colour would change to blue and I believe that's a good thing

**Comment by coderrsid** [comment] 2020-04-09 18:00
Thanks .. that was all i was asking for.. some info.. 😄
