### ISSUE TITLE
Note sorting discrepancy between Mac and Android apps

### ISSUE THREAD

**Issue by jokhallouf** [laurent22/joplin#7898] opened 2023-03-10 09:36 UTC
So I have several notes created on my Mac app (version 2.9.17) and I sorted them in a specific way and the sort order set as "Custom" . When I open Joplin on my Android (version 2.10.8) the order isn't the same even though I set the sort order to "Custom" on my Android as well.

## Environment

Joplin version: 2.9.17 (Mac), 2.10.8 (Android)
Platform: Mac os Ventura 13.2.1, Android 13
OS specifics: OnePlus 8T, OOS, KB2003_11_F.62 , Android 13

## Steps to reproduce

1. Create multiple notes
2. Sort then in a specific order based on "Custom" sorting on Mac
3. Open Android app with sorting set to "Custom" but the sort order is different 

## Describe what you expected to happen
I expect to have the same custom sort order I set on my Mac app to be reproduced and synced on my Android app
![20230309_123839_lmc_8 4](https://user-images.githubusercontent.com/18097743/224279978-2fd85f9c-6184-411d-a7b9-e39ad7aaa54b.jpg)
![Screenshot_2023-03-09-12-38-47-21_97a2b898327add53e982bbebadc3de52](https://user-images.githubusercontent.com/18097743/224279996-f360ae52-05c5-4036-ba4b-9333fd33a8dd.jpg)
![Screenshot_2023-03-09-12-38-53-79_97a2b898327add53e982bbebadc3de52](https://user-images.githubusercontent.com/18097743/224280001-4d513441-7743-4aa9-a995-7cbb7014df41.jpg)

**Comment by laurent22** [comment] 2023-03-10 13:22
Could you try with pre-release 2.10 to confirm?

**Comment by jokhallouf** [comment] 2023-03-10 14:27
Just downloaded the 2.10.8 pre-release on my mac, re sorted and synchronised, no changes happened on my android avec syncing. The custom order of my notes still isn't being synchronised
<img width="1147" alt="Screenshot 2023-03-10 at 15 25 43" src="https://user-images.githubusercontent.com/18097743/224341205-c07fa505-39d8-4286-a537-e2a98e5c26db.png">
<img width="253" alt="Screenshot 2023-03-10 at 15 25 55" src="https://user-images.githubusercontent.com/18097743/224341215-5432b995-4bc2-49c6-8ece-f9ed185b4634.png">
![signal-2023-03-10-152618_002](https://user-images.githubusercontent.com/18097743/224341220-a3f5aa20-d686-4c8e-9f3a-ae4893511cfb.jpeg)
![signal-2023-03-10-152618_003](https://user-images.githubusercontent.com/18097743/224341222-6cb4390c-2300-4837-bf77-1e8f08a0f650.jpeg)

**Comment by laurent22** [comment] 2023-03-10 14:37
@TaoK, do you know if that would be fixed by https://github.com/laurent22/joplin/pull/7765?

**Comment by TaoK** [comment] 2023-03-10 15:27
I expect so - the trick would be "did the notes get synced (to whatever the sync server/location is) after they were created, before they were sorted?". If so (and that would often/typically be the case), then Issue #7741 would have been the cause, and pull request #7765 would be the fix.

A way to be sure would be to go into each of these notes, on the mac, and update them slightly (eg add a space in the body). If the issue is fixed in #7765, the order would suddenly get fixed in Android in the next sync.

**Comment by jokhallouf** [comment] 2023-03-10 16:04
Oh wow!
so i went into each note on the Mac and added a space in the body as suggested then synced the mac app and then opened up the app on the android device and synced and the notes are now in the correct order!
Thanks a million!

**Comment by laurent22** [comment] 2023-09-24 15:40
Thanks for fixing this @TaoK!

**Closed as completed by laurent22** 2023-09-24 15:40 UTC
Labels: bug, mobile, desktop, high
