### ISSUE TITLE
Crash during sync on Andoird

### ISSUE THREAD

**Issue by jurgenhaas** [laurent22/joplin#504] opened 2018-05-09 15:18 UTC
### Operating system

Android 8.1.0

### Application

Mobile, latest version of Joplin on a Pixel 2

### Problem

I'm trying to initially sync with Nextcloud where I do have this set of notes (taken from the Joplin Desktop App):

```
Folder: 9/9
Resource: 1609/1609
Tag: 35/35
NoteTag: 639/639
MasterKey: 0/0
Insgesamt: 4573/4573
```

The mobile app starts syncing and does that in chunks of 1000 notes. When it gets to something around 3500 the app crashes and I was able to send a system report.

I've repeated this several times. I even wiped the data and re-installed the app. It's always the same problem.

Not sure if that's caused by the number of notes in general or by a particular note. If the latter, is there a way to identify which one that might be?

**Comment by laurent22** [comment] 2018-05-09 15:19
Large resources (over 10MB) can cause crashes. This is a bug that will probably be resolved at some point, once the APIs in use get better.

If you have crash report please could you send it over?

**Comment by jurgenhaas** [comment] 2018-05-09 15:30
Ah, wait a minute. What I didn't see in the Nextcloud web interface is the hidden ressource folder. That contains objects up to 36 MB for a file. So your theory still stands that it has a problem with bigger files.

**Comment by laurent22** [comment] 2018-05-09 15:36
Are there many of these? If not, you could simply move those over 10MB to another folder in Nextcloud (also move the associated .md files, which are named "RESOURCE_ID.md"), and sync again.

Once this crash is fixed, you can always put the files back in the Joplin folder on Nextcloud.

**Comment by laurent22** [comment] 2018-05-09 18:14
Duplicate of #371

**Closed** 2018-10-05 22:38 UTC
