### ISSUE TITLE
Cursor in wrong position when working with cyryllic text

### ISSUE THREAD

**Issue by kilotaras** [laurent22/joplin#3479] opened 2020-07-10 15:53 UTC
When writing a cyryllic text in markdown editor, cursor moves away from the text. There's no spaces after "лис" in following screenshot, yet the cursor appears a lot farther than it should be.

![image](https://user-images.githubusercontent.com/590292/87173045-d5dfdb00-c2dd-11ea-8bb3-15a73d761df8.png)

Looks like the reason has something to do with the width of font (it's narrower for cyryllic).

## Environment

Joplin 1.0.224 (prod, darwin)

Client ID: 646b7180cc024e93b926a56db20245d3
Sync Version: 1
Profile Version: 30
Keychain Supported: Yes

Revision: 1899d86 (master)

## Steps to reproduce

1. Create a note
2. Write some cyryllic text, e.g. `У лісі лісі темному де ходить хитрий лис`

## Describe what you expected to happen

Cursor should be right after last letter in the line.

## Logfile

Nothing in debug console

**Comment by CalebJohn** [comment] 2020-07-10 16:20
Hi @kilotaras Thanks for the report but this is a duplicate of #2991 , please refer to that issue to understand the bug.

Fortunately we are working on improving support for Cyrillic text. Instead of changing fonts you can actually go into the note settings and opt in to use the beta codemirror editor, that should fix your problem.

**Closed by CalebJohn** 2020-07-10 16:20 UTC

**Comment by kilotaras** [comment] 2020-07-10 16:42
Thanks and sorry.

I did a cursory search but missed that issue.

пт, 10 лип. 2020, 19:20 користувач Caleb John <notifications@github.com>
пише:
