### ISSUE TITLE
Cursor moves by itself in the note body; crashes when erasing text

### ISSUE THREAD

**Issue by ershov-a** [laurent22/joplin#3789] opened 2020-09-21 20:03 UTC
## Environment

Joplin version: 1.1.2
Platform: Android
OS specifics: 6.0 (MIUI 10)

## Steps to reproduce

1. Create new note.
2. Start typing something in note body.
3. The cursor starts to move by itself.
4. Start erasing text, the application will crash.

## Describe what you expected to happen

I will be able to type and edit text in the Joplin mobile application without unexpected cursor movements and crashes.

## Logfile
[syncReport-1600717255804.txt](https://github.com/laurent22/joplin/files/5257813/syncReport-1600717255804.txt)

## Screen recording
![JoplinGif](https://user-images.githubusercontent.com/5314011/93812828-d213f180-fc5a-11ea-856e-40cf9b98278a.gif)

**Comment by CalebJohn** [comment] 2020-09-21 22:01
Hi @ershov-a Thanks for the bug report with a gif!

This is a duplicate of #3199 so I'll be closing this. This issue will be attached to #3199 so your recording won't go to waste.

I'm also going to list out some other related issues just in case this comes up again.
#2939 #3036 #3538 #3303

**Closed by CalebJohn** 2020-09-21 22:01 UTC
Labels: bug
