### ISSUE TITLE
Android: Networkr request failed

### ISSUE THREAD

**Issue by fwillo** [laurent22/joplin#1696] opened 2019-06-28 21:01 UTC
### Operating system

- Android

### Application

- Mobile

Dear all,

I try to get the Joplin Android app running with my Synology WebDAV server, but unfortunately I experience a "Network Request failed". I already tried using the https:// and http:// protocol. The address typed in works with the desktop client. Accessing WebDAV with another Android app works without problems (same Address, Username, Password). Other issues regarding the "Network request failed" topic didn't help in my case. 

In the program log, the following error appears:
```
[...]
06-28T22:53:56,30,"""Operations completed: ""
06-28T22:53:56,10,"""TypeError: Network request failed
onerror@index.android.bundle:139:2655
value@index.android.bundle:124:1505
value@index.android.bundle:123:6095
value@index.android.bundle:123:2835
value@index.android.bundle:49:1280
value@index.android.bundle:28:3311
index.android.bundle:28:822
value@index.android.bundle:28:2565
value@index.android.bundle:28:794
value@[native code]""
06-28T22:53:55,30,"""RevisionService::maintenance: Done in 202990ms""
06-28T22:53:55,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
06-28T22:53:55,30,"""RevisionService::maintenance: Done in 20ms""
06-28T22:53:55,30,"""Synchronisation ist bereits im Gange. Status: in_progress""
06-28T22:53:55,30,"""Starting scheduled sync""
[...]
```

I'm using a OnePlus 6 with Android 9, OxygenOS 9.0.6. Hopefully the information delivered is helpful. Otherwise I will try to deliver necessary information in addition.

Best,
fwillo

**Comment by laurent22** [comment] 2019-06-29 09:58
Do you use a self-signed TLS certificate?

**Comment by fwillo** [comment] 2019-06-29 13:06
At the moment, no. Nevertheless, TLS certificates shouldn't be relevant when I'm using http://, right? Or am I missing something?

**Comment by tessus** [comment] 2019-06-29 23:09
@fwillo yes, you mentioned the following: _I already tried using the https:// and http:// protocol._

If you had followed the topics in the forum and checked the issues on gh, you would have seen that there is a problem with http on Android, because the new Android API blocks http by default.

**Comment by tessus** [comment] 2019-06-29 23:09
Duplicate of #1686

**Closed by tessus** 2019-06-29 23:09 UTC

**Comment by fwillo** [comment] 2019-06-30 08:10
Thank you for your hint @tessus. Searching with google regarding this topic didn't yield this post. Sorry for the inconvenience and thanks everybody for your work!
