### ISSUE TITLE
FR: Add Subnotebook menu item

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#898] opened 2018-10-17 15:09 UTC
Hi

Can you please add a menu item for adding a Subnotebook to the currently active notebook? At the moment one has to add a notebook then drag under a notebook to make it a sub.

Another way would be to having add subnotebook menu item in the right click menu of a notebook.

thanks

**Comment by gerroon** [comment] 2019-01-24 02:56
One more idea is that maybe we can have a tick in the notebook creation window, that says "create this under selected" which does what it says. It creates a new subnotebook under a currently selected one. That way one doesn ot need to worry about draggin dragging or finding the new notebook etc.

**Comment by gerroon** [comment] 2019-02-26 23:11
Just wondering if anyone is loooking for this feature?

**Comment by Traviis** [comment] 2019-05-22 13:46
I would like this feature. 

I couldn't figure out how to do sub-notebooks until I read your comment above. A first class way of doing this would be nice.

**Comment by i-need-to-tell-you-something** [comment] 2019-05-23 07:44
Your first post in this thread accidentally says "Subnote" instead of "Subnotebook", it is slightly confusing. Also you should probably mention somewhere that you're talking about the desktop client.

I want this feature as well. I felt some good ways to achieve this would be:
1. When right-clicking a notebook "Make a new notebook here" option.
2. When having a notebook selected in the notebook list, and when you click on "New notebook", make the new notebook as a sub-notebook to the selected notebook.

**Comment by gerroon** [comment] 2019-09-22 01:00
Please do not  close the issue stuipid bot

**Comment by tessus** [comment] 2019-10-14 04:36
duplicate of #1978 

fixed in #1984

**Closed by tessus** 2019-10-14 04:36 UTC
Labels: desktop, good first issue, hacktoberfest
