### ISSUE TITLE
Search function is unhelpful

### ISSUE THREAD

**Issue by 0scvr** [laurent22/joplin#6349] opened 2022-03-30 22:27 UTC
## Environment

Joplin version: Joplin 2.7.15
Platform: macOS 
OS specifics: version 12.3

## Describe what you expected to happen

Should be able to find notes without typing the whole word.

I've seen other people complain about the search function. Perhaps it should be improved (fuzzy search ?).

![Capture 2022-03-30 à 17 17 21](https://user-images.githubusercontent.com/71343264/160941271-eec60476-3535-4e23-8341-353fbf77c9fd.jpg)
![Capture 2022-03-30 à 17 17 27](https://user-images.githubusercontent.com/71343264/160941276-73230a1b-fe39-4263-a5c7-1bf62686b6df.jpg)
![Capture 2022-03-30 à 17 17 31](https://user-images.githubusercontent.com/71343264/160941280-8d54d310-6fa1-4a4b-84af-d454b3404ad1.jpg)

**Comment by hihihlo** [comment] 2022-03-31 00:57
you should use "mous*" rather than "mous".
Joplin readme.md said :

> For example, searching for cat will return all the notes that contain this exact word. 
> Note: it will not return the notes that contain the substring - thus, for "cat", notes that contain "cataclysmic" or "prevaricate" will not be returned.
>

**Comment by kacnje** [comment] 2022-03-31 04:31
I also noticed that many of my colleagues have problems when searching. Almost all of them (and I stand with them :-)) said that this should be a setting and default should probably search for notes containing the substring. 
Next to this, Joplin should HIGHLIGHT results in notes. Currently, it is really annoying when notes are longes and you have to repeat searching in it. 
I can't say for Mac, but searching behavior is annoying on Windows and Linux (I use the Android version only occasionally and can't speak about it). My experience is that this bothers many users. 
Otherwise, the Joplin is a really nice application.

**Comment by hihihlo** [comment] 2022-03-31 06:25
very much agree !
1. suggest Joplin auto search [\*cat\* \*dog\*] when input [cat dog], or provide a option setting (e.g. "auto contain substring").
    this is Intuitive and frequently use.
    in ANY text editor, everyone expect [cat] will match [catalog]
    (unless use regex like [\bcat\b], or checked "whole word")
2. in above setting, if need word boundaries e.g. [cat\*] or [\*dog], maybe can add search filter "bound:",
    e.g. [bound: cat\* dog] matched "catalog about dog", and not match "catalog about doggy"
thanks~

**Comment by 0scvr** [comment] 2022-03-31 12:17
> you should use "mous*" rather than "mous". Joplin readme.md said :
> 
> > For example, searching for cat will return all the notes that contain this exact word.
> > Note: it will not return the notes that contain the substring - thus, for "cat", notes that contain "cataclysmic" or "prevaricate" will not be returned.

My mistake, I wasn't aware this was the expected behaviour. However, as @kacnje said, I think it would be better if the default behaviour was to search for substrings. I think this is more intuitive and more useful for most.

**Comment by 0scvr** [comment] 2022-03-31 12:18
> very much agree !
> 
> 1. suggest Joplin auto search [*cat* *dog*] when input [cat dog], or provide a option setting (e.g. "auto contain substring").
>    this is Intuitive and frequently use.
>    in ANY text editor, everyone expect [cat] will match [catalog]
>    (unless use regex like [\bcat\b], or checked "whole word")
> 2. in above setting, if need word boundaries e.g. [cat*] or [*dog], maybe can add search filter "bound:",
>    e.g. [bound: cat* dog] matched "catalog about dog", and not match "catalog about doggy"
>    thanks~

Yes, something like that or a regex mode would would make more sense in my opinion.

**Comment by pth0rn** [comment] 2022-03-31 18:34
Using * in search only works after the word, and not as a prefix.
E.g. "*bar" does not return any results if a note has "foobar"
Feel like proper search is very important, I hope it gets implemented

**Comment by Daeraxa** [comment] 2022-03-31 20:43
Closing issue as it is not a bug, instructions on how to use the search function is covered in the documentation - https://joplinapp.org/help/#searching. If there is any feedback on the documentation then feel free to discuss on the forums or create a PR.

By default Joplin uses full word searching for speed but you can switch to basic search mode by adding a <kbd>/</kbd> before your search.
i.e.`/bar` would find notes that contain `bar` and `foobar`

**Closed as completed** 2022-03-31 20:43 UTC

**Comment by koppor** [comment] 2023-11-15 20:01
Is there a possibility to configure Joplin to always have partial-string search. I have a machine being powerful enough to do search-as-you-type? Reason: I am currently evaluating alternatives to Microsoft OneNote - and I don't want to type more characters for a "similar" search behavior.

**Comment by koppor** [comment] 2023-11-15 20:03
Reading https://joplinapp.org/help/apps/search#goto-anything, I learned that one should not use the search box, but should use <kbd>Ctrl</kbd>+<kbd>P</kbd> to activate a nice fulltext search.
