### ISSUE TITLE
"Network request failed" syncing with Dropbox on iOS

### ISSUE THREAD

**Issue by jacklund** [laurent22/joplin#6403] opened 2022-04-13 03:47 UTC
## Environment

Joplin version: 12.7.1
Platform: iOS
OS specifics: 15.4.1

## Steps to reproduce

1. Set up Dropbox sync, including authorizing on website
2. Set up encryption password
3. Synchronize

## Describe what you expected to happen

My notes would be synchronized between my Linux and iOS devices

## Logfile

![2022-04-12 22 41 55](https://user-images.githubusercontent.com/209634/163096196-b613a15d-bd71-4b82-bbfc-4ed54b4ef8eb.png)

**Comment by Daeraxa** [comment] 2022-04-13 08:42
Duplicate of https://github.com/laurent22/joplin/issues/6375

**Closed as completed by Daeraxa** 2022-04-13 08:42 UTC
Labels: bug
