### ISSUE TITLE
Desktop: Goto Anything modal closes even when you click inside

### ISSUE THREAD

**Issue by genneko** [laurent22/joplin#3028] opened 2020-04-12 04:28 UTC
"Goto Anything" modal dialog closes even when you click on it (including the text field and the "?" icon).
This prevents the help text for the dialog from showing up when you click "?".
I don't think it's a big issue but it would be better if it closes only when you click outside the modal.

## Environment

Joplin version: Electron v1.0.199
Platform: Linux, Windows
OS specifics: Ubuntu 18.04, Windows 10

## Steps to reproduce

1. Start Joplin Desktop app.
2. Select "Tools" > "Goto Anything" or hit Ctrl-G to open "Goto Anything" modal.
3. Click anywhere on the modal (the search text field, "?" icon or margin area). You will see the modal closes on click.

## Describe what you expected to happen

- Clicking "?" toggles the help text above the text field.
- Clicking on the modal doesn't close it.

**Comment by anjulalk** [comment] 2020-04-12 05:59
I think this is caused by #2940. Most probably it incorrectly binds the onClick event to the entire page, closing the Go to anything modal wherever you click.

I'll look into this.

**Closed** 2020-04-12 08:59 UTC
Labels: bug, desktop, high
