### ISSUE TITLE
[feature request] draw.io integration

### ISSUE THREAD

**Issue by nr458h** [laurent22/joplin#308] opened 2018-03-17 08:44 UTC
### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I use draw.io a lot to create charts and attache them to my notes. At the moment when something comes to my mind I need to open a draw.io instance create a chart save it somewhere make an jpeg-export and attache it to the note. Later when I want to rework the chart, at first I need to find it, then rework it save it export it delete the picture in the note and attache the new one - puh crazy workflow.

So it would be awesome to be able create draw.io-charts within joplin and attache the .xml to a note and than later be able to rework the chart.

This is just an idea for a very specific workflow, so if it does not fit your scope for the app feel free to close it right away.

Thanks again for the great app and the fast progress!

**Comment by laurent22** [comment] 2018-03-17 11:12
In which format are these charts? Is it the same as Mermaid? https://github.com/laurent22/joplin/issues/163

**Comment by nr458h** [comment] 2018-03-17 14:54
I do not know mermaid, draw.io works with .xml files and can be exported to different other formats.
Detailed information you may gind here:

https://support.draw.io/display/DO/Exporting+Files

**Comment by laurent22** [comment] 2018-03-26 16:24
Duplicate of #279

**Closed by laurent22** 2018-03-26 16:24 UTC
