### ISSUE TITLE
[Feature Request] Show the notebooks name after searching for notes

### ISSUE THREAD

**Issue by alwashe** [laurent22/joplin#534] opened 2018-05-18 20:51 UTC
### Operating system
- Windows

### Application
- Desktop

Sometimes I forget in which notebook I placed a note. I can find it by searching, but where is that note? It would be nice to display the name of the notebook I left the note.

**Comment by laurent22** [comment] 2018-05-20 08:53
Closed as duplicate

**Closed by laurent22** 2018-05-20 08:53 UTC

**Comment by gerroon** [comment] 2018-11-20 19:47
Duplicate of?

**Comment by laurent22** [comment] 2018-11-20 21:14
This has actually been implemented. The notebook name is now displayed in the toolbar.

**Comment by gerroon** [comment] 2018-11-20 23:10
@laurent22 

Thanks, would it be possible to clicking on it would take the user to the respective notebook?
