### ISSUE TITLE
No tray icon on Linux Mint

### ISSUE THREAD

**Issue by tiaga** [laurent22/joplin#3369] opened 2020-06-14 17:33 UTC
Since 1.0.216 Joplin's icon cannot be found in a tray on Linux Mint 19.2 with Сinnamon desktop environment.

## Environment

Joplin version: 1.0.220
Platform: Linux Mint 19.2 Tina
OS specifics: Сinnamon desktop environment

## Steps to reproduce

1. Install Joplin using `Joplin_install_and_update.sh` and run it.
2. Go to "Options > Application" and check that "Show tray icon" is enabled.
3. Restart the application.

## Describe what you expected to happen

Joplin's icon is shown in a tray on Linux Mint 19.2 Cinnamon (as it was in previous versions).

## Logfile

[debug.log on Pastebin](https://pastebin.com/8M9bggr9)

**Comment by dpoulton-github** [comment] 2020-06-15 00:56
Appears to be a duplicate of https://github.com/laurent22/joplin/issues/3242 which discusses an upstream issue causing this behaviour.

However I have tried Joplin with the Linux Mint 20 beta and not only does the icon show it also starts Joplin just by clicking it (ie no need to right-click "open")

**Closed** 2020-06-15 18:23 UTC
