### ISSUE TITLE
Inline math generates duplicate in render / does not work correctly

### ISSUE THREAD

**Issue by fdi438** [laurent22/joplin#2902] opened 2020-03-25 10:54 UTC
Inline math gets rendered twice - once the code, and then the rendered math expression. (see attached example screenshot). (I think that this actually used to work in one of the previous versions? _Update: Works on Android and Joplin Desktop 1.0.179_)

## Environment
Joplin version: 1.0.195 (prod, win32)
Platform: Windows 10
OS specifics: n/a

#### My example:
1. Type inline math, e.g. `Inline $\log (a) = \frac{1}{\sqrt{2 \pi \sigma_{1}^{2}}}$ inline continuation`
2. Look at layout
![image](https://user-images.githubusercontent.com/52065945/77528751-bfc52080-6e8e-11ea-9d40-3fd9a3e36653.png)

#### Additional example (exact code from joplin markdown guide example)
1. `This is some inline Math: $\sqrt{3x-1}+(1+x)^2$ and this is a code block.`
2. ![image](https://user-images.githubusercontent.com/52065945/77529352-b6888380-6e8f-11ea-91cc-f1f197d63801.png)

#### Other versions
- On Android (Joplin v1.0.324) the output is as expected.
- On my backup machine (Windows 10) with Joplin 1.0.179 the output is as expected.

## Describe what you expected to happen
Expected the math to render inline only, as described in the markdown guide https://joplinapp.org/markdown/

## Logfile
not required? Can upload if required.

**Comment by sealch** [comment] 2020-03-25 15:48
Duplicate of #2811

**Comment by coderrsid** [comment] 2020-03-25 16:11
It's fixed already on master. 
Platform : macOS

![image](https://user-images.githubusercontent.com/35633575/77558717-4a367000-6ee1-11ea-9d32-3a748700070a.png)

**Closed** 2020-03-25 19:07 UTC
Labels: bug
