### ISSUE TITLE
"Attach Any File" cannot attach files with spaces in their names

### ISSUE THREAD

**Issue by charlesdaniels** [laurent22/joplin#1684] opened 2019-06-24 01:11 UTC
### Operating system

- iOS

### Application

- Mobile

On an up to date (as of time of posting) copy of Joplin for iOS, the "attach any file" button will report `The file "..." couldn't be opened because there is no such file` on any file that contains spaces in the name. I was trying to attach from the "On my iPhone" "folder" if that matters. It looks like Joplin is URL-encoding the filename, so the spaces get converted to `%20`, but presumably the iOS file access API does not understand this format.

I would assume as someone not familiar with the Joplin codebase that [this](https://github.com/laurent22/joplin/blob/60ed2cbee5353be75ac38b3a1657629a73e405f3/ReactNativeClient/lib/components/screens/note.js#L390) is where the response gets checked, and presumably where the necessary conversion code should live. I'm not sure where the native and where the React part of the file picking progress starts though (being familiar with neither React nor iOS personally), so I can't be certain. 

![Image-1](https://user-images.githubusercontent.com/11738895/59984864-78f28380-95fb-11e9-9980-8624349a400d.jpg)

**Comment by metbril** [comment] 2019-07-03 20:45
duplicate of #659?

**Comment by charlesdaniels** [comment] 2019-07-04 02:39
No, I don't think it's a dupe of #659. I was able to attach a PDF file without spaces in the name, with #659 could not. Also, #659 showed the failure occurring even when there were not spaces in the file name, which is not a behavior I could re-produce.

**Closed** 2019-07-21 13:39 UTC
Labels: bug, essential, mobile

**Comment by TheOnlyGeal** [comment] 2019-08-24 05:35
Hi,
I still have the issue on iOS (iPhone). Nothing to add to the previous description.
