### ISSUE TITLE
Android: App closes and notes discarded when launching from share

### ISSUE THREAD

**Issue by Terrance** [laurent22/joplin#7170] opened 2022-11-08 19:30 UTC
## Environment

Joplin version: 2.5.5
Platform: Android 12
OS specifics: OnePlus Nord CE, OxygenOS 12.1

## Steps to reproduce

1. Share text content from another app.
2. Choose Joplin as the receiver.
3. Joplin opens, then closes again before the shared text appears in the note body.  The note hasn't been saved.

It seems to be quite inconsistent, though _more_ consistent when using a split screen to use two apps at once (i.e. sharing from the top app causes Joplin to replace the bottom app).  Sharing a second time whilst the app is "still warm" from this seems to work fine, but I can then reproduce it after, say, 15 minutes.

If I go and open Joplin explicitly after it self-closes, the note's usually there and the app then acts like I'd expect from opening as a share target (app closes again when backing out of the note, rather than showing the note list).  If I leave it too long, or share something else, the first share is lost, presumably as whatever state that's holding the content is discarded.

## Logfile

[syncReport-1667929789239.txt](https://github.com/laurent22/joplin/files/9964506/syncReport-1667929789239.txt)

There were a few failed shares between 17:00 and 18:00 on 07/11 -- this part looks relevant:

```
11-07T17:29:03,30,"""Provisional was not modified - deleting it""
11-07T17:29:03,30,"""Received shared data""
```

**Comment by laurent22** [comment] 2022-11-08 21:32
This is a rather old version, you should try the latest to see if it solves the issue

**Comment by Terrance** [comment] 2022-11-08 23:01
I'm using what I believe to be the latest version on Android with working filesystem sync?  As my workflow involves sharing content into Joplin on Android and later editing it on a computer, I can't upgrade any further until the fixes for storage access are released.

I did take a quick look at the commit history since that release, and couldn't see anything obvious that might affect sharing, though admittedly I don't know exactly what to look for.

**Comment by wh201906** [comment] 2022-11-09 02:49
You can check these PRs/issues to see how the developers resolve the problem in filesystem sync and the sharing on Android.
#6395, #6789, #6792, #6932, #6942, #6943
I guess the latest pre-release should work? You can give it a try.

**Comment by Terrance** [comment] 2022-11-09 23:14
I'm aware of the ongoing work on it, hence why I'm still on the old version until that reaches a release.

In the meantime, is the log file in the original post of any use in figuring out why the app closes on a share?  I can try and grab a full logcat next time it happens if that's more likely to help.

> I guess the latest pre-release should work?

I don't see links to any Android pre-release builds anywhere?  The [Android release repo](https://github.com/laurent22/joplin-android/releases) only appears to have stable releases (the latest one being from May), and there's no sign of any links to built APKs in the linked PRs or CI runs (besides a couple of expired custom builds you've done during reviews?).

**Comment by wh201906** [comment] 2022-11-09 23:57
The pre-release is there.
https://github.com/laurent22/joplin-android/tags

> I can try and grab a full logcat next time it happens if that's more likely to help.

Yeah the log does help.

**Comment by Terrance** [comment] 2022-11-10 00:24
So they are.  GitHub is [helpfully showing the wrong dates in that list](https://user-images.githubusercontent.com/4025899/200969513-b8c927ac-170d-48eb-bfbd-7d3adc505ee0.png) so I'd overlooked them as being current. 

In any case I just gave 2.9.8 a go, but I'm still seeing the permission-denied style errors (_'...version.txt' does not exist and could not be created_) that were originally reported with the changes in 2.6, so I guess it still needs work.  As above, I'll stay on the old version for now, and will try to get some more complete logs next time it happens.

**Comment by wh201906** [comment] 2022-11-10 01:49
OK. Thanks for your feedback.
By the way, does the text sharing in the latest version work?

**Comment by Terrance** [comment] 2022-12-10 18:46
Well it remains an issue on 2.5.5 -- unless someone on a newer version can chime in with a repro, I guess this issue is stalled.

> does the text sharing in the latest version work?

I only had it installed for a day, and it's usually longer than that between the times when it happens.  As noted above, without working sync, my daily workflow breaks down and I'd be manually copying large chunks of text from my phone to my computer, which I don't particularly want to be stuck doing.  I did have a look at the app cloning feature in OnePlus' OxygenOS but it doesn't look like I can have two different versions installed.

**Comment by wh201906** [comment] 2022-12-11 03:59
> So they are. GitHub is [helpfully showing the wrong dates in that list](https://user-images.githubusercontent.com/4025899/200969513-b8c927ac-170d-48eb-bfbd-7d3adc505ee0.png) so I'd overlooked them as being current.
> 
> In any case I just gave 2.9.8 a go, but I'm still seeing the permission-denied style errors (_'...version.txt' does not exist and could not be created_) that were originally reported with the changes in 2.6, so I guess it still needs work. As above, I'll stay on the old version for now, and will try to get some more complete logs next time it happens.

I just noticed that there is a similar issue.
https://github.com/laurent22/joplin/issues/7318#issuecomment-1341291105
Maybe it's not a permission-denied style error. It's just a bug of the synchronizer upgrading process.

**Comment by XilinJia** [comment] 2023-01-03 20:49
@Terrance 
File system sync works with 2.9.8.  I had experienced your problem with Android 12 after upgrading to 2.9.8 from early versions.  The reason it didn't work is that the path that you entered in previous versions is not correct under Android 12 and 2.9.8 inherits what you entered previously.   What you need to do is tap on the path entry area, and the new Joplin will pop up a file chooser for you to choose the folder.  You can still choose your same old fold.  After confirming, you will see the text of the path is entered, notice that it is different from before.

I also tried to reproduce this issue, and it doesn't occur on 2.9.8.  So if @Terrance also confirms, I suggest that we close this.

**Comment by Terrance** [comment] 2023-01-04 23:27
Ok, I've upgraded and reconfigured; seems to be working, though very slowly (https://github.com/laurent22/joplin/issues/6942#issuecomment-1371541710).

I'll keep it installed for now and see if the sharing issues persist.

**Comment by Terrance** [comment] 2023-01-11 23:43
Having been using 2.10.2 for the last week, I'm finding some shares now result in a grey screen, possibly at the point where before it would close the app before, but now where the UI is locking up during a sync (https://github.com/laurent22/joplin/issues/6942#issuecomment-1371541710) instead?

**Comment by Terrance** [comment] 2023-01-19 23:12
This is still occurring as originally described on 2.10.3 -- here's a fresh debug report with a couple of failed shares today.  I'm not sure on the exact times but I can see a few cases where a new _Starting application_ line is logged shortly after, possibly because it's crashing and restarting at the incoming share?

[syncReport-1674169600487.txt](https://github.com/laurent22/joplin/files/10461829/syncReport-1674169600487.txt)

**Comment by Terrance** [comment] 2023-01-24 19:03
As of 2.10.4 or 2.10.5, there seems to be an additional failure mode: sharing text into Joplin opens the app but leaves me at the notebook listing, without creating a new note (as opposed to the app closing, which is also still happening).

Here's another log, where I believe the launch at `01-24T16:09:24` was a share that left me at the notebook screen (followed by a reattempted successful share at `01-24T16:10:25`).

[syncReport-1674586516164.txt](https://github.com/laurent22/joplin/files/10493125/syncReport-1674586516164.txt)

(Please do say if these logs are/aren't helping or if there's some better output I can provide instead.)

**Comment by roman-r-m** [comment] 2023-01-24 22:58
There's this in the last log
```
01-23T08:59:00,20,"""Could not attach file:", "Error: Couldn't read row 0, col 2 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
Code: EUNSPECIFIED
Error: Couldn't read row 0, col 2 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at promiseMethodWrapper (address at index.android.bundle:1:111091)
    at copyFile (address at index.android.bundle:1:2936678)
    at ?anon_0_ (address at index.android.bundle:1:2934015)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2929989)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/164673tg/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/164673tg/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:213106)
    at _callTimer (address at index.android.bundle:1:212055)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:212219)
    at callReactNativeMicrotasks (address at index.android.bundle:1:214194)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:114578)
    at anonymous (address at index.android.bundle:1:113671)
    at __guard (address at index.android.bundle:1:114419)
    at flushedQueue (address at index.android.bundle:1:113582)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:113525)""
01-23T08:59:00,30,"""Original dimensions ", "{"width":868,"height":1156}""
01-23T08:58:59,30,"""about to attach resource {"name":"61a46649-d9c7-4de4-8aba-c759304b4e52.jpg","mimeType":"image/jpeg","uri":"content://com.jarsilio.android.scrambledeggsif.fileprovider/shared_images/61a46649-d9c7-4de4-8aba-c759304b4e52.jpg"}""
01-23T08:58:59,30,"""Got file: content://com.jarsilio.android.scrambledeggsif.fileprovider/shared_images/61a46649-d9c7-4de4-8aba-c759304b4e52.jpg""
```

Possibly has something to do with the app you shared from (Scrambled Exif I assume)

**Comment by Terrance** [comment] 2023-01-24 23:49
Ah, didn't realise that was in the log too -- I guess that's another possible result of a failed share.  (The original bug report here relates to sharing text; the image shared there was in fact a misclick and I'd forgotten about it; can't remember for sure what the UI did in that case, I think I just ended up at an empty note.)

I assume image sharing is supposed to work and attach the image to a new note?  I just tried sharing an image directly from the gallery, but that caused "Invalid column last_modified" to pop up over an empty note.
 
[syncReport-1674604022784.txt](https://github.com/laurent22/joplin/files/10494846/syncReport-1674604022784.txt)

**Comment by roman-r-m** [comment] 2023-01-25 06:36
What's your android version?

Edit
Ah, sorry, I see it in the top comment

**Comment by roman-r-m** [comment] 2023-01-25 06:43
I have a similar device (OnePlus Nord 2) and couldn't replicate this, not in the first attempt at least. Will try a bit more

**Comment by laurent22** [comment] 2023-02-20 12:23
Duplicate of #7791

(It's not really a duplicate, but part of the many share related issues in this version, and we track them in that other issue)

**Closed as completed by laurent22** 2023-02-20 12:23 UTC
Labels: bug, mobile, high

**Comment by Terrance** [comment] 2023-02-26 20:19
Unfortunately this still seems to be happening in 2.10.7 -- noting here as the linked issue has also been closed now.

New log: [syncReport-1677430814608-snip.txt](https://github.com/laurent22/joplin/files/10834638/syncReport-1677430814608-snip.txt)

The app isn't closing itself any more, but continues to just open to my note list without starting a new note.  The logs seem to indicate no data is received:

 > 02-26T16:59:37,30,"root: ""Sharing: handleShareData:", "null""

**Comment by Terrance** [comment] 2023-02-26 20:20
Relatedly, I note the content of incoming shares are now logged in full -- previously the debug logs were good at keeping personal data out, but I've had to go through and remove the cleartext copies of shared content from this one.  It would be good if the incoming data could be obfuscated from the logs in some way (e.g. just logging the length of text data).
