### ISSUE TITLE
Issue with website's linux download instructions

### ISSUE THREAD

**Issue by Flash-Git** [laurent22/joplin#1663] opened 2019-06-17 13:52 UTC
The alternative download command for linux has a backslash in it:
 `wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh \| bash`

The github readme does not :
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash`

**Comment by foxmask** [comment] 2019-06-19 10:01
in fact the backslash is also in the README.md ; when you have a look at the RAW version you see it.
I'm going to fix it

**Comment by foxmask** [comment] 2019-06-19 18:41
It seems there is bug with the markdown flavor itself o_O

**Comment by Flash-Git** [comment] 2019-06-20 21:42
Ah that's annoying, sorry for the hassle

**Comment by mollusko** [comment] 2019-06-26 14:24
I've had issues running the alternate command referenced due to the lack of a space between the slash & '| bash'; adding a space resolves the issue

**Comment by tessus** [comment] 2019-06-30 08:25
The problem is that the backslash is required to escape the `|`, because it is within a table. If it weren't escaped, the `|` would start a new cell in the table.
Somehow the script that creates the HTML from the md has to take care of removing the backslash.
We could add a marker at the beginning and the end of the table, and the script changes the code within those markers.

**Comment by tessus** [comment] 2019-07-26 20:51
This should be fixed now.

**Closed by tessus** 2019-07-26 20:51 UTC
Labels: documentation
