### ISSUE TITLE
iOS: Scrolling doesn't work with selection

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#156] opened 2018-01-10 09:41 UTC
Scrolling now works in the way that all content is visible. It doesn't work when new line is inserted or deleted. The same applies to selecting text. Screen will not scroll and it is therefore not possible to select more than the text that is already visible.

Also, scrolling doesn't work at all when metadata are shown.

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

**Comment by laurent22** [comment] 2018-03-26 16:36
Duplicate of #181

**Closed by laurent22** 2018-03-26 16:36 UTC
