### ISSUE TITLE
Search not working in MacOS desktop 1.0.160

### ISSUE THREAD

**Issue by xthursdayx** [laurent22/joplin#1674] opened 2019-06-18 22:58 UTC
### Operating system

- macOS

### Application

- Desktop

Search is not working for me in Desktop version 1.0.160. When I enter a search term either nothing happens or I am taken to a specific note that has my term in it, but am not given a list of all the notes that contain the searched for term.

**Comment by tessus** [comment] 2019-06-19 03:30
Once again, we require a debug log.

Btw, nothing has changed in search related code in the last few versions.

**Comment by xthursdayx** [comment] 2019-06-19 04:46
Yes, sorry about that, I just remembered how to grab it. Anyway, these errors appear when I try to search for a term:
```
/Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:89 Uncaught (in promise) TypeError: Cannot read property 'encryption_applied' of undefined
    at arrayHasEncryptedItems (/Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:89)
    at stateHasEncryptedItems (/Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:95)
    at reducer (/Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:721)
    at reducer (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:470)
    at reducer (/Applications/Joplin.app/Contents/Resources/app/app.js:203)
    at dispatch (/Applications/Joplin.app/Contents/Resources/app/node_modules/redux/lib/createStore.js:178)
    at Application.generalMiddleware (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:335)
    at Application.generalMiddleware (/Applications/Joplin.app/Contents/Resources/app/app.js:227)
    at Object.dispatch (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326)
    at Application.refreshNotes (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:245)
arrayHasEncryptedItems @ /Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:89
stateHasEncryptedItems @ /Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:95
reducer @ /Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:721
reducer @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:470
reducer @ /Applications/Joplin.app/Contents/Resources/app/app.js:203
dispatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/redux/lib/createStore.js:178
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:335
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/app.js:227
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326
refreshNotes @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:245
_tickCallback @ internal/process/next_tick.js:68
async function (async)
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/app.js:227
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326
refreshNotes @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:245
_tickCallback @ internal/process/next_tick.js:68
async function (async)
refreshNotes @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:241
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:388
async function (async)
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:342
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/app.js:227
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326
doCommand @ /Applications/Joplin.app/Contents/Resources/app/gui/MainScreen.min.js:220
onQuery @ /Applications/Joplin.app/Contents/Resources/app/gui/MainScreen.min.js:440
triggerOnQuery @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:23
scheduleSearchChangeEventIid_.setTimeout @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:33
setTimeout (async)
HeaderComponent.search_onChange.event @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:32
callCallback @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:100
invokeGuardedCallbackDev @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:138
invokeGuardedCallback @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:201
executeDispatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:461
executeDispatchesInOrder @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:483
executeDispatchesAndRelease @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:592
forEachAccumulated @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:560
runEventsInBatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:723
runExtractedEventsInBatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:732
handleTopLevel @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4472
batchedUpdates$1 @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16537
batchedUpdates @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:2131
dispatchEvent @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4551
interactiveUpdates$1 @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16592
interactiveUpdates @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:2150
dispatchInteractiveEvent @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4528
/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:263 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at Application.refreshNotes (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:263)
    at process._tickCallback (internal/process/next_tick.js:68)
refreshNotes @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:263
_tickCallback @ internal/process/next_tick.js:68
async function (async)
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/app.js:227
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326
doCommand @ /Applications/Joplin.app/Contents/Resources/app/gui/MainScreen.min.js:220
onQuery @ /Applications/Joplin.app/Contents/Resources/app/gui/MainScreen.min.js:440
triggerOnQuery @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:23
scheduleSearchChangeEventIid_.setTimeout @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:33
setTimeout (async)
HeaderComponent.search_onChange.event @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:32
callCallback @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:100
invokeGuardedCallbackDev @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:138
invokeGuardedCallback @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:201
executeDispatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:461
executeDispatchesInOrder @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:483
executeDispatchesAndRelease @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:592
forEachAccumulated @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:560
runEventsInBatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:723
runExtractedEventsInBatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:732
handleTopLevel @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4472
batchedUpdates$1 @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16537
batchedUpdates @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:2131
dispatchEvent @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4551
interactiveUpdates$1 @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16592
interactiveUpdates @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:2150
dispatchInteractiveEvent @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4528
/Applications/Joplin.app/Contents/Resources/app/gui/NoteText.min.js:685 Got ipc-message: setMarkerCount [0]0: 0length: 1__proto__: Array(0)
/Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:89 Uncaught (in promise) TypeError: Cannot read property 'encryption_applied' of undefined
    at arrayHasEncryptedItems (/Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:89)
    at stateHasEncryptedItems (/Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:95)
    at reducer (/Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:721)
    at reducer (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:470)
    at reducer (/Applications/Joplin.app/Contents/Resources/app/app.js:203)
    at dispatch (/Applications/Joplin.app/Contents/Resources/app/node_modules/redux/lib/createStore.js:178)
    at Application.generalMiddleware (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:335)
    at Application.generalMiddleware (/Applications/Joplin.app/Contents/Resources/app/app.js:227)
    at Object.dispatch (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326)
    at Application.refreshNotes (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:245)
arrayHasEncryptedItems @ /Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:89
stateHasEncryptedItems @ /Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:95
reducer @ /Applications/Joplin.app/Contents/Resources/app/lib/reducer.js:721
reducer @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:470
reducer @ /Applications/Joplin.app/Contents/Resources/app/app.js:203
dispatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/redux/lib/createStore.js:178
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:335
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/app.js:227
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326
refreshNotes @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:245
_tickCallback @ internal/process/next_tick.js:68
async function (async)
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/app.js:227
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326
refreshNotes @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:245
_tickCallback @ internal/process/next_tick.js:68
async function (async)
refreshNotes @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:241
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:388
async function (async)
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:342
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/app.js:227
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326
doCommand @ /Applications/Joplin.app/Contents/Resources/app/gui/MainScreen.min.js:220
onQuery @ /Applications/Joplin.app/Contents/Resources/app/gui/MainScreen.min.js:440
triggerOnQuery @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:23
scheduleSearchChangeEventIid_.setTimeout @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:33
setTimeout (async)
HeaderComponent.search_onChange.event @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:32
callCallback @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:100
invokeGuardedCallbackDev @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:138
invokeGuardedCallback @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:201
executeDispatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:461
executeDispatchesInOrder @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:483
executeDispatchesAndRelease @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:592
forEachAccumulated @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:560
runEventsInBatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:723
runExtractedEventsInBatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:732
handleTopLevel @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4472
batchedUpdates$1 @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16537
batchedUpdates @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:2131
dispatchEvent @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4551
interactiveUpdates$1 @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16592
interactiveUpdates @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:2150
dispatchInteractiveEvent @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4528
/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:263 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at Application.refreshNotes (/Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:263)
    at process._tickCallback (internal/process/next_tick.js:68)
refreshNotes @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:263
_tickCallback @ internal/process/next_tick.js:68
async function (async)
generalMiddleware @ /Applications/Joplin.app/Contents/Resources/app/app.js:227
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app/lib/BaseApplication.js:326
doCommand @ /Applications/Joplin.app/Contents/Resources/app/gui/MainScreen.min.js:220
onQuery @ /Applications/Joplin.app/Contents/Resources/app/gui/MainScreen.min.js:440
triggerOnQuery @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:23
scheduleSearchChangeEventIid_.setTimeout @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:33
setTimeout (async)
HeaderComponent.search_onChange.event @ /Applications/Joplin.app/Contents/Resources/app/gui/Header.min.js:32
callCallback @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:100
invokeGuardedCallbackDev @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:138
invokeGuardedCallback @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:201
executeDispatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:461
executeDispatchesInOrder @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:483
executeDispatchesAndRelease @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:592
forEachAccumulated @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:560
runEventsInBatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:723
runExtractedEventsInBatch @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:732
handleTopLevel @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4472
batchedUpdates$1 @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16537
batchedUpdates @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:2131
dispatchEvent @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4551
interactiveUpdates$1 @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16592
interactiveUpdates @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:2150
dispatchInteractiveEvent @ /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:4528
```

**Comment by tessus** [comment] 2019-06-19 05:03
Thanks for the log. It looks like either the decryption process is stuck somewhere or an edge case was encountered. But I don't know the internals that well. @laurent22 should have an idea what's going on.

**Comment by laurent22** [comment] 2019-06-21 06:51
@xthursdayx, do you get this error in the console every time you search? Could you try to clear the console just before you search, just to be sure?

**Comment by xthursdayx** [comment] 2019-06-21 16:03
Strangely enough, no. I've just tried search again and had no problem... I guess that means that the problem was on my end, but I'm not sure what would have changed (I hadn't even quit and restarted Joplin since those previous errors). I've tried quitting and starting again and search seems to be working fine now. Baffling. Should I share my log with you all in case there is any information to be gleaned from it?

**Comment by laurent22** [comment] 2019-06-21 16:09
If you could share your log, especially what happened before that error message that could help.

What happened is that in memory you had an empty item in your list of notes and that caused issues with other functions. So the question is, how an empty note ended up there, and your log might help figure it out.

I'm thinking it could be due to the recent bug with tags - did you use the new Ctrl+Alt+T shortcut to add tags by any chance, or tried to add tags from the menu (not from the toolbar)?

**Comment by xthursdayx** [comment] 2019-06-22 15:59
It's the same log as in the other issue, but I've attached it again here. 
[log.txt](https://github.com/laurent22/joplin/files/3317000/log.txt)

I haven't added any new tags at all, or used the Ctrl+Alt+T shortcut, however, most of the notes I imported did have tags.

**Comment by laurent22** [comment] 2019-06-22 16:19
Thanks for the info @xthursdayx but I didn't find the cause in the log. I'm a bit clueless how the above error could happen but it seems to be a one off so I'm going to close the issue for now. If it happens again or if you figure out a way to replicate it, feel free to comment back here.

**Closed by laurent22** 2019-06-22 16:19 UTC
Labels: bug, desktop, essential

**Comment by xthursdayx** [comment] 2019-06-22 16:54
Sounds good. I'll let you know if it happens again. Thanks.
