### ISSUE TITLE
Alarm not working (Android)

### ISSUE THREAD

**Issue by vinaymve** [laurent22/joplin#8341] opened 2023-06-19 13:51 UTC
## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: 13
Device: Samsung

## Steps to reproduce

1. Create to-do note
2. Set alarm to future time
3. Alarm does not show on mobile
4. Alarm shows on desktop application (macOs) instead, but only sometimes. 

## Describe what you expected to happen

Expected alarm to ring

## Older issues

[#6235](https://github.com/laurent22/joplin/issues/6235)

## Logfile

![log](https://github.com/laurent22/joplin/assets/10580258/9c81f20e-669a-4f14-9f23-17cf9d8f7ae7)

**Comment by laurent22** [comment] 2023-06-19 13:57
That should be fixed in prerelease 2.11

**Comment by JackGruber** [comment] 2023-06-19 14:58
Duplicate of https://github.com/laurent22/joplin/issues/8229

**Closed as completed** 2023-06-19 15:42 UTC
Labels: bug
