### ISSUE TITLE
Goto Anything keyboard shortut is not working well

### ISSUE THREAD

**Issue by steel-steven-87** [laurent22/joplin#5400] opened 2021-08-30 16:38 UTC
When you use Ctrl+P shortcut to open Goto Anything, search and select the matching note, the application often fails to switch to the that note.

## Environment

Joplin version: 2.3.5
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

This has been reproduced on a clean install of Joplin 2.3.5 on Ubuntu with the default sample notes:

1. Hit Ctrl+P, type "importing", then hit Enter.
2. The application switches to note "2. Importing and exporting notes" successfully.
3. Hit Ctrl+P, type "synchronizing", then hit Enter.
4. The note fails to switch to note "3. Synchronizing your notes".
5. (repeat) Hit Ctrl+P, type "synchronizing", then hit Enter.
6. The note switches to note "3. Synchronizing your notes" successfully.

## Describe what you expected to happen
The issue is that when you use the keyboard shortcut Ctrl+P, the command fails around half of the time.

An interesting thing to consider is that this does not happen when you click on menu bar option "Go", then click "Goto Anything...".

Another observation is that when you open the settings and open the keyboard shortcuts, the shortcut Ctrl+P exists but the title of the command is empty.

**Comment by Daeraxa** [comment] 2021-08-30 18:46
I believe this is the same problem, fixed in pre-release
https://github.com/laurent22/joplin/issues/5184
https://github.com/laurent22/joplin/issues/5392
https://github.com/laurent22/joplin/issues/5355
https://github.com/laurent22/joplin/issues/5361

**Comment by tessus** [comment] 2021-08-31 12:21
Duplicate of the issues Daeraxa mentioned.

**Closed by tessus** 2021-08-31 12:21 UTC
Labels: bug
