### ISSUE TITLE
Overlapping "ghost" text in tag list

### ISSUE THREAD

**Issue by yea-hung** [laurent22/joplin#8234] opened 2023-05-23 21:55 UTC
## Environment

Joplin version: 2.10.19
Platform: Linux
OS specifics: Fedora 38

## Steps to reproduce

1. Open software and inspect tag list. See below.
2. The "ghost" text temporarily disappears if I hover the mouse pointer over the text.

![ghost_text](https://github.com/laurent22/joplin/assets/7434605/adee96f5-894f-4d8b-bc6e-9822e8b28f69)

## Describe what you expected to happen

I expect to see the tag list, without any "ghost" text. The text there reads "Joplin."

**Comment by Daeraxa** [comment] 2023-05-23 22:46
Duplicate of https://github.com/laurent22/joplin/issues/7506

**Closed as completed by Daeraxa** 2023-05-23 22:46 UTC
Labels: bug
