### ISSUE TITLE
BUG: Android app cursor position on edit isn’t where clicked

### ISSUE THREAD

**Issue by sylikc** [laurent22/joplin#4216] opened 2020-12-11 03:54 UTC
## Environment

Joplin version:  (latest as of writing) Joplin Android app v1.4.11
Platform:  Android 11
OS specifics: 
Phone: Pixel 4

## Steps to reproduce

Current Behavior: 

1. Press on a Note to open
2. Press the RED edit button on the bottom right side
3. Press to put the cursor at the location that was pressed
4. Cursor moves to end of note

## Describe what you expected to happen

Expected behavior: After clicking on the RED edit button on the bottom right side
After the page moves to the bottom of the note, 

**pressing on a location should have the cursor be moved there, and not sent to the end.**

It would also be _nice to move the screen to center on the location where the cursor last was_ ( [Save cursor position within the note](https://discourse.joplinapp.org/t/save-cursor-position-within-the-note/43) ) instead of all the way to the end

Feature or bug?  I had opened a forum discussion without any replies [Android app cursor position on edit isn’t where clicked](https://discourse.joplinapp.org/t/android-app-cursor-position-on-edit-isnt-where-clicked/11887)

**Comment by axq** [comment] 2020-12-11 12:18
I'd classify this usability issue as a duplicate of https://github.com/laurent22/joplin/issues/2287.

**Comment by sylikc** [comment] 2020-12-11 20:56
hmm, it's similar.  I'd say it's in the same class of usability issue.

Going to the bottom of the note is one thing, but then at the bottom, pressing somewhere doesn't edit where the press happens, which is yet another issue.  

But yeah, the issues aren't the same, but they're closely related.

**Comment by axq** [comment] 2021-01-11 12:59
Not fixed in 1.6.6., editing on Android still very hard to use on long notes.

**Comment by axq** [comment] 2021-02-13 20:25
Not fixed.

**Comment by axq** [comment] 2021-03-20 08:52
Unfixed on 1.7.5

**Comment by roman-r-m** [comment] 2021-03-28 11:27
It's an upstream issue, there are a few reports of this on the RN repo, all are closed with no resolution.
I'll see if I can find a workaround.

**Comment by roman-r-m** [comment] 2021-03-29 09:26
Found an open issue against RN: https://github.com/facebook/react-native/issues/29911

**Closed** 2021-06-08 22:39 UTC
Labels: android, bug, medium, upstream
