### ISSUE TITLE
ALT and CMD + left/right arrows should have the behavior expected on macOS

### ISSUE THREAD

**Issue by juliennicouleaud** [laurent22/joplin#4262] opened 2020-12-29 08:30 UTC
Hi,

I believe this issue is recent (probably since my upgrade to 1.5.11), it was fine before : the ALT or CMD keys used with the left and right arrows should allow to move forward/back a word or move to the beginning or end of a line, which is not the case anymore.

## Environment

Joplin version: Joplin 1.5.11
Platform: Mac
OS specifics: macOS Catalina 10.15.7

## Steps to reproduce

1. Put the cursor in the middle of some text
2. Press ALT and use the left/right arrows to move the cursor : nothing happens
3. Press CMD and use the left/right arrows to move the cursor : the cursor moves back or forward a word

## What should happen

1. Pressing ALT and use the left/right arrows should move the cursor back or forward a word
2. Pressing CMD and use the left/right arrows should move the cursor to the end or the beginning of the line

**Comment by CalebJohn** [comment] 2020-12-29 08:42
Hi @juliennicouleaud 

Thanks for the bug report. I will be closing this because it's a duplicate of #4257 .

**Closed** 2020-12-29 08:42 UTC
Labels: bug
