### ISSUE TITLE
Android filesystem sync is broken

### ISSUE THREAD

**Issue by lighthunt** [laurent22/joplin#7318] opened 2022-11-18 20:58 UTC
I am unable to sync from desktop to android, with the same error described at #5779 and #5673 issues (i.e. "Error Could not upgrade from version 0 to 1: Error : File  '...... /Joplin/.sync/version.txt' does not exist ....")/

Using filesync / syncthing combination

## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: Android 13 (Samsung s22+)

## Steps to reproduce

1. 
2. 
3.

**Comment by wh201906** [comment] 2022-11-19 05:28
You can try the latest pre-release v2.9.8
https://github.com/laurent22/joplin-android/tags
https://github.com/laurent22/joplin-android/releases/tag/android-v2.9.8

**Comment by knsy** [comment] 2022-11-23 22:50
Wanted to leave a note since I didn't stumble on it previously:
After manually updating to v2.9.8 from the links above, I was still getting the same error, but going into Configuration and re-pointing "Directory to synchronize with" to the same directory that was previously used forced it to re-ask for permission, which I granted and that made everything work again. 

Android 13 on Pixel 6 with Syncthing.

Thank you @wh201906 and other contributors for all the hard work you do.

**Comment by Daeraxa** [comment] 2022-11-23 23:01
Duplicate of existing issues, fix is available in pre-release.

**Closed as completed by Daeraxa** 2022-11-23 23:01 UTC
Labels: bug

**Comment by lighthunt** [comment] 2022-12-07 17:08
@wh201906 and @knsy, many thanks both of you for help! I had to clear app data and reconfigure as suggested and it seems to work now.
