### ISSUE TITLE
Doesn't work in Debian Stable (Buster)

### ISSUE THREAD

**Issue by pioruns** [laurent22/joplin#2435] opened 2020-02-03 15:59 UTC
Currently doesn't work in Debian Stable (Buster), AMD64, crashes out completely without showing window or anything.

Error when running from the console:
$ ./Joplin-1.0.179.AppImage 
[26226:0203/155418.747935:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_JoplinNuxCuG/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

No window appears, no nothing, just this error.

**Comment by tessus** [comment] 2020-02-03 21:16
Duplicate of #2246

**Closed by tessus** 2020-02-03 21:16 UTC
