### ISSUE TITLE
Synchronization interval setting not working

### ISSUE THREAD

**Issue by eromawyn** [laurent22/joplin#4661] opened 2021-03-12 16:44 UTC
## Environment

Joplin version: 1.7.11
Platform: Windows 10 
OS specifics: Installed via Chocolatey.

Joplin 1.7.11 (prod, win32)

Client ID: 953ecca7fac54aba8afd0dc18ea281c5
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)

## Steps to reproduce

I am in the process of playing with Joplin to see if I am going to migrate. So I have set-up a poor man’s synchronization (webDAV).

While playing yesterday with API I noticed I had conflicts. For what I did, it was strange, may be I hit an unexpected user case, or a bug, know or unknown, but that’s not the point. So I decided not to disable synchronization, but to set its interval to 24 hours. 
Strangely, I saw a few other synchronization that day... 

So today I investigated more. This time I kept notes of what I did (see after). But basically what happens is whatever the synchronization setting, the synchronization automatically happens every 2 minutes. (or maybe 2 minutes and some seconds).

What I did as Joplin note, (in French but some people might understand) :
- https://trolleur.net/joplin/12_03_2021.jex
- with associated web logs : https://trolleur.net/joplin/joplin.trolleur.net.log

Sometimes, I might have edited other items between 2 synchronization. Strangely one sync showed 8 new items, but I am pretty sure I only added a note and its screenshot to the notebook.

**Comment by CalebJohn** [comment] 2021-03-12 18:57
Duplicate of #4512 

Please see [here](https://github.com/laurent22/joplin/search?q=synchronization+interval&type=issues) for other times this topic has come up.

**Closed by CalebJohn** 2021-03-12 18:57 UTC
