### ISSUE TITLE
Minor: Keep note history days use black text in dark theme

### ISSUE THREAD

**Issue by wjsetzer** [laurent22/joplin#1631] opened 2019-06-06 21:47 UTC
### Operating system

- Android

### Application

- Mobile

In the settings for Keep note history, the text under the slider does not change from black to white when using the dark theme, making it hard to read the number of days.

**Comment by tessus** [comment] 2019-06-07 09:25
duplicate of #1609

**Closed by tessus** 2019-06-07 09:25 UTC
Labels: bug, essential, mobile
