### ISSUE TITLE
[550:0130/173824.874877:FATAL:setuid_sandbox_host.cc(157)]

### ISSUE THREAD

**Issue by Moltkex** [laurent22/joplin#2417] opened 2020-01-30 21:58 UTC
I'm getting the following error when trying to start Joplin-1.0.179.appimage
`/Joplin-1.0.179.appimage 
[2822:0130/175257.386341:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Joplin2ogWiD/chrome-sandbox is owned by root and has mode 4755.
`trap' para punto de parada/seguimiento`
Googling about it I found that this is coming from previous versions https://github.com/laurent22/joplin/issues/2246 and seems like it hasn't been resolved so far. 
This is happening in Debian Buster 10.2 with latest Joplin 1.0.179.appimage.

**Comment by tessus** [comment] 2020-01-30 23:36
Duplicate of #2246

**Closed by tessus** 2020-01-30 23:36 UTC
Labels: bug

**Comment by Moltkex** [comment] 2020-01-31 18:21
@tessus marking duplicate doesn't say anything since the app doesn't work. I was reporting that the issue is still there and it hasn't been solved.

> Duplicate of #2246

**Comment by tessus** [comment] 2020-01-31 23:20
@Moltkex that's why the other issue is still open. I don't get your point. Do you want hundreds of issues open that all describe the same issue?

**Comment by Moltkex** [comment] 2020-02-02 13:54
@tessus Ah, sorry. Yes, you're right. No I don't. Sorry for the trouble and thanks for your time. By the way and I know it's not directly related but at the same time it is, I just experienced this same behaviour with another electron appimage.
