### ISSUE TITLE
iphone x UI not so responsive.

### ISSUE THREAD

**Issue by lanox** [laurent22/joplin#64] opened 2017-12-03 23:04 UTC
### Application

- [x ] Mobile ( iphone x)

When creating new to do in iphone x, buttons are hard to press and not responsive you need to click on specific part of the screen to get input.

Also when creating new to do, when hitting save button screen just goes white and stays white, I have to close the app.

---

**Comment by IamNguele** [comment] 2017-12-04 13:34
Just downloaded the app on iPhone X as well and had the same issue.

**Comment by flipjs** [comment] 2017-12-05 19:36
Its because the iPhone X 'notch' gets in the way. The app needs to add some padding for iPhone X screen. I posted a screenshot on #76

**Comment by laurent22** [comment] 2017-12-05 22:53
Thanks for the screenshots, I need to add some padding around the app for iPhone X support. Thankfully they've recently released a new version of React Native which has a fix for this.

Out of curiosity, if you put the phone on a table, without touching the borders, and try to touch the buttons, does it work any better? Just wondering if it's just because the hand is touching the borders of the app or if there's another bug.

Not sure what's the cause for the white button though.

**Comment by flipjs** [comment] 2017-12-05 23:05
Actually, all the buttons work on Joplin (at least for me). You just have to carefully select the bottom part of it (save icon, back button, hamburger menu button, etc). Or sometimes what I would do is, put my iphone x in landscape mode, then there is nothing in the way. Its just the portrait mode that has issues due to the 'notch'.

You are correct about adding some padding would help here.

**Comment by laurent22** [comment] 2017-12-11 20:15
Hello, I've released another version this weekend that should handle the iPhone X better. Any chance someone could give it a try and confirm if it's better?

**Comment by lanox** [comment] 2017-12-11 21:11
Hi it works as expected, although you have white borders at the bottom and top. 

I am replying on the phone so I can’t upload photo but I will when I get to my work.

**Closed** 2018-01-15 15:31 UTC
Labels: bug
