### ISSUE TITLE
TOC Automatically sorts some Headers in Rendered view

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1843] opened 2019-08-30 21:57 UTC
## Environment

Joplin version: Windows 1.0.165, Android 1.0.281
Platform: Windows, Android
OS specifics: Windows 8.1(.1), Android 9

## Steps To Reproduce

1. Download and import/paste this md test file to Joplin: [test.md.txt](https://github.com/laurent22/joplin/files/3561641/test.md.txt)
2. Change the layout to side-by-side raw & rendered view.

= Rendered view shows these TOC entries/links in incorrect order compared to the raw text:
- Headers with numbers 0-4 and 6-9 are put on top of the TOC, although those headers are located after header "z". (Header "5 test" is not affected, it's in correct place in the TOC.)
- Header with number 0 is put as the first TOC entry, although it's actually after header 9.

Same happens in Android.

Expected behavior: All TOC entries/links in rendered view should be in the order that they are in the raw text.

**Comment by tessus** [comment] 2019-09-02 16:26
We are using a plugin for toc.

Can you please open a ticket with the [markdown-it-toc-done-right](https://github.com/nagaozen/markdown-it-toc-done-right) repo?

**Comment by Perkolator** [comment] 2019-09-02 21:49
Opened the issue in the other repo. Should this be kept open for now, or closed right away?

**Comment by tessus** [comment] 2019-09-02 21:53
We can leave it open for now to track the other issue. As soon as the problem is fixed upstream we will have to update `package.json` in Joplin to use the new release.
Unless you are following the issue upstream and ping us as soon as it fixed, then you can close this issue.

**Comment by Perkolator** [comment] 2019-09-02 21:57
Let this be open. I'm following the issue in the upstream also. I can update this when something happens in the other one.

I'm not sure how this Github works yet, I just started using it; I'm guessing here, if this is left open, would there be an update in this issue when the status of the other referenced issue has been changed?

**Comment by tessus** [comment] 2019-09-02 22:01
Yep, the following (which is between the 2nd and 3rd comment) will show the status:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/223439/64134383-7b1b5000-cdab-11e9-92af-c365f83d9d11.png">

So if the other issue is closed, we can see it.

**Closed** 2019-10-30 10:18 UTC
Labels: bug, upstream
