### ISSUE TITLE
Broken Calendar styling

### ISSUE THREAD

**Issue by AzadKshitij** [laurent22/joplin#4702] opened 2021-03-18 04:15 UTC
![image](https://user-images.githubusercontent.com/54288405/111571826-4f01cd00-879f-11eb-84aa-21c1b5f5e4d5.png)

## Environment
Joplin 1.7.11 (prod, win32)

Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)
Windows 10 Home

## Steps to reproduce

1. Create a Todo
2. Try to set alarm
3. Try to change date and time 

## Describe what you expected to happen

everything should look perfect.

**Comment by roman-r-m** [comment] 2021-03-18 12:06
Duplicate of https://github.com/laurent22/joplin/issues/4397

**Comment by harshitkathuria** [comment] 2021-03-18 14:07
I have submitted a PR for this issue. Should I change the issue number to the original issue my in PR @roman-r-m ?

**Comment by roman-r-m** [comment] 2021-03-18 14:10
> I have submitted a PR for this issue. Should I change the issue number to the original issue my in PR @roman-r-m ?

No, it doesn't matter much

**Comment by harshitkathuria** [comment] 2021-03-18 14:17
Ok....Thanks

**Comment by tessus** [comment] 2021-03-18 21:27
Actually yes, you should change it, otherwise the PR will be closed due to PR guidelines: item 1.

Clossing this since it is a duplicate.

**Closed by tessus** 2021-03-18 21:27 UTC
Labels: bug

**Comment by harshitkathuria** [comment] 2021-03-19 04:32
Thanks, I have updated the issue number to the original issue in my PR.
