### ISSUE TITLE
Problem with using Joplin as a SQL code "cheatsheet"

### ISSUE THREAD

**Issue by kcrossen** [laurent22/joplin#1882] opened 2019-09-19 15:31 UTC
On macOS (1.0.167,  32865f0) enclose the SQL in triple backticks, use the notebook/note on Android (1.0.305, September 10, 2019) (in view mode) select all, copy, then paste into RemoDB, the SQL will execute but all the newlines will have been removed (very hard to read).
```
SELECT TABLE_NAME, 
       CONCAT(CONCAT(TABLE_NAME, ':'), '\n',
              GROUP_CONCAT(COLUMN_NAME, '\t', 
                           TABLE_NAME, '.', COLUMN_NAME, '\t',
                           TABLE_NAME, '.', COLUMN_NAME, ' AS ', TABLE_NAME, '_', COLUMN_NAME, '\t',
                           ' {', COLUMN_TYPE, '}'
                           SEPARATOR '\n')) AS table_columns
FROM
(SELECT COLUMNS.TABLE_SCHEMA AS TABLE_SCHEMA, COLUMNS.TABLE_NAME AS TABLE_NAME, 
        VIEWS.TABLE_NAME AS VIEW_NAME, 
        COLUMN_NAME, DATA_TYPE, COLUMN_TYPE, COLUMN_KEY, EXTRA, 
        CASE WHEN (COLUMNS.TABLE_SCHEMA IN 
                   ('information_schema', 'mysql', 'performance_schema')) THEN 'META' 
             ELSE '' END AS SCHEMA_GROUP 
 FROM information_schema.COLUMNS AS `COLUMNS` 
 LEFT JOIN information_schema.VIEWS AS `VIEWS` 
 ON (COLUMNS.TABLE_SCHEMA = VIEWS.TABLE_SCHEMA) AND 
    (COLUMNS.TABLE_NAME = VIEWS.TABLE_NAME) 
 WHERE (COLUMNS.TABLE_SCHEMA NOT IN ('information_schema', 'mysql', 'performance_schema')) 
 ORDER BY SCHEMA_GROUP, COLUMNS.TABLE_SCHEMA, COLUMNS.TABLE_NAME) AS table_columns
GROUP BY TABLE_NAME;
```
becomes
```
SELECT TABLE_NAME, CONCAT(CONCAT(TABLE_NAME, ':'), '\n', GROUP_CONCAT(COLUMN_NAME, '\t', TABLE_NAME, '.', COLUMN_NAME, '\t', TABLE_NAME, '.', COLUMN_NAME, ' AS ', TABLE_NAME, '_', COLUMN_NAME, '\t',
...etc... arbitrarily wrapped...
```
On the other hand, if in edit mode on Android, I select all, manually exclude the triple backticks from the selection, copy, then the pasted text is fine (as in the top example above).

So apparently I have a choice (as my macOS/Android executables work anyway) between tedious extra work to use the SQL "cheatsheet" or wrong display of code that will copy correctly in edit mode.

Joplin version: 1.0.167,  32865f0 (macOS 10.12.6)
Joplin version: 1.0.305, September 10, 2019 (Android Pie)

![screenshot_191](https://user-images.githubusercontent.com/1951504/65258315-ace12600-dad0-11e9-94e1-688401f5fb16.jpg)
This shows the display problem of both versions on macOS, which is the second alternative mentioned above. If, in the right-hand pane, you select all, copy, the paste buffer will contain exactly what you see, i.e. 2 missing "*" and the backticks removed from "user".

**Comment by kcrossen** [comment] 2019-09-19 15:48
Two possible workarounds (in order of preference):

1. In view mode, if the content is "markdown pure code", i.e. starts and ends w/ triple backticks, select all could exclude the triple backticks from the selection and treat them as "syntactic sugar" (which in this application they are).
2. In view mode, the content being really pure plaintext (no triple backticks), select all could select, not what you see, but the actual underlying plaintext.

Either would work well enough, but the second has the drawback of displaying incorrectly, which will introduce errors by defeating vigilance.

**Comment by foxmask** [comment] 2019-09-19 16:37
the render is still not good even with using the keyword `sql` on the first line of the 3 backsticks?

```verbatim
```sql
... some sql code...
```

**Comment by laurent22** [comment] 2019-09-19 22:31
This is working as expected as far as I can see. If copying from the view doesn't work on Android, indeed do it from the text editor. On the view, it's formatted text which may or may not be handled properly by the app where you paste it.

It's the same if you copy formatted text from your browser.

**Comment by kcrossen** [comment] 2019-09-20 00:05
I'm not understanding how you could write "This is working as expected as far as I can see." after viewing:
![screenshot_191](https://user-images.githubusercontent.com/1951504/65289422-8ba42800-db18-11e9-9d09-aa19bc03e128.jpg)
There needs to be a way to document code for which copying the code itself yields executable code...that is if Joplin is to be useful in this context. Which may not be of interest to you Laurent.

**Comment by kcrossen** [comment] 2019-09-20 00:08
If you copy the right-hand pane above, you do not get the original executable code. If you enclose the code in triple backticks and copy the code from the right-hand pane, you still don't get executable code.

**Comment by kcrossen** [comment] 2019-09-20 00:10
In another thread Laurent, you posted a screenshot using my code sample in the left-hand pane and the right-hand pane in your screenshot did not match my screenshot in the right-hand pane. How do you account for the difference? I'd call that a valid issue.

**Comment by laurent22** [comment] 2019-09-20 01:11
From what i understand it works as expected, but I could be wrong. I'm leaving the thread open in case someone else makes sense of it and wants to contribute.

**Comment by Perkolator** [comment] 2019-09-20 11:28
Maybe posting exact steps-to-reproduce would help? Would make it easier for others to test.

**Comment by kcrossen** [comment] 2019-09-20 14:01
I have already posted exact steps, but again with more detail:
Open a new ordinary note and copy/paste exactly the following code (without the triple backticks):
```
SELECT 
  tool.id, 
  tool.name, 
  user.name,
  CASE user.type
    WHEN /* LURKER */ 0 THEN 'Hidden (0)'
    WHEN /* MEMBER */ 1 THEN 'Member (1)'
    ELSE 'Unknown'
  END AS user_type 
FROM tools.tool AS tool 
JOIN tools.user AS `user` 
ON (tool.user_id = user.id) 
```
On macOS 10.12.6, Joplin 1.0.167, some of the asterisks are removed and the backticks are removed from "user", so the SQL fails when select all/copied directly from note RH pane. To function correctly, I must switch to edit mode (or LH pane) before copying. (See my screenshot below.)

Laurent apparently did this on whatever his hardware/os/joplin version was and got this:
![unnamed](https://user-images.githubusercontent.com/1951504/65328903-64377480-db85-11e9-8c82-fd1d19f7b6b5.png)
which is correct (or at least what he expected). If the content of Laurent's RH pane were select all/copied, I bet it would execute correctly on my server.

By contrast, on my MacBook with macOS 10.12.6, 
```
Joplin for Desktop
Copyright © 2016-2019 Laurent Cozic
Joplin 1.0.167 (prod, darwin)
Revision: 32865f0 (HEAD)
```
I get this:
![screenshot_191](https://user-images.githubusercontent.com/1951504/65329246-1111f180-db86-11e9-860e-3c2546576b14.jpg)
Compare the right-hand panes carefully and you can see that they are not identical.  You can see that in mine some characters are missing as noted above, and select all/copy from right-hand pane errors out on the server. Not believing in gremlins, there must be some code difference between Laurent's execution and mine.

When you select all/copy in the view mode (RH pane on macOS, view mode on Android Pie), there are two possible meanings to the copy:
a) WYSIWYG, which is anyway technically impossible since there is no plain text representation of the box around "user". This does not execute.
b) An exact copy of the *underlying source code*, in other words an identical result as select all/copy from LH pane (edit mode on Pie). This executes correctly, but the code displayed in RH pane (view mode on Pie) looks "broken".

If I want the code to look right, I must enclose the SQL in triple backticks, but then I have to get rid of the triple backticks after each select all/copy and before submitting the SQL to my server. 

A possible solution would be that RH pane select all, upon detecting that triple backticks enclose the selection, could *exclude* the enclosing triple backticks so that the copied SQL would execute correctly. This would be a true WYSIWYG solution because you can't see the triple backticks. 

So currently in the RH pane, select all/copy works differently depending on whether the content is enclosed in triple backticks (exactly copies underlying code, copy is *not* WYSIWYG) or not enclosed in triple backticks (does not copy underlying code, copy *is* WYSIWYG).

You could say this is another (possibly semantic) issue, but it complicates "discoverability" and ultimately usage of Joplin.

**Comment by kcrossen** [comment] 2019-09-20 14:17
And to Laurent, I'm not disputing that it works correctly (as expected by you) on your platform. Only that it does not work correctly (as expected by you) on my two platforms (macOS 10.12.6, Joplin 1.0.167, and on Android Pie 9, One UI 1.1, Joplin 1.0.305). In other words, your screenshot and my screenshot when compared carefully, suggest that there must be some difference in the rendering chain on the two platforms.

Also, I'm claiming that a precise definition of how select all/copy functions in view mode (RH pane) would be very complicated (in other words different depending on whether the content is enclosed in triple backticks or not).

**Comment by Perkolator** [comment] 2019-09-20 17:32
Proper steps to reproduce are like the template suggest, marked with numbers, like this:

1. do this
2. do that
3. etc.

= I also use "=" chars to make notes between or the end of the steps

Back to your "problem"; you failed to notice that in Laurent's example, he indented the code once after pasting it, then it shows like it shows in the right-hand panel correctly.

I also don't understand why you can't use three backticks to enclose the code. If copying from the right-hand "rendered" view, you don't even see or get the backticks when you paste the code somewhere else. And if you copy the code from left-hand "raw" view, you can omit selecting the backticks and again copy&paste will work just fine.

**Comment by kcrossen** [comment] 2019-09-20 18:12
> I also don't understand why you can't use three backticks to enclose the code.

Although you don't see the triple backticks in the RH pane (view mode on mobile), when you select all/copy and then paste into an execution environment, for example a GUI SQL client, then the pasted code is not executable. For macOS GUI SQL clients, e.g. Sequel Pro, this is not such a problem because you have a full keyboard, mouse or trackpad, etc. On an Android tablet, it's a big problem because the UIX on a tablet with the available software is about like building a ship in a bottle.

> you failed to notice that in Laurent's example, he indented the code once after pasting it

Yes, I tried that, but that requires starting each line with a tab, a space won't do. If Joplin had a button that inserted that tab at the beginning of each line, we'd be essentially home free, because the GUI SQL clients pretty much ignore tabs. My task involves many SQL statements, many of them having tens of lines, so manually inserting the tabs would be a daunting, error prone undertaking.

If my application was all restricted to markdown, I also wouldn't "see any problem here", but I work in a superset world that imposes syntactic rules significantly different from markdown. This wouldn't be a problem if, for example, select all/copy from the RH pane (view mode) were absolutely WYSIWYG. In practice, it's not WYSIWYG, because although the triple backticks are invisible, they are copied. As I've said above, I'd be hard put to state an "obvious to an average user" rule that exactly and accurately described how select/copy worked in the RH pane. Without triple backticks, RH pane select **is** WYSIWYG, with triple backticks, RH pane select **is not** WYSIWYG. In these two cases, the select/copy of invisible (formatting) characters is different.

**Comment by kcrossen** [comment] 2019-09-20 18:25
Select all/copy handles invisible characters in this situation (accurately described as WYSIWYG):
![raw_screenshot_193](https://user-images.githubusercontent.com/1951504/65349728-24d34d00-dbb2-11e9-8c59-4690aa3be009.jpg)
differently from this situation (**not** accurately described as WYSIWYG):
![backticked_screenshot_192](https://user-images.githubusercontent.com/1951504/65349760-3583c300-dbb2-11e9-8f07-a6580d6d075c.jpg)

**Comment by kcrossen** [comment] 2019-09-20 18:47
I'm trying to produce, for fairly complex database operations, "executable documentation", something that doesn't currently exist. It just barely exists for Python, C++, js, etc. in the form of code-embedded documentation, but those tools won't work for SQL.

I've tried several other cross-platform "notebook" applications, and they uniformly fail because of security concerns (database operations is extravagantly security-conscious, in theory at least). Joplin is quite obviously the best fit for an application domain that clearly needs a solution.

But if Laurent is not interested in extending Joplin into that domain, or doesn't see this is as a worthwhile application for Joplin, then this thread is clearly a waste of everyone's time.

**Comment by kcrossen** [comment] 2019-09-20 20:05
Real world example: 

Credit unions often invest their assets in local residential mortgages for member employees and their families. This isn't theoretical or big biz, this is your parents, your wife's sister, your newly-wed kid, and so on.

Because mortgage applications contain sensitive data, security is a huge concern and even the operational procedures for this data are considered sensitive.

Ideally, you'd automate all of these operational procedures, but there's no qualified staff, so you use a "playbook", a very complicated "playbook". Each "page" describes a process, for example eliminating duplicate records. Since missing records are a disaster and duplicates are merely painful, the processes tend to err heavily on the side of duplicates. The procedure to eliminate duplicates consists of many complicated steps (in the end, a series of complicated SQL queries).

The ideal "playbook" would be "active". It would require the user to fill in key data, sanity check that data, and eventually execute that step. And so on for each step. The "playbook" itself would be encrypted at rest, communicate via a VPN, etc. We're a long way from that, but if nobody starts somewhere, it will never happen.

That's an example of the application and it has to be open source to even be within practical consideration.

**Comment by Perkolator** [comment] 2019-09-20 21:27
> Although you don't see the triple backticks in the RH pane (view mode on mobile), when you select all/copy and then paste into an execution environment, for example a GUI SQL client, then the pasted code is not executable.

In your first post you wrote that it is executable.. now it's not? And what do you expect from a **rendered** view? If you copy text from office doc, the styles come with, same here. I was perfectly able to copy+"paste as plain text" the SQL code in Android. Ctrl+Shift+V on desktop.

And are you really doing some SQL/other? work with a phone or a tablet? Dude, get a laptop. :) Personally I'd never do anything harder than reading and very light editing of notes on a mobile device, it's just not cut out for proper working.

> but that requires starting each line with a tab, a space won't do. If Joplin had a button that inserted that tab at the beginning of each line

Copy+paste, select text lines, press tab once.

* * *

**Is your issue a bug report (Joplin behaves not as intended) or a feature request?** If it's a feature request, you need to post your request to the [discussion forum](https://discourse.joplinapp.org/) first, then you might get an approval to post it to github repo as a feature request.

I still don't see any problem/bug here. And I fail to see what you want Joplin to do actually. Others might understand better. :)

P.S. Try to avoid posting many wall of text messages, it's gets harder to try to help you, especially for Laurent that has lots of other things to take care of. Short as possible and to the point is magic. ;)

**Comment by kcrossen** [comment] 2019-09-20 21:55
I'm a bit surprised that you don't regard the different behavior of select/copy depending upon the content of the selection as a bug. Depending on the selection content, the copy operation will either be WYSIWYG or not. Examples above.

And I think I've been very clear that Joplin should always select/copy WYSIWYG, if only because that's the easiest to explain, and for the user to predict, i..e. discoverable.

> And are you really doing some SQL/other? work with a phone or a tablet? Dude, get a laptop. :) Personally I'd never do anything harder than reading and very light editing of notes on a mobile device, it's just not cut out for proper working.

As to this, laptop and desktop sales are in decline, in my area management is equipping techs with tablets. That's the future, like it or not. 

On phones, we agree.

Ken

**Comment by Perkolator** [comment] 2019-09-20 22:06
> I'm a bit surprised that you don't regard the different behavior of select/copy depending upon the content of the selection as a bug.

Of course I'm not seeing it as a bug, the program works as intended as far as I understand. The raw/edit view is just plaintext, and the rendered view is well, rendered view. These are two different views to the notes, and they behave differently.

> And I think I've been very clear that Joplin should always select/copy WYSIWYG, if only because that's the easiest to explain, and for the user to predict, i..e. discoverable.

That is not a bug, it's feature request and should be posted first to the discussion forum.

> As to this, laptop and desktop sales are in decline, in my area management is equipping techs with tablets. That's the future, like it or not.

I don't want to be a part of that future. Proper tools for employees, not some hipster tools to look good. ;)

**Comment by laurent22** [comment] 2019-09-21 11:11
I'm going to close this for now as the bug tracker is normally not the place for extended discussions.

@kcrossen:

- If there's a bug, please create a new issue and follow the template. Please limit your post to 100 words or so. If it takes more words, it's a good indication it's not a bug but a feature request.

- If it's a feature request you'd like to discuss, please open a topic on the forum.

**Closed by laurent22** 2019-09-21 11:11 UTC
