### ISSUE TITLE
[request] Synchronise notenbooks to/from different locations. 

### ISSUE THREAD

**Issue by lndr** [laurent22/joplin#297] opened 2018-03-14 13:25 UTC
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [x] Terminal

This maybe beyond the scope of the project because as of now all notebooks are stored in one database. It would however be nice to be able to synchronise notebooks to and from different locations, e.g. different folders on a network storage. Basically convert the synchronization target from a global setting to a per-notebook setting.

**Comment by laurent22** [comment] 2018-03-14 23:36
Duplicate of #74

**Closed by laurent22** 2018-03-14 23:36 UTC
