### ISSUE TITLE
Customize save interval or make it manual

### ISSUE THREAD

**Issue by shuhaowu** [laurent22/joplin#335] opened 2018-03-27 04:17 UTC
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Is it possible to sync less often or make it manual? The reason is that my system will create history based on every file write, and this is creating an excess amount of history. It would be nice to be able to either manually control this or make it less frequent.

This will also avoid having the visual distraction on the left pane where the synchronization status is displayed.

**Comment by laurent22** [comment] 2018-03-27 13:32
Duplicate of #310

**Closed by laurent22** 2018-03-27 13:32 UTC
