### ISSUE TITLE
Error Rendering Markup

### ISSUE THREAD

**Issue by MHoeller** [laurent22/joplin#3772] opened 2020-09-19 10:40 UTC
The rendering a horizontal line in an quote can create false rendering 
Pls. see steps to  reproduce

## Environment
Joplin for Desktop
Joplin 1.1.3 (Ubuntu 20.04 LTS)

## Steps to reproduce
1.  insert code
```
> ---
>  **_<span style="color:green">NOTE</span>_**    
>   The_note_content
```
this renders ok:
![grafik](https://user-images.githubusercontent.com/11714953/93664985-2bb9c780-fa73-11ea-87e6-409f6135bc4b.png)

2. add a next line with a horizontal line, you may add text or not
```
> ---
>  **_<span style="color:green">NOTE</span>_**    
>   The_note_content
>  
```
![grafik](https://user-images.githubusercontent.com/11714953/93665174-afc07f00-fa74-11ea-991f-1fba02d5fa7a.png)

this renders incorrect, the full text seems to be in h2
seems that the hr is incorrect replaced
![grafik](https://user-images.githubusercontent.com/11714953/93665221-15147000-fa75-11ea-8d0a-bee155458a83.png)

when I put the hr UNDER the quote it works 
![grafik](https://user-images.githubusercontent.com/11714953/93665242-34ab9880-fa75-11ea-8499-354dc7f50f56.png)

## Describe what you expected to happen
I would have expected to see unchanged text in the quote block

**Comment by laurent22** [comment] 2020-09-19 13:48
Please post the actual Markdown you used to create this bug. If I copy and paste what you've provided it works as expected.

**Comment by MHoeller** [comment] 2020-09-19 20:36
I can narrow it down

when I write "sdf" an empty line and then -- I get this result which looks ok
![grafik](https://user-images.githubusercontent.com/11714953/93688656-8f6de000-fac7-11ea-9d3a-bee0f8f48095.png)

when I do the same WITHOUT an empty line : "sdf" followed with -- in the next line then right after the second "-" the text rendering is changed
![grafik](https://user-images.githubusercontent.com/11714953/93688662-9a287500-fac7-11ea-975a-a0b6ecb90cde.png)

The  quotes just make it a little more irritating
```
> ---
> sdf
> ---
```
![grafik](https://user-images.githubusercontent.com/11714953/93688718-1e7af800-fac8-11ea-8e05-8510cfd07c3c.png)

You can work around it this way: add a new line by hitting enter after "sdf" and you get this:
![grafik](https://user-images.githubusercontent.com/11714953/93688761-92b59b80-fac8-11ea-872b-046b4826f818.png)

**Comment by CalebJohn** [comment] 2020-09-19 23:57
@MHoeller this is actually part of the [markdown standard](https://daringfireball.net/projects/markdown/syntax#header), but I appreciate how it can seem like a bug when you're not expecting it.

I'm going to close this because it's not a bug, just unexpected behavior.

**Closed by CalebJohn** 2020-09-19 23:57 UTC
Labels: bug
