### ISSUE TITLE
Error during synchronization on PC/Windows 11 and android version 

### ISSUE THREAD

**Issue by Jonathanlion** [laurent22/joplin#8174] opened 2023-05-12 13:56 UTC
## Error

`Completed: 12/05/2023 15:51 (24s)
Last error: Error: Error 502 Bad Gateway: <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.18.0 (Ubuntu)</center> </body> </html>`

## Environment
Joplin version: Joplin 2.10.18 (prod, win32)
Platform: Deskptop and Android device
OS specifics: Windows 11 Home (22H2, 22621.1702), Android 8.0.0

## Steps to reproduce
1. Update Joplin on Windows 11 Home or android 8 to latest version
2. Launch Joplin application
3. Press "Synchronise"
4. Error

## Describe what you expected to happen
On Windows 11 and android device - With latest updates. Error during synchronization:

`Completed: 12/05/2023 15:51 (24s)
Last error: Error: Error 502 Bad Gateway: <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.18.0 (Ubuntu)</center> </body> </html>`

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/11464759/log.txt)

**Comment by laurent22** [comment] 2023-05-12 15:56
Duplicate of https://github.com/laurent22/joplin/issues/8174

Again sorry about this, the maintenance time should have been much shorter (usually nobody notices) but there was a minor issue which is now fixed

**Closed as completed** 2023-05-12 15:56 UTC
Labels: bug
