### ISSUE TITLE
reordering to do items

### ISSUE THREAD

**Issue by smokinjo** [laurent22/joplin#140] opened 2018-01-06 18:37 UTC
### Operating system

- [ ] Windows
- [ ] macOS
- [ X] Linux  Ubuntu 16.04
- [X ] Android
- [ ] iOS

### Application

- [ X] Desktop
- [X ] Mobile
- [ ] Terminal

I tried re-ordering the items but you can not move them by touch and drag or click and drag.  Is thsi feature not implemented yet?  Maybe I am doing it incorrectly.

I did figure out how to put an item on the top of the list,. by accident.   You mark the item as done (check the box), and then un-check it.  It goes to the top.

THanks for th efeed back.

Joseph

**Comment by smokinjo** [comment] 2018-01-17 02:34
I just wanted to check in again to see if there is anyt comment on my issue?

Thanks

joe

**Comment by smokinjo** [comment] 2018-01-20 04:15
Hello again.

Can items be reordered?  Beside my deleting and restoring them?

I tried on Ubuntu and Android.

Thanks

JOseph

**Comment by laurent22** [comment] 2018-01-20 11:45
Hello, currently items cannot be manually ordered, but that might be implemented at some point.

**Comment by smokinjo** [comment] 2018-01-20 12:17
Hello,
OK, that is why I was unable to reorder them:)

Definitely add this to the feature request list.

This is important as items on list change priority level from time to time and order is how I place them in priority.

Thanks

Joseph

**Comment by quimmontal** [comment] 2018-01-26 11:58
Duplicate of #51

**Closed** 2018-01-26 11:59 UTC
