### ISSUE TITLE
Request: (optionally) disable resizing images

### ISSUE THREAD

**Issue by brenthuisman** [laurent22/joplin#1035] opened 2018-12-12 09:50 UTC
### Operating system

- Windows
- Linux

### Application

- Desktop

When I add an image it is resized (scaled down to 1920px width). I verified that exporting it indeed does not export the original image. What's funny is that the resized image (.png) is four times larger in the export, while lost resolution. It also looks like it has jpg artifacts, even though import and export fileformats are png.

Could it be a setting that images are not resized? In fact, I even think it should be the default, because it's surprising you will by default lose information you put in.

**Comment by laurent22** [comment] 2018-12-12 10:18
I don't fully understand what the issue is?

> When I add an image it is resized (scaled down to 1920px width)

So it means it was scaled down?

> What's funny is that the resized image (.png) is four times larger in the export, while lost resolution.

Or it was scaled up?

Normally images are indeed resized if they are too large since very large images could crash some of the apps, in particular in mobile. However, small images should not be scaled up. If you could clarify what the issue is as I'm not sure it's a bug.

**Comment by brenthuisman** [comment] 2018-12-12 10:30
Scaled down. Four times the filesize. Sorry for the lack of clarity there.

**Comment by daniellandau** [comment] 2019-01-20 20:19
The compression on PNGs and JPGs works very differently and even though the resolution would be smaller, the same image content can be way larger as JPG. If some intermediate step encodes JPG and that then gets put back in to PNG that might cause file size to go up.

**Comment by tsumare** [comment] 2019-02-28 01:44
#1232 is related.

**Comment by justyns** [comment] 2019-03-18 04:44
> Normally images are indeed resized if they are too large since very large images could crash some of the apps, in particular in mobile. 

Instead of resizing the image and losing the original, would it be possible to create a smaller image to show in the note and then have it link to the original untouched image?

**Comment by brenthuisman** [comment] 2019-03-19 11:05
A good-ol' thumbnail+original seems to be the solution to this problem indeed.

**Comment by tsumare** [comment] 2019-09-26 23:06
Keeping attached files in their original form is still necessary.

**Comment by justyns** [comment] 2019-12-27 05:02
This is still important to me

**Comment by laurent22** [comment] 2020-02-04 10:59
Duplicate of #1232

**Closed by laurent22** 2020-02-04 10:59 UTC
