### ISSUE TITLE
Overlapping text in sidebar

### ISSUE THREAD

**Issue by AFwcxx** [laurent22/joplin#7905] opened 2023-03-11 14:12 UTC
Here how it looks like:

![image](https://user-images.githubusercontent.com/7138726/224489334-db325283-071a-452c-9343-e223f4cac642.png)

## Environment

Joplin version: 2.9.17
Platform: Linux
OS specifics: Fedora

## Steps to reproduce

1. Setting -> Accessibility -> Large Text -> On
2. Refer to snapshot below

![image](https://user-images.githubusercontent.com/7138726/224489396-7144aa25-fd0a-47b7-a021-d4c0edaabd6d.png)

## Describe what you expected to happen

If I switch Off the `Large Text` setting, it goes back to normal. But everything will be too small for my eyes to read. So I need that feature On.

**Comment by Daeraxa** [comment] 2023-03-11 15:47
Duplicate of https://github.com/laurent22/joplin/issues/7506 and fixed in https://github.com/laurent22/joplin/pull/7897

**Closed as completed by Daeraxa** 2023-03-11 15:47 UTC
Labels: bug
