### ISSUE TITLE
[Feature Request] Multiple synchronization targets

### ISSUE THREAD

**Issue by clarenze666** [laurent22/joplin#1293] opened 2019-03-03 15:08 UTC
It would be great if would be possible to configure multiple synchronization targets. This way you could share notebooks between several persons. 

Let's assume this is your notebook hierarchy:
    my_Root
    |--my_Sub1
    |--my_Sub2
    |--my_Sub3

Notebook my_Sub1 is synced to S:\shared_notebook
The root node (including all subnotebooks except my_Sub1) would be synced to H:\my_notebook

My wife would have her own scructure:
    her_Root
    |--her_Sub1
    |--her_Sub2
    |--her_Sub3

her_Sub1 would be identical to my_Sub1, as she also syncs it to the same directory on the same share (S:\shared_notebook).

On Android you could get the same with FolderSync.

**Comment by foxmask** [comment] 2019-06-19 12:22
honestly I think it's a "good way" to loose his mind that sharing the same joplin instance between users and could lead to mistakes.

**Comment by jumpinjackjones** [comment] 2019-07-12 00:02
Oh yes please this would be a great feature! And one I was just trying to get working, I had assumed Joplin would already support it.

I'd really like to have my own private notebooks and then share a single notebook with my wife.

Keep up the great work with Joplin - it really is brilliant.

**Comment by heseber** [comment] 2019-09-26 12:42
I would like to use one synchronization target for business related data (MS OneDrive - business login) and one for private data (MS OneDrive - private account). It would be great if this were possible. Thanks for your helpful work!

**Comment by internalfx** [comment] 2019-11-18 23:28
+1

**Comment by ZWonGit** [comment] 2019-12-04 10:20
+1

I am using several notebooks: My Personal, Family, Club, Work Team, Work Projects some of them are located by different provider or using other platforms (OneDrive, NextCloud, SharePoint, File Share). I do this with KeePass too with the AutoOpen plugin that opens multiple databases as a separate tab with different colors. Currently OneNote for Desktop can do this for me in a single application instance.

**Comment by jovandeginste** [comment] 2019-12-22 10:44
Just coming to say the same thing: I have a Personal and Work notebook. I would like to share a notebook with my wife for eg. todo lists (especially useful now, during the holidays :wink:)

Also for work, I have "private" work items (think HR) on the one hand, and "document as I go" draft documentation on the other hand which might be useful to share with some co-workers.

I don't mind the different sync targets to be top level Notebooks (or even an extra layer above that). I don't expect sub-notebooks to be configurable...

**Comment by foxmask** [comment] 2019-12-22 12:28
I think the GSoC will cover this https://joplinapp.org/gsoc2020/

**Comment by internalfx** [comment] 2020-03-21 14:14
This is still a thing....

**Comment by internalfx** [comment] 2020-05-05 15:09
This is still a thing....

**Comment by heseber** [comment] 2020-05-05 16:28
Absolutely, I still need this to separate business and private notes on different storage systems.

**Comment by ldavis2020** [comment] 2020-05-06 16:56
Yes please, I definitely would like this and make great use of it. For me it is all about separating work and private notes.

Joplin is amazing software by the way, I absolutely love it.

**Comment by NerdsvilleCEO** [comment] 2020-05-08 03:05
Are there any plans to add this? I have a workaround which involves using a private git repo and publishing to different repos from there... but if this is something that Joplin should support I can volunteer to implement it @laurent22  thoughts?

**Comment by ldavis2020** [comment] 2020-05-11 17:24
> 
> 
> Are there any plans to add this? I have a workaround which involves using a private git repo and publishing to different repos from there... but if this is something that Joplin should support I can volunteer to implement it @laurent22 thoughts?

I'd be curious to know how you have this working. As perhaps that would work for me as an interim solution.

Ideally I'd like something that worked with my usual Sync target (Webdav / Nextcloud)

**Comment by alexj-m** [comment] 2020-06-25 10:36
Just a bump to keep this issue active as it is still really important for me.

**Comment by scholi** [comment] 2020-07-06 18:50
Also interested on this feature. Multiple sync or use two instance of joplin with 2 different config would also be fine for me

**Comment by colleym** [comment] 2020-07-21 09:14
+1

**Comment by frankhommers** [comment] 2020-08-03 08:11
Also important for me.

**Comment by jebbster88** [comment] 2020-09-02 09:05
This is still a requirement

**Comment by azurefreecovid** [comment] 2020-09-02 19:07
Oh yes definitely still a requirement for me.

**Comment by ZWonGit** [comment] 2020-09-02 19:28
as long it is not fixed joplin is no option for me

**Comment by rangulicon** [comment] 2020-09-07 03:53
Agreed this should be a thing. Work vs Personal is probably the biggest use case, but there are more than those two for sure. I think the easiest way would be to connect Joplin to multiple Cloud locations for sync and then assign a notebook to a connected Cloud location. Due to the nature of networks and cloud storage syncing a notebook should be one to one, not one to multiple cloud targets. More flexibility could be offered if there were a Joplin server/node that handled the syncing tasks.

**Comment by nokoa77** [comment] 2020-09-12 07:31
Very useful feature for use case « Work + Personal + Shared with significant other » !

**Comment by heseber** [comment] 2020-10-12 09:11
Still needed.

**Comment by laurent22** [comment] 2020-10-12 13:17
Duplicate of https://github.com/laurent22/joplin/issues/591

**Closed by laurent22** 2020-10-12 13:17 UTC

**Comment by Shahin-rmz** [comment] 2021-10-31 07:56
Joplin has monetized this feature.
I'm not sure if Joplin is able to add this feature for community version.

**Comment by Daeraxa** [comment] 2021-10-31 21:54
> Joplin has monetized this feature. I'm not sure if Joplin is able to add this feature for community version.

This isn't true. To start with there is only one version of Joplin, there is no 'community version'. What you refer to is probably 'joplin cloud' which is literally just a brand name for a hosted joplin server with exactly the same features as normal joplin server you can choose to self host.

**Comment by Shahin-rmz** [comment] 2021-11-01 09:03
well, first of all, monetization isn't bad. They spent time on developing and they deserve it.
then, I said you can have multiple versions of Joplin (for work and private) which is true!
I know that joplin cloud and joplin has same features.

**Comment by miromarszal** [comment] 2023-02-15 15:02
> Duplicate of #591

I must disagree with marking this as a duplicate of that issue. The discussion in #591 revolves mostly around having multiple instances and profiles, which solves different use cases, such as completely separating work and private collections, etc. Multiple sync targets would allow me to have shared notebooks alongside my private collection in the same profile. Shared notebooks would point to different WebDAV directories, where other people have access. For me this would be the most useful way to share.

**Comment by t-makaro** [comment] 2026-09-01 03:02
I agree that this is not a duplicate of #591. I'd like to configure multiple sync targets (each with their own encryption key) within one profile, and then choose which sync target to use per-notebook. This would allow notebook sharing without the need to setup an additional server beyond my existing webdav server. I'm ok with a little each setup to pre-share a key if it means having to manage fewer services.
