### ISSUE TITLE
Photos when captured from camera are not added to the note in joplin notepad. 

### ISSUE THREAD

**Issue by earlpayton** [laurent22/joplin#258] opened 2018-02-25 14:03 UTC
#### Expected behavior

A photo when captured from the camera should be added to the note just as the image is added when adding from the option select a file.
#### Actual behavior

Joplin isn't able to add an image captured from the camera directly.

#### How to reproduce

Open the app. Click on new note. Click on the options menu. Click on attach photo. Now click on take photo to click a picture from your camera. Now add the image you just captured. The image won't be added.

   +  App: Joplin Notepad v1. 0.101
   + Operating system: Android Nought
   + Device: Motorola Moto g5 plus.

#### Recording Of The Bug
![rflajyeqld8p6godtpiv.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519225060/l2vhxilmb3upooijohlj.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@earlpayton/app-crashes-when-we-try-to-launch-it">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by laurent22** [comment] 2018-03-07 17:41
Thanks for the bug report. The issue to track this is #177

**Comment by laurent22** [comment] 2018-03-07 17:42
Duplicate of #177

**Closed by laurent22** 2018-03-07 17:42 UTC
