### ISSUE TITLE
WebDAV: Access denied: Please check username and password (401)

### ISSUE THREAD

**Issue by electricar** [laurent22/joplin#9350] opened 2023-11-20 07:29 UTC
### Operating system

Windows

### Joplin version

2.12.19

### Desktop version info

Joplin 2.12.19 (prod, win32)

Client ID: f27fa977675547f993723978f4bcd126
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: 7081046

Rich Markdown: 0.10.0

### Current behaviour

1. Open Joplin
2. Click on "Synchronise"
3. Get sync error (first image)
4. Check synchronisation configurarion in the settings and get error (second image)

![joplin2](https://github.com/laurent22/joplin/assets/16311580/1b00a949-f45a-4ec9-a7c1-d6ce40433ff2)

![joplin](https://github.com/laurent22/joplin/assets/16311580/c26e2af9-f002-4880-adef-8a1d254ba1f6)

### Expected behaviour

Sync without errors with this WebDAV server as it doing on a Linux Mint PC and an Android Smartphone.

**Comment by laurent22** [comment] 2023-11-20 14:32
When it says "check your username and password", pretty much every time it's indeed an incorrect username or password.

**Comment by electricar** [comment] 2023-11-20 14:39
Unfortuntely this is not the case. I am copying both from my password manager and can also log in onto my Synology WebDAV server with these credentials.
The same are also used on my Linux Mint PC and my Android Smartphone.

**Comment by alexmbird** [comment] 2023-12-03 11:40
I can confirm the same behaviour on OSX:

- Joplin 2.12.19 (prod, darwin)
- WebDAV on nginx/1.22.1
- Basic auth with ngx_http_access_module
- Tested credentials by connecting from my browser, they work fine

**Comment by electricar** [comment] 2024-01-02 16:12
The issue still persists for me.

**Comment by HeisenbergK** [comment] 2024-01-18 15:24
I am still having this issue as well on my personal Nextcloud with Joplin on Mac.

**Comment by laurent22** [comment] 2024-01-18 17:17
Hello, as there's not enough information to investigate this particular I'm closing it as a duplicate of that one (which has more info): https://github.com/laurent22/joplin/issues/6005

If you want to add more details please do so in the other issue

**Closed as completed by laurent22** 2024-01-18 17:17 UTC
Labels: bug

**Comment by ghost** [comment] 2024-01-23 09:38
I have the same exact issue with mailbox.org and their webdav server. Joplin does not get access to the drive. In windows and android file explorer  I use the exact same wedav url, username and password, and I have access to my online drive. Only Joplin has problems.

**Comment by pranaypise59** [comment] 2025-07-06 08:48
Please share the solution. I'm frustrated with spending time on this minor issue.

**Comment by falaca** [comment] 2025-11-07 03:50
Got here from Google, so I am sharing my solution in case it helps others:

I was having this same problem with my setup, using an Apache web server with which Zotero sync has been working perfectly fine. But Joplin was giving me the same 401 error as the original bug report here. In my case, it turned out that my server was set up for Digest authentication, which Joplin doesn't support. After changing my Apache config to Basic authentication instead, it now works.

**Comment by okingfisher** [comment] 2026-02-20 09:34
Hi there, same problem. If this is an issue of authentication, I believe it should be flagged as a bug of high priority.
