### ISSUE TITLE
Android Client cannot use filesystem for syncing

### ISSUE THREAD

**Issue by valmar** [laurent22/joplin#162] opened 2018-01-12 15:42 UTC
The Android client cannot use the file system for syncing. Only the OneDrive option is available. 

If the app would be able to save the files in a folder in the internal storage or on the sd card, a non-OneDrive one could use other solutions (like FolderSync) to sync the notes.

Thank you so much for the great app, however!

Valerio

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

**Comment by laurent22** [comment] 2018-01-12 16:53
Duplicate of #61

**Closed by laurent22** 2018-01-12 16:53 UTC
