### ISSUE TITLE
Bad Table rendering with multitable 

### ISSUE THREAD

**Issue by antoniopaolini** [laurent22/joplin#2352] opened 2020-01-23 15:49 UTC
The table rendering is broken.
I upgraded from Joplin 1.0.175 to 1.0.178.

In my previous version (1.0.175) the multitable plugin allow to span cell over row, like this:
![controllo-capture_001_23012020_163329](https://user-images.githubusercontent.com/60228211/72998461-2762df00-3dfe-11ea-9f1b-3f260944be52.png)

In the 1.0.178 version the rendering is completely different, as in the next picture:
![controllo-capture_002_23012020_164024](https://user-images.githubusercontent.com/60228211/72998677-8b85a300-3dfe-11ea-8ce6-d8e110ddfaac.png)

## Environment

Joplin version: 1.0.178
Platform: Windows
OS specifcs: Windows 10 Pro version 1803

## Steps To Reproduce

1. Insert table as in the  picture.
For your convenience I put the example here: [https://raw.githubusercontent.com/antoniopaolini/file_vari/master/esempio_tabelle.md](https://raw.githubusercontent.com/antoniopaolini/file_vari/master/esempio_tabelle.md)

**Comment by laurent22** [comment] 2020-01-23 15:53
Duplicate of #2345

**Closed by laurent22** 2020-01-23 15:53 UTC
