### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [laurent22/joplin#694] opened 2018-07-24 03:18 UTC
Greetings @laurent22 ,

Sorry for not having the template regarding this issue. I would like to ask for your permission to propose designs for your logo/icon for your project. Your project seems so interesting and I would like to help the project through this issue. Hoping for your response and good luck to your project.
Thank you!

Best Regards,
-jbeguna04

**Comment by tessus** [comment] 2018-07-24 21:49
Duplicate of #307

**Closed** 2018-07-25 08:59 UTC
