### ISSUE TITLE
JEX export corrupts notes on Joplin for Android

### ISSUE THREAD

**Issue by mrjo118** [laurent22/joplin#9069] opened 2023-10-16 02:11 UTC
I've just corrupted my entire note collection (includes a good few hundred notes migrated from Evernote) after making the mistake of relying only on JEX backups and starting a fresh profile on Joplin based on the JEX import. Unfortunately all my backups were made using the Android app and I had only tested the JEX backup of the desktop app for initially deciding to migrate to Joplin and I didn't keep those backups. Doing a file search there's over 4000 hits which I now need to manually replace the characters with by making my best guess what they originally were.

The issue is that JEX backups on the Android app do not correctly store non standard characters and simply replace them with the ? character.

## Environment

Joplin version: 2.12.2
Platform: Android
OS specifics: Using Android 10

## Steps to reproduce

1. On a blank profile, create a new note which includes pound signs (£) and foreign characters such as é
2. Use the export JEX file facility on the Android app
3. Inspect the contents of the JEX file. Non standard characters and some symbols (and white-space characters) such as pound sounds have been replaced with the ? character

## Describe what you expected to happen

Non standard characters should be retained in their original form, as is the case with the desktop app on Windows

## Logfile

N/A

**Comment by personalizedrefrigerator** [comment] 2023-10-16 12:58
I can confirm this.

This seems to only affect JEX exports made on Android, however — unicode characters in iOS exports work as expected. As such, I suspect it's related to how we're using [React Native FS](https://github.com/laurent22/joplin/blob/6668a52478382a49102f368a1f1ef7bfbbc4b897/packages/app-mobile/utils/fs-driver-rn.ts#L300) (the `tar-stream` library is JavaScript, so *should* behave the same way on both platforms).

**Comment by personalizedrefrigerator** [comment] 2023-10-16 20:53
This seems to be an issue with `RNFetchBlob.fs.writeFile` when given a `utf-8` encoding.

For example,
```ts
const originalText = 'Test. 🕳️';
await fsDriver.writeFile(filePath, originalText, 'utf-8');
```
results in
```
Test. ???
```
written to `filePath`.

Here's where we're using `RNFetchBlob.fs.writeFile`:
https://github.com/laurent22/joplin/blob/cfb1f11956723910ca93dce82cf7ab7b08a54d2b/packages/app-mobile/utils/fs-driver-rn.ts#L41

Interestingly, I'm not seeing this issue reported upstream in `RNFetchBlob` ([search results and query](https://github.com/joltup/rn-fetch-blob/issues?q=writeFile+android+%3F)) or [in its possibly more-up-to-date fork](https://github.com/RonRadtke/react-native-blob-util/issues).

We should be able to work around this by base64-encoding utf-8 data before sending to `RNFetchBlob.fs.writeFile`.

Work on a fix for this (that needs to be cleaned up) can be found here https://github.com/personalizedrefrigerator/joplin/tree/pr/fix-tar-create

**Closed as completed** 2023-10-22 10:51 UTC
Labels: bug, mobile, high

**Comment by mrjo118** [comment] 2023-11-12 16:19
Thanks for the quick fix on this. I have since managed to correct all my notes. Just wondering what will determine when this code fix will be released to the Play store?

**Comment by mrjo118** [comment] 2023-11-16 10:03
Also, the Android changelog page seems to be broken:
https://joplinapp.org/changelog_android/
