### ISSUE TITLE
[Feature Request] Manual sort of Notebooks in left sidebar

### ISSUE THREAD

**Issue by HelmutL** [laurent22/joplin#487] opened 2018-05-04 07:54 UTC
### Operating system

- Windows

### Application

- Desktop

I would like to have the possibility to arrange the order of the notebooks in the left sidebar. E.g. I could shift the most used/most important to the top and the less interesting to the bottom

**Comment by foxmask** [comment] 2018-05-04 08:36
how do you consider the most/less interesting ? from the number of existing notes in the notebook ? from the most view time of the notebook ?

On my side, when a notebook becomes less interesting, I drop it and move its notes somewhere else where the notes could find another life :)

**Comment by HelmutL** [comment] 2018-05-04 08:58
It should not be an automatic ordering.

I have notebooks where I collect information that I do not want to loose
but which I do need only infrequently. At the moment, the order of the
notebooks is an arbitrary one.

I want to have the possibility to move those notebooks down (or the ones
used more often up) so that I do not need scroll down the whole sidebar
to find the notebook i swish (this might be the last one created, but
needed often for a certain period of time).

**Comment by laurent22** [comment] 2018-05-04 16:10
Duplicate of #206

**Closed by laurent22** 2018-05-04 16:10 UTC
