### ISSUE TITLE
Android editor does not open at the right position

### ISSUE THREAD

**Issue by Philipp91** [laurent22/joplin#4851] opened 2021-04-16 18:28 UTC
## Environment

Joplin version: 1.7.5
Platform: Android 10

## Steps to reproduce

1. Open a note, scroll to a certain position (e.g. the very top or bottom).
2. Click the edit button (FAB).
3. Now the scroll position is always the very end of the note.

Personally, I usually add new content at the top, and due to #4850 it takes me a long time to scroll there on Android, which makes the app practically useless for me -- I can't just open it and jot down a quick thought in the right place.

## Describe what you expected to happen

The editor should open at roughly the right vertical scroll position. Even taking the scroll position as a percentage would be fine (acknowledging that especially things like lists and tables take different amounts of vertical space in Markdown vs rendered). Ideally, the position of the character in the middle (or top) of the screen would be identified and mapped to the other view's same scroll position, in both directions (i.e. also when closing the editor). But I don't want to push for this ideal -- the quick percentage-based solution probably works fine in almost all cases.

**Comment by roman-r-m** [comment] 2021-04-16 19:14
This is a duplicate of https://github.com/laurent22/joplin/issues/4216
Unfortunately, is a bug in react-native so we'll just have to wait.

**Closed by roman-r-m** 2021-04-16 19:14 UTC
Labels: bug
