### ISSUE TITLE
UI distortion and functionality issue after clicking Toggle External Editing Button in note menu bar 

### ISSUE THREAD

**Issue by Himanshu-shukla** [laurent22/joplin#4921] opened 2021-05-05 16:06 UTC
Steps to reproduce:-
1. In a new note or existing note, click on toggle external editing button
2. Closed the external application window and observe the toggle external editing button ui.
Observation :- Stop button overlap with bold icon  
![image](https://user-images.githubusercontent.com/18285081/117172580-90027f00-ade9-11eb-8674-739eea82f15f.png)

Functionality Issue :-
After closing the External Application window, Toggle External Editing button should  restore to normal state.

**Comment by roman-r-m** [comment] 2021-05-05 16:09
Duplicate of https://github.com/laurent22/joplin/issues/4853

**Closed by roman-r-m** 2021-05-05 16:09 UTC
