### ISSUE TITLE
DESKTOP: If the text is preceeded by white spaces after converting it into bold text, the text is not selected properly.

### ISSUE THREAD

**Issue by Rishgod** [laurent22/joplin#2736] opened 2020-03-11 23:53 UTC
# Actual Behavior
![selection-bug](https://user-images.githubusercontent.com/54576074/76474357-6c2fed00-6421-11ea-88bf-58cd1f8ab7fd.gif)

# Desired Behavior
![selection-fix](https://user-images.githubusercontent.com/54576074/76474359-6df9b080-6421-11ea-9751-15d9edb67fef.gif)

**Comment by Rishgod** [comment] 2020-03-11 23:54
@PackElend @bedwardly-down thought?

**Comment by bedwardly-down** [comment] 2020-03-12 00:34
On this, I’m not sure. How exactly does this get reproduced? I’m a bit confused about what’s happening

**Comment by Rishgod** [comment] 2020-03-12 00:54
> On this, I’m not sure. How exactly does this get reproduced? I’m a bit confused about what’s happening. Could you please add steps to reproduce? Thanks

## Steps to Reproduce

-  write something on Joplin surrounded by white spaces like '   Joplin     '

-  Select the entire text '   Joplin     '  (including the white spaces) and press any of bold/italic/Code button

-  Ideally, the only selected text should be the one in between the markdown rule but due to the offset created by the white spaces that's, not the case, LOOK at the difference between GIF 1 and GIF 2 


Hope this clears it up :)

**Comment by bedwardly-down** [comment] 2020-03-12 00:56
@Rishgod, look at the new `toggleWrapSelection` function in `ElectronClient/gui/NoteText.jsx`. Does this only happen with Bold or does it occur with Italic too? I did a quick search of the code and found the `commandTextBold` function called that one and looks like it could add spaces when called. I could be wrong there, though.

**Comment by Rishgod** [comment] 2020-03-12 01:06
this will happen with bold, italics, and code block, I believe this is more of a subjective bug because I seriously think the way it highlights the text right now is really ugly, the fix to this is really simple.

**Comment by tessus** [comment] 2020-03-12 01:19
There was a PR not too long ago that had to do with this.

**Comment by bedwardly-down** [comment] 2020-03-12 01:32
> There was a PR not too long ago that had to do with this.

I believe it added the function i alluded to. It was merged like a week at the most ago, i think

**Comment by tessus** [comment] 2020-03-12 01:36
Yep, actually that code was written by @Rishgod 

https://github.com/laurent22/joplin/pull/2582

**Comment by tessus** [comment] 2020-03-12 01:36
So this is a follow-up PR to #2582

**Comment by Rishgod** [comment] 2020-03-12 01:37
> > There was a PR not too long ago that had to do with this.
> 
> I believe it added the function i alluded to. It was merged like a week at the most ago, i think

Yes, @bedwardly-down, I looked into the function you mentioned, it's for toggling text bold/italics, this is nothing to do with that, it's just about how the text is selected when you press the bold button, look at gif 1 and gif 2, there is no effect on the right-hand side markdown parser, this only changes how the text is selected in the editor after pressing the button

**Comment by bedwardly-down** [comment] 2020-03-12 01:38
Yup. That’s the one.

**Comment by Rishgod** [comment] 2020-03-12 01:38
> So this is a follow-up PR to #2582

Yes, I believe it is

**Comment by bedwardly-down** [comment] 2020-03-12 01:41
> > > There was a PR not too long ago that had to do with this.
> > 
> > 
> > I believe it added the function i alluded to. It was merged like a week at the most ago, i think
> 
> Yes, @bedwardly-down, I looked into the function you mentioned, it's for toggling text bold/italics, this is nothing to do with that, it's just about how the text is selected when you press the bold button, look at gif 1 and gif 2, there is no effect on the right-hand side markdown parser, this only changes how the text is selected in the editor after pressing the button

I’m not a programmer here, so i figured it might not have been the right location. You asked, so I attempted. Ha. 

I don’t know if @PackElend is any better at the code side of things but I’m trying to stay back a bit on this part of the project and focus more on helping in other ways like directing to bugs and the more people related stuff. ;)

**Comment by tessus** [comment] 2020-03-12 02:16
@Rishgod I'm not sure, if you saw my mention in https://github.com/laurent22/joplin/pull/2624#issuecomment-597261183. I believe you were looking for issues at one point.

**Comment by Rishgod** [comment] 2020-03-12 02:35
> @Rishgod I'm not sure, if you saw my mention in [#2624 (comment)](https://github.com/laurent22/joplin/pull/2624#issuecomment-597261183). I believe you were looking for issues at one point.

Oh yes thanks for pointing it out, I look into the same!

**Comment by laurent22** [comment] 2020-03-12 09:42
That would be a good change I think, the selection should indeed be updated to wrap the text like in your second gif.

**Comment by PackElend** [comment] 2020-03-12 12:31
> I don’t know if @PackElend is any better at the code side of things but I’m trying to stay back a bit on this part of the project and focus more on helping in other ways like directing to bugs and the more people related stuff. ;)

same here I don't find the time necessary to pursue to understand the code

**Comment by Rishgod** [comment] 2020-03-12 14:19
> > I don’t know if @PackElend is any better at the code side of things but I’m trying to stay back a bit on this part of the project and focus more on helping in other ways like directing to bugs and the more people related stuff. ;)
> 
> same here I don't find the time necessary to pursue to understand the code

No worries @PackElend

**Closed** 2020-04-11 10:02 UTC
Labels: bug
