### ISSUE TITLE
Desktop: Rich text editor: Plugin icons invisible on startup

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#8518] opened 2023-07-21 01:49 UTC
## Environment

Joplin version: 9aafdd2d10b2d3132dd15ec598831b74bcf23f4b
Platform: Desktop
OS specifics: MacOS and Ubuntu 23.04

## Steps to reproduce

1. Install plugins that put icons in the toolbar (e.g. `Freehand Drawing`)
2. Switch to the rich text editor
3. Quit Joplin
4. Reopen Joplin

## Describe what you expected to happen

I expect plugin icons to be visible in the rich text editor toolbar on startup (though as gear icons).

Toggling between the rich and plain text editors makes the icons visible.

# Notes

On some startups, some of the plugin icons do appear, so this isn't consistent.

**Comment by laurent22** [comment] 2023-08-06 11:58
Duplicate of #8504

**Closed as completed by laurent22** 2023-08-06 11:58 UTC
Labels: bug, desktop, high, plugins
