### ISSUE TITLE
--- and *** are rendered as lines in the markdown editor

### ISSUE THREAD

**Issue by SandMouse** [laurent22/joplin#7507] opened 2022-12-21 08:19 UTC
Markdown syntax `---` and `***` are rendered as lines in the markdown editor.

## Environment

Joplin version: 2.9.17 (prod, darwin)
Platform: macOS
OS specifics: 12.6.2 (21G320)

## Steps to reproduce

1.  Open a new note
2. Type --- or *** in the markdown editor.
3. Lines are rendered in _both_ the markdown editor AND the preview window.

## Describe what you expected to happen

1. I would expect to see a rendered line only in the preview window. The editor should display only raw text.

## Logfile

Since this is a cosmetic bug log files do not seem relevant. Ping me if you need a log file.

![Screenshot 2022-12-21 at 09 19 13](https://user-images.githubusercontent.com/5917501/208854927-39e71eb4-f818-4ee1-9a29-9a6540b139b5.png)

**Comment by JackGruber** [comment] 2022-12-21 16:08
Are you using any plugins or custom css styles?
Because in vanila Joplin the markdown text looks completely different. 

![grafik](https://user-images.githubusercontent.com/24863925/208950012-877900dd-fd51-49e3-8f85-9425833149c4.png)

**Comment by CalebJohn** [comment] 2022-12-21 22:39
Duplicate of https://github.com/laurent22/joplin/issues/4210

This is a feature of the Solarized theme that Joplin relies on. If you don't like the line you can switch to another theme, or use [custom css](https://github.com/laurent22/joplin#custom-css) to style Joplin however you like.

**Closed as completed** 2022-12-21 22:42 UTC
Labels: bug

**Comment by SandMouse** [comment] 2022-12-22 12:52
Thank you. I should have tested with vanilla.
