### ISSUE TITLE
Date format in 'Completed: ...' on pane is not matching setup

### ISSUE THREAD

**Issue by donbowman** [laurent22/joplin#674] opened 2018-07-09 12:00 UTC
### Description

On the sidebar, the date shows as 'Completed: 09/07/2018'. I have iso8601 selected in the tools/general options (yyyy-mm-dd).

### Operating system

- Linux

### Application

- Desktop

**Comment by tessus** [comment] 2018-07-09 16:47
Duplicate of #421

**Closed** 2018-07-25 15:54 UTC
