### ISSUE TITLE
.tox-pop Table Popup positioning is invasive and doesn't align properly. 

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#8418] opened 2023-07-06 02:09 UTC
## Environment

**Joplin version:** 

Joplin 2.11.11 (prod, win32)
Client ID: 4dab185d885945ac897a0608af59c6f7
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes
Revision: 6886f6f
Markdown Prettier: 0.1.0
MultiMarkdown Table Tools: 1.0.0
Quick HTML tags: 0.2.0
Rich Markdown: 0.13.2
Suitcase: 0.3.0
Table Formatter Plugin: 1.2.1

**Platform:** 
Windows

**OS specifics:** 
Windows 10 Pro x64 Version 22H2
Build 19045.3086

## Steps to reproduce

1. Toggle the WYSIWYG Editor
2. Create a table with a fair amount of data.
3. Click in the cells to trigger the table formatting popup.
4. Notice the positioning is out of whack, doesn't follow your selection, and a lot of the time interferes with the data you're trying to enter.

**Here's a screenshot:**

**Here's a screen recording:**

## Describe what you expected to happen

I expected the position of the table popup helper to stay out of the way of data entry. This is what used to happen, at least.

## Logfile

Any help at all would be immensely appreciated. I really want my old table tools popup behavior back.

**Comment by personalizedrefrigerator** [comment] 2023-07-06 06:50
This pull request may be related: https://github.com/laurent22/joplin/pull/8163

**Comment by marph91** [comment] 2023-07-15 14:55
I can't reproduce this issue. However, the original popup is restored in https://github.com/laurent22/joplin/pull/8393, so the default behavior should be back soon.

**Comment by laurent22** [comment] 2023-07-23 16:58
Fixed in https://github.com/laurent22/joplin/pull/8393

**Closed as completed by laurent22** 2023-07-23 16:58 UTC
Labels: bug
