### ISSUE TITLE
Little bug on the editor, ~~ have a strange beavure.

### ISSUE THREAD

**Issue by bogdahn-fr** [laurent22/joplin#5859] opened 2021-12-14 11:49 UTC
I'm french, my english is very poor, sorry for that.

Description :
In the main editor, when you use a Strikethrough text with ~~text~~ syntax, the rendering have a strange behavior :
![image](https://user-images.githubusercontent.com/91743570/145989048-e03f2c5c-8ffe-4310-878e-46ce818d010f.png)

In the viewer, everything works fine :
![image](https://user-images.githubusercontent.com/91743570/145989251-fe163578-e14f-4545-9195-21e6c3213728.png)

I tested with Manjaro linux the problem is the same :

![image](https://user-images.githubusercontent.com/91743570/145991038-277c685b-b02e-4bb7-ae2d-aefa03fd854c.png)

The Android from playstore dont have this problem.

Joplin version: latest 2.5.12 (windows) lastest appimage from joplin (for the manjaro test) 2.5.12
Platform: Windows 10 and GNU/Linux Manjaro
OS specifics: home edition strip down of bloatware. But i don't think is OS related. Also tested on Manjaro up-to-date (12/14/2021) 

## Steps to reproduce
the code used is just `~~test~~` in the editor

## Describe what you expected to happen
The test should not be Strikethrough in the editor, but appear like it should : `~~test~~`

**Comment by Daeraxa** [comment] 2021-12-14 12:18
This is by design. When you apply the `~~` tags to something then the editor will assign it the class of `.cm-strikethrough` which has an associated .css style of `text-decoration: line-through`.
This is all part of the hybrid design of the editor to show formatting + markdown tags together.
If you need to change this behaviour then you can load custom CSS to `userchrome.css` to remove the text-decoration by changing it to 
```css
span.cm-strikethrough {
    text-decoration: none !important;
}
```

**Closed** 2021-12-14 15:57 UTC

**Comment by bogdahn-fr** [comment] 2021-12-15 10:31
I'm not very happy by the closing of the bug report.
It's a design FLAW. This does not occure with html 

Mais bon, comme ici c'est pas pour expliquer, mais juste mettre des message qui ne servent à rien, je vais pas continuer.

**Comment by Daeraxa** [comment] 2021-12-15 11:58
I don't understand what you want to happen, it was designed that way intentionally and the behaviour is consistent with other markdown tags where both the tags AND the effect of those tags are shown together.
![image](https://user-images.githubusercontent.com/58074586/146182456-ff4d1ca7-2e2c-4f11-acdf-86e42350ceb6.png)
