### ISSUE TITLE
Can you create a drag drop on the todos for rearrange ? The order in which I create is not necessarily the order in which I work upon. There is a need to rearrange the todo order

### ISSUE THREAD

**Issue by krish05** [laurent22/joplin#54] opened 2017-12-01 18:31 UTC
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

**Comment by krish05** [comment] 2017-12-01 18:31
It is a feature

**Comment by laurent22** [comment] 2017-12-01 18:32
Duplicate of https://github.com/laurent22/joplin/issues/51

**Closed by laurent22** 2017-12-01 18:32 UTC
