### ISSUE TITLE
Unable to find the time and date of a note

### ISSUE THREAD

**Issue by adrianharabula** [laurent22/joplin#267] opened 2018-03-02 10:26 UTC
Using Joplin, I don't know where to look for the datetime of a note.

I can't see it anywhere or I'm missing something.

**Comment by Petemir** [comment] 2018-03-02 14:31
I believe it is available in mobile, not yet in desktop, check issue #73 .

**Comment by laurent22** [comment] 2018-03-07 17:40
Duplicate of #73

**Closed by laurent22** 2018-03-07 17:40 UTC
