### ISSUE TITLE
Arabic script does not render properly when in italics

### ISSUE THREAD

**Issue by hb20007** [laurent22/joplin#3492] opened 2020-07-13 16:37 UTC
## Environment

Joplin version: 1.0.227 (prod, win32)
Platform: Windows
OS specifics: Windows 10 Home Single Language version 1809

## Steps to reproduce

1. Type / paste some text in a language that uses the Arabic script (e.g., Arabic / Persian / Urdu).
2. Add markdown to make it italic.

---

## Screenshot

![image](https://user-images.githubusercontent.com/8860322/87322661-5a2c9b00-c536-11ea-83ad-ec2cf98419a3.png)

## More Details

I tried opening the note in the screenshot on Android and Linux, and the Arabic script renders fine in italics. So it only seems to be happening on Windows.

---

**P.S.** This is the text I used in the screenshot:
```
Greek Ελληνικά *Ελληνικά*
Devanagari ਪੰਜਾਬੀ *ਪੰਜਾਬੀ*
Cyrillic русский *русский*
Maldivian ދިވެހިބަސް *ދިވެހިބަސް*
N'Ko ߒߞߏ *ߒߞߏ*
Sinhalese සිංහල *සිංහල*
Thai ไทย *ไทย*
Ge'ez አማርኛ *አማርኛ*
Chinese 中文 *中文*
Korean 한국어 *한국어*
Hebrew *עברית* עברית
Arabic *العربية* العربية
```

**Comment by hb20007** [comment] 2020-07-13 19:02
Like https://github.com/laurent22/joplin/issues/3253, this is a regression between versions 1.0.207 and 1.0.209.

1.0.207:

![image](https://user-images.githubusercontent.com/8860322/87340977-86a1e080-c551-11ea-9dbc-0e619a0338e8.png)

1.0.209:

![image](https://user-images.githubusercontent.com/8860322/87341275-07f97300-c552-11ea-87f8-567c8c244c8f.png)

**Comment by hb20007** [comment] 2020-07-13 19:27
I tried adding Arabic as a language in my Windows Settings, which also installs language-associated features and supplemental fonts. However, the issue persists, so it doesn't seem to be related to this.

**Comment by nowayhaze** [comment] 2020-09-09 00:34
I can confirm this regression happens with the changes of commit fa76c5db8d432c15eaee56da92b6d787831e037e, which upgrades electron from 7.1.12 to 8.2.5.

**Comment by CalebJohn** [comment] 2020-09-12 05:41
@hb20007 Is this still an issue for you?

I tried your note on Joplin 1.0.241 on Ubuntu 20.04 and it seems the issue is gone
![image](https://user-images.githubusercontent.com/2179547/92988397-5959ac00-f488-11ea-8b3b-99f421600664.png)

**Comment by nowayhaze** [comment] 2020-09-12 05:44
@CalebJohn , I think it's a Windows specific issue, because I'm on 1.0.245 and the problem still occurs on Windows 10 2004.

**Comment by hb20007** [comment] 2020-09-21 22:06
In v1.1.4, the problem is now worse. Arabic-script characters in Italics are not displayed as the □ symbol in the code view as well.

**Comment by nowayhaze** [comment] 2020-12-17 01:48
As of version 1.5.7, this issue seems to be fixed on my Windows machine. @hb20007 is this fixed for you?

**Comment by hb20007** [comment] 2020-12-17 12:27
@nowayhaze Yes, it seems to be fixed now.

**Closed** 2020-12-17 12:28 UTC
Labels: backlog, bug, desktop
