### ISSUE TITLE
Editor doesn't automatically add checkbox after pressing Enter

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9675] opened 2024-01-06 22:29 UTC
### Operating system

Android

### Joplin version

2.14

### Desktop version info

- create a new checkbox and type some text
- press enter. A new checkbox should be created.
- type some misspelled text, for example "hello wold"
- accept the correction "world"
- press enter

=> A new checkbox is not created

It seems to be due to the space that's added after correction. However if I manually add a space the bug doesn't trigger

Tested only on Android but may happen on iOS too

**Comment by personalizedrefrigerator** [comment] 2024-01-07 16:38
I haven't been able to reproduce this on iOS.

Does it happen [in a CodeMirror editor with just the markdown extension?](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge21hcmtkb3dufSBmcm9tICJAY29kZW1pcnJvci9sYW5nLW1hcmtkb3duIgppbXBvcnQge2xhbmd1YWdlc30gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZ3VhZ2UtZGF0YSIKCi8vIFRoZSBNYXJrZG93biBwYXJzZXIgd2lsbCBkeW5hbWljYWxseSBsb2FkIHBhcnNlcnMKLy8gZm9yIGNvZGUgYmxvY2tzLCB1c2luZyBAY29kZW1pcnJvci9sYW5ndWFnZS1kYXRhIHRvCi8vIGxvb2sgdXAgdGhlIGFwcHJvcHJpYXRlIGR5bmFtaWMgaW1wb3J0LgpsZXQgdmlldyA9IG5ldyBFZGl0b3JWaWV3KHsKICBkb2M6ICItIFsgXSBUZXN0IiwKICBleHRlbnNpb25zOiBbCiAgICBiYXNpY1NldHVwLAogICAgbWFya2Rvd24oe2NvZGVMYW5ndWFnZXM6IGxhbmd1YWdlc30pCiAgXSwKICBwYXJlbnQ6IGRvY3VtZW50LmJvZHkKfSkK)

**Comment by laurent22** [comment] 2024-01-07 23:46
No it's not happening in this demo page but I can consistently replicate it in Joplin. With Galaxy S22, default keyboard

**Comment by personalizedrefrigerator** [comment] 2024-01-07 23:48
Sorry! I forgot to enable spellcheck.

[Updated demo.](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge21hcmtkb3dufSBmcm9tICJAY29kZW1pcnJvci9sYW5nLW1hcmtkb3duIgppbXBvcnQge2xhbmd1YWdlc30gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZ3VhZ2UtZGF0YSIKCi8vIFRoZSBNYXJrZG93biBwYXJzZXIgd2lsbCBkeW5hbWljYWxseSBsb2FkIHBhcnNlcnMKLy8gZm9yIGNvZGUgYmxvY2tzLCB1c2luZyBAY29kZW1pcnJvci9sYW5ndWFnZS1kYXRhIHRvCi8vIGxvb2sgdXAgdGhlIGFwcHJvcHJpYXRlIGR5bmFtaWMgaW1wb3J0LgpsZXQgdmlldyA9IG5ldyBFZGl0b3JWaWV3KHsKICBkb2M6ICItIFsgXSBUZXNzdCIsCiAgZXh0ZW5zaW9uczogWwogICAgYmFzaWNTZXR1cCwKICAgIG1hcmtkb3duKHtjb2RlTGFuZ3VhZ2VzOiBsYW5ndWFnZXN9KSwKICAgIEVkaXRvclZpZXcuY29udGVudEF0dHJpYnV0ZXMub2YoewogICAgICAgIGF1dG9jYXBpdGFsaXplOiAnc2VudGVuY2UnLAogICAgICAgIGF1dG9jb3JyZWN0OiAndHJ1ZScsCiAgICAgICAgc3BlbGxjaGVjazogJ3RydWUnLAogICAgfSksCiAgXSwKICBwYXJlbnQ6IGRvY3VtZW50LmJvZHkKfSkK)

**Comment by laurent22** [comment] 2024-01-08 10:43
Actually yesterday I tried with my default Android browser, Firefox, and with this none of the demos show the problem. But if I try with Chrome I can replicate the issue on both demos.

**Comment by personalizedrefrigerator** [comment] 2024-01-31 17:31
Upstream pull request: https://github.com/codemirror/view/pull/62

This pull request *might* fix the issue &mdash; I wasn't able to reproduce the spellcheck issue reported above (Android 12 emulator with GBoard), but was able to reproduce [this related issue](https://github.com/codemirror/dev/issues/1312). The pull request should fix the related issue.

**Comment by personalizedrefrigerator** [comment] 2024-02-21 15:14
This has been fixed upstream &mdash; upgrading CodeMirror should fix the issue (**edit** after a new version is released upstream).

**Comment by personalizedrefrigerator** [comment] 2024-04-15 15:06
This seems to be fixed! (See [comment](https://github.com/laurent22/joplin/pull/10032#issuecomment-2057085487)).

**Comment by personalizedrefrigerator** [comment] 2024-04-15 20:56
Closing this as fixed by either https://github.com/laurent22/joplin/pull/10174 or https://github.com/laurent22/joplin/issues/9675.

**Closed as completed by personalizedrefrigerator** 2024-04-15 20:56 UTC
Labels: bug, upstream, android, backlog
