### ISSUE TITLE
Custom sort does not work

### ISSUE THREAD

**Issue by jr1234567** [laurent22/joplin#4162] opened 2020-11-29 17:24 UTC
Custom sort does not work : I can't manage to order my notes. Sometimes, a note refuses to move, sometimes it jumps quite randomly
 
## Environment
Joplin version:  1.4.18 
Platform:  Linux
OS specifics:  Ubuntu 20.10

**Comment by johnr365** [comment] 2020-12-03 12:07
Am experiencing this also. Specifically when using custom sort for To Do items. Both on Macbook and on iOS.

Thanks @laurent22 for such a great piece of software. Much appreciated.

Environments
---
Platform: MacOS
OS version: Catalina - 10.15.7
Joplin version: 1.2.6
---
Platform: iOS
OS version: 14.0
Joplin version: 10.4.1

**Comment by jr1234567** [comment] 2020-12-28 11:06
Custom sort still does not work on 1.5.11 under ubuntu 20.20. 
Either the

**Comment by jr1234567** [comment] 2020-12-28 11:15
Custom sort still does not work  in Joplin 1.5.11 under ubuntu 20.10.
Either the note refuses to budge (a note almost never accepts to be moved down)  or it jumps 1 or 2 positions above the note rather than between the notes where it is dropped.

**Comment by johnr365** [comment] 2020-12-28 14:07
@jr1234567 - Bit confused - why did you make a note to say that custom sort "still does not work" - and then close the issue?

**Comment by jr1234567** [comment] 2020-12-28 14:16
Did I close the issue ? Ooops If so, this was a mistake on my
      part as indeed I wished to underline  that the issue was still
      very much unresolved ! 
    
    
    
    
    On 28/12/2020 15:07, John wrote:
    
      
      @jr1234567
        - Bit confused - why did you make a note to say that custom sort
        "still does not work" - and then close the issue?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/laurent22/joplin/issues/4162#issuecomment-751723945",
"url": "https://github.com/laurent22/joplin/issues/4162#issuecomment-751723945",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by johnr365** [comment] 2020-12-28 21:49
Ok, just wondered :)
Perhaps you can re-open it then?

**Comment by CypherNL** [comment] 2021-01-05 08:41
I also have this issue with to-do tasks on Joplin 1.5.11 on Windows 10.

For me it seems that you need to drag one more row up or below than needed to drag the to-do task to the correct position. I have not tested normal notes using custom order.

**Comment by jr1234567** [comment] 2021-01-05 10:53
Further tests with Joplin 1.5.14 under Linux
    - Sometimes a note moves, and lands where it is dropeed, but
      frequently it refuses to budge.
     
    - Quite often, when moved down, the note *needs* to be dropped
      one  row farther than intended in order to reach the desired
      position.
    - Also quite often, when moved up, the note moves one row farther
      than intended.
    
    
    On 05/01/2021 09:42, CypherNL wrote:
    
    
      
      I also have this issue with to-do tasks on Joplin 1.5.11 on
        Windows 10.
      For me it seems that you need to drag one more row up or below
        than needed to drag the to-do task to the correct position. I
        have not tested normal notes using custom order.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/laurent22/joplin/issues/4162#issuecomment-754493533",
"url": "https://github.com/laurent22/joplin/issues/4162#issuecomment-754493533",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jr1234567** [comment] 2021-02-05 08:06
As far as I can see from a user perspective, custom sort has not
      seen any improvement and remains unusable in version 1.7.11 under
      Linux.
    Joplin will be an even greater software when notes can be
      rearranged at will!
    
    On 04/02/2021 20:43, stale[bot] wrote:
    
    
      
      Hey there, it looks like there has been no activity on this
        issue recently. Has the issue been fixed, or does it still
        require the community's attention? This issue may be closed if
        no further activity occurs. You may comment on the issue and I
        will leave it open. Thank you for your contributions.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/laurent22/joplin/issues/4162#issuecomment-773558405",
"url": "https://github.com/laurent22/joplin/issues/4162#issuecomment-773558405",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by menzzana** [comment] 2021-02-24 09:59
Joplin version: 1.7.11 Linux
OS: Linux Mint 20

I can see the same issue.
Sort of notes in custom order does not work, or rather does place the dropped note in the wrong position.

When grabbing a note the actual place where it is sorted into
appears to be 10 places downward instead of the correct place.
If you have fewer than 10 notes, it just get dropped at the bottom.

**Comment by nicola-lunghi** [comment] 2021-02-27 06:53
Same issue here I cannot sort notebooks by draggin and dropping it always goes to the default alphabetical sorting

the ability to sort notes dragging and dripping them would be really nice
for now I just addeda number on the front of the notebook

**Comment by Groundservice** [comment] 2021-03-06 13:48
Joplin version: 1.7.11 Portable for Windows
OS: Windows 10 Professional

Same bug under windows. 
Task order: custom
Dragging a task either doesn't work at all or not to the right position.
Especially when trying to move more than once.
Position 1 and 2 seems completely impossible.

I really love Joplin very much but I need manually sorting tasks urgently.

**Comment by nunesgh** [comment] 2021-04-17 15:49
Joplin version: 1.7.11
OS: Linux Mint 20.1

Same bug when using custom sorting of notes.

Also, a nice feature would be to sync the custom sorting. It is a waste of time to have to manually sort notes in each device.

**Comment by mandavister** [comment] 2021-05-08 10:39
Joplin 1.7.11
OS: Linux

I experience that with tasks a lot. When trying to move a task one level lower, it doesn't move. When trying two level lower, it moves one level. When moving across more levels sometimes it doesn't move at all, sometimes it does just fine.

**Comment by jr1234567** [comment] 2021-06-08 08:53
Hi 
    
    Custom sort is still broken in v 2.0.2 under Linux 
    Joplin would be perfect if it worked !
    
    
    
    
    
    On 07/06/2021 15:30, stale[bot] wrote:
    
    
      
      Hey there, it looks like there has been no activity on this
        issue recently. Has the issue been fixed, or does it still
        require the community's attention? This issue may be closed if
        no further activity occurs. You may comment on the issue and I
        will leave it open. Thank you for your contributions.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/laurent22/joplin/issues/4162#issuecomment-855930399",
"url": "https://github.com/laurent22/joplin/issues/4162#issuecomment-855930399",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Yajo** [comment] 2021-06-09 15:56
I use Joplin 1.8.5 from flathub. It's broken there too, just like the others said.

[-1623253906883.log](https://github.com/laurent22/joplin/files/6625167/-1623253906883.log)


https://user-images.githubusercontent.com/973709/121388653-8ec1f600-c943-11eb-9305-cdedfa6f6284.mp4

(The terminal is used as a handy censorship.)

**Comment by Yajo** [comment] 2021-07-12 09:37
El sáb, 10 de jul de 2021 a las 13:44:58 PM, stale[bot] 
***@***.***> escribió:
> Has the issue been fixed, or does it still require the community's 
> attention?

It still requires attention.

**Comment by roman-r-m** [comment] 2021-07-13 16:28
One issue here is that custom sort conflicts with "Uncompleted to-dos on top"

**Comment by jr1234567** [comment] 2021-08-18 08:12
Great job ! It appears to be working way better. Notes do not
      jump haphazardly as they used to when trying to manually sort
      them.
      
      I notice that notes still refuse to move sometimes and I must make
      several attempts until they comply but it may be due to my lack of
      dexterity.
      
      
      
    
    On 18/08/2021 04:21, stale[bot] wrote:
    
    
      
      Hey there, it looks like there has been no activity on this
        issue recently. Has the issue been fixed, or does it still
        require the community's attention? This issue may be closed if
        no further activity occurs. You may comment on the issue and I
        will leave it open. Thank you for your contributions.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/laurent22/joplin/issues/4162#issuecomment-900761577",
"url": "https://github.com/laurent22/joplin/issues/4162#issuecomment-900761577",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nunesgh** [comment] 2021-08-18 10:10
The issue persists for me on Joplin 2.3.3 via AppImage.

**Comment by jr1234567** [comment] 2021-08-19 05:39
I agree. Another try this morning and custom sort stilll does not
      work. I do not know why it seemed to be improved yesterday.
    
    
    
    On 18/08/2021 12:11, Gabriel H. Nunes
      wrote:
    
    
      
      The issue persists for me on Joplin 2.3.3 via AppImage.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/laurent22/joplin/issues/4162#issuecomment-900991523",
"url": "https://github.com/laurent22/joplin/issues/4162#issuecomment-900991523",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jr1234567** [comment] 2021-09-02 07:06
Custom sort is still buggy in V2.4.4 under linux
    
    
    On 10/07/2021 22:44, stale[bot] wrote:
    
    
      
      Hey there, it looks like there has been no activity on this
        issue recently. Has the issue been fixed, or does it still
        require the community's attention? This issue may be closed if
        no further activity occurs. You may comment on the issue and I
        will leave it open. Thank you for your contributions.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/laurent22/joplin/issues/4162#issuecomment-877701662",
"url": "https://github.com/laurent22/joplin/issues/4162#issuecomment-877701662",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dugsmith** [comment] 2022-09-30 14:52
Custom ordering doesn't seem to work on Android either. Running Joplin 2.8.1 on Android 11. I can drag & drop TODOs in a notebook on the Mac version, but the order doesn't synchronize to Android, and drag & drop doesn't work on Android either.

**Comment by nathanosdev** [comment] 2023-01-28 17:12
I have a related issue. I often run into this scenario:
- Have the last note selected/highlighted
- Create a new note
- Most of the time the new note is created at the end but sometimes it is created as the 2nd last note
- I now move the new note to the end
- The new note indeed moves to the end, but the note that was previously in the last position now jumps to the first position
- I can now move the note from the position to the 2nd last position as it should be

I'd be happy to make a stab at fixing this if the maintainers are open to a PR for this.

**Comment by TaoK** [comment] 2023-01-30 13:02
Hi folks,

It looks like there are a few different things in play here, which should probably be tracked & addressed separately:

* Custom sort changes do not sync correctly, unless you *also* update the content of the moved note (afterwards); this is more explicitly tracked in #6956 (PR for fix: #7729)
  * Workaround: Edit notes after you reorder them 🤢

* Custom sort on Todo Items has strange/buggy drag & drop behavior in the Desktop app, when "Uncompleted todos on top" is selected, and/or "Show completed todos" is unselected. The dropped item lands higher than it should, depending on how many completed items would be "above" it in a regular custom sort without "Uncompleted todos on top" being selected or "Show completed todos" being unselected. I suspect this is the majority issue in this thread, but I'm not certain.
  * Workaround: Keep the "Uncompleted todos on top" feature disabled, keep "Show completed todos" enabled, and move your completed todo items manually 🤷
  * Follow-up: This is now explicitly/separately tracked in #7731 (with pull request #7737 ).

* Newly added items have strange sorting behavior in the Desktop app under custom sort:
  * As they initially have sort order 0, they appear at the bottom of the list (if the previous ones have already been custom-sorted)
  * When you next reorder any todo item, they get sort order initialized to "now", and therefore "pop" to the top
  * If the first sort activity is the dragging of that specific item, then it pops to the top as part of that operation, and effectively ends up one position higher than requested.
  * Workaround: be aware of this, understanding that sorting a new todo item is always a two-step operation. 🚧
  * (this is the same behavior @nathanosdev noted just above)
  * Follow-up: This is now explicitly/separately tracked in #7741 (with pull request #7765 ). 

* ~~Sometimes a drop action doesn't complete properly in the Desktop app, and the thick insert line remains rendered, even as you navigate across notebooks; the subsequent drag & drop operation seems to have unpredictable effects.~~
  * ~~Workaround: Be aware of this, and watch what you do when you unexpectedly see the thick black line between notes, as your next operation might "mess things up". I keep a separate notebook with dummy notes for testing and "safely detonating" this issue~~ (the sorting issue seems to have been a misunderstood artifact of the previous issues)

* When you drag-drop a note from one notebook into another, the positioning indicator / thick line remains visible at the previous item index, until you do a same-notebook drag/drop operation
  * This appears to be a visual artifact only; it may be Windows-specific, or already fixed since 2.9.17 (cannot reproduce in a linux dev build)

* When drag/drop reordering, the "drop zone" is limited to the todo items in the list already; if you drop just below the lowest item, or just above the highest item, nothing happens / you "miss".
  * This makes it quite hard to drop items at the top or bottom, as you only have half an item's height as target
  * This behavior is very unintuitive, as there is no visual indicator that you are "missing" - the target insert line appears to be where you want it
  * Workaround: be aware of this limitation and specifically target the upper half of the top item or lower half of the lowest one when doing this. :microscope:
  * Follow-up: This is now explicitly/separately tracked in #7776 (with first pull request #7777 ). 

* There is no drag-drop / custom order changing feature on Android. This is separately / better tracked in #4989 (thanks @yajo !)

* Newly added notes appear at the bottom of the note list, or right above any other recently-added notes. It would make more sense for them to appear always in the same place (bottom, top, or near the current selected note)
  * Workaround: None

> I'd be happy to make a stab at fixing this if the maintainers are open to a PR for this.

FWIW the maintainers are absolutely open to pull requests, and there is a formal contributors agreement and all. I haven't gone through the process yet, but I would definitely like to help address all these custom sort problems to help support my use of this app for ToDo tracking. It definitely doesn't feel like the authors or core contributors use the custom sort feature with todo items at the moment.

FYI, I also registered a separate issue about the usability of custom sort without mouse dragging: #7692 .

**Comment by laurent22** [comment] 2023-03-03 11:23
@TaoK, it's difficult to track the status of this issue so I'm closing it, but feel free to create new issues (one bug per issue) if there are remaining problems.

**Closed by laurent22** 2023-03-03 11:23 UTC
Labels: bug, desktop, high
