### ISSUE TITLE
Sync Error: Outside Latin1 Range

### ISSUE THREAD

**Issue by trymeouteh** [laurent22/joplin#1879] opened 2019-09-19 06:25 UTC
I have been using the Nextcloud syncing for awhile and it works. I just enabled TOTP 2FA on my nextcloud account and it no longer syncs so I had to create a app password within my nextcloud account to use apps with 2fa enabled. I set it up on the Nextcloud linux client by changing my nextcoud login password in joplin and it worked. However when I tried to update my login in the android app I get an error...

```
Error: Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was.

Cannot encode username/password. The string to be encoded contains characters outside of Latin1 range.
```

This only seems to happen on android, not linux.

**Comment by laurent22** [comment] 2019-09-19 13:48
Duplicate of #246

**Closed by laurent22** 2019-09-19 13:48 UTC
Labels: :bug: bug

**Comment by trymeouteh** [comment] 2019-09-19 16:39
#246 does not solve it. Is joplin not going to allow nextcloud users to use TOTP 2fa and in order for us to sync our devices to nextcloud we need to disable 2fa?

To use apps that sync with a nextcloud account that has 2fa enabled you need to generate a app password for your nextcloud account and use the nextcloud password to login. I cannot choose what the app password is, it is automatically generated and therefore I cannot remove the special characters. Please allow Joplin on Android to accept these characters.

**Comment by laurent22** [comment] 2019-09-19 16:42
This is strange, what kind of special character do they include in the 2FA password? Can you show an example of one of these characters?

If I'm not mistaken other users have successfully used 2FA with Joplin so there must be a way.

**Comment by trymeouteh** [comment] 2019-09-19 19:10
Wuv3o-9wKFw-vdQKC-LPAfI-F79ja

**Comment by laurent22** [comment] 2019-09-19 21:32
> Wuv3o-9wKFw-vdQKC-LPAfI-F79ja

This password would not cause the Latin1 error. How about your username? Does it has non-ascii characters such as Polish, Russian letters, etc.? Basically the only allowed characters in username and password are these ones:

![image](https://user-images.githubusercontent.com/1285584/65282664-581fc880-db2d-11e9-946a-20b800c34155.png)


> I even tried using WebDav sync instead of Nextcloud sync and I still get the same error :(

By error, you still mean the Latin1, right?

**Comment by trymeouteh** [comment] 2019-09-20 22:33
I do not want to reveal my username but it is all lowercase and one work. This is my username if I was to change my firstname, middle name initials and last name.

johnasmith

So no fancy characters. The nextcloud server I am using is https://armored.net which is new and is a cloud storage service by epik.

**Comment by trymeouteh** [comment] 2019-09-28 02:05
I just tried to connect to my nextcloud server again today and now it worked, I even used the same app password. Strange, I wonder why it wasn't working until now.
