### ISSUE TITLE
notebooks stored as folders

### ISSUE THREAD

**Issue by cast-away** [laurent22/joplin#303] opened 2018-03-16 00:52 UTC
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

First and foremost: many thanks for this great piece of software!

This might be an silly request since I am not a programmer, but would it be possible to store the notebooks as folders (containing the files for the notes) instead of markdown files?

I appreciate this might be tricky to implement across platforms, but it would make it easier to manage large amounts of notes within the file system and might open at least two interesting possibilities:
- notebooks within notebooks (I believe a similar feature has been reqiested)
- sharing notebooks between nextcloud users by sharing the relevant folders

**Comment by laurent22** [comment] 2018-03-16 14:11
Duplicate of #264

**Closed by laurent22** 2018-03-16 14:11 UTC
