### ISSUE TITLE
Notebook ordering is different on mobile and desktop

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#9996] opened 2024-02-25 09:10 UTC
### Operating system

Windows

### Joplin version

2.14.15

#### Desktop
Joplin 2.14.15 (prod, win32)

Client ID: 0e33609c84614b3092102ff00887b36e
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 7cfe9bb

#### Mobile
Joplin 2.13.10

### Current behaviour

I think in version 2.14 the sorting for notebooks in Joplin Desktop has changed and is now different from that of the mobile app.

#### Desktop
Starts with the sorting of numbers and letters (`a-zA-Z`) and then other characters. It also distinguishes between upper and lower case letters and sorts lower case letters to the end of the list
![grafik](https://github.com/laurent22/joplin/assets/24863925/beeabea6-0555-4462-84c1-27213495701f)

![grafik](https://github.com/laurent22/joplin/assets/24863925/a782e598-edec-44f4-bd82-4b5d2e737b69)

#### Mobile 
Starts with the sorting other characters and then numbers and letters (`a-zA-Z`) [Capitalization is irelevant]
![grafik](https://github.com/laurent22/joplin/assets/24863925/94759872-84f8-4c82-85d1-900fdc0eaecc)

### Expected behaviour

The sorting should be the same in all apps

### Logs

The sorting should be the same on all apps

**Comment by laurent22** [comment] 2024-02-25 09:49
Is that definitely a regression in 2.14? I agree it should be fixed in any case, and the correct order is the one on mobile

**Comment by JackGruber** [comment] 2024-02-25 10:01
> Is that definitely a regression in 2.14? 

Yes, in 2.13 Desktop and Mobile had the same sorting

|2.14.16|2.13.12|2.11.2|
|---|---|---|
|![grafik](https://github.com/laurent22/joplin/assets/24863925/fd9d5a1d-145e-4967-807f-ebfdd3ec98ff)|![grafik](https://github.com/laurent22/joplin/assets/24863925/0dda135d-e012-46fa-84a6-48de4b1b2c68)|![grafik](https://github.com/laurent22/joplin/assets/24863925/6b6ea69d-57f7-4de2-9e4f-8d22cdccc8ed)|

**Comment by laurent22** [comment] 2024-02-26 19:28
Indeed it looks like I broke it in a refactoring. Thanks for reporting this!

**Closed as completed by laurent22** 2024-02-26 19:28 UTC
Labels: bug, mobile, desktop, high, good first issue
