### ISSUE TITLE
iOS app does not sync with Dropbox

### ISSUE THREAD

**Issue by DealerJohn** [laurent22/joplin#6414] opened 2022-04-15 18:10 UTC
## Environment

Joplin version: 12.7.1
Platform: iOS
OS specifics: 

## Steps to reproduce

1. When I sync, nothing happens, even when I have made updates;
2. Dropbox is not updated.
(with macos all is fine and updates take place on Dropbox. But they do not sync to iOS)

## Describe what you expected to happen

Updated or created notes should sync to Dropbox and be available there as .md files.

## Logfile

![291A2175-D0FA-4DE3-9913-DADA49675247](https://user-images.githubusercontent.com/5735329/163605764-8f6928df-0279-448a-963a-b7f4d3bc6fb5.png)

**Comment by CalebJohn** [comment] 2022-04-15 21:47
Duplicate of (https://github.com/laurent22/joplin/issues/6375). The fix was identified and an update has been pushed to the IOS store (it should be available soon).

**Closed as completed by CalebJohn** 2022-04-15 21:47 UTC
Labels: bug
