### ISSUE TITLE
Link with colon isn't shown as link

### ISSUE THREAD

**Issue by th-ros** [laurent22/joplin#4125] opened 2020-11-21 21:59 UTC
A link with a colon isn't shown as hyperlink.

## Environment

Joplin version: 1.4.11 (pre-release)
Platform: Windows Portable
OS specifics: 

**The same link will work in this version**
Joplin version: 1.3.18
Platform: Windows Portable
OS specifics: 

## Steps to reproduce

1. I wrote a link like this `V2 Gravitrax stackable plate https://www.thingiverse.com/thing:3337603` and it's not marked as hyperlink.

## Describe what you expected to happen

Link should be shown as hyperlink. In Joplin version 1.3.18 windows portable it will work fine like expected.

**Comment by CalebJohn** [comment] 2020-11-21 22:27
This is probably a duplicate of #4114, please let me know if you think it's a different issue.

**Comment by th-ros** [comment] 2020-11-22 10:59
Yes, you are right. Sorry for this duplicate one. I haven't recognized that since version 1.4.x Joplin changed the behavior for plain links and with the possibility to add `<https://...>` in the markdown theres an easy way to use plain links. 

Idea: Maybe you can add a configuration option to choose the 1.3 or the 1.4 behavior. But maybe it's not a good idea because generally I like the clear GUI and option settings with only a few options.

**Comment by CalebJohn** [comment] 2020-11-23 19:41
https://discourse.joplinapp.org/t/url-links-dont-work-anymore/12620/19

Looks like this behaviour has been reverted for now, I don't know the future status but if you update to v1.4.12 link rendering will go back to the previous behaviour.

**Closed by CalebJohn** 2020-11-23 19:41 UTC

**Comment by th-ros** [comment] 2020-11-23 22:12
Thanks for working on this issue and you are right, in the new v1.4.12 the behaviour is like 1.3.18. 

Now I'll write my plain links like `<https...>`  to be ready for future changes.
