### ISSUE TITLE
Joplin markdown export fails with "Cannot read property 'type_' of undefined"

### ISSUE THREAD

**Issue by promisedlandt** [laurent22/joplin#3488] opened 2020-07-12 21:51 UTC
Trying to export my notes as markdown fails with the following error message:
> "Cannot read property 'type_' of undefined"

![image](https://user-images.githubusercontent.com/557201/87256966-5990f780-c497-11ea-903a-5dcdde788ac4.png)

The directories appear to be created correctly (too many to check manually). A `_resources` folder is also created, but it has 17 fewer entries than the `~/.local/share/joplin/.resource/` folder.

## Environment

Joplin version: 1.0.227
Platform: Linux
OS specifics: Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux

## Steps to reproduce

1. File -> Export -> Markdown -> Choose any path like `~/tmp/joplin_export`

## Describe what you expected to happen

Notes are exported as markdown.

## Logfile

<details>
  <summary>Click to expand log file</summary>
  
2020-07-12 23:48:37: "Profile directory: /home/nl/.config/joplin-desktop"
2020-07-12 23:48:37: "KeychainService: checking if keychain supported"
2020-07-12 23:48:37: "KeychainService: check was already done - skipping. Supported:", "0"
2020-07-12 23:48:37: "Client ID: b78a73945f1e4d62989789acd5613a7d"
2020-07-12 23:48:37: "Trying to load 0 master keys..."
2020-07-12 23:48:37: "Loaded master keys: 0"
2020-07-12 23:48:37: "ResourceFetcher: Auto-add resources: Mode: always"
2020-07-12 23:48:37: "ResourceFetcher: Auto-added resources: 0"
2020-07-12 23:48:37: "Refreshing notes:", "null", "null"
2020-07-12 23:48:37: "Trying to load 0 master keys..."
2020-07-12 23:48:37: "Loaded master keys: 0"
2020-07-12 23:48:37: "Scheduling sync operation...", "10000"
2020-07-12 23:48:37: "Setting up recurrent sync with interval 300"
2020-07-12 23:48:37: "Trying to load 0 master keys..."
2020-07-12 23:48:37: "Loaded master keys: 0"
2020-07-12 23:48:37: "Scheduling sync operation...", "10000"
2020-07-12 23:48:37: "Trying to load 0 master keys..."
2020-07-12 23:48:37: "Loaded master keys: 0"
2020-07-12 23:48:37: "Scheduling sync operation...", "10000"
2020-07-12 23:48:37: "Refreshing notes:", "2", "bb33178d3f7142cab48508e5651846ba"
2020-07-12 23:48:37: "Scheduling sync operation...", "10000"
2020-07-12 23:48:37: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2020-07-12 23:48:38: "Loading existing note", "dcc5a2f468ff4af1bb29475816a201f7"
2020-07-12 23:48:38: "Loaded note:", "{"id":"dcc5a2f468ff4af1bb29475816a201f7","parent_id":"bb33178d3f7142cab48508e5651846ba","title":"Joplin md export","body":"```\n/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:373 TypeError: Cannot read property 'type_' of undefined\n    at InteropService_Exporter_Md.makeDirPath_ (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService_Exporter_Md.js:21)\n    at async InteropService_Exporter_Md.processItem (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService_Exporter_Md.js:108)\n    at async InteropService.export (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:371)\n    at async Function.export (/tmp/.mount_joplinhztxau/resources/app.asar/InteropServiceHelper.js:163)\n    at async click (/tmp/.mount_joplinhztxau/resources/app.asar/app.js:430)\nexport @ /tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:373\nasync function (async)\nexport @ /tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:279\nexport @ /tmp/.mount_joplinhztxau/resources/app.asar/InteropServiceHelper.js:163\nclick @ /tmp/.mount_joplinhztxau/resources/app.asar/app.js:430\napply @ callbacks-registry.ts:45\n(anonymous) @ remote.js:292\n(anonymous) @ remote.js:272\nemit @ events.js:210\nonMessage @ init.ts:50\n\n/tmp/.mount_joplinhztxau/resources/app.asar/InteropServiceHelper.js:166 TypeError: Cannot read property 'type_' of undefined\n    at InteropService_Exporter_Md.makeDirPath_ (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService_Exporter_Md.js:21)\n    at async InteropService_Exporter_Md.prepareForProcessingItemType (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService_Exporter_Md.js:89)\n    at async InteropService.export (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:341)\n    at async Function.export (/tmp/.mount_joplinhztxau/resources/app.asar/InteropServiceHelper.js:163)\n    at async click (/tmp/.mount_joplinhztxau/resources/app.asar/app.js:430)\n```\n    ","created_time":1594588898879,"updated_time":1594588954336,"is_conflict":0,"latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplin-desktop","source_application":"net.cozic.joplin-desktop","application_data":"","order":1594588898877,"user_created_time":1594588898879,"user_updated_time":1594588954336,"encryption_cipher_text":"","encryption_applied":0,"markup_language":1,"is_shared":0,"type_":1}"
2020-07-12 23:48:39: "DecryptionWorker: cannot start because no master key is currently loaded."
2020-07-12 23:48:41: "RevisionService::maintenance: Starting..."
2020-07-12 23:48:41: "RevisionService::maintenance: Service is enabled"
2020-07-12 23:48:41: "RevisionService::collectRevisions: Created revisions for 0 notes"
2020-07-12 23:48:41: "RevisionService::maintenance: Done in 109ms"
2020-07-12 23:48:51: "SearchEngine: Updating FTS table..."
2020-07-12 23:48:51: "Preparing scheduled sync"
2020-07-12 23:48:51: "Starting scheduled sync"
2020-07-12 23:48:51: "Sync: starting: Starting synchronisation to target 2... [1594590531893]"
2020-07-12 23:48:51: "mkdir /home/nl/.local/share/joplin/.sync"
2020-07-12 23:48:51: "mkdir /home/nl/.local/share/joplin/.lock"
2020-07-12 23:48:51: "mkdir /home/nl/.local/share/joplin/.resource"
2020-07-12 23:48:51: "list /home/nl/.local/share/joplin"
2020-07-12 23:48:51: "get /home/nl/.local/share/joplin/.sync/version.txt"
2020-07-12 23:48:51: "put /home/nl/.local/share/joplin/.sync/version.txt", "null"
2020-07-12 23:48:51: "SearchEngine: Updated FTS table in 2ms. Inserted: 0. Deleted: 0"
2020-07-12 23:48:51: "delta /home/nl/.local/share/joplin"
2020-07-12 23:48:52: "BasicDelta: Report: {"timestamp":1594589167985,"older":1590,"newer":0,"equal":1}"
2020-07-12 23:48:52: "Sync: fetchingTotal: Fetching delta items from sync target"
2020-07-12 23:48:52: "Sync: finished: Synchronisation finished [1594590531893]"
2020-07-12 23:48:52: "Operations completed: "
2020-07-12 23:48:52: "fetchingTotal: -"
2020-07-12 23:48:52: "Total folders: 79"
2020-07-12 23:48:52: "Total notes: 241"
2020-07-12 23:48:52: "Total resources: 481"
2020-07-12 23:48:52: "Setting up recurrent sync with interval 300"
2020-07-12 23:48:52: "Updating all notifications..."
2020-07-12 23:48:52: "Garbage collecting alarms..."
2020-07-12 23:48:52: "Sync has finished and note has never been changed - reloading it"
</details>

## Development console log

<details>
  <summary>Click to expand development console log</summary>

/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:373 TypeError: Cannot read property 'type_' of undefined
    at InteropService_Exporter_Md.makeDirPath_ (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService_Exporter_Md.js:21)
    at async InteropService_Exporter_Md.processItem (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService_Exporter_Md.js:108)
    at async InteropService.export (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:371)
    at async Function.export (/tmp/.mount_joplinhztxau/resources/app.asar/InteropServiceHelper.js:163)
    at async click (/tmp/.mount_joplinhztxau/resources/app.asar/app.js:430)
export @ /tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:373
async function (async)
export @ /tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:279
export @ /tmp/.mount_joplinhztxau/resources/app.asar/InteropServiceHelper.js:163
click @ /tmp/.mount_joplinhztxau/resources/app.asar/app.js:430
apply @ callbacks-registry.ts:45
(anonymous) @ remote.js:292
(anonymous) @ remote.js:272
emit @ events.js:210
onMessage @ init.ts:50

/tmp/.mount_joplinhztxau/resources/app.asar/InteropServiceHelper.js:166 TypeError: Cannot read property 'type_' of undefined
    at InteropService_Exporter_Md.makeDirPath_ (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService_Exporter_Md.js:21)
    at async InteropService_Exporter_Md.prepareForProcessingItemType (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService_Exporter_Md.js:89)
    at async InteropService.export (/tmp/.mount_joplinhztxau/resources/app.asar/lib/services/InteropService.js:341)
    at async Function.export (/tmp/.mount_joplinhztxau/resources/app.asar/InteropServiceHelper.js:163)
    at async click (/tmp/.mount_joplinhztxau/resources/app.asar/app.js:430)

</details>

**Comment by laurent22** [comment] 2020-07-13 11:17
Is that the whole log? As there's no info there about the export operation. Also could you check the console too? https://joplinapp.org/debugging

**Comment by promisedlandt** [comment] 2020-07-13 11:43
Yes, that is the whole log unfortunately (opened Joplin, tried the export, closed Joplin, that's the whole log).

I have edited the issue with the error from the development console (looks like the same message as in the log file).

**Comment by laurent22** [comment] 2020-09-07 21:16
Duplicate of #3689

**Closed by laurent22** 2020-09-07 21:16 UTC
Labels: bug, desktop, high
