### ISSUE TITLE
Re-size to-do list column

### ISSUE THREAD

**Issue by internetjanitor** [laurent22/joplin#50] opened 2017-12-01 15:20 UTC
### Operating system
- [X ] Windows

### Application
- [X ] Desktop
---

When using the To-do list feature, I would like to be able to hide the content pane and/or resize the todo column so that I can use longer titles.

**Comment by laurent22** [comment] 2017-12-01 16:10
Duplicate of https://github.com/laurent22/joplin/issues/50

**Closed by laurent22** 2017-12-01 16:10 UTC
