### ISSUE TITLE
Any way to change add-on buttons in the WYSIWYG editor from the generic "Gear" icon to something else?

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#8433] opened 2023-07-09 05:06 UTC
I have a few add-ons installed that add buttons to the toolbar. They look fine in markdown editor mode, but in the WYSIWYG mode they all appear as gear icons. See this image:

![jop](https://github.com/laurent22/joplin/assets/33441569/d10212aa-b787-4911-adff-00bd7fa9f346)

## Environment

Joplin version: 

Joplin 2.12.4 (prod, win32)

Client ID: 4dab185d885945ac897a0608af59c6f7
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: dabcd3d

Markdown Prettier: 0.1.0
Menu items, Shortcuts, Toolbar icons: 1.1.0
MultiMarkdown Table Tools: 1.0.0
Quick HTML tags: 0.2.0
Rich Markdown: 0.13.2
Simple Highlighter: 1.0.0
Suitcase: 0.3.0
Table Formatter Plugin: 1.2.1

Platform: Windows
OS specifics: Windows 10 Pro x64 22H2

## Steps to reproduce

1. Install the plugins I have installed (Listed above)
2. Switch to WYSIWYG mode
3. Observe the huge row of gear icons.

## Describe what you expected to happen

I expected each plugin to have custom icons for their functionality. Since they don't, I'd like to change these icons. Or maybe I'm doing something wrong.

## Logfile

Here is a log of my console:

[Joplin Console Log.log](https://github.com/laurent22/joplin/files/11994452/Joplin.Console.Log.log)

It looks like there are a LOT of errors. I don't know why, Joplin functions fine except for the icon issue.

I would really appreciate any help.

**Comment by personalizedrefrigerator** [comment] 2023-07-09 22:17
## Summary

Joplin doesn't allow plugin authors to specify icons for the rich text editor (this is a bug).

## Explanation

It looks like TinyMCE has a different set of icons available from the markdown editor: [TinyMCE icons](https://www.tiny.cloud/docs/advanced/editor-icon-identifiers/).

Looking through the relevant code, Joplin uses the `preferences` icon if a toolbar command doesn't have a `tinymceIconName` registered:

https://github.com/laurent22/joplin/blob/d2b64f9af0b22873d450abfbfaacb7405ec1a41a/packages/lib/services/CommandService.ts#L302

<details>

The above code is called from here:
https://github.com/laurent22/joplin/blob/d2b64f9af0b22873d450abfbfaacb7405ec1a41a/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L658-L662

</details>

However, **tinymceIconName** is **not** one of the properties that is stored when registering a toolbar command:
https://github.com/laurent22/joplin/blob/d2b64f9af0b22873d450abfbfaacb7405ec1a41a/packages/lib/services/plugins/api/JoplinCommands.ts#L95-L105

Above, only the `iconName` property is copied over from the toolbar command (`tinymceIconName`, if it exists, is ignored).

Thus, this issue can be fixed by either
1. allowing plugin authors to specify `tinymceIconName`s when registering toolbar commands; or
2. getting the icon set used with the markdown editor to work in the TinyMCE toolbar.

**Comment by dpoulton-github** [comment] 2023-07-14 12:38
> Thus, this issue can be fixed by either
>
>    1. allowing plugin authors to specify tinymceIconNames when registering toolbar commands; or
>    1. getting the icon set used with the markdown editor to work in the TinyMCE toolbar.

It might also be useful to try to find a way to prevent plugins that do not work with the rich-text editor from adding icons to its toolbar.

**Comment by laurent22** [comment] 2023-07-18 14:03
> getting the icon set used with the markdown editor to work in the TinyMCE toolbar.

Yes I think that's what we should do

**Comment by laurent22** [comment] 2023-07-18 14:03
Duplicate of #8504

**Closed as completed by laurent22** 2023-07-18 14:03 UTC
Labels: bug
