### ISSUE TITLE
Support RTL languages

### ISSUE THREAD

**Issue by Yolakalemowa** [laurent22/joplin#9990] opened 2024-02-23 22:12 UTC
### Operating system

iOS

### Joplin version

12.13.10

### Current behaviour

1. Try to type in Arabic.
2. Text appears LTR (on the left side of the note)

### Expected behaviour

RTL languages like Arabic are expected to appear RTL, starting from the Right side of the note.
EVEN if the note has two languages English (LTR) and Arabic (RTL), Joploin is expected to respect both even in the same note.

**Comment by Yolakalemowa** [comment] 2024-02-23 22:12
many similar issues in the past I found that have been closed due to long time of inactivity but bug never resolved.

**Comment by tessus** [comment] 2024-02-24 02:08
nope, there's one open.

duplicate of #3991

**Closed as completed by tessus** 2024-02-24 02:08 UTC
Labels: bug
