### ISSUE TITLE
Request: Upload of image as raw file not possible

### ISSUE THREAD

**Issue by christianlupus** [laurent22/joplin#2437] opened 2020-02-04 09:45 UTC
I need to add a high-resolution image to a note that must be kept at high resolution (screenshot of 3 monitors next to each other -> approx 6000px width). When adding the image as it is #1232, #1035, and similar hits.
I thought I could add the image as an appendix (without preview, perfectly fine). However, this is not possible: the image gets detected and added as an image (with rescaling).

So, I ask for functionality to add a file as an appendix without looking into MIME type or whatever is done under the hood.

## Environment

Joplin version: 1.0.179
Platform: LInux
OS specifcs: Archlinux, AUR-Package

As this is a mere feature request, I will skip the reproduction and logs section.

**Comment by bedwardly-down** [comment] 2020-02-04 09:53
Since this is not actually a **bug** per se, have you thought about posting it on the[ forums](https://discourse.joplinapp.org/)? After doing a quick search, I'm surprised that this isn't actually a feature request others have made on there but instead just a bug report here. I think others there could further help you flesh out your idea.

I do know that a huge part of why the images are compressed is due to syncing limitations and mobile support. There are probably ways around it but they may not be feasible with the current code base and having massive uncompressed images is almost certainly an edge case usage here. But, I'm not a dev here, just a minor contributor and many of the people on the forums are substantially smarter than I am. Ha

**Comment by christianlupus** [comment] 2020-02-04 10:34
Crossposting just for reference: https://discourse.joplinapp.org/t/allow-to-add-an-image-as-a-raw-attachment/5629

**Comment by laurent22** [comment] 2020-02-04 11:00
This would be a duplicate of #1232

**Closed by laurent22** 2020-02-04 11:00 UTC
Labels: bug
