### ISSUE TITLE
Fold/unfold Notebook/Tag trees + sync status visibility

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#222] opened 2018-02-16 15:52 UTC
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Great app! I've just imported a _huge_ ENEX file, and it worked perfectly. One side effect, however, is that I have a couple of hundred tags collected in Evernote over the years which fill the left panel. It would be great if the Notebook and Tags trees could be folded and unfolded?

On a similar note, I currently have to scroll waaay down my tag list to see the sync status - I feel this should be visible all the time, since it's important info (or optionally, perhaps).

**Comment by foxmask** [comment] 2018-03-14 10:31
if we could have the same for android (and I suppose for others devices) that'll be perfect.

**Comment by kajiev** [comment] 2018-06-18 07:11
Is it the same as #522 ?

**Comment by foxmask** [comment] 2018-06-18 07:31
yes as this issue is a 3 in 1 :)

**Comment by msbentley** [comment] 2018-06-25 07:33
Excuse my confusion, but it looks like this issue and #522 are closed, but have they been solved? I haven't seen anything in the changelog of recent releases etc. Perhaps I missed it, but just checking!

**Comment by foxmask** [comment] 2018-06-25 07:54
was closed because duplicate of the current one

**Comment by msbentley** [comment] 2018-06-25 08:49
Ahh, sorry, my bad - understood now - I was mis-reading the label above and thinking this issue was closed too... sorry!

**Comment by foxmask** [comment] 2018-06-25 08:50
no problem :)

**Comment by alexdevero** [comment] 2018-11-15 13:56
+1 for desktop (Windows) and also for mobile. This could be very useful since the button for manual synchronization is placed under the notebooks and tags.

**Comment by photonxp** [comment] 2019-01-11 08:52
Sorry for being late for the comment. But after checking the issue of #1001 #1002, I think an alternative solution for this problem could be:
1) Give a relative height to the "synchronize area" at the bottom of the "notebook-tag-sync" pane. 
2) Make the "synchronize area" always visible if the "notebook-tag-sync" pane is also visible, unless new feature is added to toggle the view of "synchronize area", etc..

This way, to see the sync info, an user doesn't have to click anything, so the user experience is simpler. Meanwhile, the workload for dev isn't increased too much, I presume.

UPDATE:
After more thought, I think the two solutions could co-exist. We would probably need to toggle the view of notebook/tag/(or sync) whether we need the sync info or not.

**Comment by tessus** [comment] 2019-05-08 19:31
This has already been fixed.

**Closed by tessus** 2019-05-08 19:31 UTC
Labels: enhancement
