### ISSUE TITLE
Undefined unknown status code despite synch config passing as correct

### ISSUE THREAD

**Issue by dgcuff** [laurent22/joplin#8251] opened 2023-05-29 15:23 UTC
Include screenshots for UI problems if needed.

Tell me how to attach screenshots and I will. 

Tell me how to get the app to do more than display the log file in a window that does not all me to select it and I’ll do that too 

## Environment

Joplin version: 12.11.2
Platform: iOS
OS specifics: 16.5

## Steps to reproduce

1. Use the iOS successfully for months with joplincloud.
2. Have to replace the phone.
3. Try to log back in using the iOS app on the new phone.
4. Fill in credentials in app.
5. Check synchronization configuration. 
6. Start synch. Get error. 
7. Try deleting and reinstalling the iOS app.
8. Repeat steps 4-6.
9. Use laptop to confirm that macOS allows me to synch. 

## Describe what you expected to happen

Be able to log in once I supplied credentials. 

## Logfile

I cannot get the app to do more than SHOW me the log file. 

It’s all very well to require that I copy and paste text rather than create a screenshot, but the iOS app will not let me select text. Which means I cannot copy or paste it.

**Comment by laurent22** [comment] 2023-05-29 16:30
Duplicate of #8252

**Closed as completed by laurent22** 2023-05-29 16:30 UTC
Labels: bug
