### ISSUE TITLE
[Feature Request] "Dark Mode" à la Sublime/Atom for all platforms

### ISSUE THREAD

**Issue by Duke-Igthorn** [laurent22/joplin#690] opened 2018-07-20 14:16 UTC
### Operating system
- Windows
- macOS
- Linux
- Android
- iOS

### Application
- Desktop
- Mobile

### Request

An optional "Dark Mode", resembling the style of Sublime and Atom, where the background is a dark grey/black/blue and the text some shade of light grey/white.

In many settings this is much less straining for the eyes and should be super easy to implement.
Basically a continuation of what the side bar already does. :)

**Comment by tessus** [comment] 2018-07-20 18:50
Duplicate of #93

**Comment by tessus** [comment] 2018-07-20 18:53
Please note that you can already create themes for the mobile apps. On mobiles you can currently choose between a light and a dark theme. But there's nothing from stopping you to create a new theme and add it via a PR.

**Comment by Duke-Igthorn** [comment] 2018-07-20 19:06
Oh dang I missed that there was already a theme request. Kinda got lost in the masses. My bad!

**Comment by tessus** [comment] 2018-07-20 19:11
No worries, I made the same mistake. Actually... for this very issue. ;-)
( I opened #400) hahaha

**Closed** 2018-07-25 16:11 UTC
