### ISSUE TITLE
Not able to print under Linux

### ISSUE THREAD

**Issue by jadupl2** [laurent22/joplin#8240] opened 2023-05-26 15:36 UTC
Using Ubuntu 22.04 and RHEL 9.2 , Got 2 printers that I use all the time.
I never been able to print (using 2.10.19) 
Joplin just crash, should be easy to reproduce.
Problem has been there for a long time. 

I love your product, I am using Joplin Cloud, I love the fact that we can export to markdown.
I am using it on Mac, Windows, Linux, IOS, just work great.
Thanks in advance.

**Comment by Petemir** [comment] 2023-05-26 15:41
I suggest running joplin from the command line and pasting the terminal output here.

**Comment by Daeraxa** [comment] 2023-05-26 16:30
Duplicate of https://github.com/laurent22/joplin/issues/3161

**Closed as completed by Daeraxa** 2023-05-26 16:30 UTC
Labels: bug
