### ISSUE TITLE
SOS !! macos Cannot read property 'note_count' of undefined  

### ISSUE THREAD

**Issue by snailman** [laurent22/joplin#2079] opened 2019-11-12 09:32 UTC
Fatal error:

Cannot read property 'note_count' of undefined

TypeError: Cannot read property 'note_count' of undefined
    at noteCounts.forEach (/Applications/Joplin.app/Contents/Resources/app/lib/models/Folder.js:124:33)
    at Array.forEach (<anonymous>)
    at Function.addNoteCounts (/Applications/Joplin.app/Contents/Resources/app/lib/models/Folder.js:120:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by laurent22** [comment] 2019-11-12 09:44
@erdody, it happens on this line: https://github.com/laurent22/joplin/blob/9e227200af6b9513dba7f62d92e19eb3be969138/ReactNativeClient/lib/models/Folder.js#L124

Any idea what could be the issue? I think I'll hot-fix it later today by just checking if folder is undefined and skip it, if it is, but it would be good to understand what's causing this.

**Comment by genneko** [comment] 2019-11-12 09:45
I encountered exactly the same problem after upgrading to v1.0.173.
My temporary solution is as follows. I'm not sure about its root cause but there's similar checks all around in the file.
```
diff --git a/ReactNativeClient/lib/models/Folder.js b/ReactNativeClient/lib/models/Folder.js
index f994224a..5f9b6c50 100644
--- a/ReactNativeClient/lib/models/Folder.js
+++ b/ReactNativeClient/lib/models/Folder.js
@@ -121,6 +121,7 @@ class Folder extends BaseItem {
 			let parentId = noteCount.folder_id;
 			do {
 				let folder = foldersById[parentId];
+				if(!folder) break;
 				folder.note_count = (folder.note_count || 0) + noteCount.note_count;
 				parentId = folder.parent_id;
 			} while (parentId);
```

**Comment by laurent22** [comment] 2019-11-12 09:53
@genneko, @snailman, was the Conflict notebooks in the sidebar when you got this error?

**Comment by genneko** [comment] 2019-11-12 10:06
@laurent22 
No. I suspected that but I didn't have the folder. I also quickly queried the database for notes associated with non-existing folder but couldn't find ones.

**Comment by genneko** [comment] 2019-11-12 10:17
Correction. Actually I couldn't check the sidebar because when I got the error, the app exited right after closing the dialog box. I only examined folders and notes through sqlite3 command afterwards. Sorry for my confusion. That was a few hours before and now I don't have access to the system where the error occurred.

**Comment by laurent22** [comment] 2019-11-12 10:20
Come to think of it, it would also happen while syncing, when a notebook is downloaded but its parent hasn't been downloaded yet. So indeed the fix will simply be to check if the folder exists before proceeding.

**Comment by snailman** [comment] 2019-11-12 10:27
I changed Synchronisation from `one drive` to `File system` and then   click the `Synchronise` button and the same time  delete some files in the local directory ;close the app immediately , I got the error when restart the app.

**Closed** 2019-11-12 17:56 UTC
Labels: bug

**Comment by erdody** [comment] 2019-11-12 18:02
@laurent22 as mentioned, the most likely explanation is a reference (in the folders table) to a non-existing folder id. If we used a view, as we do with tags, that would have been avoided, at the cost of always querying for counts, even if the feature is not enabled.
