### ISSUE TITLE
[Android] Alarm date/time changes not saved in version 2.12.2

### ISSUE THREAD

**Issue by andrzej-nov** [laurent22/joplin#8805] opened 2023-09-09 06:33 UTC
In Android Joplin app version 2.12.2, saving alarm date/time stopped working. Now I have only my desktop version to edit alarms.

## Environment

Joplin version: 2.12.2
Platform: Android
OS specifics: Android 8, Android 10

## Steps to reproduce

1. Open a To-Do item.
2. Menu - Set alarm - Set Date - change to any date/time
3. Save Alarm
4. The alarm date/time changes are immediately reset to the initial values.

## Describe what you expected to happen

Alarm date/time saved, and then synchronized to the server.

**Comment by JackGruber** [comment] 2023-09-09 10:11
I think the same as here: https://github.com/laurent22/joplin/issues/8789

**Comment by andrzej-nov** [comment] 2023-09-09 10:20
> I think the same as here: #8789

Right, or at least it's very close.

**Comment by laurent22** [comment] 2023-09-10 11:33
Duplicate of https://github.com/laurent22/joplin/issues/8789

**Closed as completed by laurent22** 2023-09-10 11:33 UTC
Labels: bug
