### ISSUE TITLE
[Feature request] Free custom order of notebooks and notes - not automatic

### ISSUE THREAD

**Issue by v-marinkov** [laurent22/joplin#1628] opened 2019-06-06 20:16 UTC
### Operating system
- Windows
- macOS
- Linux

### Application
- Desktop

### Request
I would like to be able to re-order notebooks and notes in a fully custom manner. This should be another option along with sort by name or date. The custom sorting should be remembered so that switching temporarily to sort by name/date would be reversible to the custom order.

Reordering should be supported by drag&drop and keyboard shortcuts - say Ctrl+Up/Down.

Dynalist is an example of an application which does this very well (apart from keyboard shortcuts).

Thanks!

**Comment by tessus** [comment] 2019-06-07 09:23
this has been requested several times before. There's an issue open for this already.

Duplicate of #51

**Closed by tessus** 2019-06-07 09:23 UTC
