### ISSUE TITLE
Removing old/unused translation strings

### ISSUE THREAD

**Issue by milotype** [laurent22/joplin#7948] opened 2023-03-19 14:13 UTC
@laurent22 @tessus 
I've reverted the Croatian translation file with old/unused strings in #7947 as you asked for.

**QUESTION:**
Why do you insist to keep old/unused strings in the `.po` files? IMO, that is not necessary.

In most projects I translate, I remove those strings. That way, the `.pot` and `.po` are in sync. Keeping old/unused strings in the `.po` files simply makes those files bigger then needed and don't help translators is any way.

P.S. This is just my opinion.

**Comment by tessus** [comment] 2023-03-19 23:20
There are a few reasons actually:

1. > Keeping old/unused strings in the .po files simply makes those files bigger then needed and don't help translators is any way.

   It might not help the translator directly, but the free version of Poedit. If you are using the free version, Poedit won't retrieve possible translations from an online database (or only in a very limited way). Old (commented out) translations however are taken into account by Poedit.

   Furthermore Joplin does not use the `.po` files, but json files that are generated from the `.po` files. These generated files do not include any comments, so the size argument is irrelevant in this case.

2. It sometimes happens that we remove a translation which is later added again.

3. We are not using context related information in the .pot or .po files, because the .pot and .po files are generated by gettext. This means they'd be overwritten every time they are updated. Old translations _could_ help translators to crasp the context when in doubt.

**Comment by tessus** [comment] 2023-03-19 23:24
We use github issues for reproducible bugs and accepted feature request. I'll close this issue, but you still should be able to add comments. However, we'd prefer to use the forum for discussions like this.
A lot more people read forum posts than gh issues, thus if you also want input from other contributors and/or the community, posts in the forum make more sense.

**Closed as completed by tessus** 2023-03-19 23:24 UTC
