### ISSUE TITLE
Request: Nextcloud Tasks within Joplin

### ISSUE THREAD

**Issue by sunjam** [laurent22/joplin#230] opened 2018-02-17 19:26 UTC
I’d like to request the ability to at least view [Nextcloud Tasks](https://github.com/nextcloud/tasks) within Joplin

**Comment by laurent22** [comment] 2018-03-07 17:48
This is linked to #228 since if integration with Notes ever works, integration with Tasks should too. Closing as duplicate of #228

**Comment by laurent22** [comment] 2018-03-07 17:49
Duplicate of #228

**Closed by laurent22** 2018-03-07 17:48 UTC
