### ISSUE TITLE
Backtick when text is selected replaces it rather than wrapping in backticks

### ISSUE THREAD

**Issue by semyl** [laurent22/joplin#8122] opened 2023-05-03 15:39 UTC
## Environment

Joplin version: 2.9.17 (prod, win32)
Platform: Joplin for Desktop
OS specifics: Windows

## Steps to reproduce

1. Write some text
2. Select it
3. Type the backtick character `
4. The text is replaced with the backtick

## Describe what you expected to happen
I would expect the selected text to be retained and to be wrapped in backticks. Just like it is if text is selected and then an opening bracket or quotation mark is typed then the selected text is enclosed in that character.

**Comment by dpoulton-github** [comment] 2023-05-03 16:30
https://github.com/laurent22/joplin/issues/7694 seems to show that this has been reported and fixed. It looks like the fix was merged in FEB23 which would mean that it was included in a 2.10.x pre-release. As of yet none of the v2.10.x versions have been classed as a full release so the v2.9.17 desktop client will not indicate an update is available (unless including pre-releases is enabled in the application settings).

**Comment by Daeraxa** [comment] 2023-05-03 16:48
Yup, duplicate of https://github.com/laurent22/joplin/issues/7694

**Closed as completed by Daeraxa** 2023-05-03 16:48 UTC
Labels: bug
