### ISSUE TITLE
Create customizable workflow for terminal tool

### ISSUE THREAD

**Issue by pablojmarti** [laurent22/joplin#28] opened 2017-11-30 15:58 UTC
I was wondering if its possible to create a customizable workflow for the terminal tool. I would love to be able to use vim motions to use this system. If theres anyway I could help please let me know.

**Comment by laurent22** [comment] 2017-12-07 00:41
Actually this is a duplicate of https://github.com/laurent22/joplin/issues/63 but this is a good point, it should be configurable.

**Closed by laurent22** 2017-12-07 00:41 UTC
Labels: enhancement
