### ISSUE TITLE
(Math formula rendering) Horizontal division line of fractional disappeared

### ISSUE THREAD

**Issue by kenvix** [laurent22/joplin#4464] opened 2021-02-03 14:45 UTC
## Environment

Joplin version: 1.7.11 （prod, win32）
Platform:  Windows 10
OS specifics:  Microsoft Windows 10.0.19042.746 64bit

## Steps to reproduce

Write a math formula with below code:

```
$(ln|x|)'=\frac{1}{x}$

$$
\lim_{\Delta x \to 0}\frac{\Delta y}{\Delta x}=\lim_{\Delta x \to 0}\frac{f(x_0+\Delta x)-f(x_0)}{\Delta x}
$$
```

## Describe what you expected to happen

Expected (Rendered by vscode):

![image](https://user-images.githubusercontent.com/4546175/106762708-12579780-6671-11eb-9dd7-e726587d7214.png)
![image](https://user-images.githubusercontent.com/4546175/106762512-dde3db80-6670-11eb-9e40-6b6863d6a691.png)

Actual (Rendered by joplin):

![image](https://user-images.githubusercontent.com/4546175/106762724-1683b500-6671-11eb-8612-c7c549e7ceb4.png)
![image](https://user-images.githubusercontent.com/4546175/106762557-e9370700-6670-11eb-839c-3ae6b02690e5.png)

Obviously, horizontal division line of fractional disappeared

In addition, I remember that in the early version of joplin it worked normally, but it has disappeared since the UI was revised last year 

## Logfile

No logs available

**Comment by laurent22** [comment] 2021-02-03 15:52
It works for me on .11:

![image](https://user-images.githubusercontent.com/1285584/106772278-c0dee680-6637-11eb-8f45-301a4c7600ef.png)

Do you maybe have some custom CSS that could affect how the formulaes are rendered?

**Comment by tessus** [comment] 2021-02-03 17:40
It's an upstream bug. A combination of Chromium version and katex. Depending on the zoom level, the line appears and disappears.

Duplicate of #4194. Closing this one.

**Closed by tessus** 2021-02-03 17:40 UTC
Labels: bug, upstream

**Comment by talrowe** [comment] 2021-03-21 07:03
I am also having this issue. It works when you use \above or \genfrac when you specify the size but does not seem to render for the other types of fractions. I am also using Joplin.
![joplin fraction issue](https://user-images.githubusercontent.com/81068364/111896724-8d8ac800-89e9-11eb-9d6b-2c7e6d796682.PNG)

**Comment by Archer73** [comment] 2021-06-01 16:44
I am having some issue on Windows 10, FullHD resolution with interface scaling from 120 to 138 %. With interface scaling 100 %, 139 % and above, horizontal division lines renders correctly.

**Comment by tessus** [comment] 2021-06-01 17:01
Guys, did you read any of my comments? It's an upstream issue. So either Electron or Chromium fixes this, or you are out of luck. There's nothing we (as the Joplin team) can do about this problem.
