### ISSUE TITLE
Problem with drag and dropping the file (attachment) into the note

### ISSUE THREAD

**Issue by dgutkowsky** [laurent22/joplin#3557] opened 2020-07-25 17:42 UTC
When I drag and drop a file into the note I expect it to be placed on the line of the note I have chosen.
Instead it is always being placed in the first line of the note.
Looks like some kind of regression as it was working fine few versions before. 

## Environment

Joplin version: 1.0.227
Platform: Windows
OS specifics: Windows 10 (1909)

## Steps to reproduce

1.  Drag the file onto the specific place in the note
2.  Drop the file in the specifc location in the note
3.  You see that the file is being attached in the first line of the note instead of desired place (line)

## Logfile

nothing specific here really

_console:_
Got ipc-message: noteRenderComplete undefined

_log file:_
2020-07-25 19:36:29: "AceEditor: execCommand", "{"name":"dropItems","value":{"type":"files","paths":["D:\\Desktop\\userstyle.css"],"createFileURL":false}}"
2020-07-25 19:36:29: "Attaching D:\Desktop\userstyle.css"
2020-07-25 19:36:29: "File was attached."
2020-07-25 19:36:29: "Saving note...",

**Comment by CalebJohn** [comment] 2020-07-25 18:30
Hi @dgutkowsky thanks for the report. I'm going to close this because it's a duplicate of #3425 .

**Closed by CalebJohn** 2020-07-25 18:30 UTC
Labels: bug
