### ISSUE TITLE
Ordered List(Numbered) resets to 00 after every multiple of 100.

### ISSUE THREAD

**Issue by riftsandroses** [laurent22/joplin#6486] opened 2022-05-03 19:07 UTC
After every 100th Number bullet, the number sets to 00 and then continues. Is this a bug or a feature. If it is a feature then it is not a good one because one will forget which count of 100 the bullet represents.
![Screenshot from 2022-05-04 00-27-38](https://user-images.githubusercontent.com/63180210/166524104-c8b9084a-d325-404c-bc4a-46d4e79d4b08.png)

P.S. : I WOULD LOVE TO HELP FIX THIS ISSUE BUT I ONLY KNOW JAVA & JAVASCRIPT, LET ME KNOW IF THAT WILL BE OF ANY HELP IN FIXING THIS

## Environment

Joplin version: 2.7.15
Platform: Linux
OS specifics: Pop!_OS 22.04 LTS

## Steps to reproduce

1. Make a new Notebook.
2. Make a new Note inside the created Notebook.
3. Make an Numbered Ordered List in Toggle Editors and make a hundred entries in the bullet points.

## Describe what you expected to happen

Instead of 00, 01, 02, etc. it was expected to have 100, 101, 102, etc. to make it easier for the user to know which count of hundred they are currently on.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/8613056/log.txt)

**Comment by Daeraxa** [comment] 2022-05-03 19:19
Duplicate of https://github.com/laurent22/joplin/issues/4715

**Closed as completed by Daeraxa** 2022-05-03 19:19 UTC
Labels: bug
