### ISSUE TITLE
The calendar view background shows wrong size

### ISSUE THREAD

**Issue by seltinusjulio** [laurent22/joplin#4637] opened 2021-03-08 06:35 UTC
![image](https://user-images.githubusercontent.com/55385705/110283518-cd79a480-8012-11eb-9083-6486c7d77ee7.png)

## Environment

Joplin 1.7.11 (prod, win32)

Client ID: f1acecb5f7d84d4286ac907c96f9eb5e
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)

## Steps to reproduce

1. Create a to-do
2. Add due date or an alarm
3. Click the date

## Describe what you expected to happen

I expected the background would fit the calendar view size

**Comment by CalebJohn** [comment] 2021-03-08 15:33
Thanks for the report, however it is a duplicate of #4397.

**Closed by CalebJohn** 2021-03-08 15:33 UTC
Labels: bug
