### ISSUE TITLE
CTRL+K does not work

### ISSUE THREAD

**Issue by ComputingFroggy** [laurent22/joplin#1342] opened 2019-03-14 16:16 UTC
### Operating system
- Linux

### Application
- Desktop

When typing some text, if I select text and press CTRL+K, nothing happens.
If I go to the menu and then choose option Edit=>Link, it works ... and if type again CTRL+K, now it works ... but if I go back to the editor pane and type some texte, CTRL+K still does not work.

I am not sure the previous [issue](https://github.com/laurent22/joplin/issues/1081) should be closed ! ;-)
Thanks for the effort ... we are nearly there ... but not there completely !

**Comment by tessus** [comment] 2019-03-14 19:04
Hmm, it did when I added the shortcut. Maybe there's been a change in the way Electron handles this in Electron 4.x. Or it could be a bug in Electron. Which version are you using?
@laurent22 have you noticed problems with shortcuts in Electron 4.x?

**Comment by ComputingFroggy** [comment] 2019-03-15 00:56
the latest 1.0.140

**Comment by tessus** [comment] 2019-03-15 23:14
Tested on macOS and I can't reproduce the issue. Maybe it's intermittent like the problem with copy from the preview area.

**Comment by ComputingFroggy** [comment] 2019-03-21 17:33
on Ubuntu 18.04, it's intermittent, it's permanent !

**Comment by cbop-dev** [comment] 2019-05-08 17:29
I have the same problem on Linux Mint 19.1 with 1.0.145: CTRL-K does NOT bring up link dialogue, except (and only) when I first click on the "link" button, and then press ESC, then CTRL-K.  But if the cursor moves, it no longer works.

**Comment by tessus** [comment] 2019-05-08 18:06
Unfortunately I can't reproduce this problem. It seems it might be related to Linux.
It could be an upstream issuelimited to Linux. 
@laurent22 did you come across this problem before?

**Comment by Grillpfanne** [comment] 2019-05-08 22:51
I have the same problem also on Linux Mint 19.1 with 1.0.145. CTRL-K is only working when the cursor focus is NOT in the section where you write notes, i.e. the cursor is not blinking.

**Comment by tessus** [comment] 2019-07-02 23:25
What's the status of this? Is this still not working with 1.0.160? Electron has been updated in the meantime, so maybe the update fixed the Linux issue.

**Comment by cbop-dev** [comment] 2019-07-03 07:24
@tessus The problem remains for me in v. 1.0.160 on Linux Mint 19.1 Cinnamon. CTRL-K does not open the link dialogue when the focus is in the editor window. I have to click on the toolbar button to open the dialogue.

**Comment by tessus** [comment] 2019-07-03 07:45
@cbop-dev does the menu item work? `Edit -> Link`

I think I know what might be going on. Unfortunately I have no idea how to confirm it. I don't have a Linux desktop. Only servers without UI.

Does anyone have a Linux Joplin dev env who could test a patch?

**Comment by tessus** [comment] 2019-07-03 07:55
@CalebJohn I think you use Linux, right? May I ask a favor?

Can you confirm that `CTRL+K` does not open the link dialog? If so, could you change line 866 in `NoteText.jsx` from 
```
			const letters = ['F', 'T', 'P', 'Q', 'L', ',', 'G'];
```
to
```
			const letters = ['F', 'T', 'P', 'Q', 'L', ',', 'G', 'K'];
```

I'm wondering, if this fixes the problem.

**Comment by cbop-dev** [comment] 2019-07-03 07:59
@tessus Yes, the "Link" menu item works for me. What's really strange is that I just noticed that when I select text within the editor, and try the keyboard shortcut, each time I press CTRL+K it behaves like a text search, cycling to the next instance of the selected text in the editor. (While I never noticed this before -- this may not be new behavior, I may have normally selected unique text.)

**Comment by tessus** [comment] 2019-07-03 08:08
@cbop-dev yep, that's what I thought. The ace editor shortcut overrides the electron shortcut.
Theoretically my fix should solve the problem, but I have to confirm this somehow.

Do you know how to extract app images? In that case you could test my fix.

Anyway, I have to get some sleep. ttyl.

**Comment by cbop-dev** [comment] 2019-07-03 08:16
@tessus I applied your fix and compiled locally, and it seems to fix the problem. CTRL+K works! Thanks. Hopefully this can be integrated into the public source and app images for future releases. Thanks!

**Comment by tessus** [comment] 2019-07-03 08:20
Awesome, thanks for testing. I'll open a PR, thus it will be in the next release.

Time for bed....

**Closed** 2019-07-13 13:52 UTC
Labels: Linux, bug, desktop, editor, windows

**Comment by bladewolf55** [comment] 2019-07-19 21:36
Yay! This was also not working in Windows, and I hadn't got around to reporting it. Thank you, Ctrl+K works now!
