### ISSUE TITLE
Invisible window on MacOS catalina for joplin desktop

### ISSUE THREAD

**Issue by ianforcements** [laurent22/joplin#2493] opened 2020-02-11 14:57 UTC
I opened my laptop today and noticed that my Joplin window had disappeared, although the dock icon and activity monitor indicated that the app was still running. I force-quit the app and opened it again, the window still did not appear. When I right click on the app icon in the dock, I have the option to "show all windows", when I select this I see the joplin window outline highlighted, but the app itself is not rendered. When I select this outline the app is not restored.
![Screen Shot 2020-02-11 at 15 41 06](https://user-images.githubusercontent.com/6646006/74246556-0139ac00-4ce5-11ea-9191-5e328b85e27d.png)

Some steps that I have tried:
- Quitting joplin from application menu and reopening
- Force-quitting joplin and reopening
- quitting joplin from activity monitor and reopening
- Force quitting Joplin, logging out of my profile and logging back in, restarting joplin
- Force-quitting joplin, restarting the machine, reopening joplin
- reinstalling joplin via homebrew
- uninstalling via homebrew and then reinstalling
- uninstalling via homebrew and then installing via web download
- using keyboard shortcuts to minimise the app / restore to full screen
- close joplin, delete ~/Library/Preferences/net.cozic.joplin-desktop.plist and restart joplin
- close joplin, delete ~/Library/Saved Application State/net.cozic.joplin-desktop.savedState and restart joplin
- rm -rf ./private/var/folders/_t/qvw6yld57xb460zzx0cjpt800000gn/C/net.cozic.joplin-desktop.helper.\(Renderer\)/
- rm -rf ./private/var/folders/_t/qvw6yld57xb460zzx0cjpt800000gn/C/net.cozic.joplin-desktop

## Environment

Joplin version: 1.0.179
Platform: MacOS
OS specifcs: Catalina 10.15.3

## Steps To Reproduce
I'm unable to return to the previous state so I can't come up with a set of concrete steps to reproduce this, but here's the rough process that seems to have generated the problem:
1. Connect to external monitor
2. Disconnect from external monitor
3. Use the laptop without an external monitor attached
3. Repeat steps 1-3 for a couple of weeks until joplin disappears

Describe what you expected to happen:

## Logfile

Unfortunately I am not able to attach a debug log - the steps provided do not work as I cannot see the application window. The application doesn't appear to crash either - it's just not rendered.

**Comment by ianforcements** [comment] 2020-02-11 15:24
After digging around a bit more, I saw https://github.com/laurent22/joplin/issues/2454
Whilst that applies to windows, the same file appears to have been corrupted in my case.

The following steps restored my Joplin:
1. quit joplin
2. Remove ~/Library/Application Support/Joplin/window-state.prod.json
3. start joplion

**Comment by tessus** [comment] 2020-02-11 20:52
duplicate of #2396 

see #2476
Somebody is workibg on it....

**Closed by tessus** 2020-02-11 20:52 UTC
Labels: bug
