### ISSUE TITLE
Feature request: wysiwyg editor

### ISSUE THREAD

**Issue by flatsiedatsie** [laurent22/joplin#873] opened 2018-10-10 12:55 UTC
I just discovered Joplin, after tying to find a Mac Notes alternative that would be more easy to backup. Joplin is almost perfect (although I would love it if the text backup would be a folder structure mirroring my notes). 

One thing is a show stopper: text an only be added in Markdown code?

For 'normal' people like me this is not an option. I wish I could just change the text using WYSIWYG instead. It this possible?

**Comment by laurent22** [comment] 2018-10-10 19:11
Closed as duplicate.

At the moment there's two options:

- Learn Markdown (it's quite easy, although I understand it's not everybody's cup of tea)
- Use an external WYSIWYG Markdown editor

**Closed by laurent22** 2018-10-10 19:11 UTC

**Comment by bernd-wechner** [comment] 2018-10-10 20:07
For the record a duplicate of https://github.com/laurent22/joplin/issues/176
Best to check open issues before filing. The occasional duplicate is fine and manageable but triage becomes an issue if they crop up too often too.
