### ISSUE TITLE
incomplete pdf exporter

### ISSUE THREAD

**Issue by tornadoyi** [laurent22/joplin#1827] opened 2019-08-23 08:40 UTC
## Environment

Joplin version:  1.0.165 (prod, darwin) 
Revision: f3ab21f (HEAD)
Platform: (prod, darwin)
OS specifcs:

## Steps To Reproduce

1. right click note
2. click export 
3. click pdf

Describe what you expected to happen:

export to pdf is incomplete. only current note page which is shown on screen is exported to pdf file.

**Comment by tessus** [comment] 2019-08-23 09:53
duplicate of #1815

**Closed by tessus** 2019-08-23 09:53 UTC
Labels: bug
