### ISSUE TITLE
Sync != backup? ||| Auto backup? ||| How does encryption work?

### ISSUE THREAD

**Issue by w123475** [laurent22/joplin#1518] opened 2019-05-13 08:55 UTC
I have several questions, each of which is related to the previous one. Can I ask them in one issue?

**Question one:**  _Do I understand correctly that synchronization is not a backup?_ I thought that if synchronization is on, then my data is safe. However, after reinstalling the system, I still did not understand how to restore them.

Of course, I had backup my homedir and therefore my records did not disappear, but did I understand correctly that if I needed a backup, then I had to do it myself and the sync function would not help me with this question?

**Question two:** _Is it possible to make an automatic backup?_ As I understand it, one of the best ways to backup data is export as raw. But I have to do it manually via the GUI.

Of course, this does not take much effort, but I would still like to automate this task. For example, as follows: add the ability to use multiple synchronization targets at once. So that I can simultaneously use WebDAV and a folder on my hard drive, the data from which goes to backup.

**Question three:** _What is the purpose of encryption? Is it only needed so that third parties (for example, Dropbox) cannot access synchronized data?_

It is fair to say that the ability to make an automatic backup is present now: I can copy the joplin-desktop and Joplin folders from my homedir.

However, I noticed that when transferring these folders from PC to PC, Joplin does not require entering a password. So, it is saved somewhere in these folders?

However, this is expected when you consider that Joplin never requires entering a password.

Does this mean that assigning a password is protecting my data during synchronization and nothing more?

If so, is it planned to add a transition to the system that KeePassX uses, for example? Everytime. when I want to open the database, I have to enter the password.

More specifically, I would like that after restarting my PC, you need to enter a password to access the data.

---

I hope I expressed my thoughts quite clearly :)

**Comment by laurent22** [comment] 2019-05-13 09:06
These questions are more suitable for the forum, and to be honest most of them have already been asked and answered.

Sync is to two-way sync: i.e. if you delete a file on target, it will be deleted on source too. With backups you don't want that because if you've accidentally deleted the file on target, you'll want to recover it.

You need specialised software to do automatic, incremental backups, so it's out of scope of this project. On the forum there are some examples on how to set up automatic backup with a cron and the Joplin CLI tool.

E2EE is also to prevent people who gain access to your Dropbox account from viewing your data.

**Closed by laurent22** 2019-05-13 09:06 UTC

**Comment by SteveHolle** [comment] 2019-05-16 16:32
laurent22 - The problem is not the backup.  A backup of the sync file directory is easy.  Generally, the size of the directory is not a problem to run complete backups.  The user is responsible for the backups.

The problem is that when restoring the full backup, Joplin will not display them.  The sync data is all there, Joplin will just not display it.  The only current solution is to close joplin, delete the joplin-desktop and reopen joplin and resync.  It seems there must be a simple way to tell joplin to reload the sync data and ignore the date.

Thank you for your consideration.

**Comment by laurent22** [comment] 2019-05-16 20:33
@SteveHolle, could you clarify how you restored the backup? Normally you would import the notes and that would create new notebooks and new notes, so they should sync as normal. Is that what you've done?
