### ISSUE TITLE
Create links to other notes

### ISSUE THREAD

**Issue by benallan** [laurent22/joplin#370] opened 2018-04-03 09:42 UTC
Is there any way to create a link from one note to another note, similar to a wiki?

I thought it might be possible if we use the UUID of the target note in a standard markdown link, but I can't see any way to get that UUID from the desktop interface. 

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by laurent22** [comment] 2018-04-04 02:02
Duplicate of #134

**Closed by laurent22** 2018-04-04 02:02 UTC
