### ISSUE TITLE
Error: Operation not permitted.

### ISSUE THREAD

**Issue by shumafuk** [laurent22/joplin#6973] opened 2022-10-28 09:42 UTC
## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: LineageOS 19.1

## Steps to reproduce

1. Set sync folder with encrypted notes (snyced by Snycthing) in Joplin (in my case /storage/emulated/0/joplin)
2. Synchronize
3. Error: Operation not permited (but I allowed acces to media only in app permission, however I cannot find option to grant full file access)

## Describe what you expected to happen
Import my encrypted notes into Joplin app on android.

**Comment by Daeraxa** [comment] 2022-10-28 13:01
Duplicate of https://github.com/laurent22/joplin/issues/5779, fix being tested in latest beta

**Closed as completed** 2022-10-28 13:01 UTC
Labels: bug
