### ISSUE TITLE
Keeps asking for the "login" keychain when it's locked

### ISSUE THREAD

**Issue by 6gfd8** [laurent22/joplin#4615] opened 2021-03-01 18:58 UTC
## Environment

Joplin version: 1.7.11
Platform: macOS
OS specifics: macOS 10.15.7

## Steps to reproduce

1. Preopen Joplin (Joplin needs to have access to the "login" keychain for at least one time, especially if Joplin is open for the first time since boot)
2. Open Keychain Access, then right-click the "login" keychain and select "Lock after x minutes of inactivity"
3. Wait for the "login" keychain to be locked
4. Open Joplin (or reopen it), then type something on a note
5. Ignore the "Joplin Helper (Renderer) wants to use the "login" keychain. Please enter the keychain password." diaglog by pressing `Cancel`.

## Describe what you expected to happen

Joplin shouldn't need to have access to the "login" keychain every time I want to use it, especially when it has no build-in on-disk encryption (which I hope the developer can change their mind on this, and yes, I know they think full disk encryption should be enough for this purpose) and when I set the synchronization interval to Disabled (i.e. manual synchronization only, which I will happily unlock the "login" keychain then).

This behavior is especially annoying when I set the auto-lock time to say 1 minute.

## Logfile

```
07:48:58: Could not set setting on the keychain. Will be saved to database instead: encryption.passwordCache: Error: User canceled the operation.
log @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:181
error @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:232
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:1295
rejected @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:6
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:4
saveAll @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:1255
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:179
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:4
syncTables_ @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:113
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:194
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:4
syncTables @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:191
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:97
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:4
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/searchengine/SearchEngine.js:95
listOnTimeout @ internal/timers.js:549
processTimers @ internal/timers.js:492
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:181

07:48:58: Settings have been saved.
```

**Comment by CalebJohn** [comment] 2021-03-01 19:49
@6gfd8 

It seems this is a misunderstanding on how the Joplin sync system works. Joplin will initiate a sync under 3 different conditions.
1. Sync button is pressed, or sync is initiated manually
2. The sync interval time has elapsed
3. Joplin will initiate a small sync around 5 seconds (I'm not sure the exact number) after a user stops typing. This is a necessary part of the Joplin sync system that is implemented to reduce conflicts.

If you have encryption enabled, then access to the login keychain will be necessary when any of these syncs are initiated.

You can take a look at #4512 for more context on this issue. But for now I will close this issue as it is indirectly a duplicate of the linked issue.

**Closed by CalebJohn** 2021-03-01 19:49 UTC
Labels: bug
