### ISSUE TITLE
"Some items cannot be decrypted"

### ISSUE THREAD

**Issue by serpest** [laurent22/joplin#4641] opened 2021-03-08 17:40 UTC
My configuration:
- Synchronisation target: Dropbox
- Encryption is: Enabled
- OS: Windows 10
- Joplin version: 1.3.18

Many users have reported the following issue: Joplin fails to decrypt some files in the syncing resources process and an annoying warning banner appears on the top of the window.

The behavior of Joplin when it can't decrypt a file is trying again to decrypt it, but it usually doesn't work and the only way to solve this issue is downloading manually the file from Dropbox, adding the ".crypted" extension and moving it to the Joplin resources folder.

Joplin should automatically try to download again the file or there should be a button in the synchronisation status menu to do that.

**Comment by CalebJohn** [comment] 2021-03-08 17:58
Hi @serpest

Do you mind updating to the [latest version of Joplin (v1.7.11)](https://github.com/laurent22/joplin/releases/tag/v1.7.11) and checking if it improves your situation?

In any case, this seems to be a duplicate of #4403. I'll close this and direct you there instead.

**Closed by CalebJohn** 2021-03-08 17:58 UTC
Labels: bug

**Comment by serpest** [comment] 2021-03-08 20:50
Hi @CalebJohn,

I've just realized that someone else has already found the [same solution](https://github.com/laurent22/joplin/issues/4403#issuecomment-775357728) as mine in #4403, so my comment is useless.
