### ISSUE TITLE
NextCloud: Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists

### ISSUE THREAD

**Issue by quotengrote** [laurent22/joplin#407] opened 2018-04-10 17:01 UTC
### Operating system
- Windows
- iOS

### Application
- Desktop
- Mobile

In NextCloud 13.0.1 an error occours when the mobile(iOS)/desktop(Win) application sync over Nextcloud.

[1] NextCloud-Log: "Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists" 
[2] Log of Joplin Desktop(Win)
[3] Console of Joplin

[1]
Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists
/var/www/vhosts/XXX.next-cloud.org/httpdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('Photos', Object(Sabre\DAV\MkCol))
[internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/vhosts/XXX.next-cloud.org/httpdocs/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/vhosts/XXX.next-cloud.org/httpdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)
/var/www/vhosts/XXX.next-cloud.org/httpdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/vhosts/XXX.next-cloud.org/httpdocs/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
/var/www/vhosts/XXX.next-cloud.org/httpdocs/remote.php - line 164: require_once('/var/www/vhosts...')
{main}

[2]
2018-04-10 18:58:29: "Profile directory: C:\Users\mg/.config/joplin-desktop"
2018-04-10 18:58:29: "Trying to load 0 master keys..."
2018-04-10 18:58:29: "Loaded master keys: 0"
2018-04-10 18:58:29: "Reducer action", "SETTING_UPDATE_ALL"
2018-04-10 18:58:29: "Refreshing notes:", "null", "null"
2018-04-10 18:58:29: "Reducer action", "NOTE_UPDATE_ALL, "{\"options\":{\"order\":[{\"by\":\"user_updated_time\",\"dir\":\"DESC\"}],\"uncompletedTodosOnTop\":true,\"caseInsensitive\":true},\"parentId\":null}""
2018-04-10 18:58:29: "Reducer action", "NOTE_SELECT, "
2018-04-10 18:58:29: "Trying to load 0 master keys..."
2018-04-10 18:58:29: "Loaded master keys: 0"
2018-04-10 18:58:29: "Reducer action", "MASTERKEY_REMOVE_NOT_LOADED"
2018-04-10 18:58:29: "Scheduling sync operation..."
2018-04-10 18:58:29: "Setting up recurrent sync with interval 300"
2018-04-10 18:58:29: "Reducer action", "FOLDER_UPDATE_ALL"
2018-04-10 18:58:29: "Reducer action", "TAG_UPDATE_ALL"
2018-04-10 18:58:29: "Reducer action", "MASTERKEY_UPDATE_ALL"
2018-04-10 18:58:29: "Reducer action", "FOLDER_SELECT, c04f1c7c04f1c7c04f1c7c04f1c7c04f"
2018-04-10 18:58:29: "Scheduling sync operation..."
2018-04-10 18:58:29: "Refreshing notes:", "2", "c04f1c7c04f1c7c04f1c7c04f1c7c04f"
2018-04-10 18:58:29: "Reducer action", "APP_STATE_SET"
2018-04-10 18:58:29: "Reducer action", "WINDOW_CONTENT_SIZE_SET"
2018-04-10 18:58:29: "Reducer action", "NOTE_VISIBLE_PANES_SET"
2018-04-10 18:58:29: "Reducer action", "SETTING_UPDATE_ONE"
2018-04-10 18:58:29: "Reducer action", "APP_STATE_SET"
2018-04-10 18:58:29: "Reducer action", "NOTE_UPDATE_ALL, "{\"options\":{\"order\":[{\"by\":\"user_updated_time\",\"dir\":\"DESC\"}],\"uncompletedTodosOnTop\":true,\"caseInsensitive\":true},\"parentId\":\"c04f1c7c04f1c7c04f1c7c04f1c7c04f\"}""
2018-04-10 18:58:30: "Reducer action", "NOTE_SELECT, "
2018-04-10 18:58:30: "DecryptionWorker: starting decryption..."
2018-04-10 18:58:30: "DecryptionWorker: completed decryption."
2018-04-10 18:58:31: "Scheduling sync operation..."
2018-04-10 18:58:31: "Preparing scheduled sync"
2018-04-10 18:58:31: "Starting scheduled sync"
2018-04-10 18:58:31: "Reducer action", "SYNC_STARTED"
2018-04-10 18:58:31: "Sync: starting: Starting synchronisation to target 5... [1523379511361]"
2018-04-10 18:58:31: "Reducer action", "SYNC_REPORT_UPDATE"
2018-04-10 18:58:31: "mkdir .sync"
2018-04-10 18:58:59: "ResourceService::indexNoteResources: Start"
2018-04-10 18:58:59: "ResourceService::indexNoteResources: Completed"
2018-04-10 18:58:59: "ResourceService::deleteOrphanResources:", "[]"
2018-04-10 18:59:00: "Reducer action", "WINDOW_CONTENT_SIZE_SET"
2018-04-10 18:59:09: "mkdir .resource"
2018-04-10 18:59:40: "delta "
2018-04-10 19:00:10: "Sync: fetchingTotal: Fetching delta items from sync target"
2018-04-10 19:00:10: "Reducer action", "SYNC_REPORT_UPDATE"
2018-04-10 19:00:10: "Sync: finished: Synchronisation finished [1523379511361]"
2018-04-10 19:00:10: "Reducer action", "SYNC_REPORT_UPDATE"
2018-04-10 19:00:10: "Operations completed: "
2018-04-10 19:00:10: "fetchingTotal: -"
2018-04-10 19:00:10: "Total folders: 0"
2018-04-10 19:00:10: "Total notes: 0"
2018-04-10 19:00:10: "Total resources: 0"
2018-04-10 19:00:10: "Reducer action", "SYNC_COMPLETED"
2018-04-10 19:00:10: "Setting up recurrent sync with interval 300"

[3]
[Violation] 'setTimeout' handler took 1157ms

**Comment by laurent22** [comment] 2018-04-16 14:28
Duplicate of another issue.

**Closed by laurent22** 2018-04-16 14:28 UTC

**Comment by quotengrote** [comment] 2018-04-16 15:47
which issue?

**Comment by laurent22** [comment] 2018-04-16 16:39
It comes up regularly and cannot be fixed (except maybe on Nextcloud side) https://github.com/laurent22/joplin/search?q=MethodNotAllowed&type=Issues
