### ISSUE TITLE
"FetchError: certificate has expired" with valid certificate (repeat of #3348)

### ISSUE THREAD

**Issue by hack-wizard** [laurent22/joplin#5525] opened 2021-10-03 02:51 UTC
Looks like this is back, confirmed with a friend trying to access my NextCloud share over WebDAV on both Linux and Windows.  Also confirmed on my own windows install.

Confirmed that the cert for my server is very much valid, but I get an error saying it is not when I have ignore TLS errors unchecked, happens with every sync.

Joplin version: 2.4.9 and before (updating made no difference)
Platform: Window, Linux
OS specifics: Occurs when "Ignore TLS Errors' is unchecked

## Steps to reproduce

1. Sync to my NextCloud over WebDAV (https://hack-wizard.twilightparadox.com in this case) with 
2. If Ignore TLS certificate Errors is unchecked, it gives error "FetchError: request to https://hack-wizard.twilightparadox.com/remote.php/dav/files/ncp/rpnotes/info.json failed, reason: certificate has expired"
3. If that is disabled it works without issue

Expectations:
I dunno... maybe properly evaluate SSL certs???

Console log:
C:\Users\hack-\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:188 19:44:07: Synchronizer: FetchError {name: "FetchError", message: "request to https://hack-wizard.twilightparadox.com…info.json failed, reason: certificate has expired", type: "system", errno: "CERT_HAS_EXPIRED", code: "CERT_HAS_EXPIRED", …}

log.txt:
2021-10-02 19:49:29: Synchronizer: "Sync: finished: Synchronisation finished [1633229347898]"
2021-10-02 19:49:29: Synchronizer: "Operations completed: "
2021-10-02 19:49:29: Synchronizer: "Total folders: 11"
2021-10-02 19:49:29: Synchronizer: "Total notes: 74"
2021-10-02 19:49:29: Synchronizer: "Total resources: 9"
2021-10-02 19:49:29: Synchronizer: "There was some errors:"
2021-10-02 19:49:29: Synchronizer: "FetchError: request to https://hack-wizard.twilightparadox.com/remote.php/dav/files/ncp/rpnotes/info.json failed, reason: certificate has expired
Code: CERT_HAS_EXPIRED
FetchError: request to https://hack-wizard.twilightparadox.com/remote.php/dav/files/ncp/rpnotes/info.json failed, reason: certificate has expired
    at ClientRequest.<anonymous> (C:\Users\hack-\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"

**Comment by CalebJohn** [comment] 2021-10-03 04:35
Can you test this with the current [pre-release (v2.5.1)](https://github.com/laurent22/joplin/releases/tag/v2.5.1)? Please let me  know if upgrading fixes your problem.

You can see more information related to this issue below.
https://discourse.joplinapp.org/t/fix-for-certificate-has-expired-error-with-joplin-cloud-and-self-hosted-sync-targets/20638
https://discourse.joplinapp.org/t/pre-release-v2-5-is-now-available-updated-2-oct/20702

**Comment by etemam** [comment] 2021-10-03 10:40
Hi,
same problem with Joplin 2.4.9 (mac os x version). I confirm that pre-release 2.5.1 fix the bug.

Thanks a lot.

**Comment by olafthiele** [comment] 2021-10-03 11:21
Fixes it for me (win10), thanks for the pre-release :-)

**Comment by tessus** [comment] 2021-10-03 11:51
Duplicate of #5513

**Closed by tessus** 2021-10-03 11:51 UTC
Labels: bug
