### ISSUE TITLE
Blank screen when leaving the app then coming back

### ISSUE THREAD

**Issue by jasonwilliams** [laurent22/joplin#11264] opened 2024-10-26 05:20 UTC
### Operating system

iOS

### Joplin version

13.0.7

### Current behaviour

1. Open a note (any note)
2. Swipe up to leave the app and navigate to another app
3. Come back
4. You now have a blank screen

### Expected behaviour

1. Open a note (any note)
2. Swipe up to leave the app and navigate to another app
3. Come back
4. You come back to the note you were on

This could be related to https://github.com/laurent22/joplin/issues/11197 but this is happening on iOS and you don’t need to restart the phone for it to happen.

Also after some messing around, it only seems not all notes do it, one or two will persist, but the majority of them turn blank when leaving the app.

In the video below, just the act of swiping up alone blanks out the screen. 
https://github.com/user-attachments/assets/e390c17d-9b37-4e48-8bce-3337c36c2a77

iOS 17

**Comment by bsavant** [comment] 2024-10-28 00:50
I can reproduce this consistently when you search, and the note you select is not in the current notebook.  iOS 18, Joplin 13.1.5

**Comment by dejafait** [comment] 2024-11-02 20:43
This is happening to me as well on Android.

**Comment by personalizedrefrigerator** [comment] 2024-11-04 20:31
I'm linking to the [commit](https://github.com/laurent22/joplin/commit/ddd18551eba98fa68433109b4fa6f419a897f48a) that resolved #9204. It should be in [Android v3.1.7](https://github.com/laurent22/joplin/releases/tag/android-v3.1.7).

**Comment by GonzRon** [comment] 2024-11-05 19:41
@personalizedrefrigerator I don't know if the commit you linked resolved #9204, after all the issue is still recurring in latest android version 3.1.7.  I think you may be referencing a different fix since I see the following.  So two separate issues two different commits.  
```
[root@ganymede joplin]# git tag --contains 2fc9bd476b0d9abcddb0a46f615a48333779d225
[root@ganymede joplin]# git branch --contains 2fc9bd476b0d9abcddb0a46f615a48333779d225
  contains
* dev
```

**Comment by Petemir** [comment] 2024-11-06 21:19
> I can reproduce this consistently when you search, and the note you select is not in the current notebook. iOS 18, Joplin 13.1.5

Just want to add that also activating Siri (Hey Siri) blanks the screen (after following the quoted steps)

**Comment by dejafait** [comment] 2024-12-05 12:09
Still happens on 3.2.2 Android fyi.

**Comment by personalizedrefrigerator** [comment] 2024-12-14 02:15
> Still happens on 3.2.2 Android fyi.

Thank you for noticing! That may be related to an incorrectly resolved conflict in [this merge commit](https://github.com/laurent22/joplin/commit/ca9759738f52693ddec903e0fb9eb7bb50511ecd).

<details>


In `release-3.1`, where a fix was originally merged, `noteId={noteId}` overrides the `noteId` specified in `props`:
https://github.com/laurent22/joplin/blob/9c4142fcd23c655215c2dacb241a68ccd5618cfd/packages/app-mobile/components/screens/Note.tsx#L1654

This change was made such that the note editor would continue to render the last-seen note id, even if `props.noteId` became `null`. This could happen if the note selection was cleared.


In `dev`, notice that `noteId` no longer overrides the `noteId` specified in `props`:
https://github.com/laurent22/joplin/blob/0a5bc9647d3f955282b03154ae3164e9fe40e927/packages/app-mobile/components/screens/Note/Note.tsx#L1606

As a result, clearing the selection would still cause the note editor to edit nothing. 

</details>

**Closed as completed** 2024-12-18 10:58 UTC
Labels: bug, mobile, high

**Comment by jasonwilliams** [comment] 2024-12-18 15:58
I don't know if you've already pushed a release out but I don't notice this anymore, thanks for fixing!
