### ISSUE TITLE
Version 2.9.2 appimage is giving a white screen on Linux Mint

### ISSUE THREAD

**Issue by MHolkamp** [laurent22/joplin#6756] opened 2022-08-17 07:08 UTC
Hi,

Version 2.9.2 seems to start, but ends in a white screen.
No error messages, just a white window with the menus above.

**Comment by Daeraxa** [comment] 2022-08-17 09:36
Duplicate of https://github.com/laurent22/joplin/issues/6752
Also in the beta feedback thread:
https://discourse.joplinapp.org/t/pre-release-v2-9-is-now-available-updated-12-august/26416/3
and https://discourse.joplinapp.org/t/i-am-dealing-with-a-problem-to-open-app-in-new-joplin-instalation/26890/

**Comment by dayfuaim** [comment] 2022-08-18 12:31
Same for me.
Ubuntu 22.10.

**Comment by laurent22** [comment] 2022-08-18 13:11
Is it any better in this release? https://github.com/laurent22/joplin/releases/tag/v2.9.3

**Comment by MHolkamp** [comment] 2022-08-18 13:23
For me it works on Linux Mint 20.3

**Comment by laurent22** [comment] 2022-08-18 15:22
Thanks for confirming, I assume it's fixed now then.

**Closed as completed by laurent22** 2022-08-18 15:22 UTC
Labels: bug
