### ISSUE TITLE
After copying cross-row and cross-column table data from Microsoft World to the jop editor, the table content and layout will be disrupted.

### ISSUE THREAD

**Issue by zhouxinghong** [laurent22/joplin#6815] opened 2022-09-04 14:34 UTC
After copying cross-row and cross-column table data from Microsoft World to the jop editor, the table content and layout will be disrupted. . .
System: Windows 10 19043
Jop version: 2.9.4

**Comment by Daeraxa** [comment] 2022-09-04 14:37
Can you give an example? Not much anyone can do with this at the moment.

**Comment by zhouxinghong** [comment] 2022-09-04 14:51
> Can you give an example? Not much anyone can do with this at the moment.

After repeated attempts, the issue should be caused by editor reloading.
The operation steps are as follows:
1. Copy the table data in Word to the jop editor, as shown below:
![2022-09-04_1](https://user-images.githubusercontent.com/54253524/188319852-27f99188-3a4f-4649-9606-038126ce1b07.png)
![2022-09-04_2](https://user-images.githubusercontent.com/54253524/188319941-7e4d7ec2-a31b-4b2a-882d-89d262a948bf.png)
3. Click [Options]
![2022-09-04_2 1](https://user-images.githubusercontent.com/54253524/188320181-9cfcd641-b872-417f-90d8-bd2d19429b7a.png)
4. Click [Back]
![2022-09-04_2 2](https://user-images.githubusercontent.com/54253524/188320221-040e1e98-e6ce-48b0-9809-01553d30c16b.png)
5. After returning to the Jop editor, you can see that the table content and layout have been chaotic. . .
![2022-09-04_3](https://user-images.githubusercontent.com/54253524/188320404-47eef22c-d5e3-4ddc-8d85-8e85782e51b5.png)
6. Take a look at the correct table content and layout, as shown below:
![2022-09-04_2](https://user-images.githubusercontent.com/54253524/188321054-c4d0d0fa-4eac-463c-a367-444775400dde.png)

**Comment by Daeraxa** [comment] 2022-09-04 15:32
That is because standard markdown does not support merged cells like that.
I can't replicate it easily as I don't own MS Ofice, what happens if you enable the multimarkdown table extension in your markdown options and try it?

Edit - I think I can answer my own question there by merging in the richtext editor, it doesn't seem like the md converter can convert to multimarkdown format.

**Comment by zhouxinghong** [comment] 2022-09-04 16:17
> That is because standard markdown does not support merged cells like that. I can't replicate it easily as I don't own MS Ofice, what happens if you enable the multimarkdown table extension in your markdown options and try it?
> 
> Edit - I think I can answer my own question there by merging in the richtext editor, it doesn't seem like the md converter can convert to multimarkdown format.

You can try installing MS Office. . .

**Comment by Daeraxa** [comment] 2022-09-04 17:00
No thanks, I have no need of it and I explained the reason for losing the cell merging in my comment

**Comment by tomasz1986** [comment] 2022-09-04 17:09
There's no need to install any office suite. The same happens if you try to copy and paste from a website any HTML table that contains `rowspan` or `colspan`. The table looks fine at first, but if you switch editors/notes back and forth, the formatting gets butchered completely.

For testing:

<table>
	<thead>
		<tr>
			<th colspan="3">Merged columns</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th rowspan="3">Merged rows</th>
			<td>1</td>
			<td>2</td>
		</tr>
		<tr>
			<td>3</td>
			<td>4</td>
		</tr>
		<tr>
			<td>5</td>
			<td>6</td>
		</tr>
	</tbody>
</table>

I haven't tested it, but I'd assume that this should work fine if the note formatting was set to HTML instead of Markdown (see https://discourse.joplinapp.org/t/how-to-set-the-default-markup-language-to-html-instead-of-markdown-for-new-notes/27171). Is this assumption correct?

**Comment by Daeraxa** [comment] 2022-09-04 17:20
I know, I mentioned as such that it can be done entirely within Joplin itself, no need for other applications to test it:

> Edit - I think I can answer my own question there by merging in the richtext editor, it doesn't seem like the md converter can convert to multimarkdown format.

If it was set to HTML then it would be able to keep it, yes, but no decision has been made on that so far.

**Comment by tomasz1986** [comment] 2022-09-04 17:48
> If it was set to HTML then it would be able to keep it, yes, but no decision has been made on that so far.

I've just tested myself and I can confirm that it does work. Regardless of whether there's a way to manually choose formatting type in the future, this could still be used as a workaround for the specific issue right now.

1. Create a HTML note (e.g. by using the methods proposed in the forum topic, or simply use the Web Clipper to save any website as HTML, and then remove all the content).
2. Switch to RichText editor and copy and paste the Word table there.
3. The original formatting isn't lost on switching editors/notes.

On a side note, one very clear advantage of HTML here is that Markdown formatting for tables is just awful and completely unreadable when dealing with complex data tables.

**Comment by zhouxinghong** [comment] 2022-09-05 12:55
> > If it was set to HTML then it would be able to keep it, yes, but no decision has been made on that so far.
> 
> I've just tested myself and I can confirm that it does work. Regardless of whether there's a way to manually choose formatting type in the future, this could still be used as a workaround for the specific issue right now.
> 
> 1. Create a HTML note (e.g. by using the methods proposed in the forum topic, or simply use the Web Clipper to save any website as HTML, and then remove all the content).
> 2. Switch to RichText editor and copy and paste the Word table there.
> 3. The original formatting isn't lost on switching editors/notes.
> 
> On a side note, one very clear advantage of HTML here is that Markdown formatting for tables is just awful and completely unreadable when dealing with complex data tables.
👍👍👍👍👍😜

**Comment by Daeraxa** [comment] 2023-01-04 09:04
Closing to stop whatever pattern is going on here...

**Closed as completed by Daeraxa** 2023-01-04 09:04 UTC
Labels: bug
