### ISSUE TITLE
misleading decryption message with updated encrypt version

### ISSUE THREAD

**Issue by Herve5** [laurent22/joplin#8444] opened 2023-07-10 16:52 UTC
The encryption scheme has been updated in recent versions. Because of this, notes created with these versions cannot be decrypted anymore by sync'ed, older versions. Instead of announcing the origin of the problem, the old versions just announce a sync error. 
They should hint instead towards '_maybe a different, more recent sync algorithm_', for instance. this would strongly help the average user, for who the current behavior is on the verge of catastrophe. Also, an option to check if the current version is the latest one could help.

## Environment
Joplin 2.11.11 (prod, linux)

ID client : 3351cc8ec0bf45d892c41f9c405f6d46
Version de Synchro : 3
Version du profil : 43
Trousseau supporté : Non

Révision : 6886f6f

Autolinker: 1.0.4
Combine notes: 1.0.1
Email Note: 1.2.2
Freehand Drawing: 1.10.1
Markdown table calculations: 1.0.5
Paste Special: 1.1.2
Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. use Linux Joplin v. 2.9.x
2. use latest Android version
3. create note on Android, sync, then sync Linux instance : get the decryption error message.

## Describe what you expected to happen
Sync error message may hint towards '_maybe a different, more recent sync algorithm_'

## Logfile

(debug log just show decrypt failure on some notes)

**Comment by Daeraxa** [comment] 2023-07-10 17:15
I'm not sure I understand how this would be possible. The issue is that the *older* software doesn't understand the encryption from the *newer* software.

So what you need is the older one to be updated in order to understand what the new format is so that it can display an error message? At that point you just update the actual software to the newer version and it is all resolved.

Or do you mean to add this in the future somehow in case the encryption format is changed again? It seems like it might be more work than is worth it seeing how often there are sync target and encryption format upgrades (i.e. very rarely).

Edit: See this post: https://discourse.joplinapp.org/t/syncing-with-different-versions-breaks-encryption-without-explaining-the-change/31650/2. 

Closing this as it is being planned.

**Closed as completed** 2023-07-10 17:50 UTC
