### ISSUE TITLE
Feature request: Boolean search

### ISSUE THREAD

**Issue by ShaneDelmore** [laurent22/joplin#107] opened 2017-12-18 02:48 UTC
### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

I would love to have old school boolean search.  I miss it greatly in OneNote as their searches end up returning many notes not related to what I am searching for.  Joplin currently has the opposite problem of OneNote, instead of returning too many responses, it returns too few.

Example:
I downloaded Joplin, installed it, and created 3 notes
 - note1 - Just some content
 - note2 - Not much content
 - note3 - Just an empty note

Upon testing out search I found that it was difficult to match note1.
 * just content returns 0 results
 * just AND content returns 0 results
 * content returns 2 results
 * just returns 2 results.

**Comment by laurent22** [comment] 2017-12-18 13:35
I'm surprised the first case didn't work as it should convert to "just content" to "just*content" internally and so should have at least returned "just some content", so there's probably a bug.

For more advanced search, I haven't decided what's the best approach yet. Ideally, I would prefer a search that "just work" with results sorted by relevance. So those that would contain both "just" and "content" in that order will be on top, those that contain them in a different order below, and finally the results that only contain one of the words.

**Comment by ShaneDelmore** [comment] 2017-12-18 15:30
If so, it would at least be nice to be able to indicate somehow the score of the match.  If I want to update all notes that match “just AND content” I wouldn’t want to have to keep going until I found a note in which I could not find either just or content and then infer that I must have hit the lower scoring matches.

**Comment by tommyguitfiddle** [comment] 2018-01-05 06:04
Selecting multiple tags would be nice as well.

**Comment by laurent22** [comment] 2018-01-15 17:17
I was mistaken, it would search strictly for "just content" and not as I thought "just*content". Marking this as enhancement then as it should be part of an overall improvement of the search feature.

**Comment by laurent22** [comment] 2018-02-16 18:20
Closing as duplicate of #144

**Closed by laurent22** 2018-02-16 18:20 UTC
Labels: enhancement
