### ISSUE TITLE
Rendering of notes is centered 

### ISSUE THREAD

**Issue by MHoeller** [laurent22/joplin#5458] opened 2021-09-14 06:02 UTC
As of version 2.4* the rendering of notes is no longer left aligned. Now this is centered which looks odd on wide screens, also it seems that it comes to a shrinking -> seems that the notes are rendered smaller this is a much bigger issue!

## Environment

Joplin version: 2.4.6 and 2.4.1
Platform: Ubuntu 20.04

## Steps to reproduce
Just bring up a note in Version 2.4 you get the centered view
![version 2 4 6 exsample](https://user-images.githubusercontent.com/11714953/133202639-4ffd98e9-6a96-4a39-be26-70a10f69c775.png)

### Here you get the difference v2.2.x and v2.4.x:
You can clearly see how much smaller the picture and the text is rendered

#### Version 2.4.x
In the class rendered-md margin-left is set to auto, I suggest to put it to e.g. 10px

![version 2 4](https://user-images.githubusercontent.com/11714953/133202480-7c8b7825-a5ab-4f54-a385-9bd0d1f92b4f.png)

#### Version 2.2.x 
![version 2 2](https://user-images.githubusercontent.com/11714953/133202494-87b152a8-3444-4006-9686-a558ed477caa.png)

## Describe what you expected to happen
Notes should be left aligned with a small margin

**Comment by CalebJohn** [comment] 2021-09-14 06:41
Duplicate of #5339

**Closed by CalebJohn** 2021-09-14 06:41 UTC
Labels: bug
