### ISSUE TITLE
Strange sync behavior with Joplin Server and Joplin Desktop 2.1.7

### ISSUE THREAD

**Issue by Shamp0o** [laurent22/joplin#5149] opened 2021-07-02 08:21 UTC
After upgrading to Joplin 2.1.7 sync is no longer working as expected (see Steps to reproduce for a description). Right after installing Joplin Desktop 2.1.7 I got lots of attachment conflicts so I started with a clean server database and imported my notes from a local backup. At first everything seemed to work fine but after creating a public share for one of my notes the strange sync behavior appeared. 

## Environment

Sync target: Joplin Server 2.1.6-beta (also happens on latest)
Joplin version: 2.1.7
Platform: Windows

## Steps to reproduce

1. Start with fresh server database
2. Delete all local notes and import a backup from .jex
3. Push local notes to server using "Re-upload local data to sync target"
4. Wait until sync is finished
5. Press synchronise again (Without having touched any notes)
6. Sync gives me "updated remote items" for all(?) items (takes a couple of minutes)
8. go to step 4 and watch same behavior every time

The first time I got this behavior I created a public share for one of my notes between steps 4 and 5. This might have caused the issue. 

## Describe what you expected to happen
Sync shouldn't show any changes unless notes are actually changed. 

## Logfile
Debug-Log: [debug.log](https://github.com/laurent22/joplin/files/6753155/debug.log)

**Comment by laurent22** [comment] 2021-07-02 09:40
In .config/joplin-desktop, there's a log file. Could you upload this instead please? The console output can be useful too but it's very hard to read when it's large like this. https://joplinapp.org/debugging

**Comment by roadbearstudios** [comment] 2021-07-02 09:44
Duplicate of #5133

**Comment by marcogiorgio** [comment] 2021-07-02 09:55
Hi, I don't know if it's related or it is another issue, but after the update I get the error:

Last error: Error: Not allowed: PUT

**Closed** 2021-07-02 10:13 UTC
Labels: bug
