### ISSUE TITLE
Right-clicking to correct a word in a note's title creates correct word in note's body without changing the title

### ISSUE THREAD

**Issue by Elaborendum** [laurent22/joplin#4567] opened 2021-02-21 03:02 UTC
If you right-click a misspelled word in a note's title to correct it, the selected word will appear in the note's body without making any changes to the title. 

## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics:  Win10

## Steps to reproduce

1. Write a misspelled word as the title of a note
2. Right-click the misspelled word and choose the correction
3. See bug

## Describe what you expected to happen
Misspelled title is corrected without creating words in the note's body

**Comment by Nunuvin** [comment] 2021-02-24 23:27
That's interesting I actually have a slightly different bug. When I right click to correct the name of the note it just inserts the text without deleting previous name. ie Graen instead of Grain when right clicked and Grain selected will produce GraeGrainn.

Environment

Joplin version: 1.7.11 (f560563d8(master) revision) is a revision a commit? if so it could be that we have different versions.
Platform: Windows
OS specifics: Win10
Steps to reproduce

    Write a misspelled word as the title of a note
    Right-click the misspelled word and choose the correction

**Comment by Ahmad45123** [comment] 2021-03-13 22:43
I've tried to reproduce this multiple times but couldn't at all. Any screenshots or more detailed repro steps would be helpful!

Maybe it's been fixed in 1.8.0 ?

**Comment by mablin7** [comment] 2021-03-14 09:01
I can confirm it's present in v1.7.11 but not on the dev branch. It likely got fixed.

**Comment by Elaborendum** [comment] 2021-03-15 03:52
@Ahmad45123 I'm using 1.7.11, which I think is the lastest stable build. I'm also using the spanish spellchecker, here's a clip:


https://user-images.githubusercontent.com/71190696/111100750-6da16300-8516-11eb-8a50-2fe84a57b9e2.mp4

**Comment by Ahmad45123** [comment] 2021-03-18 10:57
So the issue is definitely not existent in dev branch. I'm not sure what to do here now, but you probably just need to wait for an update to prod :)

**Comment by laurent22** [comment] 2021-04-11 09:52
Looks like it's been fixed then

**Closed by laurent22** 2021-04-11 09:52 UTC
Labels: bug, desktop, high
