### ISSUE TITLE
Dirty (bad) font in the sidebar

### ISSUE THREAD

**Issue by lube62** [laurent22/joplin#7873] opened 2023-03-04 16:05 UTC
Good morning everyone
I have a new Asus Vivobook notebook with Linux Mint 21 (equivalent to Ubuntu 22.04 jammy)
After running the appimage version of Joplin and re-importing my data from a jex file, I noticed that in the sidebar there were some lines where the characters were "dirty" or bad.
Has this happened to others?
The problem is present with all latest versions of Jooplin, both appimage and flatpack

Grazie
![bad_font](https://user-images.githubusercontent.com/30412935/222916350-aea23f87-aa06-42a8-92b2-970724e0ea72.jpg)

**Comment by Daeraxa** [comment] 2023-03-04 16:12
Duplicate of https://github.com/laurent22/joplin/issues/7506

**Closed as completed by Daeraxa** 2023-03-04 16:12 UTC
Labels: bug
