### ISSUE TITLE
Joplin Update

### ISSUE THREAD

**Issue by EHMilon** [laurent22/joplin#9056] opened 2023-10-12 20:13 UTC
## Environment

Joplin version: 2.13. 2
Platform: Windows, Android
OS specifics: Windows, Android

## Steps to reproduce

Every time joplin new update available. We have to download it manually. But it's so inconvenient. 
I think it will be good if any new update available Joplin automatically sync and ask permission for update. There are a lot of software using this same functionality. For example, in VSCode if any new update available. VSCode ask permission for update. If we give permission it's not downlod the whole VSCode again only the necessary updates. It will more convenient for us.

## Describe what you expected to happen

I expect that, if any new update available, this software sync the new update and ask us to give update permission. After we give permission, software should download new updates, not entire app. Without living this software update should download in background and next time we exit from app update should automatically install.

**Comment by personalizedrefrigerator** [comment] 2023-10-13 01:23
Possible duplicate of https://github.com/laurent22/joplin/issues/8958

**Comment by laurent22** [comment] 2023-10-13 07:00
Duplicate of #8958

**Closed as completed** 2023-10-13 07:00 UTC
Labels: bug
