### ISSUE TITLE
Caret jumps to top of note frequently

### ISSUE THREAD

**Issue by mindflowgo** [laurent22/joplin#6432] opened 2022-04-20 05:00 UTC
When notes get longer, every few seconds the cursor caret resets to the TOP of the note... making it impossible to write/edit notes.

## Environment

Joplin version: latest
Platform: MacOS
OS specifics: Using joplin paid note synchronization in case that matters.

## Steps to reproduce

1.  Create a note that is more than 6 or 7 pages long
2.  Move somewhere below the top
3.  Wait a few seconds; the cursor will jump to the top.

## Describe what you expected to happen
I would NOTE expect cursor position to be reset at all.

**Comment by laurent22** [comment] 2022-04-20 09:33
version?

**Comment by meowmeowmeow2022** [comment] 2022-05-16 16:36
This problem happens to the Joplin here too.
# Environment
Version: 2.7.15 (prod, win 32)
# What happened
- Wrote some notes → typed very fast → jumped to top of note
- Sometimes the note is moving while typing, "frame-by-frame" upwards
# Describe what you expected to happen
Cursor don't move randomly, just let us type
# Dev mode command......will this help?
```
Joplin .smalltalk { background-color: rgba(0,0,0,.5); } .smalltalk input { margin-top: 1em; } .smalltalk .page { max-width: 30em; } mark { background: #CF3F00; color: white; } 
/* Adds support for RTL text in the note body. It automatically detects the direction using the content. Issue: https://github.com/laurent22/joplin/issues/3991 */ .CodeMirror-line { unicode-bidi: plaintext; } /* Disable dragging of links (which are often buttons) */ a:not([draggable=true]), img:not([draggable=true]) { -webkit-user-drag: none; }
```

**Comment by jeastonIT** [comment] 2022-05-23 17:53
It is a nightmare... I am (trying) to keep logs of a Pen Test and the cursor constantly jumps to the top of the page when I go to add an entry.  In the WYSIWYG editor,

The first few seconds it lets you type, but then it pops you to the top of the note. No matter what you are inputting, typing, pasting type stamps... any content.

In the markdown editor I can input no problem, and there seems to be no issue with short notes, but log notes always jump to the beginning of the note. 

Joplin 2.7.15 (prod, win32)

Client ID: b89aa95d397544b9848a93811bf39d39
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 8352e23

**Comment by jeastonIT** [comment] 2022-06-23 16:52
Yes gitbot it is still an issue. However, after trying some troubleshooting, multiple computers, and finally just trying to live with it. I went to obsidian.

**Comment by laurent22** [comment] 2022-07-12 10:21
If anyone is still having this issue, please let me know if you somehow managed to replicate this consistently. It happens randomly but every time I tried to replicate it somehow it never happens. I've added some debugging code to the latest pre-release which maybe will point to a solution.

**Comment by dylanmorroll** [comment] 2022-07-21 16:18
I just managed to replicate almost every time by hitting `s` and `Backspace` at the same time. This pretty consistently jumps me back to the beginning of the note. I'm running a slightly older build as I haven't updated my app in a while, here are the details:

Joplin 2.7.15 (prod, linux)

Client ID: 0f5737a6bb2b46acaff2c74dfe0764ac
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 8352e23

**Comment by mindflowgo** [comment] 2022-07-25 23:33
For me, it starts happening when the note is a long note in the WYSWIG editor. There must be something in the javascript code that tries to move the cursor caret BEFORE the HTML is fully rendered so it resets to top.

**Comment by laurent22** [comment] 2022-08-29 14:08
I can sometimes replicate this when the note is open in an external editor at the same time (using external editing). Is that the same for you too?

**Comment by mindflowgo** [comment] 2022-09-08 21:24
> I can sometimes replicate this when the note is open in an external editor at the same time (using external editing). Is that the same for you too?

For me it was NOT in an external editor, it was the DESKTOP app (on Mac Mojave). With the recent update, I am not seeing this problem anymore Laurent, so that may be good. I still see a problem where HTML is switched to MD code but I'll create a new ticket for that. Anyone else find it's fixed? If so, I will close this bug tomorrow.

**Comment by SimonP2207** [comment] 2022-09-14 10:42
Still seeing this issue with the desktop app (v2.8.8, revision c2a6a13). Although I can not pinpoint the exact trigger(s), it seems to happen (cursor moving to top of file) when using the shift key as a modifier. Details of my install/system:

MacOS Monterey 12.5.1, 16GB ram, M1 Pro

Also, I've only noticed it on a pretty long markdown document... (not sure if this is just coincidence or not)

**Comment by Entmatix** [comment] 2022-10-06 12:35
Macbook Air M1, MacOS Monterey 12.6, Joplin 2.8.8 rev. c2a6a13

Same issue here. Unable to take any note, because this "randomly go to top cursor" makes impossible to type even two lines of text. Don't see any pattern in key sequences or length of line when cursor jumps.

**Comment by alpayne** [comment] 2022-11-03 02:23
> [laurent22](https://github.com/laurent22) commented [on Aug 29](https://github.com/laurent22/joplin/issues/6432#issuecomment-1230359621)
>
> I can sometimes replicate this when the note is open in an external editor at the same time (using external editing). Is that the same for you too?

I can get it to happen fairly consistently when I open the note in Vim and then make an edit in Joplin with the external editor still open. The cursor movement also happened a couple of times while testing after closing the editor window while Joplin still had the indicator active, but this was inconsistent.

I wasn't paying enough attention previously to know if this is the only trigger though.

**Comment by Humpkes** [comment] 2022-11-24 18:31
The same here. It drives me crazy. Linux Mint, Joplin 2.1.7. desktop app, WYSIWYG editor.

**Comment by tonyliaccount** [comment] 2022-11-24 23:03
I find it's often when pressing "enter" for a new line, but only in the markup editor, or side-by-side. Not using note sync.

**Comment by erri120** [comment] 2022-12-15 18:26
This happens whenever I use the apostrophe (`'`) making writing `I'm`, `you're`, `it's` virtually impossible. What happens is I start writing `you`, hit the apostrophe key and immediately after pressing `r`, I jump to the top of the editor.

**Comment by Humpkes** [comment] 2022-12-16 19:27
Well, perhaps it's not a popular comment but because of this mess I started to look around if there would be some alternative to Joplin. Once Joplin was an alternative to OneNote. Maybe there is some new kid on the block by now. I ran into Obsidian. I'm using it for a couple of days now. I can recommend it to everyone. You can just export your Joplin content and copy it over to the default Obsidian vault location. It has been nice with Joplin, thanks for everything but I'm making a switch. Happy with Obsidian.

**Comment by jeastonIT** [comment] 2022-12-16 19:30
> I ran into Obsidian. I'm using it for a couple of days now. I can recommend it to everyone. You can just export your Joplin content and copy it over to the default Obsidian vault location. It has been nice with Joplin, thanks for everything but I'm making a switch. Happy with Obsidian.

Yes! I posted my issue May 2022... after no resolution I abandoned Joplin for Obsidian. It's been wonderful, their Live Preview is incredible. I also don't recommend my team use Joplin, though some still do.

**Comment by tmfink-juniper** [comment] 2023-01-18 17:51
This issue occurs for me as well. I'm using `Joplin 2.9.17 (prod, darwin)` and edit in Vim mode. There's no clear pattern on when jumping to the top occurs--it seems to happen randomly every several minutes while typing.

**Comment by laurent22** [comment] 2023-01-18 22:46
Duplicate of #7617

**Closed as completed by laurent22** 2023-01-18 22:46 UTC
Labels: bug, desktop, high

**Comment by 7ff04da4aa6ac37197e249299066ac30** [comment] 2023-05-15 13:53
On the Linux AppImage, Joplin version 2.10.18, this still happens. It does not happen when following the procedure on #7617.

Though I am using the Rich Markdown plugin and custom userchrome.css and userstyle.css, the issue still occurs with all of these disabled.

> This issue occurs for me as well. I'm using `Joplin 2.9.17 (prod, darwin)` and edit in Vim mode. There's no clear pattern on when jumping to the top occurs--it seems to happen randomly every several minutes while typing.

This seems to most closely resemble my experience with Joplin. It only happens while typing and seemingly randomly; repeating the text I wrote before the jump does not replicate the issue.

Edit to mention that I mostly use the plain text editor.

**Comment by mindflowgo** [comment] 2023-05-15 18:02
For me I found the Caret error happened with bigger files. It may be related to delays in rendering JavaScript. However with the later versions I no longer see this problem. I consider it fixed. The only remaining problem is markdown gets reverted to text.  Sent from Proton Mail for iOS On Mon, May 15, 2023 at 14:53, 7ff04da4aa6ac37197e249299066ac30 ***@***.***> wrote:  
On the Linux AppImage, Joplin version 2.10.18, this still happens. It does not happen when following the procedure on #7617.
Though I am using the Rich Markdown plugin and custom userchrome.css and userstyle.css, the issue still occurs with all of these disabled.

This issue occurs for me as well. I'm using Joplin 2.9.17 (prod, darwin) and edit in Vim mode. There's no clear pattern on when jumping to the top occurs--it seems to happen randomly every several minutes while typing.

This seems to most closely resemble my experience with Joplin. It only happens while typing and seemingly randomly; repeating the text I wrote before the jump does not replicate the issue.

**Comment by GettingTechnicl** [comment] 2023-08-18 04:39
This has happened periodically over a period of time for me

I utilize arch, windows 10, and windows 11 on a frequent basis. 

On windows 11 entering notes, anytime it jumps it happens when I'm typing and I see that it started syncing. If I try to replicate it and force issue to happen again, it does not. 

on arch I have not seen the issue in some time, maybe 4-6 months. 
On windows 10, I have not seen the issue at all recently - I may be running an older joplin client there so I'll need to look in to that. 
On Windows 11, running latest joplin version, it's happened to me atleast 3 times in the past 2 hours. as well as the past few days. It's very frustrating when I look at my notes and see the last paragraph I typed went to the top of the page. 

I have the same plugins active on all machines - Enhancement, Inline TODO, Kanban and Note Tabs. 

I have not attempted disabling plugins as I'd like for that to not be the solution. This happened much more frequently in the past and appeared to have gone away for a time. 

If I gather more info, I'll revisit this thread to see if anything I gather helps any.

**Comment by lexnel** [comment] 2023-08-24 19:35
> This has happened periodically over a period of time for me
> 
> I utilize arch, windows 10, and windows 11 on a frequent basis.
> 
> On windows 11 entering notes, anytime it jumps it happens when I'm typing and I see that it started syncing. If I try to replicate it and force issue to happen again, it does not.
> 
> on arch I have not seen the issue in some time, maybe 4-6 months. On windows 10, I have not seen the issue at all recently - I may be running an older joplin client there so I'll need to look in to that. On Windows 11, running latest joplin version, it's happened to me atleast 3 times in the past 2 hours. as well as the past few days. It's very frustrating when I look at my notes and see the last paragraph I typed went to the top of the page.
> 
> I have the same plugins active on all machines - Enhancement, Inline TODO, Kanban and Note Tabs.
> 
> I have not attempted disabling plugins as I'd like for that to not be the solution. This happened much more frequently in the past and appeared to have gone away for a time.
> 
> If I gather more info, I'll revisit this thread to see if anything I gather helps any.

Jup, same here for me. I'm using windows 10 and the latest Joplin version 2.12.10. The only plugin installed is the backup plugin. When I'm typing and the sync is running in the meanwhile, the cursor jumps to the beginning of the note about every 10th time. Pretty annoying...

**Comment by benmotyka** [comment] 2023-08-30 13:37
Can confirm this issue exists. MacOS Ventura 13.5.1, Joplin 2.11.11 (prod, darwin). Very difficult to reproduce. I have pretty long document in markdown edit mode. In my case, very rarely when I hit space and enter it jumps to first line.

**Comment by SpiceMan** [comment] 2023-12-20 04:27
Just posting to confirm the issue still exists.
On the Mac OS (Sonoma 14.2) desktop app.
Not using syncronization.

edit: might be related to mermaid? It's just a feeling, but seems to happen often when mermaid code failed to render.
Might as well be happening when it gets re-rendered for whatever reason besides the mermaid code being changed. But since the mermaid graph stays the same it looks "unrelated".

```text
Joplin 2.13.9 (prod, darwin)

Client ID: <redacted>
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 1bbec44
```

**Comment by agreatfool** [comment] 2024-01-23 02:03
The bug still exists: `OSX 14.2.1（23C71）+ Joplin 2.13.15 (prod, darwin)`

- long post
- if no input , the caret is good to keep it's original position
- seems a periodic issue?

**Comment by SpiceMan** [comment] 2024-01-29 14:19
> I can sometimes replicate this when the note is open in an external editor at the same time (using external editing). Is that the same for you too?

Yes! It seems to happen when "External editing" is Toggled on (regardless of if you are actually also editing/have the file open in another editor)

1) When "External editing" is toggled (In the menu: Note -> Toggle External Editing) it starts to "randomly" seek the top of the file.

2) Since the shortcut is Command + E, I guess that people that have to type diacritics in languages like spanish, etc, like me (and use Option + E a lot to type them) sometimes toggle External Editing by accident -> caret starts jumping to the top and "seems" random.

**Comment by chevdor** [comment] 2024-01-29 15:32
I am using external editing from time to time but I am not using CMD+E by mistake and see this issue out of the "external editor" context. I think it it is more related to the sync as mentioned in #9724

**Comment by SpiceMan** [comment] 2024-01-30 20:17
> I am using external editing from time to time but I am not using CMD+E by mistake and see this issue out of the "external editor" context. I think it it is more related to the sync as mentioned in #9724

Maybe in code it's related somehow when saving/loading/etc.... (I can imagine implementing remote syncing of files with locally syncing files somewhat in the same area of code)

But I don't use mutiple devices, use zero syncing nor anything.... and the cursor "randomly" jumps to the top of the document when External Editing is enabled.

When it starts happening to me, I just check if External Editing is enabled, and it is somehow enabled (here is where I came up with the Option-E / Command-E theory).

Disabling External Editing "fixes" it in my case.

**Comment by Freeedim** [comment] 2024-02-15 15:17
The issue is still there with:
- Joplin 2.14.11 (prod, linux), Synchro version: 3, Simple Backup: 1.3.6;
- external editor turned off;
- view in double panel (MD editor and rendering);
- quite long note (300+ lines);
- E2E encryption properly working for all the notes;
- Auto-backup to a Nextcloud instance.

I could systematically reproduce the faulty behaviour like this:
1. Place the caret anywhere, write a character and wait for the autosync to happen.
2. When autosync starts, start typing.
3. See how, after a few characters (like 10-20), the caret will be brought back to the beginning of the note

Note 1: Typing while the autosync is not carrying out its task never triggers bringing the caret back to the beginning of the note.
Note 2: Letting the Autosync work until it finishes without typing anything leaves the caret where it is.

**Comment by pretubedongit** [comment] 2024-04-26 01:20
I can confirm this bug still exists in the latest version of both macOS and iOS version.

**Comment by executed** [comment] 2024-09-05 03:58
Related: https://github.com/laurent22/joplin/issues/10195
