### ISSUE TITLE
Android WebDAV Error: 412 Unknown error

### ISSUE THREAD

**Issue by temaoz** [laurent22/joplin#1228] opened 2019-02-16 13:32 UTC
### Operating system

- Android

### Application

- Mobile

Currently it isn't possible to enable the WebDAV sync between Joplin and mailbox.org (which uses OpenXchange).

The WebDAV URL and credentials are correct. WebDAV Sync in general is working without any problemsn and e.g. used with Kepass2Android for syncing the database file.

When I enter the WebDAV URL and the credentials in Joplin and click the button to check the settings, I get the following error:

'PROFIND: Unknown error 2 (412): (Code 412)

You can test the WebDAV sync with the following credentials and URL:

URL: https://dav.mailbox.org/servlet/webdav.infostore/Userstore/Joplin%20Testuser/Documents/Joplin
User: joplin_test@mailbox.org
Password: J0plin19!

I've also attached my error log below.

[syncReport-1550322713286.txt](https://github.com/laurent22/joplin/files/2871962/syncReport-1550322713286.txt)

**Comment by danieldev** [comment] 2019-02-22 07:20
I can reproduce this bug. There is already an issue for that which was closed even though this problem still occurs with mailbox.org: #1064

**Comment by laurent22** [comment] 2019-02-23 16:12
This is a bug in their WebDAV implementation so it needs to be reported either to mailbox.org or OpenXchange.

For various reasons described [there](https://github.com/laurent22/joplin/blob/1f384c7ae44169df702c9ce498ff4b2e1d7d98eb/ReactNativeClient/lib/WebDavApi.js#L302), Joplin sends a random "If-None-Match" header with PROPFIND call. A non-buggy implementation like Nextcloud would look at this header, see that it doesn't correspond to any resource (it's a cache miss), and thus send back what was requested.

However OpenXchange seems to look at this tag, see that there's no such resource and respond with an error. According to RFC-7232, it shouldn't because it's just a cache miss - it should just send back the requested resource.

I cannot be fixed easily in Joplin (if we fix it for OpenXchange we'll break other things) so for that reason it won't be fixed here.

**Closed by laurent22** 2019-02-23 16:12 UTC
Labels: bug, essential
