### ISSUE TITLE
Joplin is invisible on GNOME on first start after system reboot

### ISSUE THREAD

**Issue by iRomanyshyn** [laurent22/joplin#8256] opened 2023-05-30 11:31 UTC
![Joplin-invisible-on-Gnome](https://github.com/laurent22/joplin/assets/11888301/432303db-eae1-4c60-9d7d-a498acaafc34)

Every time I start Joplin on just rebooted machine it won't open the main window but is only shown in GNOME as an empty preview.
To start using it, I need to close that invisible window and then start Joplin again. Then it starts up with a visible window.

## Environment

Joplin 2.10.19 (prod, linux)

Client ID: cc5c1a4a39ff42ca90d4d9766175d84b
Sync Version: 3
Profile Version: 42
Keychain Supported: No

Revision: 1100ab0

OS openSUSE current version, GNOME DE, Wayland DM. Also happens on fresh Fedora with GNOME and Wayland.

Installed with shell script provided on the website https://joplinapp.org/help/#desktop-applications

## Steps to reproduce

1. Reboot the machine.
2. Open Joplin by clicking the pinned icon.
3. Joplin isn't opened but its invisible window is shown in the "switcher".
4. Close that empty window.
5. Click the Joplin icon again and now it works.

If debug log is needed, please help to enable it.

**Comment by zrebar** [comment] 2023-06-01 14:36
I have exactly the same issue on Ubuntu 23.04.

**Comment by mcmxcdev** [comment] 2023-06-04 20:48
Running into the same issue, thought I would leave the exact OS specs here for debugging purposes:
Ubuntu 23.04, Gnome 44.0, Kernel 6.3.1, Wayland

**Comment by rio-codes** [comment] 2023-06-15 02:33
It seems like lots of apps that use hardware acceleration by default are having issues with Wayland. I found an old issue: https://github.com/laurent22/joplin/issues/5776 to allow users to turn it off that never got resolved, and I dug into a more recent issue: https://github.com/laurent22/joplin/issues/8226 with the same problem. I think at this point as Wayland proliferates, it is more urgent to allow disabling hardware acceleration until they get these issues fixed. Out of curiosity, @iRomanyshyn @zrebar @mcmxcdev are you all using Nvidia drivers? It seems to be a common theme with people having Wayland/hardware accel/vsync issues.

**Comment by mcmxcdev** [comment] 2023-06-15 13:05
I use a laptop with hybrid graphics:
NVIDIA GeForce RTX™ 3050 Ti Laptop GPU / AMD Radeon™ Graphics

NVIDIA driver metapackage is nvidia-driver-525, but I could try out nvidia-driver-530 which is available as well.

**Comment by zrebar** [comment] 2023-06-15 18:54
Thank you @rio-codes, for looking deeper into this.
Yes I do have an Nvidia GPU, but I don't think this is Wayland related because almost all Ubuntu systems with Nvidia cards use Xorg by default and not Wayland.

My system: NVIDIA GeForce RTX™ 3070 Laptop GPU, Gnome 44.1, Linux 6.2.0-20-generic, i7-11800H, Ubuntu 23.04

I just went down the rabbit hole and tested Joplin on all the following scenarios: 
1- I was already on Xorg, Nvidia-525, Gnome 44.1, I purged everything Nvidia related, went on Nouveau driver and the issue still existed.
2- Tried to go on Wayland and then Xorg again, had the issue on both.
3- Installed the latest Nvidia 530, [Xorg of course] and the issue still exists. (As far as I know, you can't even get Nvidia-driver-530 to work on Wayland on Ubuntu 23.04)

Unfortunately JS/TS/Node/Electron is not my cup of tea, but if there is anything more I can do to provide more info to resolve the issue please let me know.

**Comment by rio-codes** [comment] 2023-06-16 03:52
@zrebar can you grab `journalctl`/GNOME logs while it's happening?

**Comment by zrebar** [comment] 2023-06-18 10:20
@rio-codes , sure, this is the only one I've seen so far: 

> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

I wanted to say okay this must be the culprit, but it's not because this was happening when Joplin had the issue we talked about and also when it was launched successfully. So I don't think this is the heart of the problem, not sure.

**Comment by rio-codes** [comment] 2023-06-18 20:27
@zrebar Is that the error that comes up right after you click it and it doesn't open? Can you open a terminal window, type `journalctl -f` and then try and open it? Let us know what comes up right when you click it even if it doesn't say error.

**Comment by zrebar** [comment] 2023-06-20 10:49
Yes, that is the only Joplin related log there. And it happens (the log) when it doesn't open and also when it works.

**Comment by rio-codes** [comment] 2023-06-23 07:39
what about non-Joplin related logs? Can you post the whole log file?

**Comment by mikeGolf08** [comment] 2023-06-28 16:00
![Joplin_Bug](https://github.com/laurent22/joplin/assets/52482050/f27d15ba-9145-4815-a934-1acf4791c241)

I can confirm the **same bug** on my end **since** starting using Joplin for probably **2.5 months** on Fedora 37 & 38 but strangely not on the respective Silverblue versions in a VM and not on an older notebook running same environment but with NVidia GPU proprietary drivers.

In comparison to the author of this bug report I even **face this bug some time after closing Joplin and at trying launching it again** so no OS reboot needed to reproduce.

After closing the invisible window and relaunching Joplin it is launching but the window is not maxed.

## Environment

Joplin version: **All** Flatpak **versions** since ~2.5 months from Flathub
Flatpak settings: **Standard** but tried out launching it with just X11, just Wayland, just Fallback and all combinations out of these options
Platform: Wayland & **GNOME** 43 & 44
OS specifics: Fedora 37 & 38 Workstation

## About Joplin
Joplin 2.11.11 (prod, linux)
Sync-Version: 3
Profil-Version: 43

### Plugins:
Kanban: 1.0.7
Note Tabs: 1.4.0
Quick Links: 1.2.4
Templates: 2.3.0

**Comment by zrebar** [comment] 2023-07-01 20:16
![image](https://github.com/laurent22/joplin/assets/1140683/904a4102-cf13-4a14-8f12-1fcb951f6e3a)

I also updated my Nvidia drivers to 535. I still have the issue. However, it's not only after a cold boot now. I can not say for sure, but I think it's only the second run this time, so weird. 

@rio-codes

**Comment by personalizedrefrigerator** [comment] 2023-07-03 13:33
Possibly related portion of code:
https://github.com/laurent22/joplin/blob/51fbb38f66bfe8c12edbea5cceed9fc168979e67/packages/app-desktop/ElectronAppWrapper.ts#L101-L103

This likely explains why the desktop app appears as expected in dev mode, but often doesn't when built for release.

**Closed as completed** 2023-07-10 10:59 UTC
Labels: bug

**Comment by thraindk** [comment] 2024-09-26 12:41
I can confirm this issue also exists in Ubuntu MATE 24.04.1

First time opening the app will ALWAYS result in an empty, blank white window. Closing and reopening the app resolves the issue. Happens on both app center an snap Joplin Desktop version 3.0.13

Kernel Linux 6.8.0-45-generic x86_64
MATE 1.26.2
xserver-xorg-core 2:21.1.12-1
