### ISSUE TITLE
Sync Error WebDav: GET info.json: unknown error 2 (412)

### ISSUE THREAD

**Issue by Bomitter** [laurent22/joplin#4006] opened 2020-10-30 16:11 UTC
## Environment

Joplin version: 1.2.6 (Linux & Android App)
Platform: Android & iOS, Linux
OS specifics: 

I have the following setting: 
Joplin stored on mailbox.org and syncing via webdav on Linux Mint, Android and iOS Apps. Worked fine for over a year.
For about 2 weeks now, I couldn't sync anymore to iOS first (which didn't bother me too much), However for some days now I can't sync via Linux and Android either. 
When I try to sync it on iOS or Android I get the follow error (no error message on Linux however)
Error: GET info.json unknown error 2 (412)

I have no clue what might be the reason. 
I have the notion that it might be connected to the following issue:
https://github.com/laurent22/joplin/issues/1228

I am quite new to all of this, so any hint or advice highly welcomed or if additional info is needed :)

**Comment by Bomitter** [comment] 2020-11-04 09:33
Any hints from anyone, please?
I made additional observations:
I re installed the android app. I investigated it a bit, I can (sometimes / initially) download the syncronisation from the mailbox webdav. However if I modify a note or write something and try to upload it, I now get another error (I guess still related to the unknown error 2 - 412):

error: GET sfkdsjhfsdjfhdshf[random letters].md: unknown error 2 (412)

Any explanations?

**Comment by linuxissuper** [comment] 2020-11-10 02:28
I have the same problem, but only on Android
I can still sync between two desktops (Linux)

[syncReport-1604972757373.txt](https://github.com/laurent22/joplin/files/5514443/syncReport-1604972757373.txt)

**Comment by da2x** [comment] 2020-12-03 03:41
I’ve got Joplin on macOS, Windows, Linux, and Android. Only the Android version complain about `Sync Error WebDav: GET info.json: unknown error 2`. The other sync just fine with each other.

**Comment by da2x** [comment] 2020-12-03 03:44
This affects OpenXchange (#1228) and LightHTTPD (#3457) servers. @laurent22 has said in other issues that this isn’t a bug in Joplin. However, it does seem likely to be a Joplin bug as it only affects the Android version of Joplin and affects multiple WebDAV servers.

**Comment by jvdgeest** [comment] 2020-12-04 15:11
I'm having the same issue unfortunately. Guess that we have to contact mailbox.org...

**Comment by AndrewNalin** [comment] 2020-12-30 12:14
Version 1.26 is working fine on android with mailbox.org for me. But same Error with the newer Android versions.
No problems with the Linux versions and mailbox.org.  So it must be a problem with the android version.

**Comment by nmheim** [comment] 2021-01-19 22:25
@jvdgeest did you contact mailbox.org (and got a response?) or did you solve you issue another way? I am running to the same error...

**Comment by jvdgeest** [comment] 2021-01-20 10:59
> @jvdgeest did you contact mailbox.org (and got a response?) or did you solve you issue another way? I am running to the same error...

I went for another WebDAV host in the end, and did not contact mailbox.org.

**Comment by AndrewNalin** [comment] 2021-02-08 09:06
just cleared the app cache from joplin and sync is working again. can anyone test and confirm this?

**Comment by webdever-de** [comment] 2021-02-14 12:32
Confirmed, deleting the app cache has solved the problem.

**Comment by Bomitter** [comment] 2021-02-20 20:23
works as well for me, thanks for the tip! From times to times I need to delete the cache, I am suspecting "conflict" notes. But then works again.

**Comment by roman-r-m** [comment] 2021-03-25 13:30
I take it, the issue is resolved? Closing the issue, if anyone still sees, it let me know.

**Closed by roman-r-m** 2021-03-25 13:30 UTC

**Comment by remcoboerma** [comment] 2021-11-27 20:05
Same problem i Guess. Even removed all data and still had the same issue. 
Any suggestions?

**Comment by remcoboerma** [comment] 2021-11-27 20:15
Ah, i have found what caused this error in my case. Probably my android version was auto updated but my docker version had become old.  
Because my server was  "Joplin Server 2.5.1, " , in the logs of the android app it says a 2.6.0 minimum is required. Updating docker to 2.6.12 (newest latest at the time of writing) solved my issue.
