### ISSUE TITLE
Can not re-arrange notes

### ISSUE THREAD

**Issue by dev2games** [laurent22/joplin#684] opened 2018-07-15 00:06 UTC
### Operating system

- Windows

### Application

- Desktop

At the moment there is no way to re-arrange your notes, also you can't right click to create a new note / notebook?

**Comment by dev2games** [comment] 2018-07-15 10:33
@foxmask , being able to change the order of the notes and notebooks. So if for example you have 3 notes, apple, orange, grapes. And you want to change the order of the list. At the moment it shows by date DESC.  and you can not change the order. so for example you might want to have a note with a higher priority, at the top.

**Comment by foxmask** [comment] 2018-07-15 10:36
Ok, so there are a lot of issues opened about that :) 
duplicate of #51

**Closed by foxmask** 2018-07-15 10:36 UTC
