### ISSUE TITLE
Make shortcuts configurable

### ISSUE THREAD

**Issue by breneser** [laurent22/joplin#123] opened 2017-12-26 14:52 UTC
### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [X] Terminal

---

Is there a way to change shortcuts on terminal application ? That would be great, checking the docs I did not see it mentioned anywhere. Sorry if it exists but I couldn't find it. In that case adding it to docs would be great.

Thanks for creating Joplin. I quite like it

**Comment by laurent22** [comment] 2017-12-26 19:48
Duplicate of #63

**Closed by laurent22** 2017-12-26 19:48 UTC
