### ISSUE TITLE
Note rendered is false

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#3053] opened 2020-04-14 08:26 UTC
## Environment

Joplin version: 1.0.200
Platform: linux
OS specifics: debian

## Steps to reproduce

1.  select several notes
2. move them to another notebook
3. then you now see the content of the note that was above the one you moved but the rendering of the note is the last one you moved.

I screencasted that behavior https://send.firefox.com/download/c6511b07094956e8/#-AJJAGgdpcl3GIAapwUG6g

**Comment by foxmask** [comment] 2020-04-14 10:20
update the link that will expire in 7days https://send.firefox.com/download/33e37cab4250e811/#A1PBqx5T9u5cgRh9EUgWyg

**Comment by coderrsid** [comment] 2020-04-14 10:24
> update the link that will expire in 7days 

Although you can use this link [video-to-gif]( https://www.onlineconverter.com/video-to-gif) and can paste the GIF directly here in the comment box and that will stay for a long time 😄

**Comment by coderrsid** [comment] 2020-04-14 11:24
>then you now see the content of the note that was above the one you moved but the rendering of the note is the last one you moved.

i'm not able to understand this.

**Comment by foxmask** [comment] 2020-04-14 11:57
watch the video you will understand

**Comment by laurent22** [comment] 2020-04-14 13:36
@coderrsid, the problem is that at the end there's a note selected in the list, but the note being displayed is not the one that's selected.

**Comment by foxmask** [comment] 2020-04-14 13:39
at least, instead of selecting the one that we move, the selected note could be one of the current notebook.?

**Comment by kowalskidev** [comment] 2020-04-14 19:44
> update the link that will expire in 7days https://send.firefox.com/download/33e37cab4250e811/#A1PBqx5T9u5cgRh9EUgWyg

Link expired! can you please try to upload video on google drive OR as @coderrsid said you can use  video-to-gif

**Comment by foxmask** [comment] 2020-04-15 06:44
![joplin-move-bug](https://user-images.githubusercontent.com/208212/79306305-451f7c00-7ef5-11ea-953a-1d4dbf5c17ae.gif)

**Comment by coderrsid** [comment] 2020-04-15 10:21
So as much as i can understand this.. you're saying that for example whenever you move some notes from notebook `B` to a notebook `A`, it should open that notebook `A` instead of showing remaining notes from notebook `B`, right?

**Comment by foxmask** [comment] 2020-04-15 10:26
Joplin does the right thing by selecting the remaining note from the notebook B. 
The issue is to render THAT note properly instead of rendering the note I moved to nootebook A.
What do you think ?

**Comment by coderrsid** [comment] 2020-04-15 13:08
Ohh sure sure. Huh.. it took time to understand.. sorry. Now i know the issue perfectly. I'll start working on this right away.

**Comment by foxmask** [comment] 2020-04-15 13:10
no problem :) take your time

**Comment by coderrsid** [comment] 2020-04-16 11:19
I tried it on my OS. It's not an issue i see. In my case, the note which is rendered is the note which is left but not the one which i moved.
**OS: macOS**
 
### Joplin Version
![image](https://user-images.githubusercontent.com/35633575/79449741-67062500-8001-11ea-9003-5b3d35741fff.png)

### Here you see i have 4 notes and after moving the remaining notes to another notebook, the note which is rendered is the one which is left in the notebook.
![Screen-Recording-2020-04-16-at-4](https://user-images.githubusercontent.com/35633575/79450180-34a8f780-8002-11ea-9147-8593a1c5ea93.gif)

**Comment by foxmask** [comment] 2020-04-16 11:36
so it looks like to be linux related, is n't it ?

**Comment by coderrsid** [comment] 2020-04-16 11:41
Maybe, laurent can you provide any insight?

**Comment by foxmask** [comment] 2020-04-16 12:17
1.0.201 seems to have fixed that behavior
I don't have the issue at all now

**Comment by coderrsid** [comment] 2020-04-16 13:27
Great to hear that.

**Comment by coderrsid** [comment] 2020-04-16 13:27
@laurent22 you can close this issue.

**Comment by laurent22** [comment] 2020-04-16 22:03
Hmm ok, I don't know what was changed in that version related to this. If it happens again please let me know.

**Closed by laurent22** 2020-04-16 22:03 UTC
Labels: bug, high
