### ISSUE TITLE
2.9.17 in ubuntu glitches in notebook pane

### ISSUE THREAD

**Issue by magowiz** [laurent22/joplin#7639] opened 2023-01-20 10:39 UTC
Using new version in ubuntu, the 2.9.17 installed using script (AppImage format), notebooks names are ruined by glitches, they goes away if I hover mouse on names but comes up again on scrolling notebook pane or or opening app.

## Environment

Joplin version:  2.9.17 (AppImage)
Platform: Linux
OS specifics: Ubuntu 22.10, session type x11, gnome-shell DE

## Steps to reproduce

1. open joplin application 
2. have some notebooks
3. see some notebook names with glitch

## Describe what you expected to happen
Notebook names should be rendered correctly

## Logfile

[joplin.log](https://github.com/laurent22/joplin/files/10465487/joplin.log)

## Screenshot
screenshot showing issue

![Screenshot from 2023-01-20 11-27-53](https://user-images.githubusercontent.com/1067544/213675761-f1264962-dea0-41a0-88cc-8fafadd4b85e.png)

**Comment by ScriptInfra** [comment] 2023-01-20 11:47
Do you have any plugins enabled? If so maybe try disabling them?

**Comment by magowiz** [comment] 2023-01-20 13:16
I had draw.io that wasn't working anymore with 2.9.x versions, I disabled it, it was the only plugin enabled, then restarted joplin but the problem is still there. Same happens also if I remove plugin completely.

**Comment by laurent22** [comment] 2023-01-20 15:12
Duplicate of #7506

**Closed as completed by laurent22** 2023-01-20 15:12 UTC
Labels: bug
