### ISSUE TITLE
Create subnotebooks in terminal

### ISSUE THREAD

**Issue by mikelu92** [laurent22/joplin#1728] opened 2019-07-12 20:42 UTC
### Operating system

- macOS
- Linux

### Application

- Terminal

Just wondering if there was a way to create new subnotebooks in the terminal app? Was looking through the [terminal docs](https://joplinapp.org/terminal/) and was not able to find that feature.

**Comment by laurent22** [comment] 2019-07-12 22:38
You can use the `set` command to set the notebook `parent_id` to another notebook.

**Comment by mikelu92** [comment] 2019-07-13 00:53
I thought the `set` command was only used for notes? the documentation doesn't say anything about using `set` with notebooks, only notes? Do you have an example of how to do that?

**Comment by laurent22** [comment] 2019-07-13 08:30
You're right, I forgot it was only for notes. So at the moment it seems it's just not possible to create sub-notebook on the CLI, and you'd have to use the desktop app and sync. I guess the `set` command could be improved to deal with notebooks too.

**Comment by mikelu92** [comment] 2019-07-14 16:42
If this feature were to be added is there a general time frame in which this functionality would be added?

**Comment by tessus** [comment] 2019-10-12 09:32
Can we flesh out the specifics?

Shall we use the `set` command? If yes, what should the sub-command be? Or how would an example command look like?

What is the parent_id of the root folder? e.g. when we want to move a sub-notebook to the top level?

**Comment by laurent22** [comment] 2019-10-14 18:33
@tessus, I feel `set` is not very user friendly for this particular task. How about extending `mv` for this?

Currently it's like this:

	mv <note> [notebook]

		Moves the notes matching <note> to [notebook].
		
We could upgrade it to this:

	mv <item> [notebook]

		Moves the notes or notebooks matching <item> to [notebook].

How about it?

**Comment by tessus** [comment] 2019-10-14 19:15
@laurent22 This sounds like a great idea. I like it.

I hereby give others the chance to grab it. If nobody takes it for a week, I'll assign it to myself.

**Comment by tessus** [comment] 2019-10-14 23:45
@laurent22 if you don't mind, I'd also like to change the `mkbook` command to allow an optional parent id. what do you think?

**Comment by tessus** [comment] 2019-10-17 06:02
@laurent22 while looking into this, I came across a few problems. maybe you can help me understand them.

It is possible to have several notebooks with the same name. For my tests I use book1, book2, and book2. However, it seems that it is currently not possible to move a note from book1 to the second book2 (or from book2 to the other book2). Or am I missing something?
Furthermore, meta data is only displayed for notes, but not for folders, so using the id to move the notes doesn't work either. When using the metadata parent_id from an existing note, the mv command still does not accept a valid id as the destination.

I'm a bit puzzled how to solve this.

Maybe we have to come up with a way to handle folders with the same name first. Please advise.

**Comment by laurent22** [comment] 2019-10-17 08:55
> @laurent22 if you don't mind, I'd also like to change the `mkbook` command to allow an optional parent id. what do you think?

Yes that would work. Maybe an option `-p, --parent <notebook>`

**Comment by laurent22** [comment] 2019-10-17 09:02
> It is possible to have several notebooks with the same name. For my tests I use book1, book2, and book2. However, it seems that it is currently not possible to move a note from book1 to the second book2 (or from book2 to the other book2). Or am I missing something?

You can using for example `Note.moveToFolder` but why do you want to move notes?

To move a notebook you can use `Folder.moveToFolder`

>  Furthermore, meta data is only displayed for notes, but not for folders, so using the id to move the notes doesn't work either. When using the metadata parent_id from an existing note, the mv command still does not accept a valid id as the destination.

You don't need to use the ID. It can be done by title too. But maybe we can also extend the `cat` command to display info about notebooks in order to get the ID.

**Comment by tessus** [comment] 2019-10-17 09:14
> You can using for example Note.moveToFolder but why do you want to move notes?

I'm looking at the current mv command, which I should change to allow to move folders. However, if I can't move a note to a folder (the problem I described with 2 folders with the same name), I won't be able to move a folder to a folder with the same name either.

The problem is that I currently cannot use an ID to move the note. But this has to be implemented, otherwise moving a folder would only work, if the target folder name is unique.

> You don't need to use the ID. It can be done by title too.

Not when there are 2 or more folders with the same name. Ok, please create 3 folders:

book1
book2
book2

Now create a note in folder book1. Please try to move the note to the second book2 folder. As you can see, it doesn't work. So moving a folder won't work either.

All I am saying is that we should make it possible to also specify the folder id instead of the folder name to move a note/folder. Otherwise we have the problem above. But we can only do this, if there's a way to actually see the folder id somehow.

**Comment by tessus** [comment] 2019-10-22 04:35
Ok, I am going to take it, but before starting on this we have to find a solution to the issues I described above.

**Comment by tessus** [comment] 2020-01-20 05:30
Still waiting for architectural input.

**Comment by t0mmy44-h** [comment] 2020-03-03 10:13
I'm interested in helping out with this issue in whatever way I can - feature parity is a linchpin that's kind of holding back Joplin from being a daily-use application for me. This issue specifically is a pain point for me as a heavy terminal user.

I have some broader questions about the architecture / responsibility split between the various clients though, that I think could provide a good baseline discussion for how to move forward in keeping feature parity between the clients. Is there somewhere better than individual git issues to get in touch/have a chat?

In the meantime, I will keep reading through the code and past issues/discussions to get some more context.

**Comment by tessus** [comment] 2020-03-03 23:50
It's not the coding I need help with, although you are more than welcome to take it .

As mentioned a few times in this issue, we need architectural input from Laurent. But I think he's rather busy, so I'm not sure when we can expect this info.

**Comment by tessus** [comment] 2020-04-18 00:30
@laurent22 as soon as I have your input on

- https://github.com/laurent22/joplin/issues/1728#issuecomment-543017735
- https://github.com/laurent22/joplin/issues/1728#issuecomment-543084316

I can start working on it.

**Comment by gaalcaras** [comment] 2020-05-03 09:14
This would be a *very* useful feature, so I'm adding my comment here to bring this issue to the top. Hope that @laurent22 will be able to study your proposal!

**Comment by tessus** [comment] 2020-07-10 17:52
Still waiting for Laurent's input on the architectural questions.

**Comment by tessus** [comment] 2020-08-09 18:14
Still waiting for Laurent's input on the architectural questions.

**Comment by laurent22** [comment] 2020-09-04 23:56
If we change this:

```
mv <note> [notebook]

    Moves the notes matching <note> to [notebook].
```

to this:

```
mv <source-item> <dest-item>

    Moves the given child item to the given parent item.
```

And "item" can be an ID, a title, etc. Wouldn't that cover all cases? (including tags, if we ever merge the hierarchical tag feature)

As for getting the ID of an item, I'm open to suggestions. Maybe some key shortcut which, when pressed, display the IDs in the sidebar next to the titles?

It would temporarily turn this:

```
Work
	Project 1
	Project 2
Holidays
	Spain
	France
	Italy
```

Into this

```
f8a3f5 Work
	277dac Project 1
	5512fa Project 2
f6a0c4 Holidays
	87f366 Spain
	902afe France
	ab981b Italy
```

(the CLI app supports entering only the first 6 characters of the ID)

**Comment by DominicLavery** [comment] 2020-09-16 09:48
Something like this for the IDs? 
https://github.com/DominicLavery/joplin/commit/6428e669b294c6225d8ec487bc00bd0597765a23

**Comment by Tylryan** [comment] 2021-03-19 16:21
Has there been an update on this? It would be incredibly useful. Thanks for looking into it.

**Comment by OmarMohamedKhallaf** [comment] 2021-06-13 11:07
Will this feature be added soon?

**Comment by kai11** [comment] 2021-07-15 09:13
https://github.com/laurent22/joplin/pull/5191 This is my quick and dirty attempt to extend mv command to move notebooks.
In a few days I'm going to finish this and pass for review.
Quick question to @laurent22  and @tessus:
Which method I can use to get "find notebook or note by id, partial id or title" functionality?

**Comment by RickoNoNo3** [comment] 2022-05-29 12:56
I'm glad I'm not alone in this problem and want Joplin to implement this feature.

Is the data different in different platform clients? Or is the data actually the same, but the user interface of the outer package is different?

Can we first implement a more low-level PROGRAMMING interface only for the shell, and then consider the terminal UI?

The reason why I have this suggestion is because I really want to connect Joplin into my personal blog website, and let Joplin the only software I used to write Markdown, on the whole Internet. Since my personal blog website server is completely written by myself, I only need Joplin to expose a simple API via sockets or shell commands, then I'll call it, and do not need any kind of terminal UI. The CRUD functions on the web page can be implemented by me at a higher level (based on Joplin cli, of course). If possible, it can be written as a Joplin B/S client module independently from my blog.

I noticed that, in the result of the `joplin ls -f json /` command, a hash string has been displayed as an ID. If I use this set of completely ID based data from beginning to end to:
    1. **list notebooks and notes**. (`use->ls->use->ls->...`)
    2. **get the content of a note** and render it to HTML by Joplin or by myself. (`cat`)
    3. **edit a note**. (`edit`, since there is not a direct assignment command to change notes, the editor must be my agent tool connected to the website as a medium)
    4. send the ID when **executing the Joplin shell to maintain notebooks and notes**. (`mv`, `rm`, etc)

If the requirements are like this, will it be easier to implement similar functions?

Thanks for all of your work.

**Comment by charlescochran** [comment] 2022-08-22 22:07
Looking forward to this functionality!

**Comment by Daeraxa** [comment] 2022-09-05 11:45
@laurent22 I think this is the wrong issue that has been closed? #6722 is the still open PR for subnotebooks.

**Comment by laurent22** [comment] 2022-09-05 11:59
This issue was mentioned in the PR so I thought that was one. But yes in that case let's reopen until the other PR is merged.

**Comment by xargon666** [comment] 2022-11-20 15:58
would love this functionality added

**Comment by axsaucedo** [comment] 2023-01-01 21:43
+1 this functionality would be great. Are there any workarounds atm?

**Comment by kai11** [comment] 2023-01-02 15:48
@xargon666 @axsaucedo Won't be added. See [note for Android](https://github.com/laurent22/joplin/pull/5571#issuecomment-1361108479). 
Similar reasoning for terminal.

**Comment by xargon666** [comment] 2023-01-02 22:57
> @xargon666 @axsaucedo Won't be added. See [note for Android](https://github.com/laurent22/joplin/pull/5571#issuecomment-1361108479). Similar reasoning for terminal.

That's a shame but appreciate the response, maybe someday

**Comment by laurent22** [comment] 2023-01-02 23:18
There's an active PR about this, which we hope to merge so not sure where that speculation comes from.

**Comment by charlescochran** [comment] 2023-01-03 00:00
Yeah, I was confused as well. Looking forward to this feature!

**Closed** 2023-02-26 12:13 UTC
Labels: enhancement, cli, backlog

**Comment by Ekaums** [comment] 2024-09-03 01:40
Hi, just wondering if this feature was ever added? Laurent22 mentioned that there is an active PR about this but I could not find one
