### ISSUE TITLE
iOS WebDAV sync issue with Stackstorage

### ISSUE THREAD

**Issue by metbril** [laurent22/joplin#2153] opened 2019-12-04 20:25 UTC
Since the last update (to 10.0.40) both my iPhone and iPad no longer sync to Stackstorage over WebDAV. They did with earlier versions. My MacBook and iMac are currently running Desktop version 1.0.174 and are syncing perfectly fine.

This issue is created per request at the forum:
https://discourse.joplinapp.org/t/bug-new-ios-update-fails-to-sync-on-webdav-connection/4267/19

I have attached iPad screenshots to show the error(s).

My suspicion is that a PROPFIND is executed for the path ending in a double slash (`//'). See the logs for what I mean.

    https://rtvb.stackstorage.com/remote.php/webdav/Apps/Joplin//

If required for testing/reproducing, I am willing to provide a temporary login to my stackstorage to @laurent22.

## Environment

Joplin version: 10.0.40 iOS / 1.0.174 macOS

Platform: iOS
OS specifcs: iOS 13.1.3

## Steps To Reproduce

1. Configure WebDAV for stackstorage 
2. Hit Sync

WebDAV path: `https://mysite.stackstorage.com/remote.php/webdav/Apps/Joplin/`

Mind the trailing slash. Same error without a slash (`[...]/Joplin`) or with double slashes (`[...]/Joplin//`)

Describe what you expected to happen:

* Succesfull sync

## Logfile

See attached screen shots.
![4956adbe16a76b962390464ea59af53550f3d2ec](https://user-images.githubusercontent.com/559346/70178300-5309f880-16dc-11ea-98ee-4e1c3042f81e.png)
![61d7f17644520f42ac2ebfe2415d2631a784957a](https://user-images.githubusercontent.com/559346/70178310-569d7f80-16dc-11ea-964e-ac225fd7a20f.png)
![1fc04c8ce7ea3ffe57b0a71b9806f6ce7fe6e141](https://user-images.githubusercontent.com/559346/70178321-59987000-16dc-11ea-8072-0b0a60d3e2d0.png)

**Comment by mark185p1** [comment] 2019-12-14 18:41
Exactly the same problem here. Is there a work-around available?

**Comment by metbril** [comment] 2019-12-14 18:49
There is no workaround, yet.
You have only 2 alternatives: 

1. don't sync until the issue is fixed
2. use another sync target (other (free) webdav service)

An example of a 2GB free service in NL is https://thegood.cloud (not related to me in any way)

**Comment by laurent22** [comment] 2019-12-18 10:29
Could someone share an account to test and debug the issue? You can send it there: https://github.com/laurent22/joplin/blob/master/Assets/AdresseSupport.png

**Comment by metbril** [comment] 2019-12-18 16:51
Done.

**Comment by martijnhazebroek** [comment] 2019-12-18 17:22
+1 having the same issue

**Comment by metbril** [comment] 2019-12-27 07:42
Have you had any luck reproducing the error and/or troubleshooting it?

**Comment by martijnhazebroek** [comment] 2020-03-26 11:05
Because of this issue my workflow was broken and I had to stop using Joplin.

**Comment by metbril** [comment] 2020-03-26 11:39
I shared an account with @laurent22 but apparently he has not had time to look into this yet.

**Comment by possybility** [comment] 2020-04-10 07:46
same here, i don't want to tie into a specific ecosystem, but I started exploring other options for my markdown notes.

**Comment by metbril** [comment] 2020-04-10 13:56
I have since moved to a "real" Nextcloud instance. So for me there is no urgency. However, I will keep the test account open as long as this issue is open, too.

**Comment by johnvanhienen** [comment] 2020-04-19 20:01
The issue is still present in the current version on iOS. Really prevents me from using this app across all my devices. The URL also includes the double / on the end before generating an unauthorised response.

**Comment by dkreeft** [comment] 2020-05-14 08:02
Indeed, this issue is still present in version 10.0.47. Basically renders WebDAV useless.

**Comment by laurent22** [comment] 2020-05-14 08:32
Could someone provide a test account again?

**Comment by metbril** [comment] 2020-05-14 10:09
The account I shared earlier is still valid. Do I need to resend the credentials?

**Comment by metbril** [comment] 2020-06-14 13:50
It's been a few weeks since my last post. Were you able to login to the account I provided you with? @laurent22

**Comment by felixfaassen** [comment] 2020-06-18 20:42
I have the same issues and using stack storage as well. Also seeing trailing slashes. If I can help testing with this issue please let me know.

**Comment by laurent22** [comment] 2020-06-20 10:16
@metbril, I'm getting 401 unauthorized with the provided credentials.

**Comment by metbril** [comment] 2020-06-20 15:59
I will reset the password and resend it to you.

**Comment by Lkuijk** [comment] 2020-07-10 18:26
What is the status of this problem?

**Comment by metbril** [comment] 2020-07-15 17:27
I have resend the login credentials for the test account to the support email address @laurent22 .

**Comment by metbril** [comment] 2020-08-15 04:42
Needs fix

**Comment by metbril** [comment] 2020-09-14 19:43
Not yet fixed.

**Comment by metbril** [comment] 2020-10-15 05:21
Not yet fixed

**Comment by dkreeft** [comment] 2020-11-08 16:10
Indeed, this is still not fixed. @laurent22 you are probably busy, but perhaps you could share part of the code that handles WebDAV? Then we could debug and try to come up with a fix ourselves. It is such a pity, because Joplin works well on my desktop.

**Comment by metbril** [comment] 2020-11-10 18:41
For the record. The owner of STACK today sent out an email that free accounts will be removed within 3 months from now. This will mean I'll look for a different permanent solution and will not be able to assist in troubleshooting or testing. 

Paid accounts will remain so resolving the issue would still be needed for those accounts.

**Comment by felixfaassen** [comment] 2020-11-18 18:00
@laurent22 @metbril I have a paid account on STACK and also have this problem so I would love to test things out and help this bug get fixed please let me know what I need to do in order to have all the info needed for fixing it

**Comment by bramhooimeijer** [comment] 2022-04-05 10:49
@laurent22 For me this issue is still present with Webdav. For me, this prevents me from using Joplin though I like it much better than e.g. OneNote.

Let me know if there's anything I can do to help out w.r.t. testing or such.

**Comment by MassiveMarmot** [comment] 2022-12-21 17:09
Also trying to sync with Stack (4.16.3) on iOS (16.02) and get the same error.

> let me know if there's anything I can do to help out w.r.t. testing or such.

ditto

**Comment by mcaklein** [comment] 2023-09-13 09:00
I'm also willing to help out. I'm using the paid Stackstorage service as well, and I would really like to use it for Joplin on my iOS device. The bug seems to be very specific for Stack and only hampers the synchronization to the device (i.e. after entering synchronization details on an iOS device, a new folder "Welcome! (Mobile)" is created in the repository.

@laurent22, is there a way we can help? Creating a test account would be simple.

**Comment by laurent22** [comment] 2023-09-13 09:43
Yes we'd need a test account, please send the credentials to https://github.com/laurent22/joplin/blob/master/Assets/AdresseSupport.png

**Comment by mcaklein** [comment] 2023-09-13 09:52
Great, I've sent you an account!

**Comment by laurent22** [comment] 2023-09-14 11:48
Ok that should be fixed now, it will be in the next pre-release. Thanks @mcaklein for providing the test account!

**Closed** 2023-09-14 11:48 UTC
Labels: bug, iOS, high

**Comment by mcaklein** [comment] 2023-09-18 17:08
> Ok that should be fixed now, it will be in the next pre-release. Thanks @mcaklein for providing the test account!

Thanks a lot, much appreciated!
