### ISSUE TITLE
fatal error with cli 1.0.141 on start

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1778] opened 2019-07-31 21:19 UTC
## Environment

Joplin version: 1.0.141
Platform: CLI on Linux (using tmux)

## Steps To Reproduce

1. upgrade from previous version (I used `npm-check -gu`)
2. run `joplin` from within tmux
3. following error message occurs:

```
Fatal error:
TypeError: Cannot read property 'fullscreen' of undefined
    at AppGui.fullScreen (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/app-gui.js:560:15)
    at new AppGui (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/app-gui.js:86:9)
    at Application.start (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/app.js:410:16)
```

Describe what you expected to happen:

Joplin should start up.

## Logfile

No debug log. Just stack trace above.

**Comment by tessus** [comment] 2019-08-01 23:39
I narrowed the issue down a bit. Actually this is a combination of several issues.

1. The catch in the constructor can't reference a method, since the object would not have been instantiated, if there had been an error.
2. joplin apparently can't run in tmux anymore

So I'm not sure what happened between version 1.0.140 and 1.0.141, but the constructor throws an error when joplin is run from within tmux. This should not be the case and until now it has been working without issues.

@laurent22 you know the code better. did you limit the terminals somehow?

I just found out the following: without tmux my `TERM` is `xterm-256color`. Within tmux, the `TERM` is `screen-256color`. If I do `export TERM=xterm-256color` within tmux, joplin starts up without an error. This is not really a valid workaround and joplin should run with a `TERM` setting of `screen-256color` as well.

**Comment by laurent22** [comment] 2019-08-03 08:10
I use tmux too and can't replicate this. In your case it seems to fail very early, before the terminal handler is even created. In the try/catch block of the constructor of app-gui.js could you try to comment out the line `this.fullScreen(false);` so that it can print the error message? It's also possible it's a regression in terminal-kit, in which case we might have to report it over there.

**Comment by tessus** [comment] 2019-08-03 08:17
Yep, I've done that already, but it didn't tell me anything:

```
Error: Bad RGB value
    at Terminal.registerForRgb (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/terminal-kit/lib/Terminal.js:1662:9)
    at Terminal.color256 (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/terminal-kit/lib/termconfig/xterm.js:280:26)
    at str.replace (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/string-kit/lib/format.js:213:26)
    at String.replace (<anonymous>)
    at Object.format (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/string-kit/lib/format.js:97:12)
    at applyEscape (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/terminal-kit/lib/Terminal.js:558:47)
    at createOptimized (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/terminal-kit/lib/Terminal.js:494:43)
    at Object.createTerminal (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/terminal-kit/lib/Terminal.js:418:2)
    at terminal (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/terminal-kit/lib/termkit.js:102:18)
    at Object.get [as terminal] (/data/home/tessus/.node_modules_global/lib/node_modules/joplin/node_modules/lazyness/lib/Lazyness.js:48:16)
```

> I use tmux too and can't replicate this.

Hmm, what's your `echo $TERM` output from within tmux?

**Comment by laurent22** [comment] 2019-08-03 08:52
> Hmm, what's your echo $TERM output from within tmux?

`screen`

From the error and stacktrace it looks like an issue with terminal-kit, so it's probably best to report it there.

**Comment by laurent22** [comment] 2019-08-03 08:57
> I just found out the following: without tmux my `TERM` is `xterm-256color`. Within tmux, the `TERM` is `screen-256color`. If I do `export TERM=xterm-256color` within tmux, joplin starts up without an error. This is not really a valid workaround and joplin should run with a `TERM` setting of `screen-256color` as well.

Maybe the issue is that this screen-256color constant is not parsed properly by terminal-kit?

**Comment by laurent22** [comment] 2019-08-03 09:56
https://github.com/cronvel/terminal-kit/issues/95

**Comment by cronvel** [comment] 2019-08-03 15:16
@tessus @laurent22 It should be fixed with Terminal-Kit v1.29.3.

**Comment by tessus** [comment] 2019-08-03 16:17
@cronvel this is great news. Thank you very much.

@laurent22 I'm heading to another BBQ. We Canadians love our BBQ season. ;-) Anyway, I'll test the new terminal-kit version later this evening.
I will have to do that on my Linux box, because I can't replicate this on macOS w/ tmux and `./run.sh` either. Thus I will just update terminal-kit on my installed 1.0.141.

However, the other fatal error in catch will still be there. We need some check there, before we access an object that might not exist.

**Comment by tessus** [comment] 2019-08-04 05:40
@laurent22 I've updated terminal-kit to 1.29.3. It definitely fixes the issue. I'm a bit confused though. I had to do it manually, because terminal-kit is not in the `package.json` file as dependency. What's up with that?

Also, we still need a check for property 'fullscreen' not undefined before calling it.

@cronvel awesome. problem is gone with 1.29.3. Thank you.

**Comment by laurent22** [comment] 2019-08-04 18:20
@cronvel, that's great, many thanks for the fix.

@tessus, yes that will need to be fixed. Basically checking if the term exists and only then cancel fullscreen mode.

**Comment by tessus** [comment] 2019-08-04 19:03
@laurent22 how do I update terminal-kit in the code, if there's no entry for it in `package.json`?

**Comment by tessus** [comment] 2019-08-06 01:18
yep, `if (this.term_) { this.fullScreen(false) };` does the trick....

Still, I can't create a PR, when I don't know how to update terminal-kit in the code, if there's no entry for it in `package.json`. Do I just add it? (Why wasn't it there in the first place?)

**Comment by cronvel** [comment] 2019-08-07 13:31
@laurent22 @tessus Yes I remember testing Joplin and was wondering if it was using Terminal-Kit at all, since it's not in the `package.json`.

Beside, having a 8000+ stars as a dependent package would be a plus for Terminal-Kit reputation! ^^

Also I could even test if major release of Terminal-Kit run fine with Joplin.

Recently, I have made some work on want I call the 'document model' that aims to be used for GUI (with lot of widgets at the same time), instead of what I call the 'inline mode' (one input at the end of the screen). It's still alpha (and not documented so far), but it starts being really great. It have event delegation, keyboard focus cycling. It could be interesting for you. You can look at some sample codes in the `./sample/document/` directory of Terminal-Kit.

**Comment by cronvel** [comment] 2019-08-07 14:12
Ah ok, you already have your own framework widget. Never heard of `tkwidgets` before, you should have tell me @laurent22 ! ^^

**Comment by laurent22** [comment] 2019-08-07 15:25
Yes I guess the terminal-kit dependency comes via tkwidgets, but we should also add it to the cli app package.json since it makes use of it directly too.

Joplin indeed uses this tkwidgets package to manage its controls but it has various issues and is made mostly to work with Joplin, so an alternative, more generic lib would be welcome.

**Comment by tessus** [comment] 2019-08-07 19:22
Ok, I will create a PR according to the info in this issue.

**Closed** 2019-08-29 16:05 UTC
Labels: bug, essential, terminal
