### ISSUE TITLE
Wrong display for titles of notebooks

### ISSUE THREAD

**Issue by af-beng** [laurent22/joplin#7816] opened 2023-02-21 13:32 UTC
Display bug on titles of notebooks when the option "Show note counts" is enable and an emoji icon is present.

![image](https://user-images.githubusercontent.com/91530842/220353738-6529f410-6157-41b6-9ff7-37734fde3437.png)

## Environment

Joplin version: 2.9.17
Platform: Linux
OS specifics: Ubuntu 22.04.1

## Steps to reproduce

1. Create multiples notebooks with emoji icon.
2. Enable "Show note counts" in "View" tab.
3. Move the cursor on the titles of notebooks.

**Comment by laurent22** [comment] 2023-02-21 14:31
Duplicate of #7506

**Closed as completed by laurent22** 2023-02-21 14:31 UTC
Labels: bug
