### ISSUE TITLE
Fatal Errors in Nextcloud 13 when syncing

### ISSUE THREAD

**Issue by Rumblejunkie** [laurent22/joplin#323] opened 2018-03-22 19:11 UTC
### Operating system

- Windows
- Android

### Application

- Desktop
- Mobile

**First of all sorry for my english.**
I setup Joplin in Android and Windows and it works without a problem.
Make a note on Android -> sync -> it show up in the Windows app, and vice versa.

The only thing i have is this "Fatal-Error" in the Nextcloud logging-tab when i sync.
Everytime i hit the sync-button on Android or Windows i get this two errors.

![joplin_nextcloud_sync_fatal_error](https://user-images.githubusercontent.com/37671097/37791690-29c2ca54-2e0a-11e8-9dcf-e8c903810c42.png)

**Comment by laurent22** [comment] 2018-03-22 19:12
Duplicate of #319

**Closed by laurent22** 2018-03-22 19:12 UTC

**Comment by Rumblejunkie** [comment] 2018-03-22 19:18
Sorry @laurent22, its my first time on GitHub and i miss/overlook the "Closed" tab/section.
Thanks for your hard work
