### ISSUE TITLE
[Bug] Undo action in notes exhibits strange behavior  

### ISSUE THREAD

**Issue by desk7** [laurent22/joplin#1642] opened 2019-06-10 06:27 UTC
- Windows 10
- Desktop

When Ctrl-Z is pressed, the last action *in note* should be undone and the prompt should position itself where the change occurs. But it doesn't work when you use buttons in toolbar. 
How to reproduce the bug:
- click on any button of toolbar (Bold, Italic, Hyperlink, code, numbered list, bulleted list, checkbox, Heading, Horizontal rule, Date & time)
- press Ctrl-Z
- the prompt never positions itself where change occurs but all the text in the note gets selected
- in addition, with some buttons, undo doesn't work.

**Comment by alinuxfan** [comment] 2019-06-28 14:53
Confirming same behavior in Linux

**Comment by hb20007** [comment] 2019-07-16 14:17
This also happens if keyboard shortucts (e.g., `Ctrl` + `B` for bold) are used instead of toolbar buttons.

**Comment by Perkolator** [comment] 2019-10-16 20:24
Not fixed. Do not close. (damn that bot is annoying)

**Comment by siddhugolu** [comment] 2019-12-18 13:26
Confirming that this is still happening. Can reproduce across all the desktop platforms - Linux, Windows and Mac.

**Comment by superfreeman1989** [comment] 2020-02-19 06:10
I just started trying Joplin today and this is the very first annoying thing I noticed. Ctrl-Z loses my focus and brings me to end of document.

**Comment by Perkolator** [comment] 2020-04-15 13:57
Still relevant.

**Comment by siddhugolu** [comment] 2020-05-30 14:49
Please don't close this issue. It's still relevant.

**Comment by Snaxeko** [comment] 2020-06-01 00:51
Sooo after 1 year, is this a bug, or an intended behavior ?

**Comment by hb20007** [comment] 2020-07-10 17:37
Not fixed

**Comment by hb20007** [comment] 2020-08-09 19:37
Not fixed.

**Comment by hb20007** [comment] 2020-09-10 07:16
Not fixed.

**Comment by hb20007** [comment] 2020-10-10 08:04
Not fixed.

**Comment by hb20007** [comment] 2020-11-09 09:54
Not fixed.

**Comment by hb20007** [comment] 2020-12-09 23:02
Not fixed.

**Comment by hb20007** [comment] 2021-01-09 16:24
Not fixed.

**Comment by hb20007** [comment] 2021-02-13 12:04
Not fixed.

**Comment by hb20007** [comment] 2021-03-20 00:15
Not fixed.

**Comment by hb20007** [comment] 2021-06-03 06:38
Not fixed.

**Comment by roman-r-m** [comment] 2021-06-03 19:18
I can't reproduce this, neither in markdown editor nor in Rich Text mode.
Can you post a screenshot or a video?

**Comment by hb20007** [comment] 2021-06-03 21:17
@roman-r-m You are right, it seems to have been fixed between v1.0.245 and v1.1.1. I believe this issue can be closed.

**Comment by roman-r-m** [comment] 2021-06-03 21:31
Thanks for confirming!

**Closed by roman-r-m** 2021-06-03 21:31 UTC
