### ISSUE TITLE
Exporting to PDF generates corrupted file

### ISSUE THREAD

**Issue by tydel** [laurent22/joplin#1276] opened 2019-02-27 20:25 UTC
### Operating system

- Windows 10

### Application

- Desktop

### Description

Since upgrading to 1.0.32/1.0.34 I am now unable to export to PDF as the resulting file cannot be read by any PDF readers I've tried.  This includes Acrobat Reader DC, Microsoft Edge, and Google PDF Viewer.

The readers complain that the file could not be read and may be corrupted.  I've attached a sample export here to this issue: [test.pdf](https://github.com/laurent22/joplin/files/2912162/test.pdf) as well as the error I'm getting in Acrobat Reader DC:

![corrupted_pdf](https://user-images.githubusercontent.com/425605/53520577-cc5c2700-3a8a-11e9-9073-7790ae881a88.png)

**Comment by tessus** [comment] 2019-02-27 21:21
Duplicate of #1268

**Closed by tessus** 2019-02-27 21:21 UTC
