### ISSUE TITLE
Pasting images doesn't work on macOS

### ISSUE THREAD

**Issue by petrz12** [laurent22/joplin#330] opened 2018-03-25 14:55 UTC
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I often makes screenshots into the Clipboard with e.g. Control-Shift-Command-4. Unfortunately pasting them into the desktop app doesn't work. Pasting it on Github (here) works (Firefox).

It would be nice to have.

**Comment by zelvik** [comment] 2018-03-25 15:27
Duplicate of #200

**Closed** 2018-03-25 19:07 UTC
