### ISSUE TITLE
Size of 'search all' (F6) field

### ISSUE THREAD

**Issue by Key-Snapper** [laurent22/joplin#8342] opened 2023-06-19 14:07 UTC
## Environment
Joplin version: 
   Joplin for Desktop (appimage)
   Copyright © 2016-2023 Laurent Cozic
   Joplin 2.10.19 (prod, linux)
   Sync-Version: 3
  Profil-Version: 42
  Revision: 1100ab0
Platform: Linux
OS specifics: Linux Mint Cinnamon 21.1 
                      Kernel 6.1.0-1014-oem
-->
![Joplin Screenshot2023-06-19 15-35-12](https://github.com/laurent22/joplin/assets/84930208/e3a2eebb-2079-4d74-9fb1-c4119f97f647)

**Comment by Daeraxa** [comment] 2023-06-19 14:49
Duplicate of https://github.com/laurent22/joplin/issues/8159

**Closed as completed by Daeraxa** 2023-06-19 14:49 UTC
Labels: bug
