### ISSUE TITLE
Can't Sync with Nextcloud 13

### ISSUE THREAD

**Issue by hitam4450** [laurent22/joplin#315] opened 2018-03-20 16:17 UTC
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x ] Mobile
- [ ] Terminal

I downloaded the mobile app and tried to connect to my nextcloud instance unsuccessfully!

https://server-ip/nextcloud/remote.php/dav seams to check the connection indefinitely!!

No response, no error message available!

What happen(ed)? How to connect to NC 13 successfully ??

Regards, hitam

**Comment by laurent22** [comment] 2018-03-20 16:24
Did you try to click on the button "Check synchronisation configuration" in the config page? If so, are you getting any error message? Also you mention a server IP. Are you using a self-signed certificate? Because that's currently not supported (might be at some point).

**Comment by hitam4450** [comment] 2018-03-20 16:27
Yes, I checked synchronization configuration..the it sits there checking ..wiothout any result!

No error message available!

I use a self signed certificate for my NC 13 instance!

**Comment by laurent22** [comment] 2018-03-20 16:35
Yes unfortunately self-signed certificate aren't supported at this time - see #191

The fact that it does nothing and doesn't show an error message is quite annoying though.

**Comment by hitam4450** [comment] 2018-03-20 16:47
Well, thanks for your reply! My system: Samsung ANDROID 7.0 !

**Comment by hitam4450** [comment] 2018-03-20 17:00
Ok, i tried one more time. This time I received an error message:

Error. Please check that URL, username, password, etc. atr correct (YES they are correct) and that the sync target is accessible! The reported error was:

Network request failed!

**Comment by blissb2599** [comment] 2018-03-20 17:33
I wonder if this is related to the issue I've had (#312) -- I'm syncing against NC 13, also.  Works great on Windows, not on Linux.

**Comment by laurent22** [comment] 2018-03-26 16:35
Duplicate of #191

**Closed by laurent22** 2018-03-26 16:35 UTC
